
##############################
# Country definition for DDR #
##############################

province = { id = 296 ic = 1 naval_base = 8 air_base = 5 } # ƒƒXƒgƒbƒN
province = { id = 300 ic = 2 air_base = 10 } # ƒxƒ‹ƒŠƒ“
province = { id = 301 landfort = 9 } # ƒVƒ…ƒgƒ‰[ƒ‹ƒYƒ“ƒg
province = { id = 309 landfort = 9 } # ƒRƒbƒgƒuƒX
province = { id = 310 ic = 1 air_base = 6 } # ƒ‰ƒCƒvƒcƒBƒq
province = { id = 311 ic = 1 air_base = 4 } # ƒhƒŒƒXƒfƒ“
province = { id = 546 landfort = 9 } # ƒtƒ‰ƒ“ƒNƒtƒ‹ƒgEƒAƒ“EƒfƒAEƒI[ƒ_[

#####################
# Country main data #
#####################

country =
{ tag                 = DDR
  manpower            = 4250
  energy              = 58000
  metal               = 36000
  rare_materials      = 45000
  oil                 = 12000
  supplies            = 8000
  money               = 3500
  capital             = 300
  transports          = 1800
  escorts             = 1500
  regular_id          = U02
  nationalprovinces   = { 296 297 298 299 300 301 546 84 309 310 311 }
  ownedprovinces      = { 296 297 298 299 300 301 546 84 309 310 311 }
  controlledprovinces = { 296 297 298 299 300 301 546 84 309 310 311 }
  techapps            = { 
                         1130 1230 1570 1670 1770 1870 1970
                         2010 2020 2030 2040 2050 2310 2320 2610 2620 2910 2920 10050 10060 1010  10190 1020  10200 1030    1110  1120 
                          1210  1220  1470  1490  1510  1530  1550  1560  1650  1660
                          1750  1760  1850  1860  1950  1960
                          3010  3020  30410 30420 30510 30520 3110  3310
                          3120  3210  3220  3460  3470
                          3560      3910  3920
                          3940  40100 40110 4390  4400  4010  4020  4110  4120  4210  4220  4640  4650  4820  4830
                          4560  50020 50030   50070 50080  5010    50090 50100 5020  50290 50300 50310
                          5090  5100  5170  5180  5250  5260  5330  5340  5410  5420
                          5490  5500  5600  5610  5680  5690  5760  5770  5780  5790  5800  5810
                          5910  5920  7010  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990  6000  6010  6020  6030  6040
                          6180  6190  6400  6410
                        }
  inventions          = { }
  policy              = { democratic = 2 political_left = 9 freedom = 2 free_market = 2 professional_army = 9 defense_lobby = 10 interventionism = 9 }

#ˆÈ‰ºƒhƒCƒc–¯å‹¤˜a‘‘‰Æl–¯ŒR
  landunit =
  { id       = { type = 15001 id = 1 }
    name     = "‘‰Æl–¯ŒR‘i—ß•”’¼Š—\”õ"
    location = 300
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 1 }
      name          = "‘‰Æl–¯ŒR‘i—ß•”"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 2 }
      name          = "‘æ601íp‹@’†‘à"
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 3 }
      name          = "‘æ602íp‹@’†‘à"
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 4 }
      name          = "‘æ603íp‹@’†‘à"
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 5 }
      name          = "‘æ604íp‹@’†‘à"
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 6 }
      name          = "‘æ304‹@“®•à•º‘å‘à"
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 7 }
      name          = "‘æ1íÔ‘å‘à"
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 8 }
      name          = "‘æ2íÔ‘å‘à"
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 9 }
      name          = "‘æ3íÔ‘å‘à"
    }
  }
  landunit =
  { id       = { type = 15001 id = 2 }
    name     = "‘‰Æl–¯ŒRƒI[ƒfƒ‹ŒRW’c"
    location = 309
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 10 }
      name          = "‘‰Æl–¯ŒRƒI[ƒfƒ‹ŒRW’ci—ß•”"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 11 }
      name          = "‘æ641íp‹@’†‘à"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 12 }
      name          = "‘æ642íp‹@’†‘à"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 13 }
      name          = "‘æ643íp‹@’†‘à"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 14 }
      name          = "‘æ644íp‹@’†‘à"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 15 }
      name          = "‘æ344‹@“®•à•º‘å‘à"
      experience    = 43
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 16 }
      name          = "‘æ12íÔ‘å‘à"
      experience    = 63
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 17 }
      name          = "‘æ13íÔ‘å‘à"
      experience    = 61
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 18 }
      name          = "‘æ14íÔ‘å‘à"
      experience    = 71
    }
  }
  landunit =
  { id       = { type = 15001 id = 3 }
    name     = "‘‰Æl–¯ŒRƒiƒCƒZŒRW’c"
    location = 546
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 19 }
      name          = "‘‰Æl–¯ŒRƒiƒCƒZŒRW’ci—ß•”"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 20 }
      name          = "‘æ651íp‹@’†‘à"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 21 }
      name          = "‘æ652íp‹@’†‘à"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 22 }
      name          = "‘æ653íp‹@’†‘à"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 23 }
      name          = "‘æ654íp‹@’†‘à"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 24 }
      name          = "‘æ394‹@“®•à•º‘å‘à"
      experience    = 43
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 25 }
      name          = "‘æ395‹@“®•à•º‘å‘à"
      experience    = 43
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 26 }
      name          = "‘æ25íÔ‘å‘à"
      experience    = 33
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 27 }
      name          = "‘æ26íÔ‘å‘à"
      experience    = 31
    }
  }
  landunit =
  { id       = { type = 15001 id = 4 }
    name     = "‘‰Æl–¯ŒR“Œ•û‘ŒR"
    location = 301
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 28 }
      name          = "‘‰Æl–¯ŒR“Œ•û‘ŒRi—ß•”"
      experience    = 88
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 29 }
      name          = "‘æ661íp‹@’†‘à"
      experience    = 67
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 30 }
      name          = "‘æ662íp‹@’†‘à"
      experience    = 66
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 31 }
      name          = "‘æ663íp‹@’†‘à"
      experience    = 67
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 32 }
      name          = "‘æ664íp‹@’†‘à"
      experience    = 66
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 33 }
      name          = "‘æ398‹@“®•à•º‘å‘à"
      experience    = 48
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 34 }
      name          = "‘æ399‹@“®•à•º‘å‘à"
      experience    = 48
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 35 }
      name          = "‘æ33íÔ‘å‘à"
      experience    = 38
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 36 }
      name          = "‘æ34íÔ‘å‘à"
      experience    = 74
    }
  }
  landunit =
  { id       = { type = 15001 id = 5 }
    name     = "—ÕW¬íp‹@‘å‘àƒnƒ“ƒjƒoƒ‹"
    location = 301
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 37 }
      name          = "‘æ666íp‹@’†‘à"
      experience    = 100
      strength     = 22
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 38 }
      name          = "‘æ667íp‹@’†‘à"
      experience    = 67
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 39 }
      name          = "‘æ668íp‹@’†‘à"
      experience    = 67
      strength     = 33
      max_strength = 33
    }
  }
  landunit =
  { id       = { type = 15001 id = 6 }
    name     = "•‘•Œx@ŒR‘æ1íp‹@b˜A‘à"
    location = 300
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 40 }
      name          = "•‘•Œx@ŒR‘ŒRi—ß•”"
      experience    = 88
      extra         = rocket_artillery
      brigade_model = 2
      locked = yes
    }
    division =
    { type          = infantry
      model         = 2
      id            = { type = 15004 id = 41 }
      name          = "ƒ”ƒFƒAƒ”ƒHƒ‹ƒt‘å‘à"
      experience    = 90
      locked = yes
    }
    division =
    { type          = infantry
      model         = 2
      id            = { type = 15004 id = 42 }
      name          = "ƒ”ƒ@ƒ“ƒs[ƒŒ‘å‘à"
      experience    = 67
      locked = yes
    }
    division =
    { type          = infantry
      model         = 2
      id            = { type = 15004 id = 43 }
      name          = "ƒW[ƒNƒtƒŠ[ƒg‘å‘à"
      experience    = 67
      locked = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 7 }
    name     = "‘æ501íp‹@b‘å‘à"
    location = 309
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 44 }
      name          = "‘æ304íp‹@’†‘à"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 45 }
      name          = "‘æ305íp‹@’†‘à"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 46 }
      name          = "‘æ306íp‹@’†‘à"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
  }
  landunit =
  { id       = { type = 15001 id = 8 }
    name     = "‘æ221íp‹@b‘å‘à"
    location = 309
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 47 }
      name          = "‘æ25íp‹@’†‘à"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 48 }
      name          = "‘æ36íp‹@’†‘à"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 49 }
      name          = "‘æ47íp‹@’†‘à"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
  }
  landunit =
  { id       = { type = 15001 id = 9 }
    name     = "ƒz[ƒlƒbƒJ[‹@ŠB‰»ŒR"
    location = 546
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 50 }
      name          = "ƒvƒŠƒ“ƒc¥ƒIƒCƒQƒ“‘å‘à"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 51 }
      name          = "ƒz[ƒGƒ“ƒVƒ…ƒ^ƒEƒtƒFƒ“‘å‘à"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 52 }
      name          = "ƒnƒ“ƒWƒƒ‘å‘à"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 53 }
      name          = "ƒXƒJƒ“ƒfƒ‹ƒxƒO‘å‘à"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 54 }
      name          = "ƒPƒ“ƒvƒt‘å‘à"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 55 }
      name          = "ƒQƒbƒcEƒtƒHƒ“Eƒxƒ‹ƒŠƒqƒ“ƒQƒ“‘å‘à"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 56 }
      name          = "ƒzƒ‹ƒXƒgEƒ”ƒFƒbƒZƒ‹‘å‘à"
      experience    = 20
    }
  }
  landunit =
  { id       = { type = 15001 id = 10 }
    name     = "‘‰Æl–¯ŒR¼•û‘ŒR"
    location = 84
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 57 }
      name          = "‘‰Æl–¯ŒR¼•û‘ŒRi—ß•”"
      experience    = 88
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 2
      id            = { type = 15004 id = 58 }
      name          = "‘æ4íp‹@’†‘à"
      experience    = 30
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 2
      id            = { type = 15004 id = 59 }
      name          = "‘æ5íp‹@’†‘à"
      experience    = 30
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 2
      id            = { type = 15004 id = 60 }
      name          = "‘æ6íp‹@’†‘à"
      experience    = 30
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 2
      id            = { type = 15004 id = 61 }
      name          = "‘æ7íp‹@’†‘à"
      experience    = 30
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
  }
  landunit =
  { id       = { type = 15001 id = 11 }
    name     = "‘æ7‹@ŠB‰»•à•ºŒR"
    location = 546
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 62 }
      name          = "ƒpƒEƒ‹¥ƒŒƒ”ƒB‘å‘à"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 63 }
      name          = "ƒ‰[ƒRƒV¥ƒ}[ƒ`ƒƒ[ƒVƒ…‘å‘à"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 64 }
      name          = "ƒnƒCƒ“ƒŠƒq¥ƒuƒ‰ƒ“ƒhƒ‰[‘å‘à"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 65 }
      name          = "ƒNƒ“¥ƒx[ƒ‰‘å‘à"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 66 }
      name          = "ƒ‹[ƒg¥ƒtƒBƒbƒVƒƒ[‘å‘à"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 67 }
      name          = "ƒAƒ‹ƒJƒfƒB¥ƒ}ƒYƒ[‘å‘à"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 68 }
      name          = "ƒGƒ‹ƒ“ƒXƒg¥ƒe[ƒ‹ƒ}ƒ“‘å‘à"
      experience    = 20
    }
  }
  navalunit =
  { id       = { type = 15102 id = 6 }
    name     = "l–¯ŠCŒR"
    location = 296
    base     = 296
    division =
    { type  = battleship
      model = 3
      id    = { type = 15105 id = 43 }
      name  = "Karl Marx"
    }
    division =
    { type  = escort_carrier
      model = 5
      id    = { type = 15105 id = 44 }
      name  = "Peenemunde"
    }
    division =
    { type  = battlecruiser
      model = 5
      id    = { type = 15105 id = 45 }
      name  = "Hertha"
    }
    division =
    { type  = battlecruiser
      model = 5
      id    = { type = 15105 id = 46 }
      name  = "Freya"
    }
    division =
    { type  = battlecruiser
      model = 5
      id    = { type = 15105 id = 47 }
      name  = "Vineta"
    }
    division =
    { type  = battlecruiser
      model = 5
      id    = { type = 15105 id = 48 }
      name  = "Hansa"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 49 }
      name  = "—g—¤’ø1†"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 50 }
      name  = "—g—¤’ø2†"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 51 }
      name  = "—g—¤’ø3†"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 52 }
      name  = "—g—¤’ø4†"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 53 }
      name  = "—g—¤’ø5†"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 54 }
      name  = "—g—¤’ø6†"
    }
  }
  airunit =
  { location = 300
    id       = { type = 14501 id = 1 }
    name     = "‘æ801q‹óí“¬’c"
    base     = 300
    division =
    { id       = { type = 14500 id = 1 }
      name     = "‘æ61í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 2 }
      name     = "‘æ62í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 3 }
      name     = "‘æ63í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 4 }
      name     = "‘æ64í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
  }
  airunit =
  { location = 300
    id       = { type = 14501 id = 2 }
    name     = "‘æ1íp–C•º•”‘à"
    base     = 300
    division =
    { id       = { type = 14500 id = 5 }
      name     = "‘æ1íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 6 }
      name     = "‘æ2íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 7 }
      name     = "‘æ3íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 8 }
      name     = "‘æ4íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
  }
  airunit =
  { location = 296
    id       = { type = 14501 id = 3 }
    name     = "‘æ2íp–C•º•”‘à"
    base     = 296
    division =
    { id       = { type = 14500 id = 9 }
      name     = "‘æ5íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 10 }
      name     = "‘æ6íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 11 }
      name     = "‘æ7íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 12 }
      name     = "‘æ8íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
  }
  airunit =
  { location = 310
    id       = { type = 14501 id = 4 }
    name     = "‘æ3íp–C•º•”‘à"
    base     = 310
    division =
    { id       = { type = 14500 id = 13 }
      name     = "‘æ9íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 14 }
      name     = "‘æ10íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 15 }
      name     = "‘æ11íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 16 }
      name     = "‘æ12íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
  }
  airunit =
  { location = 311
    id       = { type = 14501 id = 5 }
    name     = "‘æ4íp–C•º•”‘à"
    base     = 311
    division =
    { id       = { type = 14500 id = 17 }
      name     = "‘æ13íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 18 }
      name     = "‘æ14íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 19 }
      name     = "‘æ15íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 20 }
      name     = "‘æ16íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
  }
  airunit =
  { location = 66
    id       = { type = 14501 id = 6 }
    name     = "‘æ5íp–C•º•”‘à"
    base     = 66
    division =
    { id       = { type = 14500 id = 21 }
      name     = "‘æ17íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 22 }
      name     = "‘æ18íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 23 }
      name     = "‘æ19íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 24 }
      name     = "‘æ20íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
  }
  airunit =
  { location = 67
    id       = { type = 14501 id = 7 }
    name     = "‘æ6íp–C•º•”‘à"
    base     = 67
    division =
    { id       = { type = 14500 id = 25 }
      name     = "‘æ21íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 26 }
      name     = "‘æ22íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 27 }
      name     = "‘æ23íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 28 }
      name     = "‘æ24íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
  }
  airunit =
  { location = 75
    id       = { type = 14501 id = 8 }
    name     = "‘æ7íp–C•º•”‘à"
    base     = 75
    division =
    { id       = { type = 14500 id = 29 }
      name     = "‘æ25íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 30 }
      name     = "‘æ26íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 31 }
      name     = "‘æ27íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 32 }
      name     = "‘æ28íp–C•º•”‘à"
      strength = 100
      type     = flying_bomb
      model    = 2
    }
  }
  airunit =
  { location = 300
    id       = { type = 14501 id = 9 }
    name     = "‘æ802q‹óí“¬’c"
    base     = 300
    division =
    { id       = { type = 14500 id = 33 }
      name     = "‘æ65í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 34 }
      name     = "‘æ66í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 35 }
      name     = "‘æ67í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 36 }
      name     = "‘æ68í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
  }
  airunit =
  { location = 300
    id       = { type = 14501 id = 10 }
    name     = "‘æ803q‹óí“¬’c"
    base     = 300
    division =
    { id       = { type = 14500 id = 37 }
      name     = "‘æ69í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 38 }
      name     = "‘æ70í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 39 }
      name     = "‘æ71í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 40 }
      name     = "‘æ72í“¬ƒwƒŠ‘å‘à"
      strength = 100
      type     = cas
      model    = 2
    }
   }
  airunit =
  { location = 300
    id       = { type = 14501 id = 11 }
    name     = "‘æ12”šŒ‚q‹ó’c"
    base     = 300
    division =
    { id       = { type = 14500 id = 41 }
      name     = "‘æ1”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 42 }
      name     = "‘æ2”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 43 }
      name     = "‘æ3”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 44 }
      name     = "‘æ4”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
   }
  airunit =
  { location = 300
    id       = { type = 14501 id = 12 }
    name     = "‘æ15”šŒ‚q‹ó’c"
    base     = 300
    division =
    { id       = { type = 14500 id = 45 }
      name     = "‘æ5”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 46 }
      name     = "‘æ6”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 47 }
      name     = "‘æ7”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 48 }
      name     = "‘æ8”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
   }
  airunit =
  { location = 300
    id       = { type = 14501 id = 13 }
    name     = "‘æ19”šŒ‚q‹ó’c"
    base     = 300
    division =
    { id       = { type = 14500 id = 49 }
      name     = "‘æ9”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 50 }
      name     = "‘æ10”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 51 }
      name     = "‘æ11”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 52 }
      name     = "‘æ12”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
   }
  airunit =
  { location = 300
    id       = { type = 14501 id = 14 }
    name     = "‘æ21”šŒ‚q‹ó’c"
    base     = 300
    division =
    { id       = { type = 14500 id = 53 }
      name     = "‘æ13”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 54 }
      name     = "‘æ14”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 55 }
      name     = "‘æ15”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 56 }
      name     = "‘æ16”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
   }
  airunit =
  { location = 300
    id       = { type = 14501 id = 15 }
    name     = "‘æ23”šŒ‚q‹ó’c"
    base     = 300
    division =
    { id       = { type = 14500 id = 57 }
      name     = "‘æ17”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 58 }
      name     = "‘æ18”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 59 }
      name     = "‘æ19”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
    division =
    { id       = { type = 14500 id = 60 }
      name     = "‘æ20”šŒ‚q‹ó‘à"
      strength = 100
      type     = tactical_bomber
      model    = 2
    }
   }
}