
##############################
# Country definition for FIN #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = FIN
  manpower            = 4250
  energy              = 58000
  metal               = 36000
  rare_materials      = 45000
  oil                 = 12000
  supplies            = 8000
  money               = 3500
  capital             = 142
  transports          = 1800
  escorts             = 1500
  regular_id          = U02
  nationalprovinces   = { 103 130 131 132 136 137 138 139 140 141 142 144 147 148 149 }
  ownedprovinces      = { 103 130 131 132 136 137 138 139 140 141 142 144 147 148 149 }
  controlledprovinces = { 103 130 131 132 136 137 138 139 140 141 142 144 147 148 149 }
  techapps            = { 
                         1130 1230 1570 1670 1770 1870 1970
                         2010 2020 2030 2040 2050 2310 2320 2610 2620 2910 2920 10050 10060 1010  10190 1020  10200 1030    1110  1120 
                          1210  1220  1470  1490  1510  1530  1550  1560  1650  1660
                          1750  1760  1850  1860  1950  1960
                          3010  3020  30410 30420 30510 30520 3110 
                          3120  3210  3220  3460  3470
                          3560      3910  3920
                          3940  40100 40110 4390  4400  4010  4020  4110  4120  4210  4220  4640  4650  4820  4830
                          4560  50020 50030   50070 50080  5010    50090 50100 5020  50290 50300 50310
                          5090  5100  5170  5180  5250  5260  5330  5340  5410  5420
                          5490  5500  5600  5610  5680  5690  5760  5770  5780  5790  5800  5810
                          5910  5920  7010  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990  2000  2210  3000  4000  5000 2000  2210  3000  4000  5000
                        }
  inventions          = { }
  policy =
  { democratic        = 10
    political_left    = 2
    freedom           = 9
    free_market       = 9
    professional_army = 9
    defense_lobby     = 10
    interventionism   = 9
  }
  landunit =
  { id       = { type = 25001 id = 182 }
    name     = "ƒJƒ„[ƒjíp‹@b—·’c"
    location = 128
    division =
    { id            = { type = 25001 id = 183 }
      name          = "‘æ1íp‹@b‘å‘à"
      model         = 1
      type          = bergsjaeger
      brigade_model = 0
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 184 }
      name          = "‘æ2íp‹@b‘å‘à"
      model         = 1
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 185 }
      name          = "‘æ3íp‹@b‘å‘à"
      model         = 1
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 186 }
      name          = "‘æ1‹@b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 187 }
      name          = "‘æ1‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 188 }
    name     = "ƒ|ƒŠíp‹@b—·’c"
    location = 128
    division =
    { id            = { type = 25001 id = 189 }
      name          = "‘æ4íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 190 }
      name          = "‘æ5íp‹@b‘å‘à"
      model         = 1
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 191 }
      name          = "‘æ6íp‹@b‘å‘à"
      model         = 1
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 192 }
      name          = "‘æ2‹@b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 193 }
      name          = "‘æ2‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 194 }
    name     = "ƒJƒŒƒŠƒAíp‹@b—·’c"
    location = 125
    division =
    { id            = { type = 25001 id = 195 }
      name          = "‘æ7íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 196 }
      name          = "‘æ8íp‹@b‘å‘à"
      model         = 1
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 197 }
      name          = "‘æ9íp‹@b‘å‘à"
      model         = 1
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 198 }
      name          = "‘æ3‹@b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 199 }
      name          = "‘æ3‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 200 }
    name     = "‘æ4íÔ—·’c"
    location = 125
    division =
    { id            = { type = 25001 id = 201 }
      name          = "‘æ10íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 202 }
      name          = "‘æ4‹@b‘å‘à"
      model         = 2
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 203 }
      name          = "‘æ5‹@b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 204 }
      name          = "‘æ4‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 205 }
      name          = "‘æ5‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 206 }
    name     = "‘æ14íÔ—·’c"
    location = 125
    division =
    { id            = { type = 25001 id = 207 }
      name          = "‘æ11íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 208 }
      name          = "‘æ6‹@b‘å‘à"
      model         = 2
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 209 }
      name          = "‘æ7‹@b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 210 }
      name          = "‘æ6‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 211 }
      name          = "‘æ7‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 212 }
    name     = "‘æ2íÔ—·’c"
    location = 126
    division =
    { id            = { type = 25001 id = 213 }
      name          = "‘æ12íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 214 }
      name          = "‘æ8‹@b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 215 }
      name          = "‘æ9‹@b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 216 }
      name          = "‘æ8‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 217 }
      name          = "‘æ9‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 232 }
    name     = "–k•”ŒRŠÇ‹æ"
    location = 125
    home     = 125
    division =
    { id            = { type = 25001 id = 233 }
      name          = "–k•”ŒRŠÇ‹æi—ß•”"
      model         = 2
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 234 }
    name     = "¼•”ŒRŠÇ‹æ"
    location = 128
    home     = 128
    division =
    { id            = { type = 25001 id = 235 }
      name          = "¼•”ŒRŠÇ‹æi—ß•”"
      model         = 2
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 236 }
    name     = "“ì•”ŒRŠÇ‹æ"
    location = 127
    home     = 127
    division =
    { id            = { type = 25001 id = 237 }
      name          = "“ì•”ŒRŠÇ‹æi—ß•”"
      model         = 2
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
}
