
##############################
# Country definition for TUR #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = TUR
  manpower            = 4250
  energy              = 58000
  metal               = 36000
  rare_materials      = 45000
  oil                 = 12000
  supplies            = 8000
  money               = 3500
  capital             = 448
  transports          = 1800
  escorts             = 1500
  regular_id          = U03
  nationalprovinces   = { 408 409 437 438 439 440 441 442 443 444 445 446 447 448 449 450 1158 1159 1851 1852 1853 1854 1855 2322 }
  ownedprovinces      = { 408 409 437 438 439 440 441 442 443 444 445 446 447 448 449 450 1158 1159 1851 1852 1853 1854 1855 2322 }
  controlledprovinces = { 408 409 437 438 439 440 441 442 443 444 445 446 447 448 449 450 1158 1159 1851 1852 1853 1854 1855 2322 }
  techapps            = { 
                         1130 1230 1570 1670 1770 1870 1970
                         2010 2020 2030 2040 2050 2310 2320 2610 2620 2910 2920 10050 10060 1010  10190 1020  10200 1030  1050  1110  1120 
                          1210  1220  1470  1490  1510  1530  1550  1560  1650  1660
                          1750  1760  1850  1860  1950  1960
                          3010  3020  30410 30420 30510 30520 3110 
                          3120  3210  3220  3460  3470
                          3560  3640  3650  3910  3920
                          3940  40100 40110 4390  4400  4010  4020  4110  4120  4210  4220  4640  4650  4820  4830
                          4560  50020 50030 50040 50050 50070 50080 50090 5010  50100 50090 50100 50090 50100 5020  50290 50300 50310
                          5090  5100  5170  5180  5250  5260  5330  5340  5410  5420
                          5490  5500  5600  5610  5680  5690  5760  5770  5780  5790  5800  5810
                          5910  5920  7010  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990  2000  2210  3000  4000  5000
                          6130  6120  6310
                        }
  inventions          = { }
  policy =
  { democratic        = 10
    political_left    = 2
    freedom           = 9
    free_market       = 9
    professional_army = 9
    defense_lobby     = 10
    interventionism   = 9
  }
landunit = {
	name = "‘æ1‹@bt’c"
	id = { type = 10050 id = 1 }
	location = 1855
	division = {
	id = { type = 10050 id = 2 }
	name = "‘æ1íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 3 }
	name = "‘æ2íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 4 }
	name = "‘æ3íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 5 }
	name = "‘æ1‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	extra = anti_air
	brigade_model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 6 }
	name = "‘æ2‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	extra = anti_air
	brigade_model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 7 }
	name = "‘æ3‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
  }
landunit = {
	name = "‘æ5•à•ºt’c"
	id = { type = 10050 id = 78 }
	location = 1855
	division = {
	id = { type = 10050 id = 79 }
	name = "‘æ18íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 80 }
	name = "‘æ31‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 81 }
	name = "‘æ32‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 82 }
	name = "‘æ33‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 83 }
	name = "‘æ34‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 84 }
	name = "‘æ35‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ25•à•ºt’c"
	id = { type = 10050 id = 85 }
	location = 1855
	division = {
	id = { type = 10050 id = 86 }
	name = "‘æ19íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 87 }
	name = "‘æ36‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 88 }
	name = "‘æ37‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 89 }
	name = "‘æ38‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 90 }
	name = "‘æ39‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 91 }
	name = "‘æ40‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
  }
landunit = {
	name = "‘æ3•à•ºt’c"
	id = { type = 10050 id = 22 }
	location = 1855
	division = {
	id = { type = 10050 id = 23 }
	name = "‘æ10íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 24 }
	name = "‘æ1©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 25 }
	name = "‘æ2©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 26 }
	name = "‘æ3©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 27 }
	name = "‘æ7‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 28 }
	name = "‘æ8‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ26•à•ºt’c"
	id = { type = 10050 id = 29 }
	location = 1855
	division = {
	id = { type = 10050 id = 30 }
	name = "‘æ11íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 31 }
	name = "‘æ4©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 32 }
	name = "‘æ5©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 33 }
	name = "‘æ6©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 34 }
	name = "‘æ9‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 35 }
	name = "‘æ10‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ28•à•ºt’c"
	id = { type = 10050 id = 36 }
	location = 1855
	division = {
	id = { type = 10050 id = 37 }
	name = "‘æ12íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 38 }
	name = "‘æ7©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 39 }
	name = "‘æ8©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 40 }
	name = "‘æ9©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 41 }
	name = "‘æ11‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 42 }
	name = "‘æ12‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ2•à•ºt’c"
	id = { type = 10050 id = 43 }
	location = 1855
	division = {
	id = { type = 10050 id = 44 }
	name = "‘æ13íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 45 }
	name = "‘æ10©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 46 }
	name = "‘æ11©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 47 }
	name = "‘æ12©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 48 }
	name = "‘æ13‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 49 }
	name = "‘æ14‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ47•à•ºt’c"
	id = { type = 10050 id = 50 }
	location = 1855
	division = {
	id = { type = 10050 id = 51 }
	name = "‘æ14íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 52 }
	name = "‘æ13©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 53 }
	name = "‘æ14©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 54 }
	name = "‘æ15©“®Ô‰»•à•º‘å‘à"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 10050 id = 55 }
	name = "‘æ15‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 10050 id = 56 }
	name = "‘æ16‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
 }
}
