
##############################
# Country definition for U07 #
##############################

province = { id = 53 landfort = 10 } # プラハティッエ
province = { id = 208 anti_air = 1 } # ブィドゴシュチュ
province = { id = 211 anti_air = 1 } # カリシュ
province =
{ id         = 303
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
}              # ダンツィヒ
province = { id = 305 anti_air = 1 } # プウォツク
province =
{ id         = 306
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # グディニャ
province = { id = 307 anti_air = 1 } # トルン
province = { id = 466 landfort = 10 } # カルロヴィ・ヴァリ
province = { id = 467 landfort = 10 } # ズノイモ
province = { id = 468 landfort = 10 } # フラデツ・クラーロヴェー
province =
{ id       = 469
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # プラハ
province =
{ id       = 470
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ピルセン
province = { id = 471 landfort = 10 } # リベレツ
province = { id = 472 landfort = 10 } # オパヴァ
province =
{ id       = 474
  anti_air = 2
  landfort = 5
  air_base = { size = 2 current_size = 2 }
}            # オストラヴァ
province = { id = 475 anti_air = 2 } # ブルノ
province =
{ id       = 479
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # クラクフ
province = { id = 480 anti_air = 1 } # チェンストホーヴァ
province =
{ id       = 481
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ウッチ
province = { id = 483 anti_air = 2 } # ポズナン
province =
{ id       = 485
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
}            # ワルシャワ
province = { id = 486 anti_air = 2 } # カトヴィツェ
province =
{ id       = 487
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ルブリン
province = { id = 505 anti_air = 1 } # ビェルスク
province = { id = 509 anti_air = 1 } # スヴァウキ
province = { id = 478 landfort = 10 }
province = { id = 1887 landfort = 10 }
province = { id = 499 landfort = 10 }
province = { id = 1402 landfort = 10 }
province = { id = 1403 landfort = 10 }
province = { id = 1173 landfort = 10 }
province = { id = 1401 landfort = 10 }
province = { id = 230 landfort = 10 }
province = { id = 434 landfort = 10 }
province = { id = 435 landfort = 10 }
province = { id = 296 ic = 1 naval_base = 8 air_base = 5 } # ロストック
province = { id = 300 ic = 2 air_base = 10 } # ベルリン
province = { id = 301 landfort = 9 } # シュトラールズント
province = { id = 309 landfort = 9 } # コットブス
province = { id = 310 ic = 1 air_base = 6 } # ライプツィヒ
province = { id = 311 ic = 1 air_base = 4 } # ドレスデン
province = { id = 546 landfort = 9 } # フランクフルト・アン・デア・オーダー

#####################
# Country main data #
#####################

country =
{ tag                 = U07
  manpower            = 850
  energy              = 58000
  metal               = 38000
  rare_materials      = 48000
  oil                 = 5900
  supplies            = 8000
  money               = 580
  regular_id          = U06
  transports          = 250
  escorts             = 150
  capital             = 469
  policy              = { democratic = 3 political_left = 9 freedom = 2 free_market = 2 professional_army = 9 defense_lobby = 10 interventionism = 9 }
  nationalprovinces   = { 53 466 467 468 469 470 471 472 474 475 476 477 478 490 499 1887 1888 1889 1566 1874 1885 230 
                          423 424 425 426 427 428 429 430 431 432 433 434 435 436 495 496 498 1173 1401 1402 1403 1449
                          1899 2449 2450 2602 2603 2604 2605 224 456 457 458 491 492 497 1890 2447 291 380 381 382 383 
                          384 385 386 387 388 389 390 391 392 393 394 395 396 398 399 400 401 402 403 405 410 411 412 413 414 
                          415 416 417 418 419 420 421 422 451 452 453 454 455 459 493 494 563 653 664 665 1057 1168 1169 1891 
                          1892 1893 1894 1895 1896 1897 1911 2319 2321 2323 2324 296 297 298 299 300 301 546 84 309 310 311 302 
                          1779 1810 1400 473 482 1623 1595 }
  ownedprovinces      = { 53 466 467 468 469 470 471 472 474 475 476 477 478 490 499 1887 1888 1889 230 
                          423 424 425 426 427 428 429 430 431 432 433 434 435 436 495 496 498 1173 1401 1402 1403 1449
                          1899 2449 2450 2602 2603 2604 2605 224 456 457 458 491 492 497 1890 2447 291 380 381 382 383 
                          384 385 386 387 388 389 390 391 392 393 394 395 396 398 399 400 401 402 403 405 410 411 412 413 414 
                          415 416 417 418 419 420 421 422 451 452 453 454 455 459 493 494 563 653 664 665 1057 1168 1169 1891 
                          1892 1893 1894 1895 1896 1897 1911 2319 2321 2323 2324 296 297 298 299 300 301 546 84 309 310 311 2322
                          409 }
  controlledprovinces = { 53 466 467 468 469 470 471 472 474 475 476 477 478 490 499 1887 1888 1889 230 
                          423 424 425 426 427 428 429 430 431 432 433 434 435 436 495 496 498 1173 1401 1402 1403 1449
                          1899 2449 2450 2602 2603 2604 2605 224 456 457 458 491 492 497 1890 2447 291 380 381 382 383 
                          384 385 386 387 388 389 390 391 392 393 394 395 396 398 399 400 401 402 403 405 410 411 412 413 414 
                          415 416 417 418 419 420 421 422 451 452 453 454 455 459 493 494 563 653 664 665 1057 1168 1169 1891 
                          1892 1893 1894 1895 1896 1897 1911 2319 2321 2323 2324 296 297 298 299 300 301 546 84 309 310 311 2322
                          409 }
  techapps            = { 
                         1130 1230 1570 1670 1770 1870 1970
                         2010 2020 2030 2040 2050 2310 2320 2610 2620 2910 2920 
                         1130 1230 1570 1670 1770 1870 1970
                         2010 2020 2030 2040 2050 2310 2320 2610 2620 2910 2920 10050 10060 1010  10150 10190 1020  10200 1030  10390 10440 1110  1120  1130  1210  1220  1230  1470  1550  1560  1570 
                          1650  1660  1670  1750  1760  1850  1860  1950  2010  2020  20210 2030  20310 2040  20510 2310  2320  2610  2620  2910 
                          2920  3010  3020  3030  30410 30510 3110  3120  3210  3220  3310  3460  3470  3480  3610  3710  3810  3820  3830  40000
                          40010 40020 4010  40100 40110 40120 4020  40200 4110  4120  4210  4390  4400  4410  4560  4640  4650  4660  4820  4830 
                          50020 50030 50040 50070 50080 50090 5010  50100 50090 50100 50190 5020  50290 5030  50300 5090  5100  5170  5250  5330  5340 
                          5410  5420  5490  5600  5610  5620  5680  5760  5770  5780  5910  5920  5930  6010  6030  6060  6740  6750  6760  6770 
                          6780  7010  7030  7670  80080 80090 8010  80160 8020  8030  8040  8050  8060  8070  8480  8490  8500  90040 9010  90140
                          90190 9020  9030  9040  9050  9190  9200  9340  9350  9360  9370  9380  9390  9520  9670  9680  9690  9700  9840  9850 
                        }
  free                = { energy = 180 metal = 100 rare_materials = 100 oil = 30 ic = 10 }
 #ドイツ民主共和国国家人民軍
  landunit =
  { id       = { type = 15011 id = 1 }
    name     = "国家人民軍総司令部直轄予備"
    location = 300
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 1 }
      name          = "国家人民軍総司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 2 }
      name          = "第601戦術機中隊"
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 3 }
      name          = "第602戦術機中隊"
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 4 }
      name          = "第603戦術機中隊"
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 5 }
      name          = "第604戦術機中隊"
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 6 }
      name          = "第304機動歩兵大隊"
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 7 }
      name          = "第1戦車大隊"
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 8 }
      name          = "第2戦車大隊"
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 9 }
      name          = "第3戦車大隊"
    }
  }
  landunit =
  { id       = { type = 15011 id = 2 }
    name     = "国家人民軍オーデル軍集団"
    location = 309
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 10 }
      name          = "国家人民軍オーデル軍集団司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 11 }
      name          = "第641戦術機中隊"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 12 }
      name          = "第642戦術機中隊"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 13 }
      name          = "第643戦術機中隊"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 14 }
      name          = "第644戦術機中隊"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 15 }
      name          = "第344機動歩兵大隊"
      experience    = 43
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 16 }
      name          = "第12戦車大隊"
      experience    = 63
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 17 }
      name          = "第13戦車大隊"
      experience    = 61
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 18 }
      name          = "第14戦車大隊"
      experience    = 71
    }
  }
  landunit =
  { id       = { type = 15011 id = 3 }
    name     = "国家人民軍ナイセ軍集団"
    location = 546
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 19 }
      name          = "国家人民軍ナイセ軍集団司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 20 }
      name          = "第651戦術機中隊"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 21 }
      name          = "第652戦術機中隊"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 22 }
      name          = "第653戦術機中隊"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 23 }
      name          = "第654戦術機中隊"
      experience    = 61
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 24 }
      name          = "第394機動歩兵大隊"
      experience    = 43
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 25 }
      name          = "第395機動歩兵大隊"
      experience    = 43
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 26 }
      name          = "第25戦車大隊"
      experience    = 33
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 27 }
      name          = "第26戦車大隊"
      experience    = 31
    }
  }
  landunit =
  { id       = { type = 15011 id = 4 }
    name     = "国家人民軍東方総軍"
    location = 301
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 28 }
      name          = "国家人民軍東方総軍司令部"
      experience    = 88
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 29 }
      name          = "第661戦術機中隊"
      experience    = 67
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 30 }
      name          = "第662戦術機中隊"
      experience    = 66
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 31 }
      name          = "第663戦術機中隊"
      experience    = 67
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 32 }
      name          = "第664戦術機中隊"
      experience    = 66
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 33 }
      name          = "第398機動歩兵大隊"
      experience    = 48
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 34 }
      name          = "第399機動歩兵大隊"
      experience    = 48
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 35 }
      name          = "第33戦車大隊"
      experience    = 38
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 36 }
      name          = "第34戦車大隊"
      experience    = 74
    }
  }
  landunit =
  { id       = { type = 15011 id = 5 }
    name     = "臨時集成戦術機大隊ハンニバル"
    location = 301
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 37 }
      name          = "第666戦術機中隊"
      experience    = 100
      strength     = 22
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 38 }
      name          = "第667戦術機中隊"
      experience    = 67
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 39 }
      name          = "第668戦術機中隊"
      experience    = 67
      strength     = 33
      max_strength = 33
    }
  }
  landunit =
  { id       = { type = 15011 id = 6 }
    name     = "武装警察軍第1戦術機甲連隊"
    location = 300
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 40 }
      name          = "武装警察軍総軍司令部"
      experience    = 88
      extra         = rocket_artillery
      brigade_model = 2
      locked = yes
    }
    division =
    { type          = infantry
      model         = 2
      id            = { type = 15004 id = 41 }
      name          = "ヴェアヴォルフ大隊"
      experience    = 90
      locked = yes
    }
    division =
    { type          = infantry
      model         = 2
      id            = { type = 15004 id = 42 }
      name          = "ヴァンピーレ大隊"
      experience    = 67
      locked = yes
    }
    division =
    { type          = infantry
      model         = 2
      id            = { type = 15004 id = 43 }
      name          = "ジークフリート大隊"
      experience    = 67
      locked = yes
    }
  }
  landunit =
  { id       = { type = 15011 id = 7 }
    name     = "第501戦術機甲大隊"
    location = 309
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 44 }
      name          = "第304戦術機中隊"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 45 }
      name          = "第305戦術機中隊"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 46 }
      name          = "第306戦術機中隊"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
  }
  landunit =
  { id       = { type = 15011 id = 8 }
    name     = "第221戦術機甲大隊"
    location = 309
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 47 }
      name          = "第25戦術機中隊"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 48 }
      name          = "第36戦術機中隊"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 49 }
      name          = "第47戦術機中隊"
      experience    = 30
      strength     = 33
      max_strength = 33
    }
  }
  landunit =
  { id       = { type = 15011 id = 9 }
    name     = "ホーネッカー機械化軍団"
    location = 546
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 50 }
      name          = "プリンツ･オイゲン大隊"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 51 }
      name          = "ホーエンシュタウフェン大隊"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 52 }
      name          = "ハンジャ大隊"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 53 }
      name          = "スカンデルベグ大隊"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 54 }
      name          = "ケンプフ大隊"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 55 }
      name          = "ゲッツ・フォン・ベルリヒンゲン大隊"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 56 }
      name          = "ホルスト・ヴェッセル大隊"
      experience    = 20
    }
  }
  landunit =
  { id       = { type = 15011 id = 10 }
    name     = "国家人民軍西方総軍"
    location = 84
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 57 }
      name          = "国家人民軍西方総軍司令部"
      experience    = 88
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 2
      id            = { type = 15004 id = 58 }
      name          = "第4戦術機中隊"
      experience    = 30
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 2
      id            = { type = 15004 id = 59 }
      name          = "第5戦術機中隊"
      experience    = 30
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 2
      id            = { type = 15004 id = 60 }
      name          = "第6戦術機中隊"
      experience    = 30
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
    division =
    { type          = paratrooper
      model         = 2
      id            = { type = 15004 id = 61 }
      name          = "第7戦術機中隊"
      experience    = 30
      extra         = rocket_artillery
      brigade_model = 2
      strength     = 33
      max_strength = 33
    }
  }
  landunit =
  { id       = { type = 15011 id = 11 }
    name     = "第7機械化歩兵軍団"
    location = 546
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 62 }
      name          = "パウル･レヴィ大隊"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 63 }
      name          = "ラーコシ･マーチャーシュ大隊"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 64 }
      name          = "ハインリヒ･ブランドラー大隊"
      experience    = 20
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 65 }
      name          = "クン･ベーラ大隊"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 66 }
      name          = "ルート･フィッシャー大隊"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 67 }
      name          = "アルカディ･マズロー大隊"
      experience    = 20
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 68 }
      name          = "エルンスト･テールマン大隊"
      experience    = 20
    }
  }
  landunit =
  { id       = { type = 15004 id = 69 }
    name     = "チェコスロバキア軍第7機械化旅団"
    location = 471
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 70 }
      name          = "第7機械化旅団司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 71 }
      name          = "第6戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 72 }
      name          = "第7戦術機大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 73 }
      name          = "第71機械化大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 74 }
      name          = "第72機械化大隊"
      strength     = 100
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 75 }
      name          = "第73戦車大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 76 }
      name          = "第74軽自動車化大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 77 }
    name     = "ルーマニア軍第1歩兵師団「ダキア」"
    location = 468
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 78 }
      name          = "第1歩兵師団司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 79 }
      name          = "第313戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 80 }
      name          = "第53戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 81 }
      name          = "第205戦術機甲大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 82 }
      name          = "第21機械化大隊"
      strength     = 100
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 83 }
      name          = "第114戦車大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 84 }
      name          = "第2歩兵大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 85 }
    name     = "ハンガリー軍第5歩兵旅団"
    location = 472
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 86 }
      name          = "第5歩兵旅団司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 87 }
      name          = "第62戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 88 }
      name          = "第24戦術機大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 89 }
      name          = "第1軽歩兵大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 90 }
      name          = "第2軽歩兵大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 91 }
      name          = "第3軽歩兵大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 92 }
    name     = "ハンガリー軍第25歩兵旅団"
    location = 474
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 93 }
      name          = "第25歩兵旅団司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = light_armor
      model         = 3
      id            = { type = 15004 id = 94 }
      name          = "第1軽戦車大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 95 }
      name          = "第111戦術機大隊"
      extra         = rocket_artillery
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 96 }
      name          = "第7軽歩兵大隊"
      extra         = rocket_artillery
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 97 }
      name          = "第8軽歩兵大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 98 }
      name          = "第10軽歩兵大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 99 }
    name     = "東ドイツ軍東欧派遣軍"
    location = 469
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 100 }
      name          = "東欧派遣軍司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 3
      id            = { type = 15004 id = 101 }
      name          = "第528戦術機大隊"
      extra         = rocket_artillery
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 102 }
      name          = "第200戦術機大隊"
      extra         = rocket_artillery
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 103 }
      name          = "第8機械化大隊"
      extra         = rocket_artillery
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 104 }
    name     = "チェコスロバキア軍第4緊急展開旅団"
    location = 478
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 105 }
      name          = "第4緊急展開旅団司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 106 }
      name          = "第16戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 107 }
      name          = "第27戦術機大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 108 }
      name          = "第41機械化大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 109 }
      name          = "第42機械化大隊"
      strength     = 100
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 15004 id = 110 }
      name          = "第43空挺戦車大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 111 }
      name          = "第44軽自動車化大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 112 }
    name     = "ポーランド軍第11装甲騎兵師団"
    location = 1887
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 113 }
      name          = "第23戦術機大隊"
      extra         = rocket_artillery
      strength     = 60
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 114 }
      name          = "第2戦術機大隊"
      strength     = 50
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 115 }
      name          = "第31機械化大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 116 }
      name          = "第12機械化大隊"
      strength     = 100
    }
    division =
    { type          = armor
      model         = 4
      id            = { type = 15004 id = 117 }
      name          = "第16戦車大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 118 }
    name     = "ポーランド軍第16機械化歩兵師団"
    location = 499
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 119 }
      name          = "第33戦術機大隊"
      extra         = rocket_artillery
      strength     = 60
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 120 }
      name          = "第21高地ライフル旅団"
      strength     = 80
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 121 }
      name          = "第34機械化大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 122 }
      name          = "第25機械化大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 123 }
      name          = "第25空中騎兵旅団"
      strength     = 70
    }
  }
  landunit =
  { id       = { type = 15004 id = 124 }
    name     = "ハンガリー軍第6軍"
    location = 1887
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 125 }
      name          = "第25戦術機甲大隊"
      extra         = rocket_artillery
      strength     = 60
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 126 }
      name          = "第79戦術機甲大隊"
      strength     = 80
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 127 }
      name          = "第28機械化大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 128 }
      name          = "第92機械化大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 129 }
      name          = "第93機械化大隊"
      strength     = 70
    }
  }
  landunit =
  { id       = { type = 15004 id = 130 }
    name     = "チェコスロバキア軍第8軍"
    location = 499
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 131 }
      name          = "第1戦術機甲大隊"
      extra         = rocket_artillery
      strength     = 60
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 132 }
      name          = "第2戦術機甲大隊"
      strength     = 80
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 133 }
      name          = "第3戦術機甲大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 134 }
      name          = "第4戦術機甲大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 135 }
      name          = "第30機械化大隊"
      strength     = 70
    }
    division =
    { type          = mechanized
      model         = 4
      id            = { type = 15004 id = 136 }
      name          = "第72機械化大隊"
      strength     = 70
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 137 }
      name          = "第95戦術機甲大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 138 }
      name          = "第26戦術機甲大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 139 }
    name     = "ルーマニア軍第2歩兵師団「ゲティカ」"
    location = 1403
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 140 }
      name          = "第2歩兵師団司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 141 }
      name          = "第32戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 142 }
      name          = "第191戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 143 }
      name          = "第17戦術機甲大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 144 }
      name          = "第24機械化大隊"
      strength     = 100
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 145 }
      name          = "第814戦車大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 146 }
      name          = "第911歩兵大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 174 }
    name     = "ルーマニア軍第4歩兵師団「ゲミナ」"
    location = 1402
    division =
    { type          = hq
      model         = 2
      id            = { type = 15004 id = 175 }
      name          = "第4歩兵師団司令部"
      extra         = rocket_artillery
      brigade_model = 2
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 176 }
      name          = "第341戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 177 }
      name          = "第631戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 178 }
      name          = "第284戦術機甲大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 179 }
      name          = "第151機械化大隊"
      strength     = 100
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 180 }
      name          = "第912戦車大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 181 }
      name          = "第811歩兵大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 182 }
    name     = "ブルガリア軍第2戦術機甲旅団"
    location = 230
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 183 }
      name          = "第1戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 184 }
      name          = "第2戦術機大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 185 }
      name          = "第1機械化大隊"
      strength     = 100
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 186 }
      name          = "第1戦車大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 187 }
    name     = "ブルガリア軍第61戦術機甲旅団"
    location = 1173
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 188 }
      name          = "第3戦術機大隊"
      strength     = 100
    }
    division =
    { type          = paratrooper
      model         = 4
      id            = { type = 15004 id = 189 }
      name          = "第4戦術機大隊"
      strength     = 100
    }
    division =
    { type          = mechanized
      model         = 2
      id            = { type = 15004 id = 190 }
      name          = "第2機械化大隊"
      strength     = 100
    }
    division =
    { type          = armor
      model         = 2
      id            = { type = 15004 id = 191 }
      name          = "第2戦車大隊"
      strength     = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 192 }
    name     = "チェコスロヴァキア軍第1戦術機甲師団"
    location = 1401
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 193 }
      name  = "第4戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 194 }
      name  = "第5戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 195 }
      name  = "第6戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 196 }
      name  = "第1戦車大隊"
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 197 }
      name  = "第2戦車大隊"
    }
    division =
    { type  = mechanized
      model = 2
      id    = { type = 15004 id = 198 }
      name  = "第3機械化狙撃兵大隊"
    }
  }
  landunit =
  { id       = { type = 15004 id = 199 }
    name     = "ユーゴスラビア軍第1戦術機甲師団"
    location = 434
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 200 }
      name  = "第1戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 201 }
      name  = "第2戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 202 }
      name  = "第3戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 203 }
      name  = "第1戦車大隊"
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 204 }
      name  = "第2戦車大隊"
    }
    division =
    { type  = mechanized
      model = 2
      id    = { type = 15004 id = 205 }
      name  = "第1機械化狙撃兵大隊"
    }
  }
  landunit =
  { id       = { type = 15004 id = 206 }
    name     = "ユーゴスラビア軍第2戦術機甲師団"
    location = 435
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 207 }
      name  = "第4戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 208 }
      name  = "第5戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 209 }
      name  = "第6戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 210 }
      name  = "第3戦車大隊"
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 211 }
      name  = "第4戦車大隊"
    }
    division =
    { type  = mechanized
      model = 2
      id    = { type = 15004 id = 212 }
      name  = "第2機械化狙撃兵大隊"
    }
  }
  landunit =
  { id       = { type = 15004 id = 213 }
    name     = "国連軍第1東欧派遣兵団"
    location = 435
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 214 }
      name  = "第107戦術偵察大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 215 }
      name  = "第23戦術偵察大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 216 }
      name  = "第98戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 217 }
      name  = "第226戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 218 }
      name  = "第706戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 219 }
      name  = "第907戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 15004 id = 220 }
    name     = "国連軍第2東欧派遣兵団"
    location = 434
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 221 }
      name  = "第500戦術偵察大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 222 }
      name  = "第142戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 223 }
      name  = "第606戦術機甲大隊"
      extra         = artillery
      brigade_model = 2
    }
  }
  landunit =
  { id       = { type = 15004 id = 224 }
    name     = "国連軍第101機甲旅団"
    location = 1401
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 225 }
      name  = "第501戦術偵察大隊"
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 226 }
      name  = "第667機甲大隊"
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 227 }
      name  = "第668機甲大隊"
    }
    division =
    { id            = { type = 15004 id = 228 }
      name          = "第16機械化装甲歩兵大隊"
      model         = 2
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 15004 id = 229 }
      name          = "第17機械化装甲歩兵大隊"
      model         = 2
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 230 }
    name     = "国連軍第167機甲旅団"
    location = 1173
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 231 }
      name  = "第502戦術偵察大隊"
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 232 }
      name  = "第669機甲大隊"
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 233 }
      name  = "第670機甲大隊"
    }
    division =
    { id            = { type = 15004 id = 234 }
      name          = "第17機械化装甲歩兵大隊"
      model         = 2
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 15004 id = 235 }
      name          = "第18機械化装甲歩兵大隊"
      model         = 2
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15004 id = 236 }
    name     = "国連軍第107機甲旅団"
    location = 230
    division =
    { type  = paratrooper
      model = 2
      id    = { type = 15004 id = 237 }
      name  = "第503戦術偵察大隊"
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 238 }
      name  = "第6671機甲大隊"
    }
    division =
    { type  = armor
      model = 2
      id    = { type = 15004 id = 239 }
      name  = "第672機甲大隊"
    }
    division =
    { id            = { type = 15004 id = 240 }
      name          = "第19機械化装甲歩兵大隊"
      model         = 2
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 15004 id = 241 }
      name          = "第20機械化装甲歩兵大隊"
      model         = 2
      type          = mechanized
      strength      = 100
    }
  }
  navalunit =
  { id       = { type = 15102 id = 6 }
    name     = "人民海軍"
    location = 296
    base     = 296
    division =
    { type  = battleship
      model = 3
      id    = { type = 15105 id = 43 }
      name  = "Karl Marx"
    }
    division =
    { type  = escort_carrier
      model = 5
      id    = { type = 15105 id = 44 }
      name  = "Peenemunde"
    }
    division =
    { type  = battlecruiser
      model = 5
      id    = { type = 15105 id = 45 }
      name  = "Hertha"
    }
    division =
    { type  = battlecruiser
      model = 5
      id    = { type = 15105 id = 46 }
      name  = "Freya"
    }
    division =
    { type  = battlecruiser
      model = 5
      id    = { type = 15105 id = 47 }
      name  = "Vineta"
    }
    division =
    { type  = battlecruiser
      model = 5
      id    = { type = 15105 id = 48 }
      name  = "Hansa"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 49 }
      name  = "揚陸艇1号"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 50 }
      name  = "揚陸艇2号"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 51 }
      name  = "揚陸艇3号"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 52 }
      name  = "揚陸艇4号"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 53 }
      name  = "揚陸艇5号"
    }
    division =
    { type  = transport
      model = 4
      id    = { type = 15105 id = 54 }
      name  = "揚陸艇6号"
    }
  }
}