
##############################
# Country definition for U02 #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = YUG
  manpower            = 4250
  energy              = 58000
  metal               = 36000
  rare_materials      = 45000
  oil                 = 12000
  supplies            = 8000
  money               = 3500
  capital             = 453
  transports          = 1800
  escorts             = 1500
  regular_id          = U06
  nationalprovinces   = { 291 380 381 382 383 384 455 459 1893 385 386 387 388 1891 1892 452 453 454 493 494 1057 1895 1897 389 413 414 415 451 1168 1169 1894 1896 }
  ownedprovinces      = { 291 380 381 382 383 384 455 459 1893 385 386 387 388 1891 1892 452 453 454 493 494 1057 1895 1897 389 413 414 415 451 1168 1169 1894 1896 }
  controlledprovinces = { 291 380 381 382 383 384 455 459 1893 385 386 387 388 1891 1892 452 453 454 493 494 1057 1895 1897 389 413 414 415 451 1168 1169 1894 1896 }
  techapps            = { 
                         1130 1230 1570 1670 1770 1870 1970
                         2010 2020 2030 2040 2050 2310 2320 2610 2620 2910 2920 10050 10060 1010  10190 1020  10200 1030  1050  1110  1120 
                          1210  1220  1470  1490  1510  1530  1550  1560  1650  1660
                          1750  1760  1850  1860  1950  1960
                          3010  3020  30410 30420 30510 30520 3110 
                          3120  3210  3220  3460  3470
                          3560  3640  3650  3910  3920
                          3940  40100 40110 4390  4400  4010  4020  4110  4120  4210  4220  4640  4650  4820  4830
                          4560  50020 50030 50040 50050 50070 50080 50090 5010  50100 50090 50100 50090 50100 5020  50290 50300 50310
                          5090  5100  5170  5180  5250  5260  5330  5340  5410  5420
                          5490  5500  5600  5610  5680  5690  5760  5770  5780  5790  5800  5810
                          5910  5920  7010  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990  6000  6010  6020  6030  6040
                        }
  inventions          = { }
  policy              = { democratic = 2 political_left = 9 freedom = 2 free_market = 2 professional_army = 9 defense_lobby = 10 interventionism = 9 }
  landunit =
  { id       = { type = 25181 id = 118 }
    name     = "‘æ4íp‹@bt’c"
    location = 291
    division =
    { id            = { type = 25181 id = 119 }
      name          = "‘æ1íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 120 }
      name          = "‘æ2íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 121 }
      name          = "‘æ3íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 122 }
      name          = "‘æ4íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 123 }
      name          = "‘æ5íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 124 }
      name          = "‘æ6íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 125 }
      name          = "‘æ7íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 126 }
      name          = "‘æ8íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 127 }
      name          = "‘æ9íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 128 }
      name          = "‘æ1íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 129 }
      name          = "‘æ2íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 130 }
      name          = "‘æ3íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25181 id = 131 }
    name     = "‘æ5íp‹@bt’c"
    location = 383
    division =
    { id            = { type = 25181 id = 132 }
      name          = "‘æ10íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 133 }
      name          = "‘æ11íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 134 }
      name          = "‘æ12íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 135 }
      name          = "‘æ13íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 136 }
      name          = "‘æ14íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 137 }
      name          = "‘æ15íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 138 }
      name          = "‘æ16íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 139 }
      name          = "‘æ17íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 140 }
      name          = "‘æ18íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 141 }
      name          = "‘æ4íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 142 }
      name          = "‘æ5íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 143 }
      name          = "‘æ6íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25181 id = 144 }
    name     = "‘æ3íp‹@bt’c"
    location = 459
    division =
    { id            = { type = 25181 id = 145 }
      name          = "‘æ19íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 146 }
      name          = "‘æ20íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 147 }
      name          = "‘æ21íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 148 }
      name          = "‘æ22íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 149 }
      name          = "‘æ23íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 150 }
      name          = "‘æ24íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 151 }
      name          = "‘æ25íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 152 }
      name          = "‘æ26íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 153 }
      name          = "‘æ27íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 154 }
      name          = "‘æ7íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 155 }
      name          = "‘æ8íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 156 }
      name          = "‘æ9íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25181 id = 157 }
    name     = "‘æ7íp‹@bt’c"
    location = 452
    division =
    { id            = { type = 25181 id = 158 }
      name          = "‘æ28íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 159 }
      name          = "‘æ29íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 160 }
      name          = "‘æ30íp‹@b‘å‘à"
      model         = 1
      brigade_model = 0
      type          = infantry
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 161 }
      name          = "‘æ31íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 162 }
      name          = "‘æ32íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 163 }
      name          = "‘æ33íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 164 }
      name          = "‘æ34íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 165 }
      name          = "‘æ35íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 166 }
      name          = "‘æ36íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 167 }
      name          = "‘æ10íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 168 }
      name          = "‘æ11íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25181 id = 169 }
      name          = "‘æ12íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
}
