
##############################
# Country definition for ARG #
##############################

province = { id = 667 ic = 4 } # ƒ‰ƒvƒ‰ƒ^
province = { id = 843 ic = 2 } # ƒTƒ‹ƒ^
province =
{ id       = 844
  air_base = { size = 2 current_size = 2 }
}            # ƒŒƒVƒXƒeƒ“ƒVƒA
province = { id = 845 nuclear_power = 3 } # ƒƒTƒŠƒI
province = { id = 850 ic = 3 } # ƒRƒŠƒGƒ“ƒeƒX
province =
{ id         = 851
  ic         = 8
  anti_air   = 5
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # ƒuƒGƒmƒXƒAƒCƒŒƒX
province =
{ id            = 852
  air_base      = { size = 2 current_size = 2 }
  nuclear_power = 4
}                 # ƒRƒ‹ƒhƒo
province = { id = 853 ic = 3 } # ƒTƒ“Eƒ~ƒQƒ‹EƒfEƒgƒDƒNƒ}ƒ“
province =
{ id         = 857
  ic         = 3
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 4 current_size = 4 }
}              # ƒ}ƒ‹Eƒfƒ‹Eƒvƒ‰ƒ^
province = { id = 858 ic = 2 } # ƒŠƒIEƒKƒWƒF[ƒSƒX
province =
{ id         = 859
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # ƒRƒ‚ƒhƒEƒŠƒoƒ_ƒrƒA

#####################
# Country main data #
#####################

country =
{ tag                 = ARG
  manpower            = 50
  transports          = 54
  escorts             = 18
  energy              = 5000
  metal               = 5000
  rare_materials      = 5000
  oil                 = 5000
  supplies            = 80000
  capital             = 851
  money               = 350
    regular_id = U08
  nationalprovinces   = { 667 853 852 843 844 845 851 854 855 857 858 859 862 863 850 866 }
  ownedprovinces      = { 667 853 852 843 844 845 851 854 855 857 858 859 862 863 850 }
  controlledprovinces = { 667 853 852 843 844 845 851 854 855 857 858 859 862 863 850 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  6050  6060  6070  6080  6090  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340 
                        }
  policy              = { democratic = 8 political_left = 4 freedom = 8 free_market = 7 professional_army = 3 defense_lobby = 6 interventionism = 3 }
  landunit =
  { id       = { type = 1001 id = 6155 }
    name     = "‘æ1ŒR’c"
    location = 667
    home     = 667
    division =
    { id            = { type = 1001 id = 6157 }
      name          = "‘æ1©‘–x‰‡’S•Ût’c"
      model         = 2
      brigade_model = 0
      type          = garrison
      strength      = 100
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 1001 id = 6158 }
    name     = "‘æ2ŒR’c"
    location = 844
    home     = 844
    division =
    { id            = { type = 1001 id = 6160 }
      name          = "‘æ2©‘–x‰‡’S•Ût’c"
      model         = 2
      brigade_model = 0
      type          = garrison
      strength      = 100
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 1001 id = 6161 }
    name     = "‘æ3ŒR’c"
    location = 843
    home     = 843
    division =
    { id            = { type = 1001 id = 6163 }
      name          = "‘æ3©‘–x‰‡’S•Ût’c"
      model         = 2
      brigade_model = 0
      type          = garrison
      strength      = 100
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 1001 id = 6164 }
    name     = "‘æ4ŒR’c"
    location = 852
    home     = 852
    division =
    { id            = { type = 1001 id = 6166 }
      name          = "‘æ4©‘–x‰‡’S•Ût’c"
      model         = 2
      brigade_model = 0
      type          = garrison
      strength      = 100
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 1001 id = 6167 }
    name     = "‘æ5ŒR’c"
    location = 858
    home     = 858
    division =
    { id            = { type = 1001 id = 6169 }
      name          = "‘æ5©‘–x‰‡’S•Ût’c"
      model         = 2
      brigade_model = 0
      type          = garrison
      strength      = 100
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 1001 id = 6170 }
    name     = "‘æ6ŒR’c"
    location = 851
    home     = 851
    division =
    { id            = { type = 1001 id = 6172 }
      name          = "‘æ1‹@ŠB‰»•à•ºt’c"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 1001 id = 6173 }
    name     = "‘æ7ŒR’c"
    location = 851
    home     = 851
    division =
    { id            = { type = 1001 id = 6175 }
      name          = "‘æ1å—ÍíÔt’c"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
      locked        = yes
    }
    division =
    { id            = { type = 1001 id = 6176 }
      name          = "‘æ1•à•ºíÔt’c"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
      locked        = yes
    }
  }
  navalunit =
  { id       = { type = 1002 id = 2365 }
    name     = "‘æ1í‘à"
    location = 857
    home     = 857
    base     = 857
    division =
    { id       = { type = 1002 id = 6177 }
      name     = "‘æ1ƒ~ƒTƒCƒ‹’øt’c"
      model    = 3
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 1002 id = 6178 }
      name     = "‘æ2ƒ~ƒTƒCƒ‹’øt’c"
      model    = 3
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 1002 id = 6179 }
      name     = "‘æ1‹ì’€ŠÍt’c"
      model    = 2
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 1002 id = 6180 }
      name     = "‘æ2‹ì’€ŠÍt’c"
      model    = 2
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 1002 id = 6181 }
      name     = "‘æ1—A‘—ŠÍ/—g—¤ŠÍt’c"
      model    = 4
      type     = transport
      strength            = 100
    }
  }
}
