
##############################
# Country definition for U19 #
##############################

province = { id = 130 air_base = 10 radar_station = 10  rocket_test = 10 infra = 2.0  anti_air = 10 } # ÉçÉîÉ@ÉjÉGÉ~

#####################
# Country main data #
#####################

country =
{ tag                 = U19
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 130
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 130 }
  ownedprovinces      = { 130 }
  controlledprovinces = { 136 108 109 129 112 114 107 104 110 116 117 111 118 124 125 128 105 106 93 97 98 99 100 101
                          113 115 119 121 126 127 130 131 132 137 143 138 139 140 141 142 147 148 149 144 146 145
                          292 92 120 122 91 293 294 96 103 295 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 15351 id = 4072 }
    name     = "ëÊ1åRíc"
    location = 183
    division =
    { id            = { type = 15351 id = 4074 }
      name          = "ëÊ1éióﬂåQ"
      model         = 33
      type          = hq
      strength      = 100.0000
      brigade_model = 0
      extra         = light_armor_brigade
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15351 id = 4075 }
    name     = "ëÊ2åRíc"
    location = 139
    division =
    { id            = { type = 15351 id = 4077 }
      name          = "ëÊ2éióﬂåQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15351 id = 4078 }
    name     = "ëÊ3åRíc"
    location = 149
    division =
    { id            = { type = 15351 id = 4080 }
      name          = "ëÊ3éióﬂåQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15351 id = 4081 }
    name     = "ëÊ4åRíc"
    location = 134
    division =
    { id            = { type = 15351 id = 4083 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4086 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4089 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4090 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4091 }
      name          = "ëÊ6BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15351 id = 4097 }
    name     = "ëÊ5åRíc"
    location = 135
    division =
    { id            = { type = 15351 id = 4099 }
      name          = "ëÊ12BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4102 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4105 }
      name          = "ëÊ15BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4106 }
      name          = "ëÊ16BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4107 }
      name          = "ëÊ17BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15351 id = 4113 }
    name     = "ëÊ6åRíc"
    location = 107
    division =
    { id            = { type = 15351 id = 4115 }
      name          = "ëÊ23BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4118 }
      name          = "ëÊ7BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4121 }
      name          = "ëÊ26BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4122 }
      name          = "ëÊ27BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4123 }
      name          = "ëÊ28BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15351 id = 4129 }
    name     = "ëÊ7åRíc"
    location = 163
    division =
    { id            = { type = 15351 id = 4131 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15351 id = 4134 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15351 id = 4137 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15351 id = 4138 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15351 id = 4139 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15351 id = 4145 }
    name     = "ëÊ8åRíc"
    location = 137
    division =
    { id            = { type = 15351 id = 4147 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4150 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4153 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4154 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15351 id = 4155 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15351 id = 1 }
    name     = "ÉçÉîÉ@ÉjÉGÉ~ÉnÉCÉî"
    location = 130
    division =
    { type   = garrison
      model  = 14
      id     = { type = 15354 id = 1 }
      name   = "ÉçÉîÉ@ÉjÉGÉ~ÉnÉCÉî"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 15354 id = 2 }
      name   = "ñÂãâ"
      locked = yes
    }
  }
}
