
##############################
# Country definition for U24 #
##############################

province = { id = 722 air_base = 10 radar_station = 10  rocket_test = 10 infra = 2.0  anti_air = 10 } # É{Å[ÉpÅ[Éã

#####################
# Country main data #
#####################

country =
{ tag                 = U24
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 722
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 722 }
  ownedprovinces      = { 722 }
  controlledprovinces = { 722  1458 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1478 1479 1505 1506 1507 1508 1509 1510 
                          1511 1513 1514 1515 599  685  687  736  1476 1477 1705 2092 2199 593  597  669  697  726  769  785  1699  611  631 635 
                          714  1701 1721 2091 2094 2133 773  774  775  1694 1758 2106 702  703  771  1695 2099 2175 729  791  2124  2198 
                          781  1284 1287 1454 1456 1457 1519 2104 2592 1512 777  2085 1285 1286 1288 1590 1592 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 15551 id = 4072 }
    name     = "ëÊ1åRíc"
    location = 1721
    division =
    { id            = { type = 15551 id = 4074 }
      name          = "ëÊ1éióﬂåQ"
      model         = 33
      type          = hq
      strength      = 100.0000
      brigade_model = 0
      extra         = light_armor_brigade
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15551 id = 4075 }
    name     = "ëÊ2åRíc"
    location = 599
    division =
    { id            = { type = 15551 id = 4077 }
      name          = "ëÊ2éióﬂåQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15551 id = 4078 }
    name     = "ëÊ3åRíc"
    location = 2043
    division =
    { id            = { type = 15551 id = 4080 }
      name          = "ëÊ3éióﬂåQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15551 id = 4081 }
    name     = "ëÊ4åRíc"
    location = 1464
    division =
    { id            = { type = 15551 id = 4083 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4086 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4089 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4090 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4091 }
      name          = "ëÊ6BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15551 id = 4097 }
    name     = "ëÊ5åRíc"
    location = 1506
    division =
    { id            = { type = 15551 id = 4099 }
      name          = "ëÊ12BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4102 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4105 }
      name          = "ëÊ15BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4106 }
      name          = "ëÊ16BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4107 }
      name          = "ëÊ17BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15551 id = 4113 }
    name     = "ëÊ6åRíc"
    location = 1458
    division =
    { id            = { type = 15551 id = 4115 }
      name          = "ëÊ23BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4118 }
      name          = "ëÊ7BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4121 }
      name          = "ëÊ26BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4122 }
      name          = "ëÊ27BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4123 }
      name          = "ëÊ28BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15551 id = 4129 }
    name     = "ëÊ7åRíc"
    location = 1457
    division =
    { id            = { type = 15551 id = 4131 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4134 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4137 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4138 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4139 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15551 id = 4145 }
    name     = "ëÊ8åRíc"
    location = 1285
    division =
    { id            = { type = 15551 id = 4147 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4150 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4153 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4154 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4155 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15551 id = 4161 }
    name     = "ëÊ9åRíc"
    location = 2099
    division =
    { id            = { type = 15551 id = 4163 }
      name          = "ëÊ56BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4166 }
      name          = "ëÊ16BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4169 }
      name          = "ëÊ59BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4170 }
      name          = "ëÊ60BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4171 }
      name          = "ëÊ61BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15551 id = 4177 }
    name     = "ëÊ10åRíc"
    location = 1695
    division =
    { id            = { type = 15551 id = 4179 }
      name          = "ëÊ67BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4182 }
      name          = "ëÊ19BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4185 }
      name          = "ëÊ70BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4186 }
      name          = "ëÊ71BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15551 id = 4187 }
      name          = "ëÊ72BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15551 id = 1 }
    name     = "É{ÉpÅ[ÉãÉnÉCÉî"
    location = 722
    division =
    { type   = garrison
      model  = 14
      id     = { type = 15554 id = 1 }
      name   = "É{ÉpÅ[ÉãÉnÉCÉî"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 15554 id = 2 }
      name   = "ñÂãâ"
      locked = yes
    }
  }
}
