
##############################
# Country definition for U27 #
##############################

province =
{ id              = 2551
  air_base        = 10
  radar_station   = 10
  
  rocket_test     = 10
  infra           = 2.0
  anti_air        = 10
}                   # èdåc(É`ÉáÉìÉ`Éì)

#####################
# Country main data #
#####################

country =
{ tag                 = U27
  manpower            = 50
  energy              = 100
  metal               = 50
  rare_materials      = 25
  oil                 = 50
  supplies            = 200
  money               = 100
  capital             = 2551
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 2551 }
  ownedprovinces      = { 2551 }
  controlledprovinces = { 2551 
                          1685
                          1217 1219 1220 1235 1236 1237 1966 2556 1238 1239 1240 1241 2570 2571 2572 1243
                          1244 1245 1246 1247 1936 1937 1231 1232 1253 1264 1266 1910 1939 1995 1996 1997 2502 1218 1221 1222 1233 1234 1964 1965 2558
                          2573 2574 1223 1224 1227 1228 1229 1230 2508 2513 2515 2516 1209 1225 1226 2517 2518 2520 1203 1204 1205 1206 1210 1211 1212
                          1397 2318 2523 2525 2526 2527 2576 1213 1214 1215 1216 2522 2528 2529 2530 2531 2533 2534 1293 1294 1307 1308 1327 1362 1905
                          1918 1928 1978 1983 1263 1265 1279 1280 1281 1282 1360 1361 1903 2550 2559 2560 2561 746  1321 557  559  674  695  720  1258
                          1309 1310 1311 1319 1325 568  570  1248 1249 1312 1313 1314 1317 1318 1320 1880 1912 1262 1363 1364 1365 1984 1993 2000 2311
                          1255 1256 1257 1259 1260 1261 1913 1914 1921 1922 1242 1250 1251 1252 1254 1938 1941 2567 2568 2569
                          1267 1268 1269 1270 1271 2505 2507 1386 1388 1398 2246 2337
                          1382 1377 1387 1389 1390 2241 2333 2338 2487 2511 1374 1375 1378 1379 1380 1381 1530 2281 2485 2486 1202 1394 1395 1396 2317
                          2340 2341 2344 2345 2346 2347 2348 2349 696  1315 1316 1898 1877
                          1817
                          1194
                          1175
                          1366 1367 1368 1369 1370 1371 1372 1527 1528
                          1529 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 17001 id = 4 }
    name     = "ëÊ4åRíc"
    location = 1202
    division =
    { id            = { type = 17001 id = 5 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 6 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 7 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 8 }
    name     = "ëÊ4åRíc"
    location = 1394
    division =
    { id            = { type = 17001 id = 9 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 10 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 11 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 12 }
    name     = "ëÊ4åRíc"
    location = 1395
    division =
    { id            = { type = 17001 id = 13 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 14 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 15 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 16 }
    name     = "ëÊ4åRíc"
    location = 2347
    division =
    { id            = { type = 17001 id = 17 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 18 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 19 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 20 }
    name     = "ëÊ4åRíc"
    location = 1203
    division =
    { id            = { type = 17001 id = 21 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 22 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 23 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 24 }
    name     = "ëÊ4åRíc"
    location = 2527
    division =
    { id            = { type = 17001 id = 25 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 26 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 27 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 28 }
    name     = "ëÊ4åRíc"
    location = 2526
    division =
    { id            = { type = 17001 id = 29 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 30 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 31 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 32 }
    name     = "ëÊ4åRíc"
    location = 1213
    division =
    { id            = { type = 17001 id = 33 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 34 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 35 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 36 }
    name     = "ëÊ4åRíc"
    location = 2531
    division =
    { id            = { type = 17001 id = 37 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 38 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 39 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 40 }
    name     = "ëÊ4åRíc"
    location = 2530
    division =
    { id            = { type = 17001 id = 41 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 42 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 43 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 44 }
    name     = "ëÊ4åRíc"
    location = 1215
    division =
    { id            = { type = 17001 id = 45 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 46 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 47 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 48 }
    name     = "ëÊ4åRíc"
    location = 1217
    division =
    { id            = { type = 17001 id = 49 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 50 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 51 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 52 }
    name     = "ëÊ4åRíc"
    location = 1966
    division =
    { id            = { type = 17001 id = 53 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 54 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 55 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 56 }
    name     = "ëÊ4åRíc"
    location = 1219
    division =
    { id            = { type = 17001 id = 57 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 58 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 59 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 60 }
    name     = "ëÊ4åRíc"
    location = 2571
    division =
    { id            = { type = 17001 id = 61 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 62 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 63 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 64 }
    name     = "ëÊ4åRíc"
    location = 1238
    division =
    { id            = { type = 17001 id = 65 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 66 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 67 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 68 }
    name     = "ëÊ4åRíc"
    location = 1241
    division =
    { id            = { type = 17001 id = 69 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 70 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 71 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 72 }
    name     = "ëÊ4åRíc"
    location = 1239
    division =
    { id            = { type = 17001 id = 73 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 74 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 75 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 76 }
    name     = "ëÊ4åRíc"
    location = 1240
    division =
    { id            = { type = 17001 id = 77 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 78 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 79 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 80 }
    name     = "ëÊ4åRíc"
    location = 1245
    division =
    { id            = { type = 17001 id = 81 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 82 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 83 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 84 }
    name     = "ëÊ4åRíc"
    location = 1247
    division =
    { id            = { type = 17001 id = 85 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 86 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 87 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 88 }
    name     = "ëÊ4åRíc"
    location = 1936
    division =
    { id            = { type = 17001 id = 89 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 90 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 91 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 92 }
    name     = "ëÊ4åRíc"
    location = 1248
    division =
    { id            = { type = 17001 id = 93 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 94 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 95 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 96 }
    name     = "ëÊ4åRíc"
    location = 1317
    division =
    { id            = { type = 17001 id = 97 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 98 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 99 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 100 }
    name     = "ëÊ4åRíc"
    location = 1318
    division =
    { id            = { type = 17001 id = 101 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 102 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 103 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 104 }
    name     = "ëÊ4åRíc"
    location = 1320
    division =
    { id            = { type = 17001 id = 105 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 106 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 107 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 108 }
    name     = "ëÊ4åRíc"
    location = 696
    division =
    { id            = { type = 17001 id = 109 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 110 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 111 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 112 }
    name     = "ëÊ4åRíc"
    location = 1321
    division =
    { id            = { type = 17001 id = 113 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 114 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 115 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 116 }
    name     = "ëÊ4åRíc"
    location = 746
    division =
    { id            = { type = 17001 id = 117 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 118 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 119 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 120 }
    name     = "ëÊ4åRíc"
    location = 1325
    division =
    { id            = { type = 17001 id = 121 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 122 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 123 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 124 }
    name     = "ëÊ4åRíc"
    location = 1316
    division =
    { id            = { type = 17001 id = 125 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 126 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 127 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 128 }
    name     = "ëÊ4åRíc"
    location = 1313
    division =
    { id            = { type = 17001 id = 129 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 130 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 131 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 132 }
    name     = "ëÊ4åRíc"
    location = 1314
    division =
    { id            = { type = 17001 id = 133 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 134 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 17001 id = 135 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 17001 id = 1 }
    name     = "èdåcÉnÉCÉî"
    location = 2551
    division =
    { type   = garrison
      model  = 14
      id     = { type = 17001 id = 2 }
      name   = "èdåcÉnÉCÉî"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 17001 id = 3 }
      name   = "ñÂãâ"
      locked = yes
    }
  }
}
