
##############################
# Country definition for U30 #
##############################

province =
{ id              = 1525
  air_base        = 10
  radar_station   = 10
  rocket_test     = 10
  infra           = 2.0
  anti_air        = 10
}                   # ƒuƒ‰ƒSƒGƒXƒ`ƒFƒ“ƒXƒN

#####################
# Country main data #
#####################

country =
{ tag                 = U30
  manpower            = 50
  energy              = 100
  metal               = 50
  rare_materials      = 25
  oil                 = 50
  supplies            = 200
  money               = 100
  capital             = 1525
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 1525 }
  ownedprovinces      = { 1525 }
  controlledprovinces = { 1525 1526 1410 1411 1167 2650 2647 2649 2653 2651 2652 2654 2655 2656 2657 2658 1521 1524 1522 1383 2659 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 17151 id = 1 }
    name     = "ƒuƒ‰ƒSƒGƒXƒ`ƒFƒ“ƒXƒNƒnƒCƒ”"
    location = 1525
    division =
    { type   = garrison
      model  = 11
      id     = { type = 17151 id = 2 }
      name   = "ƒuƒ‰ƒSƒGƒXƒ`ƒFƒ“ƒXƒNƒnƒCƒ”"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 17151 id = 3 }
      name   = "–å‹‰"
      locked = yes
    }
  }
  landunit =
  { id       = { type = 17151 id = 23 }
    name     = "‘æ6ŒR’c"
    location = 2649
    division =
    { id            = { type = 17151 id = 24 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 25 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 26 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 27 }
      name          = "‘æ8BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 28 }
      name          = "‘æ9BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 17151 id = 29 }
    name     = "‘æ6ŒR’c"
    location = 2649
    division =
    { id            = { type = 17151 id = 30 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 31 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 32 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 33 }
      name          = "‘æ8BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 34 }
      name          = "‘æ9BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 17151 id = 35 }
    name     = "‘æ6ŒR’c"
    location = 2649
    division =
    { id            = { type = 17151 id = 36 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 37 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 38 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 39 }
      name          = "‘æ8BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 40 }
      name          = "‘æ9BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 17151 id = 41 }
    name     = "‘æ6ŒR’c"
    location = 2649
    division =
    { id            = { type = 17151 id = 42 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 43 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 44 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 45 }
      name          = "‘æ8BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 46 }
      name          = "‘æ9BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 17151 id = 65 }
    name     = "‘æ6ŒR’c"
    location = 2647
    division =
    { id            = { type = 17151 id = 66 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 67 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 68 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 69 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 70 }
      name          = "‘æ9BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 17151 id = 71 }
    name     = "‘æ6ŒR’c"
    location = 2647
    division =
    { id            = { type = 17151 id = 72 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 73 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 74 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 75 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 76 }
      name          = "‘æ9BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 17151 id = 77 }
    name     = "‘æ6ŒR’c"
    location = 2647
    division =
    { id            = { type = 17151 id = 78 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 79 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 80 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 81 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 82 }
      name          = "‘æ9BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 17151 id = 83 }
    name     = "‘æ6ŒR’c"
    location = 2647
    division =
    { id            = { type = 17151 id = 84 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 85 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 86 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 87 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 88 }
      name          = "‘æ9BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 17151 id = 89 }
    name     = "‘æ6ŒR’c"
    location = 2647
    division =
    { id            = { type = 17151 id = 90 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 91 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 92 }
      name          = "‘æ3BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 93 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17151 id = 94 }
      name          = "‘æ9BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
}
