
##############################
# Country definition for U31 #
##############################

province = { id = 1199 air_base = 10 radar_station = 10  rocket_test = 10 infra = 2.0  anti_air = 10 } # ãûèÈ(É\ÉEÉã)

#####################
# Country main data #
#####################

country =
{ tag                 = U31
  manpower            = 50
  energy              = 100
  metal               = 50
  rare_materials      = 25
  oil                 = 50
  supplies            = 200
  money               = 100
  capital             = 1199
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 1199 }
  ownedprovinces      = { 1199 }
  controlledprovinces = { 1199 1376 1391 1392 1393 1200 1201 2236 2219 2231 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 17201 id = 4145 }
    name     = "ëÊ8åRíc"
    location = 2349
    division =
    { id            = { type = 17201 id = 4147 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17201 id = 4150 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17201 id = 4153 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17201 id = 4154 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17201 id = 4155 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
    landunit =
  { id       = { type = 17201 id = 4 }
    name     = "ëÊ8åRíc"
    location = 1199
    division =
    { id            = { type = 17201 id = 5 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 6 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 7 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 8 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 9 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
    landunit =
  { id       = { type = 17201 id = 10 }
    name     = "ëÊ8åRíc"
    location = 1199
    division =
    { id            = { type = 17201 id = 11 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 12 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 13 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 14 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 15 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
    landunit =
  { id       = { type = 17201 id = 16 }
    name     = "ëÊ8åRíc"
    location = 1199
    division =
    { id            = { type = 17201 id = 17 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 18 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 19 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 20 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 21 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
    landunit =
  { id       = { type = 17201 id = 22 }
    name     = "ëÊ8åRíc"
    location = 1199
    division =
    { id            = { type = 17201 id = 23 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 24 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 25 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 26 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 27 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
    landunit =
  { id       = { type = 17201 id = 28 }
    name     = "ëÊ8åRíc"
    location = 1198
    division =
    { id            = { type = 17201 id = 29 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 30 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 31 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 32 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 33 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
    landunit =
  { id       = { type = 17201 id = 34 }
    name     = "ëÊ8åRíc"
    location = 1198
    division =
    { id            = { type = 17201 id = 35 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 36 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 37 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 38 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 17201 id = 39 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 17201 id = 1 }
    name     = "ìSå¥ÉnÉCÉî"
    location = 1199
    division =
    { type   = garrison
      model  = 13
      id     = { type = 17201 id = 2 }
      name   = "ìSå¥ÉnÉCÉî"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 17201 id = 3 }
      name   = "ñÂãâ"
      locked = yes
    }
  }
}
