
##############################
# Country definition for SOV #
##############################

province =
{ id         = 133
  anti_air   = 4
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # ムルマンスク
province = { id = 145 landfort = 2 anti_air = 3 } # ヴィープリ
province =
{ id         = 154
  anti_air   = 4
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # アルハンゲリスク
province =
{ id       = 163
  air_base = { size = 4 current_size = 4 }
  landfort = 5
  anti_air = 3
}            # スターリングラード
province =
{ id       = 166
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ゴーリキー
province =
{ id       = 171
  air_base = { size = 2 current_size = 2 }
}            # ヴォログダ
province =
{ id       = 175
  air_base = { size = 10 current_size = 10 }
  landfort = 5
  anti_air = 4
}            # モスクワ
province =
{ id       = 178
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ヴラジーミル
province =
{ id              = 187
  anti_air        = 6
  naval_base      = { size = 10 current_size = 10 }
  air_base        = { size = 4 current_size = 4 }
  landfort        = 5
  coastalfort     = 5
}                   # レニングラード
province =
{ id       = 200
  air_base = { size = 4 current_size = 4 }
}            # ノヴゴルド
province = { id = 216 anti_air = 1 } # ドノー
province =
{ id       = 217
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # ヴィテブスク
province =
{ id       = 219
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # スモレンスク
province =
{ id       = 220
  air_base = { size = 4 current_size = 4 }
}            # モギリフ
province =
{ id       = 223
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # インステルブルク
province =
{ id       = 228
  air_base = { size = 4 current_size = 4 }
}            # ヴィニンツァ
province =
{ id       = 233
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # オデッサ
province =
{ id         = 234
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # ムィコラーイウ
province =
{ id       = 238
  anti_air = 3
  air_base = { size = 8 current_size = 8 }
}            # キエフ
province =
{ id       = 248
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ハリコフ
province =
{ id       = 249
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ザポリージャ
province =
{ id          = 253
  anti_air    = 6
  naval_base  = { size = 8 current_size = 8 }
  air_base    = { size = 4 current_size = 4 }
  landfort    = 3
  coastalfort = 5
}               # セヴァストポリ
province =
{ id       = 256
  air_base = { size = 2 current_size = 2 }
}            # クラスノダール
province =
{ id       = 263
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ロッソ
province =
{ id       = 269
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # ロストフ・ナ・ドヌ
province =
{ id       = 274
  air_base = { size = 4 current_size = 4 }
}            # ホメリ
province =
{ id       = 276
  air_base = { size = 4 current_size = 4 }
}            # オリョール
province =
{ id       = 279
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # リャザン
province =
{ id       = 281
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ヴォロネジ
province =
{ id       = 282
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # クルスク
province =
{ id       = 288
  air_base = { size = 2 current_size = 2 }
}            # ルジェフ
province =
{ id         = 510
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # ケーニヒスベルク
province = { id = 550 ic = 14 } # セラウィカ
province = { id = 908 ic = 24 air_base = 8 infra = 2.0 naval_base = 10 } # ベセル
province =
{ id         = 1167
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 5 current_size = 5 }
}              # マガダン
province =
{ id       = 1170
  ic       = 10
  air_base = { size = 8 current_size = 8 }
}            # ベリゴンスキー
province = { id = 1171 ic = 8 } # パラナ
province =
{ id       = 1172
  ic       = 12
  air_base = { size = 8 current_size = 8 }
}            # ペトロパヴロフスク・カムチャツキ
province =
{ id       = 1366
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic       = 4
}            # ハバロフスク
province = { id = 1367 ic = 3 } # テチューヘ(ダリネゴルスク)
province = { id = 1368 ic = 4 } # ソヴィエツカヤ・ガヴァニ
province = { id = 1370 ic = 5 } # セミョノフカ
province = { id = 1371 ic = 6 } # ナホトカ
province =
{ id          = 1372
  anti_air    = 5
  naval_base  = { size = 4 current_size = 4 }
  air_base    = { size = 4 current_size = 4 }
  landfort    = 1
  coastalfort = 3
  ic          = 14
}               # ウラジオストック
province = { id = 1399 ic = 12 } # ホライトマウンテン
province =
{ id       = 1414
  air_base = { size = 8 current_size = 8 }
}            # イルクーツク
province =
{ id       = 1418
  air_base = { size = 6 current_size = 6 }
}            # キジル
province =
{ id       = 1424
  air_base = { size = 2 current_size = 2 }
}            # アルマアタ
province =
{ id       = 1427
  air_base = { size = 2 current_size = 2 }
}            # タシュケント
province =
{ id       = 1522
  air_base = { size = 8 current_size = 8 }
  ic       = 2
}            # ヤクーツク
province =
{ id       = 1523
  air_base = { size = 8 current_size = 8 }
  anti_air = 2
  ic       = 15
}            # 北樺太
province =
{ id       = 1527
  air_base = { size = 8 current_size = 8 }
  ic       = 2
}            # コムソモリスク・ナ・アムーレ
province =
{ id       = 1539
  air_base = { size = 2 current_size = 2 }
}            # トムスク
province =
{ id       = 1543
  air_base = { size = 2 current_size = 2 }
}            # ノヴォシビルスク
province = { id = 1544 ic = 2 } # ビイスク
province =
{ id       = 1550
  air_base = { size = 2 current_size = 2 }
}            # パヴロダル(カザフ)
province =
{ id       = 1552
  air_base = { size = 2 current_size = 2 }
}            # オムスク
province =
{ id       = 1562
  air_base = { size = 2 current_size = 2 }
}            # クラスノヤルス
province =
{ id       = 1564
  air_base = { size = 4 current_size = 4 }
}            # オポーチカ(プスコフ)
province =
{ id       = 1567
  air_base = { size = 2 current_size = 2 }
}            # チェリャビンスク
province =
{ id       = 1575
  air_base = { size = 2 current_size = 2 }
}            # スベルドロフスク
province =
{ id       = 1597
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ブリャンスク
province =
{ id       = 2641
  ic       = 17
  air_base = { size = 6 current_size = 6 }
}            # ガリナ
province = { id = 2642 ic = 16 } # ミント
province = { id = 2646 ic = 18 landfort = 8 } # バハチ
province = { id = 2648 ic = 12 landfort = 8 } # アナドゥイリ

#####################
# Country main data #
#####################

country =
{ tag                 = SOV
  manpower            = 1000
  energy              = 58000
  metal               = 38000
  rare_materials      = 48000
  oil                 = 5900
  supplies            = 8000
  money               = 580
  capital             = 908
  transports          = 250
  escorts             = 150
  regular_id          = U06
  policy              = { democratic = 2 political_left = 9 freedom = 2 free_market = 2 professional_army = 9 defense_lobby = 10 interventionism = 9 }
  ownedprovinces      = { 1149 1150 1151 1152 1153 1154 1155 1167 1170 1171 1172 1175 123  133  134  135  1366 1367 1368 1369 1370 1371 1372 1383 1384
                          1410 1411 1412 1413 1414 1415 1416 1417 1418 1422 1423 1424 1425 1426 1427 1428 1429 143  145  146  1485 1488 1489 1490 1491
                          150  151  152  1520 1521 1522 1523 1524 1526 1527 1528 1529 153  1533 1534 1536 1535 1538 1539 154  1540 1541 1542 1543 1544
                          1545 1546 1547 1548 1549 155  1550 1552 1555 1556 1558 1559 156  1561 1562 1564 1565 1566 1567 1569 157  1570 1571 1572 1573
                          1574 1575 1576 1577 1578 1579 158  1580 1581 1582 1583 1584 1585 1586 1587 1588 159  1593 1594 1596 1597 1598 160  161  162 
                          163  164  165  166  167  168  169  170  171  172  173  174  175  176  177  1771 1772 1773 1774 1775 1776 1777 1778 178  1780
                          1781 1782 1783 179  180  181  182  1827 1828 1829 183  1830 1831 1832 1833 1834 1836 1837 1838 1839 184  1840 1841 1842
                          1843 1844 1845 1846 1847 1848 1849 185  1850 1856 1857 1858 186  187  1874 188  189  190  1907 191  192  200  201  215  216 
                          217  218  219  220  221  223  2240 225  226  227  228  231  232  233  234  235  236  237  238  239  240  241  242  243  244 
                          245  246  247  2470 248  2488 249  250  251  252  253  254  255  256  257  258  259  260  261  262  263  264  265  266  267 
                          268  269  270  271  272  273  274  275  276  277  278  279  280  281  282  283  284  285  286  287  288  289  510  550  94  
                          908  2641 2642 1399 2646 2647 2648 2649 2650 2652 2653 2654 2655 2656 2657 2658 2659 2651 2660
                        }
  controlledprovinces = { 2648 1170 2646 1171 1172 1523 1399 2641 2642 550 908 }
  techapps            = { 10050 10060 10070 10080 10090 1010  10150 10160 10190 1020  10200 10210 10220 1030  1040  10440 10490 1050  1110  1120 
                          1130  1140  1150  1210  1220  1230  1240  1250  1470  1490  1510  1530  1550  1560  1570  1580  1590  1650  1660  1670 
                          1680  1690  1750  1760  1770  1780  1790  1850  1860  1870  1950  1960  1970  1980  2010  2020  20210 20220 2030  20310
                          20320 2040  20410 2050  20510 2060  2070  2080  2310  2320  2330  2610  2620  2630  2640  2650  2660  2910  2920  2930 
                          2940  2950  2960  3010  3020  3030  3040  30410 30420 30430 3050  30510 30520 30530 3110  3120  3130  3140  3210  3220 
                          3230  3240  3310  3320  3330  3340  3350  3410  3460  3470  3480  3490  3500  3610  3620  3630  3710  3720  3810  3820 
                          3830  3910  3920  3930  3940  3950  3960  40100 40110 40120 40130 40200 4390  4400  4410  4420  4430  4480  4490  4500 
                          4510  4560  4570  50020 50030 50040 50050 50070 50080 50090 5010  50100 50110 50120 5020  5030  5040  5090  5100  5110 
                          5120  5170  5180  5190  5200  5250  5260  5270  5280  5330  5340  5350  5360  5410  5420  5430  5460  5490  5500  5600 
                          5610  5620  5630  5680  5690  5760  5770  5780  5790  5800  5810  5820  5830  5840  5850  5860  5910  5920  5930  5940 
                          5950  7010  7500  7510  7520  7530  7670  7680  7690  80080
                          80090 8010  80160 8020  8030  8040  8050  8060  8070  8080  8090  8100  8110  90040 90090 9010  9020  90240 9030  9040 
                          9050  9060  9070  9080  9190  9200  9210  9220  9230  9340  9350  9360  9370  9380  9390  9400  9410  9520  9530  9670 
                          9680  9690  9700  9710  9720  9730  9840  9850  9860  9870  9880  2340  2360  2090  2670  2970  60380
                          60390 60400 60410 10390 4010  4020  4030  4040  4050  4110  4120  4130  4140  4150  4210  4220  4230  4240  4250  4640
                          4650  4660  4670  4680  4820  4830  4840  4850  4860  40000 40010 40020 40030 40040 7270  7280
                          50290 50300 50310 50320 50330 5520  5530  5540  5550  5560  7150  7160  7170  7180
                          6000  6010  6020  6030  6040  6160  6170  6370  6380  6390  6700  6710  6720
                        }
  nationalprovinces   = { 1149 1150 1151 1152 1153 1154 1155 1156 1167 1170 1171 1172 1175 123  133  134  135  1366 1367 1368 1369 1370 1371 1372 1383
                          1384 1410 1411 1412 1413 1414 1415 1416 1417 1418 1422 1423 1424 1425 1426 1427 1428 1429 143  145  146  1485 1488 1489 1490
                          1491 150  151  152  1520 1521 1522 1523 1524 1525 1526 1527 1528 1529 153  1533 1534 1536 1535 1538 1539 154  1540 1541 1542
                          1543 1544 1545 1546 1547 1548 1549 155  1550 1551 1552 1555 1556 1557 1558 1559 156  1560 1561 1562 1564 1565 1566 1567 1568
                          1569 157  1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 158  1580 1581 1582 1583 1584 1585 1586 1587 1588 159  1593 1594
                          1596 1597 1598 160  161  162  163  164  165  166  167  168  169  170  171  172  173  174  175  176  177  1771 1772 1773 1774
                          1775 1776 1777 1778 178  1780 1781 1782 1783 179  180  181  182  1827 1828 1829 183  1830 1831 1832 1833 1834 1836 1837
                          1838 1839 184  1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 185  1850 1856 1857 1858 186  187  1874 188  189  190  1907
                          191  192  200  201  212  215  216  217  218  219  220  221  223  2240 225  226  227  228  231  232  233  234  235  236  237 
                          238  239  240  241  242  243  244  245  246  247  2470 248  2488 249  250  251  252  253  254  255  256  257  258  259  260 
                          261  262  263  264  265  266  267  268  269  270  271  272  273  274  275  276  277  278  279  280  281  282  283  284  285 
                          286  287  288  289  510  550  94   1176 908  2641 2642 1399 2646 2647 2648 2649 2650 2651 2652 2653 2654 2655 2656 2657 2658
                          2659 2660
                        }
free                = { energy = 300 manpower = 0.4 metal = 100 rare_materials = 200 oil = 50 }
inventions             = { 8006 8011 8004 }
  landunit =
  { id       = { type = 19501 id = 3063 }
    name     = "第11軍団"
    location = 550
    home     = 550
    division =
    { id            = { type = 19501 id = 3065 }
      name          = "第1支援部隊"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3066 }
    name     = "第12軍団"
    location = 1171
    division =
    { id            = { type = 19501 id = 3068 }
      name          = "第2支援部隊"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3069 }
    name     = "第13軍団"
    location = 1172
    home     = 1172
    division =
    { id            = { type = 19501 id = 3071 }
      name          = "第3支援部隊"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3072 }
    name     = "第14軍団"
    location = 1170
    division =
    { id            = { type = 19501 id = 3074 }
      name          = "第4支援部隊"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3075 }
    name     = "第15軍団"
    location = 1399
    division =
    { id            = { type = 19501 id = 3077 }
      name          = "第5支援部隊"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3078 }
    name     = "第16軍団"
    location = 2641
    division =
    { id            = { type = 19501 id = 3080 }
      name          = "第6支援部隊"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3081 }
    name     = "第17軍団"
    location = 2661
    division =
    { id            = { type = 19501 id = 3083 }
      name          = "第7支援部隊"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3084 }
    name     = "第18軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3086 }
      name          = "第8支援部隊"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3087 }
    name     = "第19軍団"
    location = 1523
    home     = 1523
    division =
    { id            = { type = 19501 id = 3089 }
      name          = "第9支援部隊"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3090 }
    name     = "第一方面軍司令部"
    location = 908
    home     = 908
    division =
    { id            = { type = 19501 id = 3092 }
      name          = "第1軍司令部"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3093 }
    name     = "第20軍団"
    location = 908
    home     = 908
    division =
    { id            = { type = 19501 id = 3095 }
      name          = "第1機械化装甲歩兵部隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3096 }
      name          = "第2機械化装甲歩兵部隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3097 }
      name          = "第3機械化装甲歩兵部隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3098 }
    name     = "第21軍団"
    location = 1523
    division =
    { id            = { type = 19501 id = 3100 }
      name          = "第4機械化装甲歩兵部隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3101 }
      name          = "第5機械化装甲歩兵部隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3102 }
    name     = "第五方面軍司令部"
    location = 2646
    division =
    { id            = { type = 19501 id = 3104 }
      name          = "第2軍司令部"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3105 }
    name     = "第22軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3107 }
      name          = "第6機械化装甲歩兵部隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3108 }
      name          = "第7機械化装甲歩兵部隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3109 }
    name     = "第23軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3111 }
      name          = "第8機械化装甲歩兵部隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3112 }
      name          = "第9機械化装甲歩兵部隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3113 }
    name     = "第二方面軍司令部"
    location = 1171
    division =
    { id            = { type = 19501 id = 3115 }
      name          = "第3軍司令部"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3116 }
    name     = "第24軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3118 }
      name          = "ジャール大隊"
      model         = 8
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
      experience    = 80
    }
    division =
    { id            = { type = 19501 id = 3119 }
      name          = "第16戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3120 }
      name          = "第5機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3121 }
    name     = "第25軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3123 }
      name          = "第17戦術機甲大隊"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3124 }
      name          = "第18戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3125 }
      name          = "第6機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3126 }
    name     = "第三方面軍司令部"
    location = 2648
    division =
    { id            = { type = 19501 id = 3128 }
      name          = "第4軍司令部"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3129 }
    name     = "第26軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3131 }
      name          = "第19戦術機甲大隊"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3132 }
      name          = "第20戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3133 }
      name          = "第7機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3134 }
    name     = "第27軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3136 }
      name          = "第21戦術機甲大隊"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3137 }
      name          = "第22戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3138 }
      name          = "第8機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3139 }
    name     = "第四方面軍司令部"
    location = 2646
    division =
    { id            = { type = 19501 id = 3141 }
      name          = "第5軍司令部"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3142 }
    name     = "第28軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3144 }
      name          = "第23戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3145 }
      name          = "第24戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3146 }
      name          = "第9機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3147 }
    name     = "第29軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3149 }
      name          = "第25戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3150 }
      name          = "第26戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3151 }
      name          = "第10機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3152 }
    name     = "第30軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3154 }
      name          = "第27戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3155 }
      name          = "第28戦術機甲大隊"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3156 }
      name          = "第11機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3162 }
    name     = "第32軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3164 }
      name          = "第12機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3165 }
      name          = "第13機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3166 }
      name          = "第14機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3167 }
    name     = "第33軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3169 }
      name          = "第15機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3170 }
      name          = "第16機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3171 }
      name          = "第17機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3172 }
    name     = "第34軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3174 }
      name          = "第18機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3175 }
      name          = "第19機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3176 }
      name          = "第20機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3177 }
    name     = "第35軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3179 }
      name          = "第21機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3180 }
      name          = "第22機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3181 }
      name          = "第23機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3197 }
    name     = "第39軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3199 }
      name          = "第10装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3200 }
      name          = "第11装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3201 }
      name          = "第12装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3202 }
    name     = "第40軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3204 }
      name          = "第101戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3205 }
      name          = "第102戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3206 }
      name          = "第103戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3207 }
    name     = "第41軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3209 }
      name          = "第104戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3210 }
      name          = "第105戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3211 }
      name          = "第106戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3212 }
    name     = "第42軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3214 }
      name          = "第13装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3215 }
      name          = "第14装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3216 }
      name          = "第15装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3217 }
    name     = "第43軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3219 }
      name          = "第16装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3220 }
      name          = "第17装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3221 }
      name          = "第18装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3222 }
    name     = "第44軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3224 }
      name          = "第19装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3225 }
      name          = "第20装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3226 }
      name          = "第21装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3227 }
    name     = "第45軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3229 }
      name          = "第22装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3230 }
      name          = "第23装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3231 }
      name          = "第24装甲部隊"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3232 }
    name     = "第46軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3234 }
      name          = "第29戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3235 }
      name          = "第30戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3236 }
      name          = "第24機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3237 }
    name     = "第47軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3239 }
      name          = "第31戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3240 }
      name          = "第32戦術機甲大隊"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3241 }
      name          = "第25機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3242 }
    name     = "第48軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3244 }
      name          = "第33戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3245 }
      name          = "第34戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3246 }
      name          = "第26機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3247 }
    name     = "第49軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3249 }
      name          = "第35戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3250 }
      name          = "第36戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3251 }
      name          = "第27機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3252 }
    name     = "第50軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3254 }
      name          = "第107戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3255 }
      name          = "第108戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3256 }
      name          = "第109戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3257 }
    name     = "第51軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3259 }
      name          = "第37戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3260 }
      name          = "第38戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3261 }
      name          = "第28機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3262 }
    name     = "第52軍団"
    location = 2648
    division =
    { id            = { type = 19501 id = 3264 }
      name          = "第29機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3265 }
      name          = "第30機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3266 }
      name          = "第31機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3267 }
    name     = "第53軍団"
    location = 2646
    division =
    { id            = { type = 19501 id = 3269 }
      name          = "第39戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3270 }
      name          = "第40戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3271 }
      name          = "第32機甲部隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  navalunit =
  { id       = { type = 19511 id = 5825 }
    name     = "ソ連海軍第1艦隊"
    location = 908
    home     = 908
    base     = 908
    division =
    { id       = { type = 19511 id = 5827 }
      name     = "ソビエツキー・ソユーズ"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5829 }
      name     = "ソビエツカヤ・ベロルーシヤ"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5830 }
      name     = "ソビエツカヤ・ロシア"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5831 }
      name     = "キーロフ"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 1 }
      name     = "フルーンゼ"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 3 }
      name     = "アドミラール・ナヒーモフ"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 4 }
      name     = "ピョートル・ヴェリーキイ"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5832 }
      name     = "ウダロイ"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5833 }
      name     = "ヴィツェ-アドミラル・クラコフ"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5834 }
      name     = "マルシャル・ワシレフスキー"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5835 }
      name     = "アドミラル・ザハロフ"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5836 }
      name     = "アドミラル・スピリドノフ"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5837 }
      name     = "アドミラル・トリブツ"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5838 }
      name     = "マルシャル・シャポシニコフ"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5839 }
      name     = "セヴェロモルスク"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5840 }
      name     = "アドミラル・レフチェンコ"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5841 }
      name     = "アドミラル・ヴィノグラドフ"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5807 }
      name     = "第1輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5808 }
      name     = "第2輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5809 }
      name     = "第3輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5810 }
      name     = "第4輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5811 }
      name     = "第5輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5812 }
      name     = "第6輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5813 }
      name     = "第7輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5814 }
      name     = "第8輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5815 }
      name     = "第9輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5816 }
      name     = "第10輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5817 }
      name     = "第11輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 19511 id = 5818 }
      name     = "第12輸送隊"
      model    = 3
      type     = transport
      strength = 100.0000
    }
  }
  ####################海軍整備計画関連##############################
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5819 }
    name    = "キエフ"
    type    = carrier
    model   = 2
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5820 }
    name    = "ミンスク"
    type    = carrier
    model   = 2
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5821 }
    name    = "ノヴォシローフスク"
    type    = carrier
    model   = 2
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5822 }
    name    = "バクー"
    type    = carrier
    model   = 2
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5823 }
    name    = "アドミラル･クズネツォフ"
    type    = carrier
    model   = 4
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5824 }
    name    = "ヴァリャーグ"
    type    = carrier
    model   = 4
    extra1  = cag
    brigade_model1 = 4
  }
}
