
##############################
# Country definition for U05 #
##############################

province =
{ id       = 559
  ic       = 2
  air_base = { size = 2 current_size = 2 }
}            # Œj—Ñ(ƒOƒDƒCƒŠƒ“)
province =
{ id         = 696
  ic         = 1
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 100
}              # LB˜p‘dØ’n
province = { id = 746 ic = 2 } # OˆŸ(ƒTƒ“ƒ„[/ŠC“ì“‡)
province =
{ id         = 1202
  ic         = 6
  air_base   = { size = 5 current_size = 5 }
  naval_base = { size = 6 current_size = 6 }
}              # ‘å˜A(ƒ^[ƒŠƒGƒ“)
province =
{ id         = 1204
  anti_air   = 1
  ic         = 3
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # “V’Ã(ƒeƒBƒGƒ“ƒWƒ“)
province =
{ id       = 1205
  ic       = 20
  air_base = { size = 4 current_size = 4 }
}            # –k‹(ƒxƒCƒWƒ“)
province = { id = 1207 ic = 3 } # ŒÄ˜a_“Á(ƒtƒtƒzƒg)
province =
{ id       = 1209
  ic       = 4
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ‘å“¯(ƒ^[ƒgƒ“)
province =
{ id       = 1211
  air_base = { size = 2 current_size = 2 }
}            # Î‰Æ¯(ƒV[ƒ`ƒƒƒ`ƒ‡ƒƒ“)
province = { id = 1217 ic = 6 } # ˜A‰_`(ƒŠƒGƒ“ƒ†ƒ“ƒJƒ“)
province =
{ id       = 1222
  air_base = { size = 2 current_size = 2 }
}            # •Œ—z(ƒt[ƒ„ƒ“)
province =
{ id       = 1225
  air_base = { size = 2 current_size = 2 }
}            # ‘¾Œ´(ƒ^ƒCƒˆƒAƒ“)
province =
{ id       = 1228
  air_base = { size = 2 current_size = 2 }
}            # “AF(ƒ`ƒ‡ƒ“ƒ`ƒ‡ƒE)
province =
{ id       = 1232
  anti_air = 1
  ic       = 3
  air_base = { size = 2 current_size = 2 }
}            # •Š¿(ƒE[ƒnƒ“)
province =
{ id       = 1235
  anti_air = 1
  ic       = 6
  air_base = { size = 4 current_size = 4 }
}            # “ì‹(ƒiƒ“ƒLƒ“)
province =
{ id         = 1237
  anti_air   = 1
  ic         = 3
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # ãŠC(ƒVƒƒƒ“ƒnƒC)
province =
{ id       = 1238
  air_base = { size = 2 current_size = 2 }
}            # YF(ƒnƒ“ƒ`ƒ‡ƒE)
province = { id = 1240 ic = 6 } # ‰·F(ƒEƒFƒ“ƒ`ƒ‡ƒE)
province =
{ id         = 1244
  anti_air   = 1
  ic         = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 6 current_size = 6 }
}              # •ŸB(ƒt[ƒaƒ‡ƒE)
province =
{ id       = 1247
  ic       = 3
  air_base = { size = 2 current_size = 2 }
}            # ›ú–å(ƒVƒƒ[ƒƒ“)
province = { id = 1248 supplypool = 500 oilpool = 50 } # Ÿˆ“ª(ƒVƒƒƒ“ƒgƒE)
province =
{ id       = 1267
  ic       = 5
  air_base = { size = 2 current_size = 2 }
}            # ¼ˆÀ(ƒV[ƒAƒ“)
province = { id = 1270 ic = 4 landfort = 3 } # ‰„ˆÀ(ƒCƒGƒ“ƒAƒ“)
province = { id = 1271 landfort = 3 } # ¾—Ñ(ƒ†[ƒŠƒ“)
province = { id = 1275 landfort = 3 } # •½™y(ƒsƒ“ƒŠƒAƒ“)
province =
{ id       = 1276
  ic       = 1
  air_base = { size = 2 current_size = 2 }
}            # —–F(ƒ‰ƒ“ƒ`ƒ‡ƒE)
province =
{ id       = 1283
  air_base = { size = 5 current_size = 5 }
}            # ƒ`ƒƒƒ€ƒh(¹“s)
province =
{ id       = 1307
  ic       = 5
  air_base = { size = 2 current_size = 2 }
}            # ©–¾(ƒNƒ“ƒ~ƒ“)
province =
{ id         = 1313
  anti_air   = 1
  ic         = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # LB(ƒOƒ@ƒ“ƒaƒ‡ƒE)
province =
{ id          = 1315
  anti_air    = 4
  ic          = 5
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 4 current_size = 4 }
  landfort    = 1
  coastalfort = 1
  oilpool     = 200
  supplypool  = 1000
}               # `(ƒzƒ“ƒRƒ“)
province = { id = 1318 ic = 4 } # —z](ƒ„ƒ“ƒWƒƒƒ“)
province =
{ id         = 1321
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # ŠCŒû(ƒnƒCƒRƒE/ŠC“ì“‡)
province =
{ id            = 1323
  ic            = 5
  air_base      = { size = 5 current_size = 5 }
}                 # ‘ä–k(ƒ^ƒCƒyƒC)
province = { id = 1324 ic = 3 } # ‰Ô˜@(ƒzƒƒŠƒFƒ“)
province =
{ id       = 1360
  ic       = 2
  air_base = { size = 2 current_size = 2 }
}            # ¬“s(ƒ`ƒFƒ“ƒgƒD[)
province =
{ id       = 1364
  ic       = 2
  air_base = { size = 2 current_size = 2 }
}            # ‹M—z(ƒRƒCƒ„ƒ“)
province =
{ id       = 1379
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ™û¢•l(ƒnƒ‹ƒrƒ“)
province = { id = 1385 ic = 3 } # ƒ`ƒ‡ƒCƒoƒ‹ƒTƒ“
province = { id = 1389 ic = 4 } # —ÉŒ¹(ƒŠƒƒƒIƒ†ƒGƒ“)
province = { id = 1390 ic = 6 } # ‹g—Ñ(ƒW[ƒŠƒ“)
province =
{ id         = 1394
  naval_base = { size = 1 current_size = 1 }
}              # ’O“Œ(ƒ_ƒ“ƒhƒ“)
province =
{ id         = 1396
  naval_base = { size = 1 current_size = 1 }
}              # ‹àŒk(ƒWƒ“ƒV[)
province =
{ id       = 1397
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ³“¿(ƒ`ƒFƒ“ƒh[)
province = { id = 1419 ic = 1 } # ƒ‚ƒƒ“
province = { id = 1420 ic = 1 } # ƒEƒ‹ƒM[
province =
{ id       = 1433
  air_base = { size = 1 current_size = 1 }
}            # ƒEƒ‹ƒ€ƒ`(’¹˜D–Øê)
province = { id = 1434 ic = 1 } # ƒoƒ„ƒ“ƒzƒ“ƒSƒ‹
province =
{ id       = 1439
  air_base = { size = 5 current_size = 5 }
}            # ƒoƒ„ƒ“ƒm[ƒ‹
province =
{ id       = 1442
  air_base = { size = 2 current_size = 2 }
}            # ƒSƒ‹ƒ€ƒh(Ši¢–Ø)
province =
{ id       = 1877
  air_base = { size = 5 current_size = 5 }
}            # ƒ~ƒs
province = { id = 1921 ic = 6 } # ’·¹(ƒ`ƒƒƒ“ƒVƒƒ[)
province = { id = 1923 ic = 4 } # ‘ä’†(ƒ^ƒCƒ`ƒ…ƒ“)
province = { id = 2241 ic = 6 } # V‹(ƒVƒ“ƒWƒ“)
province = { id = 2515 ic = 8 } # ‹–¹(ƒVƒ…[ƒ`ƒƒƒ“)
province =
{ id            = 2529
  ic            = 6
  air_base      = { size = 5 current_size = 5 }
  naval_base    = { size = 4 current_size = 4 }
}                 # Â“‡(ƒ`ƒ“ƒ^ƒI)
province = { id = 2533 ic = 6 } # Ï“ì(ƒW[ƒiƒ“)
province = { id = 2569 ic = 5 } # “ì¹(ƒiƒ“ƒ`ƒƒƒ“)
province =
{ id         = 2638
  ic         = 4
  air_base   = { size = 5 current_size = 5 }
  naval_base = { size = 4 current_size = 4 }
}              # ‚—Y
province = { id = 2639 ic = 1 } # àOŒÎ”“‡

#####################
# Country main data #
#####################

country =
{ tag                 = U05
  manpower            = 500
  energy              = 35000
  metal               = 40000
  rare_materials      = 38000
  oil                 = 25000
  supplies            = 8000
  money               = 2200
  capital             = 1323
  regular_id          = U06
  transports          = 1200
  escorts             = 1000
  policy              = { democratic = 2 political_left = 1 freedom = 2 free_market = 3 professional_army = 8 defense_lobby = 9 interventionism = 8 }
  ownedprovinces      = { 1217 1219 1220 1235 1236 1237 1966 2556 1238 1239 1240 1241 2570 2571 2572 1243 1244 1245 1246 1247 1936 1937 1231 1232 1253
                          1264 1266 1910 1939 1995 1996 1997 2502 1218 1221 1222 1233 1234 1964 1965 2558 2573 2574 1223 1224 1227 1228 1229 1230 2508
                          2513 2515 2516 1209 1225 1226 2517 2518 2520 1203 1204 1205 1206 1210 1211 1212 1397 2318 2523 2525 2526 2527 2576 1213 1214
                          1215 1216 2522 2528 2529 2530 2531 2533 2534 1293 1294 1307 1308 1327 1362 1905 1918 1928 1978 1983 1263 1265 1279 1280 1281
                          1282 1360 1361 1903 2550 2559 2560 2561 746  1321 557  559  674  695  720  1258 1309 1310 1311 1319 1325 568  570  1248 1249
                          1312 1313 1314 1317 1318 1320 1880 1912 1262 1363 1364 1365 1984 1993 2000 2311 1255 1256 1257 1259 1260 1261 1913 1914 1921
                          1922 1242 1250 1251 1252 1254 1938 1941 2567 2568 2569 1442 1443 1444 1275 1276 1277 1440 2503 1267 1268 1269 1270 1271 2505
                          2507 1421 1432 1433 1435 1445 1446 1447 1406 1450 1451 1452 1453 1283 1448 1207 1208 1272 1273 1274 1439 2504 1386 1388 1398
                          2246 2337 1382 1377 1387 1389 1390 2241 2333 2338 2487 2511 1374 1375 1378 1379 1380 1381 1530 2281 2485 2486 1202 1394 1395
                          1396 2317 2340 2341 2344 2345 2346 2347 2348 2349 1322 1323 1324 1923 696  1315 1316 1898 1430 1728 1877 1878 2043 2638 2639
                          1385 1419 1420 1434 1438
                        }
  controlledprovinces = { 1323 1923 1322 1324 2638 2639 }
  techapps            = { 10050 10060 10070 10080 10090 1010  10150 10160 10190 1020  10200 10210 10220 1030  10390 1040  10440 10490 1050  1110 
                          1120  1130  1140  1150  1210  1220  1230  1240  1250  1470  1490  1510  1530  1550  1560  1570  1580  1590  1650  1660 
                          1670  1680  1690  1750  1760  1770  1780  1790  1850  1860  1870  1950  1960  1970  1980  2010  2020  20210 2030  20310
                          20320 2040  20410 2050  2060  2070  2080  2310  2320  2330  2610  2620  2630  2640  2650  2660  2910  2920  2930  2940 
                          2950  2960  3010  3020  3030  3040  30410 30420 30430 30440 30450 3050  30510 30520 30530 30540 30550 3110  3120  3130 
                          3140  3150  3210  3220  3230  3240  3250  3310  3320  3330  3340  3350  3410  3460  3470  3480  3490  3500  3560  3570 
                          3610  3620  3630  3640  3650  3710  3720  3730  3740  3750  3810  3820  3830  3840  3850  3910  3920  3930  3940  3950 
                          3960  40100 40110 40120 40130 40200 40210 40220 40230 4390  4400  4410  4420  4430  4480  4490  4500  4510  4560  4570 
                          50020 50030 50040 50050 50070 50080 50090 5010  50100 50110 50120 5020  5030  5040  5050  5090  5100  5110  5120  5170 
                          5180  5190  5200  5250  5260  5270  5280  5330  5340  5350  5360  5370  5410  5420  5430  5460  5490  5500  5600  5610 
                          5620  5630  5910  5920  5930  5940  5950  7010  80080 80090 8010 
                          80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140 90190 9020  9030  9040 
                          9050  9060  9070  9080  9190  9200  9210  9220  9230  9340  9350  9360  9370  9380  9390  9400  9410  9520  9530  9540 
                          9550  9560  9670  9680  9690  9700  9710  9720  9730  9840  9850  9860  9870  9880  9990  60380 60390 60400 60410 4010  4020  4030 
                          4040  4050  4110  4120  4130  4140  4150  4210  4220  4230  4240  4250  2340  2360  2090  2670  2970  7270  7280
                          4640  4650  4660  4670  4680  4820  4830  4840  4850  4860  40000 40010 40020 40030 40040 
                          6000  6010  6020  6030  6040  6200  6210  6430  6440  6450  6700
                        }
  nationalprovinces   = { 1217 1219 1220 1235 1236 1237 1966 2556 1238 1239 1240 1241 2570 2571 2572 1243 1244 1245 1246 1247 1936 1937 1231 1232 1253
                          1264 1266 1910 1939 1995 1996 1997 2502 1218 1221 1222 1233 1234 1964 1965 2558 2573 2574 1223 1224 1227 1228 1229 1230 2508
                          2513 2515 2516 1209 1225 1226 2517 2518 2520 1203 1204 1205 1206 1210 1211 1212 1397 2318 2523 2525 2526 2527 2576 1213 1214
                          1215 1216 2522 2528 2529 2530 2531 2533 2534 1293 1294 1307 1308 1327 1362 1905 1918 1928 1978 1983 1263 1265 1279 1280 1281
                          1282 1360 1361 1903 2550 2551 2559 2560 2561 746  1321 557  559  674  695  720  1258 1309 1310 1311 1319 1325 568  570  1248
                          1249 1312 1313 1314 1317 1318 1320 1880 1912 1262 1363 1364 1365 1984 1993 2000 2311 1255 1256 1257 1259 1260 1261 1913 1914
                          1921 1922 1242 1250 1251 1252 1254 1938 1941 2567 2568 2569 1442 1443 1444 1275 1276 1277 1440 1441 2503 1267 1268 1269 1270
                          1271 2505 2507 1421 1432 1433 1435 1445 1446 1447 1406 1450 1451 1452 1453 1283 1448 1207 1208 1272 1273 1274 1439 2504 1386
                          1388 1398 2246 2337 1382 1377 1387 1389 1390 2241 2333 2338 2487 2511 1374 1375 1378 1379 1380 1381 1530 2281 2485 2486 1202
                          1394 1395 1396 2317 2340 2341 2344 2345 2346 2347 2348 2349 1322 1323 1324 1923 696  1315 1316 1898 1430 1728 1877 1878 2043
                          2638 2639 1431 1385 1404 1419 1420 1434 1438
                        }
free                = { energy = 20 manpower = 0.3 metal = 10 rare_materials = 20 oil = 10 ic = 60 }
inventions             = { 8006 }
  landunit =
  { id       = { type = 26501 id = 1 }
    name     = "‘æ20ŒR’c"
    location = 1323
    division =
    { id            = { type = 26501 id = 2 }
      name          = "‘æ40íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 3 }
      name          = "‘æ41íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 4 }
      name          = "‘æ20‹@b•”‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 5 }
    name     = "‘æ1ŒR’c"
    location = 1323
    division =
    { id            = { type = 26501 id = 6 }
      name          = "‘æ1íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 7 }
      name          = "‘æ2íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 8 }
      name          = "‘æ3‹@b•”‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 9 }
    name     = "‘æ2ŒR’c"
    location = 1323
    division =
    { id            = { type = 26501 id = 10 }
      name          = "‘æ3íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 11 }
      name          = "‘æ4íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 12 }
      name          = "‘æ4‹@b•”‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 13 }
    name     = "‘æ3ŒR’c"
    location = 1323
    division =
    { id            = { type = 26501 id = 14 }
      name          = "‘æ5íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 15 }
      name          = "‘æ6íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 16 }
      name          = "‘æ5‹@b•”‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 17 }
    name     = "‘æ4ŒR’c"
    location = 2632
    division =
    { id            = { type = 26501 id = 18 }
      name          = "‘æ7íp‹@b‘å‘à"
      model         = 8
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 19 }
      name          = "‘æ8íp‹@b‘å‘à"
      model         = 8
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 20 }
      name          = "‘æ9íp‹@b‘å‘à"
      model         = 8
      type          = paratrooper
      brigade_model = 0
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 21 }
    name     = "‘æ5ŒR’c"
    location = 2632
    division =
    { id            = { type = 26501 id = 22 }
      name          = "‘æ10íp‹@b‘å‘à"
      model         = 8
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 23 }
      name          = "‘æ11íp‹@b‘å‘à"
      model         = 8
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 24 }
      name          = "‘æ12íp‹@b‘å‘à"
      model         = 8
      type          = paratrooper
      brigade_model = 0
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 25 }
    name     = "‘æ6ŒR’c"
    location = 2632
    division =
    { id            = { type = 26501 id = 26 }
      name          = "‘æ13íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 27 }
      name          = "‘æ14íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 28 }
      name          = "‘æ15íp‹@b‘å‘à"
      model         = 5
      type          = paratrooper
      brigade_model = 0
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 29 }
    name     = "‘æ7ŒR’c"
    location = 2632
    division =
    { id            = { type = 26501 id = 30 }
      name          = "‘æ16íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 31 }
      name          = "‘æ17íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 32 }
      name          = "‘æ18íp‹@b‘å‘à"
      model         = 5
      type          = paratrooper
      brigade_model = 0
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 33 }
    name     = "‘æ8ŒR’c"
    location = 2632
    division =
    { id            = { type = 26501 id = 34 }
      name          = "‘æ19íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 35 }
      name          = "‘æ20íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 36 }
      name          = "‘æ21íp‹@b‘å‘à"
      model         = 5
      type          = paratrooper
      brigade_model = 0
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 37 }
    name     = "‘æ9ŒR’c"
    location = 1322
    division =
    { id            = { type = 26501 id = 38 }
      name          = "‘æ22íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 39 }
      name          = "‘æ23íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 40 }
      name          = "‘æ24íp‹@b‘å‘à"
      model         = 5
      type          = paratrooper
      brigade_model = 0
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 41 }
    name     = "‘æ10ŒR’c"
    location = 1322
    division =
    { id            = { type = 26501 id = 42 }
      name          = "‘æ22íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 43 }
      name          = "‘æ23íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 44 }
      name          = "‘æ24íp‹@b‘å‘à"
      model         = 6
      type          = paratrooper
      brigade_model = 0
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 45 }
    name     = "‘æ11ŒR’c"
    location = 1322
    division =
    { id            = { type = 26501 id = 46 }
      name          = "‘æ25íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 47 }
      name          = "‘æ26íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 48 }
      name          = "‘æ27íp‹@b‘å‘à"
      model         = 6
      type          = paratrooper
      brigade_model = 0
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 26501 id = 49 }
    name     = "‘æ11ŒR’c"
    location = 1923
    division =
    { id            = { type = 26501 id = 50 }
      name          = "‘æ28íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 51 }
      name          = "‘æ29íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 26501 id = 52 }
      name          = "‘æ30íp‹@b‘å‘à"
      model         = 6
      type          = paratrooper
      brigade_model = 0
      strength      = 100
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8144 }
    name     = "“ˆê’†‘ŠCŒR ‘æ3ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3742 }
      name     = "“ì’¿"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8146 }
    name     = "“ˆê’†‘ŠCŒR ‘æ4ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632

    division =
    { id       = { type = 26502 id = 3743 }
      name     = "•Û–¯"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8148 }
    name     = "“ˆê’†‘ŠCŒR ‘æ5ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3745 }
      name     = "ƒgƒ“ƒ`["
      model    = 2
      type     = light_cruiser
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8150 }
    name     = "“ˆê’†‘ŠCŒR ‘æ6ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3747 }
      name     = "ŠCâÔ"
      model    = 2
      type     = light_cruiser
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8152 }
    name     = "“ˆê’†‘ŠCŒR ‘æ7ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3748 }
      name     = "ŠC’¿"
      model    = 2
      type     = light_cruiser
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8154 }
    name     = "“ˆê’†‘ŠCŒR ‘æ8ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3750 }
      name     = "‘æ2‹ì’€ŠÍx‘à"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8156 }
    name     = "“ˆê’†‘ŠCŒR ‘æ9ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3753 }
      name     = "‘æ5‹ì’€ŠÍx‘à"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8158 }
    name     = "“ˆê’†‘ŠCŒR ‘æ10ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3754 }
      name     = "‘æ6‹ì’€ŠÍx‘à"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8160 }
    name     = "“ˆê’†‘ŠCŒR ‘æ11ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3756 }
      name     = "‘æ8‹ì’€ŠÍx‘à"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8162 }
    name     = "“ˆê’†‘ŠCŒR ‘æ12ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3757 }
      name     = "‘æ9‹ì’€ŠÍx‘à"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8164 }
    name     = "“ˆê’†‘ŠCŒR ‘æ13ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3759 }
      name     = "‘æ11‹ì’€ŠÍx‘à"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8166 }
    name     = "“ˆê’†‘ŠCŒR ‘æ14ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3760 }
      name     = "‘æ12‹ì’€ŠÍx‘à"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8168 }
    name     = "“ˆê’†‘ŠCŒR ‘æ15ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3762 }
      name     = "‘æ14‹ì’€ŠÍx‘à"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8170 }
    name     = "“ˆê’†‘ŠCŒR ‘æ21ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3764 }
      name     = "‘æ1‹ì’€ŠÍt’c"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8172 }
    name     = "“ˆê’†‘ŠCŒR ‘æ22ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3766 }
      name     = "‘æ3‹ì’€ŠÍt’c"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8174 }
    name     = "“ˆê’†‘ŠCŒR ‘æ23ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3767 }
      name     = "‘æ4‹ì’€ŠÍt’c"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8176 }
    name     = "“ˆê’†‘ŠCŒR ‘æ24ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3768 }
      name     = "‘æ5‹ì’€ŠÍt’c"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8178 }
    name     = "“ˆê’†‘ŠCŒR ‘æ25ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3769 }
      name     = "‘æ1—A‘—ŠÍ•”‘à"
      model    = 4
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8180 }
    name     = "“ˆê’†‘ŠCŒR ‘æ26ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3770 }
      name     = "‘æ2—A‘—ŠÍ•”‘à"
      model    = 4
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 26502 id = 8182 }
    name     = "“ˆê’†‘ŠCŒR ‘æ27ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 26502 id = 3771 }
      name     = "‘æ3—A‘—ŠÍ•”‘à"
      model    = 4
      type     = transport
      strength = 100.0000
    }
  }
  navaldivision = {
    dormant = yes
    id      = { type = 26502 id = 3780 }
    name    = "—É”J"
    type    = carrier
    model   = 4
    extra1  = cag
    brigade_model1 = 4
  }
}
