
##############################
# Country definition for U12 #
##############################

province = { id = 1431 air_base = 10 radar_station = 10  rocket_test = 10 infra = 2.0  anti_air = 10 } # ö\èY

#####################
# Country main data #
#####################

country =
{ tag                 = U12
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 1431
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 1431 }
  ownedprovinces      = { 1431 }
  controlledprovinces = { 1431 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 500 supplies = 1000 }
  landunit =
  { id       = { type = 15001 id = 5177 }
    name     = "ëÊ1åRíc"
    location = 183
    home     = 136
    division =
    { id            = { type = 15001 id = 5179 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5180 }
    name     = "ëÊ2åRíc"
    location = 139
    home     = 136
    division =
    { id            = { type = 15001 id = 5182 }
      name          = "ëÊ2BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = super_heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5183 }
    name     = "ëÊ3åRíc"
    location = 149
    home     = 136
    division =
    { id            = { type = 15001 id = 5185 }
      name          = "ëÊ3BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5186 }
    name     = "ëÊ4åRíc"
    location = 125
    division =
    { id            = { type = 15001 id = 5188 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5189 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5190 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5191 }
      name          = "ëÊ2BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5192 }
      name          = "ëÊ3BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5193 }
    name     = "ëÊ5åRíc"
    location = 110
    division =
    { id            = { type = 15001 id = 5195 }
      name          = "ëÊ2BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5196 }
      name          = "ëÊ2BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5197 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5198 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5199 }
      name          = "ëÊ6BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5200 }
    name     = "ëÊ6åRíc"
    location = 118
    division =
    { id            = { type = 15001 id = 5202 }
      name          = "ëÊ3BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5203 }
      name          = "ëÊ3BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5204 }
      name          = "ëÊ7BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5205 }
      name          = "ëÊ8BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5206 }
      name          = "ëÊ9BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5207 }
    name     = "ëÊ7åRíc"
    location = 124
    division =
    { id            = { type = 15001 id = 5209 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5210 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5211 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5212 }
      name          = "ëÊ11BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5213 }
      name          = "ëÊ12BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5214 }
    name     = "ëÊ8åRíc"
    location = 129
    division =
    { id            = { type = 15001 id = 5216 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5217 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5218 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5219 }
      name          = "ëÊ14BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5220 }
      name          = "ëÊ15BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5221 }
    name     = "ëÊ9åRíc"
    location = 1792
    home     = 1864
    division =
    { id            = { type = 15001 id = 5223 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5224 }
    name     = "ëÊ10åRíc"
    location = 1806
    home     = 1864
    division =
    { id            = { type = 15001 id = 5226 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = super_heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5227 }
    name     = "ëÊ11åRíc"
    location = 1822
    home     = 1864
    division =
    { id            = { type = 15001 id = 5229 }
      name          = "ëÊ6BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5230 }
    name     = "ëÊ12åRíc"
    location = 1813
    home     = 1864
    division =
    { id            = { type = 15001 id = 5232 }
      name          = "ëÊ6BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5233 }
      name          = "ëÊ6BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5234 }
      name          = "ëÊ16BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5235 }
      name          = "ëÊ17BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5236 }
      name          = "ëÊ18BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5237 }
    name     = "ëÊ13åRíc"
    location = 1792
    home     = 1864
    division =
    { id            = { type = 15001 id = 5239 }
      name          = "ëÊ7BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5240 }
      name          = "ëÊ7BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5241 }
      name          = "ëÊ19BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5242 }
      name          = "ëÊ20BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5243 }
      name          = "ëÊ21BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5244 }
    name     = "ëÊ14åRíc"
    location = 1804
    home     = 1864
    division =
    { id            = { type = 15001 id = 5246 }
      name          = "ëÊ8BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5247 }
      name          = "ëÊ8BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5248 }
      name          = "ëÊ22BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5249 }
      name          = "ëÊ23BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5250 }
      name          = "ëÊ24BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5251 }
    name     = "ëÊ15åRíc"
    location = 700
    home     = 1864
    division =
    { id            = { type = 15001 id = 5253 }
      name          = "ëÊ9BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5254 }
      name          = "ëÊ9BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5255 }
      name          = "ëÊ25BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5256 }
      name          = "ëÊ26BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5257 }
      name          = "ëÊ27BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5258 }
    name     = "ëÊ16åRíc"
    location = 2219
    division =
    { id            = { type = 15001 id = 5260 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5261 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5262 }
      name          = "ëÊ28BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5263 }
      name          = "ëÊ29BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5264 }
      name          = "ëÊ30BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5279 }
    name     = "ëÊ19åRíc"
    location = 2529
    division =
    { id            = { type = 15001 id = 5281 }
      name          = "ëÊ7BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5282 }
    name     = "ëÊ20åRíc"
    location = 1543
    home     = 1551
    division =
    { id            = { type = 15001 id = 5284 }
      name          = "ëÊ8BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5285 }
    name     = "ëÊ21åRíc"
    location = 1539
    home     = 1557
    division =
    { id            = { type = 15001 id = 5287 }
      name          = "ëÊ9BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5288 }
    name     = "ëÊ22åRíc"
    location = 1244
    division =
    { id            = { type = 15001 id = 5290 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5291 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5292 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5293 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5294 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5295 }
    name     = "ëÊ23åRíc"
    location = 1396
    division =
    { id            = { type = 15001 id = 5297 }
      name          = "ëÊ14BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5298 }
      name          = "ëÊ14BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5299 }
      name          = "ëÊ40BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5300 }
      name          = "ëÊ41BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5301 }
      name          = "ëÊ42BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5302 }
    name     = "ëÊ24åRíc"
    location = 1372
    division =
    { id            = { type = 15001 id = 5304 }
      name          = "ëÊ15BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5305 }
      name          = "ëÊ15BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5306 }
      name          = "ëÊ43BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5307 }
      name          = "ëÊ44BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5308 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5309 }
    name     = "ëÊ25åRíc"
    location = 1237
    division =
    { id            = { type = 15001 id = 5311 }
      name          = "ëÊ16BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5312 }
      name          = "ëÊ16BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5313 }
      name          = "ëÊ46BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5314 }
      name          = "ëÊ47BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5315 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5316 }
    name     = "ëÊ26åRíc"
    location = 1214
    division =
    { id            = { type = 15001 id = 5318 }
      name          = "ëÊ17BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5319 }
      name          = "ëÊ17BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5320 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5321 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5322 }
      name          = "ëÊ51BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5323 }
    name     = "ëÊ27åRíc"
    location = 1204
    division =
    { id            = { type = 15001 id = 5325 }
      name          = "ëÊ18BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5326 }
      name          = "ëÊ18BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5327 }
      name          = "ëÊ52BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5328 }
      name          = "ëÊ53BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5329 }
      name          = "ëÊ54BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5330 }
    name     = "ëÊ28åRíc"
    location = 1448
    home     = 1473
    division =
    { id            = { type = 15001 id = 5332 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5333 }
    name     = "ëÊ29åRíc"
    location = 1446
    home     = 1431
    division =
    { id            = { type = 15001 id = 5335 }
      name          = "ëÊ11BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5336 }
    name     = "ëÊ30åRíc"
    location = 1556
    home     = 1551
    division =
    { id            = { type = 15001 id = 5338 }
      name          = "ëÊ12BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5339 }
    name     = "ëÊ31åRíc"
    location = 2647
    division =
    { id            = { type = 15001 id = 5341 }
      name          = "ëÊ19BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5342 }
      name          = "ëÊ20BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5343 }
      name          = "ëÊ21BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5344 }
      name          = "ëÊ19BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5345 }
      name          = "ëÊ20BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5346 }
      name          = "ëÊ21BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5347 }
      name          = "ëÊ55BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5348 }
      name          = "ëÊ56BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5349 }
      name          = "ëÊ57BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5350 }
      name          = "ëÊ58BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5351 }
      name          = "ëÊ59BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5352 }
      name          = "ëÊ60BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5353 }
      name          = "ëÊ61BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5354 }
      name          = "ëÊ62BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5371 }
    name     = "ëÊ33åRíc"
    location = 1337
    division =
    { id            = { type = 15001 id = 5373 }
      name          = "ëÊ25BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5374 }
      name          = "ëÊ26BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5375 }
      name          = "ëÊ27BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5376 }
      name          = "ëÊ25BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5377 }
      name          = "ëÊ26BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5378 }
      name          = "ëÊ27BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5387 }
    name     = "ëÊ34åRíc"
    location = 1347
    division =
    { id            = { type = 15001 id = 5389 }
      name          = "ëÊ28BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5390 }
      name          = "ëÊ29BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5391 }
      name          = "ëÊ30BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5392 }
      name          = "ëÊ28BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5393 }
      name          = "ëÊ29BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5394 }
      name          = "ëÊ30BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5395 }
      name          = "ëÊ79BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5396 }
      name          = "ëÊ80BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5397 }
      name          = "ëÊ81BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5398 }
      name          = "ëÊ82BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5399 }
      name          = "ëÊ83BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5400 }
      name          = "ëÊ84BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5401 }
      name          = "ëÊ85BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5402 }
      name          = "ëÊ86BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5403 }
    name     = "ëÊ35åRíc"
    location = 2219
    division =
    { id            = { type = 15001 id = 5405 }
      name          = "ëÊ31BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5406 }
      name          = "ëÊ32BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5407 }
      name          = "ëÊ33BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5408 }
      name          = "ëÊ31BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5409 }
      name          = "ëÊ32BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5410 }
      name          = "ëÊ33BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5411 }
      name          = "ëÊ87BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5412 }
      name          = "ëÊ88BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5413 }
      name          = "ëÊ89BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5414 }
      name          = "ëÊ90BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5415 }
      name          = "ëÊ91BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5416 }
      name          = "ëÊ92BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5417 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5418 }
      name          = "ëÊ94BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5419 }
    name     = "ëÊ36åRíc"
    location = 1199
    division =
    { id            = { type = 15001 id = 5421 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5422 }
      name          = "ëÊ35BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5423 }
      name          = "ëÊ36BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5424 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5425 }
      name          = "ëÊ35BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5426 }
      name          = "ëÊ36BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5427 }
      name          = "ëÊ95BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5428 }
      name          = "ëÊ96BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5429 }
      name          = "ëÊ97BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5430 }
      name          = "ëÊ98BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5431 }
      name          = "ëÊ99BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5432 }
      name          = "ëÊ100BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5433 }
      name          = "ëÊ101BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5434 }
      name          = "ëÊ102BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5435 }
    name     = "ëÊ37åRíc"
    location = 1199
    division =
    { id            = { type = 15001 id = 5437 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5438 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5439 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5440 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5441 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5442 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5443 }
      name          = "ëÊ103BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5444 }
      name          = "ëÊ104BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5445 }
      name          = "ëÊ105BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5446 }
      name          = "ëÊ106BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5447 }
      name          = "ëÊ107BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5448 }
      name          = "ëÊ108BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5449 }
      name          = "ëÊ109BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5450 }
      name          = "ëÊ110BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5451 }
    name     = "ëÊ38åRíc"
    location = 2219
    division =
    { id            = { type = 15001 id = 5453 }
      name          = "ëÊ40BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5454 }
      name          = "ëÊ41BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5455 }
      name          = "ëÊ42BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5456 }
      name          = "ëÊ40BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5457 }
      name          = "ëÊ41BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5458 }
      name          = "ëÊ42BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5459 }
      name          = "ëÊ111BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5460 }
      name          = "ëÊ112BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5467 }
    name     = "ëÊ39åRíc"
    location = 1721
    home     = 722
    division =
    { id            = { type = 15001 id = 5469 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5470 }
    name     = "ëÊ40åRíc"
    location = 599
    home     = 722
    division =
    { id            = { type = 15001 id = 5472 }
      name          = "ëÊ14BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5473 }
    name     = "ëÊ41åRíc"
    location = 2043
    home     = 1455
    division =
    { id            = { type = 15001 id = 5475 }
      name          = "ëÊ15BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5476 }
    name     = "ëÊ42åRíc"
    location = 1513
    home     = 722
    division =
    { id            = { type = 15001 id = 5478 }
      name          = "ëÊ43BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5479 }
      name          = "ëÊ43BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5480 }
      name          = "ëÊ119BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5481 }
      name          = "ëÊ120BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5482 }
      name          = "ëÊ121BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5483 }
    name     = "ëÊ43åRíc"
    location = 1297
    home     = 722
    division =
    { id            = { type = 15001 id = 5485 }
      name          = "ëÊ44BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5486 }
      name          = "ëÊ44BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5487 }
      name          = "ëÊ122BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5488 }
      name          = "ëÊ123BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5489 }
      name          = "ëÊ124BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5490 }
    name     = "ëÊ44åRíc"
    location = 1315
    division =
    { id            = { type = 15001 id = 5492 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5493 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5494 }
      name          = "ëÊ125BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5495 }
      name          = "ëÊ126BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5496 }
      name          = "ëÊ127BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5497 }
    name     = "ëÊ45åRíc"
    location = 1515
    home     = 722
    division =
    { id            = { type = 15001 id = 5499 }
      name          = "ëÊ46BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5500 }
      name          = "ëÊ46BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5501 }
      name          = "ëÊ128BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5502 }
      name          = "ëÊ129BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5503 }
      name          = "ëÊ130BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5504 }
    name     = "ëÊ46åRíc"
    location = 1694
    division =
    { id            = { type = 15001 id = 5506 }
      name          = "ëÊ47BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5507 }
      name          = "ëÊ47BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5508 }
      name          = "ëÊ131BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5509 }
      name          = "ëÊ132BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5510 }
      name          = "ëÊ133BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5511 }
    name     = "ëÊ47åRíc"
    location = 1472
    home     = 1473
    division =
    { id            = { type = 15001 id = 5513 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5514 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5515 }
      name          = "ëÊ134BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5516 }
      name          = "ëÊ135BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5517 }
      name          = "ëÊ136BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5518 }
    name     = "ëÊ48åRíc"
    location = 1345
    division =
    { id            = { type = 15001 id = 5520 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5521 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5522 }
      name          = "ëÊ137BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5523 }
      name          = "ëÊ138BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5524 }
      name          = "ëÊ139BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5525 }
    name     = "ëÊ49åRíc"
    location = 1299
    division =
    { id            = { type = 15001 id = 5527 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5528 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5529 }
      name          = "ëÊ140BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5530 }
      name          = "ëÊ141BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5531 }
      name          = "ëÊ142BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5532 }
    name     = "ëÊ50åRíc"
    location = 109
    division =
    { id            = { type = 15001 id = 5534 }
      name          = "ëÊ51BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5535 }
      name          = "ëÊ52BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5536 }
      name          = "ëÊ53BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5537 }
      name          = "ëÊ51BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5538 }
      name          = "ëÊ52BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5539 }
      name          = "ëÊ53BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5540 }
      name          = "ëÊ143BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5541 }
      name          = "ëÊ144BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5542 }
      name          = "ëÊ145BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5543 }
      name          = "ëÊ146BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5544 }
      name          = "ëÊ147BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5545 }
      name          = "ëÊ148BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5546 }
    name     = "ëÊ51åRíc"
    location = 1199
    division =
    { id            = { type = 15001 id = 5548 }
      name          = "ëÊ54BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5549 }
      name          = "ëÊ55BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5550 }
      name          = "ëÊ56BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5551 }
      name          = "ëÊ54BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5552 }
      name          = "ëÊ55BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5553 }
      name          = "ëÊ56BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5560 }
    name     = "ëÊ52åRíc"
    location = 1392
    division =
    { id            = { type = 15001 id = 5562 }
      name          = "ëÊ57BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5563 }
      name          = "ëÊ58BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5564 }
      name          = "ëÊ59BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5565 }
      name          = "ëÊ57BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5566 }
      name          = "ëÊ58BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5567 }
      name          = "ëÊ59BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5588 }
    name     = "ëÊ54åRíc"
    location = 38
    division =
    { id            = { type = 15001 id = 5590 }
      name          = "ëÊ63BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5591 }
      name          = "ëÊ64BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5592 }
      name          = "ëÊ65BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5593 }
      name          = "ëÊ63BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5594 }
      name          = "ëÊ64BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5595 }
      name          = "ëÊ65BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5644 }
    name     = "ëÊ58åRíc"
    location = 2219
    division =
    { id            = { type = 15001 id = 5646 }
      name          = "ëÊ75BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5647 }
      name          = "ëÊ76BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5648 }
      name          = "ëÊ77BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5649 }
      name          = "ëÊ75BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5650 }
      name          = "ëÊ76BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5651 }
      name          = "ëÊ77BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5658 }
    name     = "ëÊ59åRíc"
    location = 1800
    home     = 1864
    division =
    { id            = { type = 15001 id = 5660 }
      name          = "ëÊ78BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5661 }
      name          = "ëÊ79BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5662 }
      name          = "ëÊ80BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5663 }
      name          = "ëÊ78BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5664 }
      name          = "ëÊ79BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5665 }
      name          = "ëÊ80BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5666 }
      name          = "ëÊ197BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5667 }
      name          = "ëÊ198BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5668 }
      name          = "ëÊ199BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5669 }
      name          = "ëÊ200BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5670 }
      name          = "ëÊ201BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5671 }
      name          = "ëÊ202BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5686 }
    name     = "ëÊ61åRíc"
    location = 1800
    division =
    { id            = { type = 15001 id = 5688 }
      name          = "ëÊ84BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5689 }
      name          = "ëÊ85BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5690 }
      name          = "ëÊ86BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5691 }
      name          = "ëÊ84BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5692 }
      name          = "ëÊ85BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5693 }
      name          = "ëÊ86BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5694 }
      name          = "ëÊ209BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5695 }
      name          = "ëÊ210BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5696 }
      name          = "ëÊ211BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5697 }
      name          = "ëÊ212BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5698 }
      name          = "ëÊ213BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5699 }
      name          = "ëÊ214BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5700 }
    name     = "ëÊ62åRíc"
    location = 1466
    home     = 722
    division =
    { id            = { type = 15001 id = 5702 }
      name          = "ëÊ87BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5703 }
      name          = "ëÊ88BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5704 }
      name          = "ëÊ89BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5705 }
      name          = "ëÊ87BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5706 }
      name          = "ëÊ88BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5707 }
      name          = "ëÊ89BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5708 }
      name          = "ëÊ215BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5716 }
    name     = "ëÊ63åRíc"
    location = 1346
    division =
    { id            = { type = 15001 id = 5718 }
      name          = "ëÊ90BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5719 }
      name          = "ëÊ91BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5720 }
      name          = "ëÊ92BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5721 }
      name          = "ëÊ90BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5722 }
      name          = "ëÊ91BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5723 }
      name          = "ëÊ92BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5732 }
    name     = "ëÊ64åRíc"
    location = 1347
    division =
    { id            = { type = 15001 id = 5734 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5735 }
      name          = "ëÊ94BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5736 }
      name          = "ëÊ95BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5737 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5738 }
      name          = "ëÊ94BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5739 }
      name          = "ëÊ95BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5740 }
      name          = "ëÊ231BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5741 }
      name          = "ëÊ232BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5742 }
      name          = "ëÊ233BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5743 }
      name          = "ëÊ234BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5744 }
      name          = "ëÊ235BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5745 }
      name          = "ëÊ236BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5746 }
      name          = "ëÊ237BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5747 }
      name          = "ëÊ238BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5796 }
    name     = "ëÊ7åRíc"
    location = 1157
    division =
    { id            = { type = 15001 id = 5797 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5798 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5799 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5800 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5801 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5802 }
    name     = "ëÊ7åRíc"
    location = 346
    division =
    { id            = { type = 15001 id = 5803 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5804 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5805 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      ##locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5808 }
    name     = "ëÊ7åRíc"
    location = 345
    division =
    { id            = { type = 15001 id = 5809 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5810 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5811 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5812 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5813 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5814 }
    name     = "ëÊ7åRíc"
    location = 352
    division =
    { id            = { type = 15001 id = 5815 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5816 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5817 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5818 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5819 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5820 }
    name     = "ëÊ7åRíc"
    location = 1563
    division =
    { id            = { type = 15001 id = 5821 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5822 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5823 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5826 }
    name     = "ëÊ7åRíc"
    location = 515
    division =
    { id            = { type = 15001 id = 5827 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5828 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5829 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5830 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5831 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5832 }
    name     = "ëÊ7åRíc"
    location = 512
    division =
    { id            = { type = 15001 id = 5833 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5834 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5835 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5836 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5837 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5838 }
    name     = "ëÊ7åRíc"
    location = 542
    division =
    { id            = { type = 15001 id = 5839 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5840 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5841 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5842 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5843 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15001 id = 5844 }
    name     = "ëÊ7åRíc"
    location = 523
    division =
    { id            = { type = 15001 id = 5845 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5846 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5847 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15001 id = 5848 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
     }
    }
    landunit =
    { id       = { type = 15001 id = 5849 }
      name     = "ëÊ7åRíc"
      location = 93
      division =
      { id            = { type = 15001 id = 5850 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5851 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5852 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5853 }
      name     = "ëÊ7åRíc"
      location = 98
      division =
      { id            = { type = 15001 id = 5854 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5855 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5856 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5857 }
      name     = "ëÊ7åRíc"
      location = 104
      division =
      { id            = { type = 15001 id = 5858 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5859 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5860 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5861 }
      name     = "ëÊ7åRíc"
      location = 112
      division =
      { id            = { type = 15001 id = 5862 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5863 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5864 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5865 }
      name     = "ëÊ7åRíc"
      location = 114
      division =
      { id            = { type = 15001 id = 5866 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5867 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5868 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5869 }
      name     = "ëÊ7åRíc"
      location = 108
      division =
      { id            = { type = 15001 id = 5870 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5871 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5872 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5873 }
      name     = "ëÊ7åRíc"
      location = 117
      division =
      { id            = { type = 15001 id = 5874 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5875 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5876 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5877 }
      name     = "ëÊ7åRíc"
      location = 128
      division =
      { id            = { type = 15001 id = 5878 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5879 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5880 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5881 }
      name     = "ëÊ7åRíc"
      location = 132
      division =
      { id            = { type = 15001 id = 5882 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5883 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5884 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5885 }
      name     = "ëÊ7åRíc"
      location = 133
      division =
      { id            = { type = 15001 id = 5886 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5887 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5888 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5889 }
      name     = "ëÊ7åRíc"
      location = 334
      division =
      { id            = { type = 15001 id = 5890 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5891 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 58920 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5892 }
      name     = "ëÊ7åRíc"
      location = 331
      division =
      { id            = { type = 15001 id = 5893 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5894 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5895 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5896 }
      name     = "ëÊ7åRíc"
      location = 59
      division =
      { id            = { type = 15001 id = 5897 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5898 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5899 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5900 }
      name     = "ëÊ7åRíc"
      location = 34
      division =
      { id            = { type = 15001 id = 5901 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5902 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5903 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5904 }
      name     = "ëÊ7åRíc"
      location = 32
      division =
      { id            = { type = 15001 id = 5905 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5906 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5907 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5908 }
      name     = "ëÊ7åRíc"
      location = 37
      division =
      { id            = { type = 15001 id = 5909 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5910 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5911 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5912 }
      name     = "ëÊ7åRíc"
      location = 39
      division =
      { id            = { type = 15001 id = 5913 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5914 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5915 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5916 }
      name     = "ëÊ7åRíc"
      location = 41
      division =
      { id            = { type = 15001 id = 5917 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5918 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5919 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5920 }
      name     = "ëÊ7åRíc"
      location = 18
      division =
      { id            = { type = 15001 id = 5921 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5922 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5923 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5924 }
      name     = "ëÊ7åRíc"
      location = 43
      division =
      { id            = { type = 15001 id = 5925 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5926 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5927 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5928 }
      name     = "ëÊ7åRíc"
      location = 45
      division =
      { id            = { type = 15001 id = 5929 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5930 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5931 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5932 }
      name     = "ëÊ7åRíc"
      location = 48
      division =
      { id            = { type = 15001 id = 5933 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5934 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5935 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5936 }
      name     = "ëÊ7åRíc"
      location = 46
      division =
      { id            = { type = 15001 id = 5937 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5938 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5939 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5940 }
      name     = "ëÊ7åRíc"
      location = 78
      division =
      { id            = { type = 15001 id = 5941 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5942 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5943 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5944 }
      name     = "ëÊ7åRíc"
      location = 87
      division =
      { id            = { type = 15001 id = 5945 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5946 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5947 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5948 }
      name     = "ëÊ7åRíc"
      location = 91
      division =
      { id            = { type = 15001 id = 5949 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5950 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5951 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5952 }
      name     = "ëÊ7åRíc"
      location = 122
      division =
      { id            = { type = 15001 id = 5953 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5954 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 5955 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 5971 }
      name     = "ëÊ63åRíc"
      location = 2649
      division =
      { id            = { type = 15001 id = 5972 }
        name          = "ëÊ90BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5973 }
        name          = "ëÊ91BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5974 }
        name          = "ëÊ92BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = light_armor_brigade
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5975 }
        name          = "ëÊ90BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5976 }
        name          = "ëÊ91BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = light_armor_brigade
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5977 }
        name          = "ëÊ92BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = super_heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5978 }
        name          = "ëÊ223BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5979 }
        name          = "ëÊ224BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5980 }
        name          = "ëÊ225BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5981 }
        name          = "ëÊ226BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5982 }
        name          = "ëÊ227BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5983 }
        name          = "ëÊ228BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = light_armor_brigade
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5984 }
        name          = "ëÊ229BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = light_armor_brigade
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5985 }
        name          = "ëÊ230BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = light_armor_brigade
        strength      = 100.0000
      }
    }
    landunit =
    { id       = { type = 15001 id = 5986 }
      name     = "ëÊ63åRíc"
      location = 2649
      division =
      { id            = { type = 15001 id = 5987 }
        name          = "ëÊ90BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5988 }
        name          = "ëÊ91BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5989 }
        name          = "ëÊ92BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = light_armor_brigade
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 59900 }
        name          = "ëÊ90BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5990 }
        name          = "ëÊ91BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = light_armor_brigade
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5992 }
        name          = "ëÊ92BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = super_heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5993 }
        name          = "ëÊ223BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5994 }
        name          = "ëÊ224BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5995 }
        name          = "ëÊ225BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5996 }
        name          = "ëÊ226BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5997 }
        name          = "ëÊ227BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = heavy_armor
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5998 }
        name          = "ëÊ228BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = light_armor_brigade
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 5999 }
        name          = "ëÊ229BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = light_armor_brigade
        strength      = 100.0000
      }
      division =
      { id            = { type = 15001 id = 6000 }
        name          = "ëÊ230BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = light_armor_brigade
        strength      = 100.0000
      }
    }
    landunit =
    { id       = { type = 15001 id = 6016 }
      name     = "ëÊ7åRíc"
      location = 337
      division =
      { id            = { type = 15001 id = 6017 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 60180 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6018 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6019 }
      name     = "ëÊ7åRíc"
      location = 332
      division =
      { id            = { type = 15001 id = 6020 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6021 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6022 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6023 }
      name     = "ëÊ7åRíc"
      location = 1726
      division =
      { id            = { type = 15001 id = 6024 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6025 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6026 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6027 }
      name     = "ëÊ7åRíc"
      location = 326
      division =
      { id            = { type = 15001 id = 6028 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6029 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6030 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6031 }
      name     = "ëÊ7åRíc"
      location = 325
      division =
      { id            = { type = 15001 id = 6032 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6033 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6034 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6035 }
      name     = "ëÊ7åRíc"
      location = 60
      division =
      { id            = { type = 15001 id = 6036 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6037 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6038 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6039 }
      name     = "ëÊ7åRíc"
      location = 35
      division =
      { id            = { type = 15001 id = 6040 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6041 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6042 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6043 }
      name     = "ëÊ7åRíc"
      location = 2555
      division =
      { id            = { type = 15001 id = 6044 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6045 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6046 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6047 }
      name     = "ëÊ7åRíc"
      location = 92
      division =
      { id            = { type = 15001 id = 6048 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6049 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6050 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6051 }
      name     = "ëÊ7åRíc"
      location = 292
      division =
      { id            = { type = 15001 id = 6052 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6053 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6054 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6055 }
      name     = "ëÊ7åRíc"
      location = 293
      division =
      { id            = { type = 15001 id = 6056 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6057 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6058 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6059 }
      name     = "ëÊ7åRíc"
      location = 294
      division =
      { id            = { type = 15001 id = 6060 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6061 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6062 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6063 }
      name     = "ëÊ7åRíc"
      location = 349
      division =
      { id            = { type = 15001 id = 6064 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6065 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6066 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6067 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6068 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6069 }
      name     = "ëÊ7åRíc"
      location = 350
      division =
      { id            = { type = 15001 id = 6070 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6071 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6072 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6073 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6074 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6075 }
      name     = "ëÊ7åRíc"
      location = 1714
      division =
      { id            = { type = 15001 id = 6076 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6077 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6078 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6079 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6080 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6081 }
      name     = "ëÊ7åRíc"
      location = 354
      division =
      { id            = { type = 15001 id = 6082 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6083 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6084 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6085 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6086 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6087 }
      name     = "ëÊ7åRíc"
      location = 355
      division =
      { id            = { type = 15001 id = 6088 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6089 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6090 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6091 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6092 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6093 }
      name     = "ëÊ7åRíc"
      location = 356
      division =
      { id            = { type = 15001 id = 6094 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6095 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6096 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6097 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6098 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6099 }
      name     = "ëÊ7åRíc"
      location = 357
      division =
      { id            = { type = 15001 id = 6100 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6101 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6102 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6103 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6104 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6105 }
      name     = "ëÊ7åRíc"
      location = 358
      division =
      { id            = { type = 15001 id = 6106 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6107 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6108 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6109 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6110 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6111 }
      name     = "ëÊ7åRíc"
      location = 362
      division =
      { id            = { type = 15001 id = 6112 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6113 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6114 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6115 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6116 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6117 }
      name     = "ëÊ7åRíc"
      location = 363
      division =
      { id            = { type = 15001 id = 6118 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6119 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6120 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6121 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6122 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6123 }
      name     = "ëÊ7åRíc"
      location = 366
      division =
      { id            = { type = 15001 id = 6124 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6125 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6126 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6127 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6128 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6129 }
      name     = "ëÊ7åRíc"
      location = 513
      division =
      { id            = { type = 15001 id = 6130 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6131 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6132 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6133 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6134 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6135 }
      name     = "ëÊ7åRíc"
      location = 1376
      division =
      { id            = { type = 15001 id = 6136 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6137 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6138 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6139 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6140 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6141 }
      name     = "ëÊ7åRíc"
      location = 1393
      division =
      { id            = { type = 15001 id = 6142 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6143 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6144 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6145 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6146 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6147 }
      name     = "ëÊ7åRíc"
      location = 2236
      division =
      { id            = { type = 15001 id = 6148 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6149 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6150 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6151 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6152 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6153 }
      name     = "ëÊ7åRíc"
      location = 1200
      division =
      { id            = { type = 15001 id = 6154 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6155 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6156 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6157 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6158 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6171 }
      name     = "ëÊ7åRíc"
      location = 2653
      division =
      { id            = { type = 15001 id = 6172 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6173 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6174 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6175 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6176 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6177 }
      name     = "ëÊ7åRíc"
      location = 1524
      division =
      { id            = { type = 15001 id = 6178 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6179 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6180 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6181 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6182 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6183 }
      name     = "ëÊ7åRíc"
      location = 50
      division =
      { id            = { type = 15001 id = 6184 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6185 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6186 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6187 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6188 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6189 }
      name     = "ëÊ7åRíc"
      location = 120
      division =
      { id            = { type = 15001 id = 6190 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6191 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6192 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6193 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6194 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 6195 }
      name     = "ëÊ7åRíc"
      location = 378
      division =
      { id            = { type = 15001 id = 6196 }
        name          = "ëÊ34BETAåQ"
        model         = 33
        brigade_model = 0
        type          = marine
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6197 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6198 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6199 }
        name          = "ëÊ10BETAåQ"
        model         = 33
        brigade_model = 0
        type          = bergsjaeger
        extra         = heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
      division =
      { id            = { type = 15001 id = 6200 }
        name          = "ëÊ37BETAåQ"
        model         = 33
        brigade_model = 0
        type          = infantry
        extra         = super_heavy_armor
        strength      = 100.0000
        #locked        = yes
      }
    }
    landunit =
    { id       = { type = 15001 id = 1 }
      name     = "ÉJÉVÉÖÉKÉãÉnÉCÉî"
      location = 1431
      division =
      { type   = garrison
        model  = 16
        id     = { type = 15004 id = 1 }
        name   = "ÉJÉVÉÖÉKÉãÉnÉCÉî"
        locked = yes
      }
      division =
      { type   = garrison
        model  = 33
        id     = { type = 15004 id = 2 }
        name   = "ñÂãâ"
        locked = yes
      }
    }
}
