
##############################
# Country definition for U15 #
##############################

province = { id = 1156 air_base = 10 radar_station = 10  rocket_test = 10 infra = 2.0  anti_air = 10 } # ƒ”ƒFƒŠƒXƒN

#####################
# Country main data #
#####################

country =
{ tag                 = U15
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 1156
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 1156 }
  ownedprovinces      = { 1156 }
  controlledprovinces = { 1156 133 134 135 150 151 152 153 154 165 183 184  1534 1771 94 123 156 157 158 159 160 163 164 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 185 186
                          187 188 189 190 191 192 200 201 215 216 219 264 275 276 277 278 279 280 281 283 284 285 286 287 288 289 1150 1155
                          1533 1536 1564 1596 1597 1598 1774 1775 1776 1777 1778 1780 1781 1782 1783 1828 1829 1830 1831 1832 1833 1834 1836
                          1839 1840 1841 2240 2488 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 15151 id = 4072 }
    name     = "‘æ1ŒR’c"
    location = 1792
    division =
    { id            = { type = 15151 id = 4074 }
      name          = "‘æ1Ži—ßŒQ"
      model         = 33
      type          = hq
      strength      = 100.0000
      brigade_model = 0
      extra         = light_armor_brigade
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15151 id = 4075 }
    name     = "‘æ2ŒR’c"
    location = 1806
    division =
    { id            = { type = 15151 id = 4077 }
      name          = "‘æ2Ži—ßŒQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15151 id = 4078 }
    name     = "‘æ3ŒR’c"
    location = 1822
    division =
    { id            = { type = 15151 id = 4080 }
      name          = "‘æ3Ži—ßŒQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15151 id = 4081 }
    name     = "‘æ4ŒR’c"
    location = 1793
    division =
    { id            = { type = 15151 id = 4083 }
      name          = "‘æ1BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4086 }
      name          = "‘æ1BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4089 }
      name          = "‘æ4BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4090 }
      name          = "‘æ5BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4091 }
      name          = "‘æ6BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15151 id = 4097 }
    name     = "‘æ5ŒR’c"
    location = 406
    division =
    { id            = { type = 15151 id = 4099 }
      name          = "‘æ12BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4102 }
      name          = "‘æ4BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4105 }
      name          = "‘æ15BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4106 }
      name          = "‘æ16BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4107 }
      name          = "‘æ17BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15151 id = 4113 }
    name     = "‘æ6ŒR’c"
    location = 404
    division =
    { id            = { type = 15151 id = 4115 }
      name          = "‘æ23BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4118 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4121 }
      name          = "‘æ26BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4122 }
      name          = "‘æ27BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4123 }
      name          = "‘æ28BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15151 id = 4129 }
    name     = "‘æ7ŒR’c"
    location = 1812
    division =
    { id            = { type = 15151 id = 4131 }
      name          = "‘æ34BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4134 }
      name          = "‘æ10BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4137 }
      name          = "‘æ37BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4138 }
      name          = "‘æ38BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4139 }
      name          = "‘æ39BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15151 id = 4145 }
    name     = "‘æ8ŒR’c"
    location = 1819
    division =
    { id            = { type = 15151 id = 4147 }
      name          = "‘æ45BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4150 }
      name          = "‘æ13BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4153 }
      name          = "‘æ48BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4154 }
      name          = "‘æ49BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4155 }
      name          = "‘æ50BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15151 id = 4161 }
    name     = "‘æ9ŒR’c"
    location = 1823
    division =
    { id            = { type = 15151 id = 4163 }
      name          = "‘æ56BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4166 }
      name          = "‘æ16BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4169 }
      name          = "‘æ59BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4170 }
      name          = "‘æ60BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4171 }
      name          = "‘æ61BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15151 id = 4177 }
    name     = "‘æ10ŒR’c"
    location = 1822
    division =
    { id            = { type = 15151 id = 4179 }
      name          = "‘æ67BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4182 }
      name          = "‘æ19BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4185 }
      name          = "‘æ70BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4186 }
      name          = "‘æ71BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15151 id = 4187 }
      name          = "‘æ72BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15151 id = 1 }
    name     = "ƒ”ƒFƒŠƒXƒNƒnƒCƒ”"
    location = 1156
    division =
    { type  = garrison
      model = 15
      id    = { type = 15154 id = 1 }
      name  = "ƒ”ƒFƒŠƒXƒNƒnƒCƒ”"
    }
    division =
    { type  = garrison
      model = 33
      id    = { type = 15154 id = 2 }
      name  = "–å‹‰"
    }
  }
}
