
##############################
# Country definition for U23 #
##############################

province = { id = 529 air_base = 10 radar_station = 10  rocket_test = 10  anti_air = 10 infra = 2.0 } # ƒŠƒˆƒ“

#####################
# Country main data #
#####################

country =
{ tag                 = U23
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 529
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 529 }
  ownedprovinces      = { 529 }
  controlledprovinces = { 529 32 33 34 35 37 38 39 40 41 2555 18 42 43 44 36 57 58 60 61 323 325 326 59 54 56 62 63 319 320 321 322
                          324 360 361 328 358 359 362 363 55 64 317 841 318 2557 2514 1643 1676 364 365 527 528 2509 2242 327 72 73
                          316 1022 366 45 50 51 52 65 68  69 70 71  46  47  49   1019 1082 77   78  79  530 532 533  372  80  81 86
                          87  88   89  90 296 301 82 84 313 547 970 83 85 374 375 376 312 297 298 299 300 546 302 308 1779 1810 309
                          310 311  314 315 1014 989 66 67 74 75 76  1405 1018 1015 1016 48 
                          1563 345 344 1163 336 965 337 335
                          348 1157 346 347 343 338
                          350 351 353 1161 340 349
                          334 1537 1532 339 333 961 962
                          332 1726 331 2244 2243
                          341 342 1531 1162 1734 330
                          352 1714 354 355
                          356 357 536 537 329 1400 1623 473 482 1595 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 15501 id = 4072 }
    name     = "‘æ1ŒR’c"
    location = 52
    division =
    { id            = { type = 15501 id = 4074 }
      name          = "‘æ1Ži—ßŒQ"
      model         = 33
      type          = hq
      strength      = 100.0000
      brigade_model = 0
      extra         = light_armor_brigade
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4075 }
    name     = "‘æ2ŒR’c"
    location = 36
    division =
    { id            = { type = 15501 id = 4077 }
      name          = "‘æ2Ži—ßŒQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4078 }
    name     = "‘æ3ŒR’c"
    location = 324
    division =
    { id            = { type = 15501 id = 4080 }
      name          = "‘æ3Ži—ßŒQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4081 }
    name     = "‘æ4ŒR’c"
    location = 33
    division =
    { id            = { type = 15501 id = 4083 }
      name          = "‘æ1BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4086 }
      name          = "‘æ1BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4089 }
      name          = "‘æ4BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4090 }
      name          = "‘æ5BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4091 }
      name          = "‘æ6BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4097 }
    name     = "‘æ5ŒR’c"
    location = 42
    division =
    { id            = { type = 15501 id = 4099 }
      name          = "‘æ12BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4102 }
      name          = "‘æ4BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4105 }
      name          = "‘æ15BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4106 }
      name          = "‘æ16BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4107 }
      name          = "‘æ17BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4113 }
    name     = "‘æ6ŒR’c"
    location = 47
    division =
    { id            = { type = 15501 id = 4115 }
      name          = "‘æ23BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4118 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4121 }
      name          = "‘æ26BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4122 }
      name          = "‘æ27BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4123 }
      name          = "‘æ28BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4129 }
    name     = "‘æ7ŒR’c"
    location = 323
    division =
    { id            = { type = 15501 id = 4131 }
      name          = "‘æ34BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4134 }
      name          = "‘æ10BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4137 }
      name          = "‘æ37BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4138 }
      name          = "‘æ38BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4139 }
      name          = "‘æ39BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4145 }
    name     = "‘æ8ŒR’c"
    location = 364
    division =
    { id            = { type = 15501 id = 4147 }
      name          = "‘æ45BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4150 }
      name          = "‘æ13BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4153 }
      name          = "‘æ48BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4154 }
      name          = "‘æ49BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4155 }
      name          = "‘æ50BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4161 }
    name     = "‘æ9ŒR’c"
    location = 369
    division =
    { id            = { type = 15501 id = 4163 }
      name          = "‘æ56BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4166 }
      name          = "‘æ16BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4169 }
      name          = "‘æ59BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4170 }
      name          = "‘æ60BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4171 }
      name          = "‘æ61BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4177 }
    name     = "‘æ10ŒR’c"
    location = 368
    division =
    { id            = { type = 15501 id = 4179 }
      name          = "‘æ67BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4182 }
      name          = "‘æ19BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4185 }
      name          = "‘æ70BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4186 }
      name          = "‘æ71BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4187 }
      name          = "‘æ72BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4188 }
    name     = "‘æ10ŒR’c"
    location = 519
    division =
    { id            = { type = 15501 id = 4189 }
      name          = "‘æ67BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4190 }
      name          = "‘æ19BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4191 }
      name          = "‘æ70BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4192 }
      name          = "‘æ71BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4193 }
      name          = "‘æ72BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4194 }
    name     = "‘æ10ŒR’c"
    location = 524
    division =
    { id            = { type = 15501 id = 4195 }
      name          = "‘æ67BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4196 }
      name          = "‘æ19BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4197 }
      name          = "‘æ70BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4198 }
      name          = "‘æ71BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4199 }
      name          = "‘æ72BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4200 }
    name     = "‘æ10ŒR’c"
    location = 523
    division =
    { id            = { type = 15501 id = 4201 }
      name          = "‘æ67BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4202 }
      name          = "‘æ19BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4203 }
      name          = "‘æ70BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4204 }
      name          = "‘æ71BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4205 }
      name          = "‘æ72BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4206 }
    name     = "‘æ10ŒR’c"
    location = 520
    division =
    { id            = { type = 15501 id = 4207 }
      name          = "‘æ67BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4208 }
      name          = "‘æ19BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4209 }
      name          = "‘æ70BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4210 }
      name          = "‘æ71BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4211 }
      name          = "‘æ72BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4212 }
    name     = "‘æ10ŒR’c"
    location = 517
    division =
    { id            = { type = 15501 id = 4213 }
      name          = "‘æ67BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4214 }
      name          = "‘æ19BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4215 }
      name          = "‘æ70BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4216 }
      name          = "‘æ71BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4217 }
      name          = "‘æ72BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 4218 }
    name     = "‘æ10ŒR’c"
    location = 514
    division =
    { id            = { type = 15501 id = 4219 }
      name          = "‘æ67BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4220 }
      name          = "‘æ19BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4221 }
      name          = "‘æ70BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4222 }
      name          = "‘æ71BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
    division =
    { id            = { type = 15501 id = 4223 }
      name          = "‘æ72BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      #locked        = yes
    }
  }
  landunit =
  { id       = { type = 15501 id = 1 }
    name     = "ƒŠƒˆƒ“ƒnƒCƒ”"
    location = 529
    division =
    { type   = garrison
      model  = 15
      id     = { type = 15504 id = 1 }
      name   = "ƒŠƒˆƒ“ƒnƒCƒ”"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 15504 id = 2 }
      name   = "–å‹‰"
      locked = yes
    }
  }
}
