
##############################
# Country definition for CAN #
##############################

province =
{ id       = 541
  anti_air = 3
  air_base = { size = 2 current_size = 2 }
}            # ƒ”ƒ@ƒ“ƒN[ƒ”ƒ@[
province =
{ id         = 556
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # ƒ”ƒBƒNƒgƒŠƒA
province =
{ id       = 569
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ƒEƒBƒjƒyƒO
province =
{ id         = 574
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # ƒPƒxƒbƒNƒVƒeƒB
province =
{ id         = 576
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # ƒZƒ“ƒgƒWƒ‡ƒ“
province =
{ id         = 579
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # ƒnƒŠƒtƒ@ƒbƒNƒX
province =
{ id            = 585
  anti_air      = 2
  air_base      = { size = 2 current_size = 2 }
}                 # ƒ‚ƒ“ƒgƒŠƒI[ƒ‹
province =
{ id            = 588
  anti_air      = 3
  air_base      = { size = 2 current_size = 2 }
}                 # ƒIƒ^ƒ
province =
{ id       = 797
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ƒJƒ‹ƒKƒŠ[

#####################
# Country main data #
#####################

country =
{ tag                 = CAN
  energy              = 5000
  metal               = 5000
  rare_materials      = 5000
  oil                 = 3000
  supplies            = 80000
  transports          = 115
  escorts             = 36
  manpower            = 110
  capital             = 588
  regular_id          = U92
  money               = 350
  nationalprovinces   = { 1909 541 552 554 555 556 558 560 564 565 566 569 571 574 575 576 578 579 580 585 588 589 590 796 797 798 799 }
  ownedprovinces      = { 1909 541 552 554 555 556 558 560 564 565 566 569 571 574 575 576 578 579 580 585 588 589 590 796 797 798 799 }
  controlledprovinces = { 1909 541 552 554 555 556 558 560 564 565 566 569 571 574 575 576 578 579 580 585 588 589 590 796 797 798 799 }
  techapps            = { 10050 1010  10150 10190 1020  10200 10210 1030  10390 1040  10440 10490 1110  1120  1130  1210  1220  1550  1560  1570 
                          1650  1660  1850  1860  1870  1950  3010  3020  3030  3110  3120  3130  3460  3470  3810  3910  3920  3930  4390  4400 
                          4410  4480  4560  50020 50030 50040 50070 50080 50090 5010  50100 50110 5020  50290 50300 5090  5100  5170  5180  5250 
                          5330  5410  5420  5430  5460  5600  5610  5620  5760  5910  5920  7010  80080
                          80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8880  8890  8900  8910  8920  9010  9020  9030  9040  9050 
                          9190  9200  9340  9350  9360  9370  9380  9520  9530  9670  9680  9690  9700  9840  4010  4020  4030 
                          4040  4050  4110  4120  4130  4140  4150  4210  4220  4230  4240  4250
                          4640  4650  4660  4670  4680  4820  4830  4840  4850  4860  40000 40010 40020 40030 40040 2010  2020  2030  2040  2050
                          2060  2070  2080
                          6050  6060  6070  6080  6090  6260  6270  6520  6530
                        }
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    free_market       = 10
    freedom           = 10
    professional_army = 6
    defense_lobby     = 7
    interventionism   = 8
  }
  inventions             = { 8006 }
  landunit =
  { id       = { type = 4501 id = 5962 }
    name     = "‘æ1ŒR’c"
    location = 579
    home     = 579
    mission  = { type = none target = 579 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 4501 id = 5964 }
      name          = "‘æ1©‘–x‰‡’S•Ût’c"
      model         = 2
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 4501 id = 5965 }
    name     = "‘æ2ŒR’c"
    location = 569
    home     = 569
    mission  = { type = none target = 569 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 4501 id = 5967 }
      name          = "‘æ2©‘–x‰‡’S•Ût’c"
      model         = 2
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 4501 id = 5968 }
    name     = "‘æ3ŒR’c"
    location = 589
    home     = 589
    mission  = { type = none target = 589 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 4501 id = 5970 }
      name          = "‘æ3©‘–x‰‡’S•Ût’c"
      model         = 2
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 4501 id = 5971 }
    name     = "‘æ4ŒR’c"
    location = 585
    home     = 585
    mission  = { type = none target = 585 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 4501 id = 5973 }
      name          = "‘æ4©‘–x‰‡’S•Ût’c"
      model         = 2
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 4501 id = 5974 }
    name     = "‘æ5ŒR’c"
    location = 576
    home     = 576
    mission  = { type = none target = 576 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 4501 id = 5976 }
      name          = "‘æ5©‘–x‰‡’S•Ût’c"
      model         = 2
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 4501 id = 5977 }
    name     = "‘æ6ŒR’c"
    location = 588
    home     = 588
    mission  = { type = none target = 588 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 4501 id = 5979 }
      name          = "‘æ1‹@ŠB‰»•à•ºt’c"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 4501 id = 5980 }
      name          = "‘æ2‹@ŠB‰»•à•ºt’c"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 4501 id = 5981 }
      name          = "‘æ3‹@ŠB‰»•à•ºt’c"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 4501 id = 5982 }
    name     = "‘æ7ŒR’c"
    location = 588
    home     = 588
    mission  = { type = none target = 588 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 4501 id = 5984 }
      name          = "‘æ1•à•ºíÔt’c"
      model         = 2
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 4501 id = 5985 }
      name          = "‘æ2•à•ºíÔt’c"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 4501 id = 5986 }
      name          = "‘æ3•à•ºíÔt’c"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 4501 id = 5987 }
    name     = "‘æ8ŒR’c"
    location = 588
    home     = 588
    mission  = { type = none target = 588 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 4501 id = 5989 }
      name          = "‘æ1å—ÍíÔt’c"
      model         = 2
      brigade_model = 0
      type          = armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 4501 id = 5990 }
      name          = "‘æ2å—ÍíÔt’c"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 4501 id = 5991 }
      name          = "‘æ3å—ÍíÔt’c"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  navalunit =
  { id       = { type = 4502 id = 2389 }
    name     = "‘æ1í‘à"
    location = 574
    home     = 574
    base     = 574
    division =
    { id       = { type = 4502 id = 5992 }
      name     = "‘æ1„—mŠÍt’c"
      model    = 3
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 5993 }
      name     = "‘æ2„—mŠÍt’c"
      model    = 3
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 5994 }
      name     = "‘æ3„—mŠÍt’c"
      model    = 2
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 5995 }
      name     = "‘æ1ƒ~ƒTƒCƒ‹’øt’c"
      model    = 3
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 5996 }
      name     = "‘æ2ƒ~ƒTƒCƒ‹’øt’c"
      model    = 3
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 5997 }
      name     = "‘æ3ƒ~ƒTƒCƒ‹’øt’c"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 5998 }
      name     = "‘æ4ƒ~ƒTƒCƒ‹’øt’c"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 5999 }
      name     = "‘æ5ƒ~ƒTƒCƒ‹’øt’c"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6000 }
      name     = "‘æ1‹ì’€ŠÍt’c"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6001 }
      name     = "‘æ2‹ì’€ŠÍt’c"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6002 }
      name     = "‘æ3‹ì’€ŠÍt’c"
      model    = 2
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6003 }
      name     = "‘æ4‹ì’€ŠÍt’c"
      model    = 2
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6004 }
      name     = "‘æ5‹ì’€ŠÍt’c"
      model    = 2
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6005 }
      name     = "‘æ6‹ì’€ŠÍt’c"
      model    = 2
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6006 }
      name     = "‘æ1—A‘—ŠÍ/—g—¤ŠÍt’c"
      model    = 4
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6007 }
      name     = "‘æ2—A‘—ŠÍ/—g—¤ŠÍt’c"
      model    = 4
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6008 }
      name     = "‘æ3—A‘—ŠÍ/—g—¤ŠÍt’c"
      model    = 4
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6009 }
      name     = "‘æ1ö…ŠÍŠÍ‘à"
      model    = 2
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 4502 id = 6010 }
      name     = "‘æ2ö…ŠÍŠÍ‘à"
      model    = 2
      type     = submarine
      strength            = 100
    }
  }
}
