
##############################
# Country definition for SOV #
##############################

province =
{ id         = 133
  anti_air   = 4
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # ƒ€ƒ‹ƒ}ƒ“ƒXƒN
province = { id = 145 landfort = 2 anti_air = 3 } # ƒ”ƒB[ƒvƒŠ
province =
{ id         = 154
  anti_air   = 4
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # ƒAƒ‹ƒnƒ“ƒQƒŠƒXƒN
province =
{ id       = 163
  air_base = { size = 4 current_size = 4 }
  landfort = 5
  anti_air = 3
}            # ƒXƒ^[ƒŠƒ“ƒOƒ‰[ƒh
province =
{ id       = 166
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ƒS[ƒŠƒL[
province =
{ id       = 171
  air_base = { size = 2 current_size = 2 }
}            # ƒ”ƒHƒƒOƒ_
province =
{ id       = 175
  air_base = { size = 10 current_size = 10 }
  landfort = 5
  anti_air = 4
}            # ƒ‚ƒXƒNƒ
province =
{ id       = 178
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ƒ”ƒ‰ƒW[ƒ~ƒ‹
province =
{ id              = 187
  anti_air        = 6
  naval_base      = { size = 10 current_size = 10 }
  air_base        = { size = 4 current_size = 4 }
  landfort        = 5
  coastalfort     = 5
}                   # ƒŒƒjƒ“ƒOƒ‰[ƒh
province =
{ id       = 200
  air_base = { size = 4 current_size = 4 }
}            # ƒmƒ”ƒSƒ‹ƒh
province = { id = 216 anti_air = 1 } # ƒhƒm[
province =
{ id       = 217
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # ƒ”ƒBƒeƒuƒXƒN
province =
{ id       = 219
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # ƒXƒ‚ƒŒƒ“ƒXƒN
province =
{ id       = 220
  air_base = { size = 4 current_size = 4 }
}            # ƒ‚ƒMƒŠƒt
province =
{ id       = 223
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒCƒ“ƒXƒeƒ‹ƒuƒ‹ƒN
province =
{ id       = 228
  air_base = { size = 4 current_size = 4 }
}            # ƒ”ƒBƒjƒ“ƒcƒ@
province =
{ id       = 233
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # ƒIƒfƒbƒT
province =
{ id         = 234
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # ƒ€ƒBƒRƒ‰[ƒCƒE
province =
{ id       = 238
  anti_air = 3
  air_base = { size = 8 current_size = 8 }
}            # ƒLƒGƒt
province =
{ id       = 248
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒnƒŠƒRƒt
province =
{ id       = 249
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ƒUƒ|ƒŠ[ƒWƒƒ
province =
{ id          = 253
  anti_air    = 6
  naval_base  = { size = 8 current_size = 8 }
  air_base    = { size = 4 current_size = 4 }
  landfort    = 3
  coastalfort = 5
}               # ƒZƒ”ƒ@ƒXƒgƒ|ƒŠ
province =
{ id       = 256
  air_base = { size = 2 current_size = 2 }
}            # ƒNƒ‰ƒXƒmƒ_[ƒ‹
province =
{ id       = 263
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ƒƒbƒ\
province =
{ id       = 269
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # ƒƒXƒgƒtEƒiEƒhƒk
province =
{ id       = 274
  air_base = { size = 4 current_size = 4 }
}            # ƒzƒƒŠ
province =
{ id       = 276
  air_base = { size = 4 current_size = 4 }
}            # ƒIƒŠƒ‡[ƒ‹
province =
{ id       = 279
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒŠƒƒƒUƒ“
province =
{ id       = 281
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒ”ƒHƒƒlƒW
province =
{ id       = 282
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒNƒ‹ƒXƒN
province =
{ id       = 288
  air_base = { size = 2 current_size = 2 }
}            # ƒ‹ƒWƒFƒt
province =
{ id         = 510
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # ƒP[ƒjƒqƒXƒxƒ‹ƒN
province = { id = 550 ic = 14 } # ƒZƒ‰ƒEƒBƒJ
province = { id = 908 ic = 24 air_base = 8 infra = 2.0 naval_base = 10 } # ƒxƒZƒ‹
province =
{ id         = 1167
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 5 current_size = 5 }
}              # ƒ}ƒKƒ_ƒ“
province =
{ id       = 1170
  ic       = 10
  air_base = { size = 8 current_size = 8 }
}            # ƒxƒŠƒSƒ“ƒXƒL[
province = { id = 1171 ic = 8 } # ƒpƒ‰ƒi
province =
{ id       = 1172
  ic       = 12
  air_base = { size = 8 current_size = 8 }
}            # ƒyƒgƒƒpƒ”ƒƒtƒXƒNEƒJƒ€ƒ`ƒƒƒcƒL
province =
{ id       = 1366
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic       = 4
}            # ƒnƒoƒƒtƒXƒN
province = { id = 1367 ic = 3 } # ƒeƒ`ƒ…[ƒw(ƒ_ƒŠƒlƒSƒ‹ƒXƒN)
province = { id = 1368 ic = 4 } # ƒ\ƒ”ƒBƒGƒcƒJƒ„EƒKƒ”ƒ@ƒj
province = { id = 1370 ic = 5 } # ƒZƒ~ƒ‡ƒmƒtƒJ
province = { id = 1371 ic = 6 } # ƒiƒzƒgƒJ
province =
{ id          = 1372
  anti_air    = 5
  naval_base  = { size = 4 current_size = 4 }
  air_base    = { size = 4 current_size = 4 }
  landfort    = 1
  coastalfort = 3
  ic          = 14
}               # ƒEƒ‰ƒWƒIƒXƒgƒbƒN
province = { id = 1399 ic = 12 } # ƒzƒ‰ƒCƒgƒ}ƒEƒ“ƒeƒ“
province =
{ id       = 1414
  air_base = { size = 8 current_size = 8 }
}            # ƒCƒ‹ƒN[ƒcƒN
province =
{ id       = 1418
  air_base = { size = 6 current_size = 6 }
}            # ƒLƒWƒ‹
province =
{ id       = 1424
  air_base = { size = 2 current_size = 2 }
}            # ƒAƒ‹ƒ}ƒAƒ^
province =
{ id       = 1427
  air_base = { size = 2 current_size = 2 }
}            # ƒ^ƒVƒ…ƒPƒ“ƒg
province =
{ id       = 1522
  air_base = { size = 8 current_size = 8 }
  ic       = 2
}            # ƒ„ƒN[ƒcƒN
province =
{ id       = 1523
  air_base = { size = 8 current_size = 8 }
  anti_air = 2
  ic       = 15
}            # –kŠ’‘¾
province =
{ id       = 1527
  air_base = { size = 8 current_size = 8 }
  ic       = 2
}            # ƒRƒ€ƒ\ƒ‚ƒŠƒXƒNEƒiEƒAƒ€[ƒŒ
province =
{ id       = 1539
  air_base = { size = 2 current_size = 2 }
}            # ƒgƒ€ƒXƒN
province =
{ id       = 1543
  air_base = { size = 2 current_size = 2 }
}            # ƒmƒ”ƒHƒVƒrƒ‹ƒXƒN
province = { id = 1544 ic = 2 } # ƒrƒCƒXƒN
province =
{ id       = 1550
  air_base = { size = 2 current_size = 2 }
}            # ƒpƒ”ƒƒ_ƒ‹(ƒJƒUƒt)
province =
{ id       = 1552
  air_base = { size = 2 current_size = 2 }
}            # ƒIƒ€ƒXƒN
province =
{ id       = 1562
  air_base = { size = 2 current_size = 2 }
}            # ƒNƒ‰ƒXƒmƒ„ƒ‹ƒX
province =
{ id       = 1564
  air_base = { size = 4 current_size = 4 }
}            # ƒIƒ|[ƒ`ƒJ(ƒvƒXƒRƒt)
province =
{ id       = 1567
  air_base = { size = 2 current_size = 2 }
}            # ƒ`ƒFƒŠƒƒƒrƒ“ƒXƒN
province =
{ id       = 1575
  air_base = { size = 2 current_size = 2 }
}            # ƒXƒxƒ‹ƒhƒƒtƒXƒN
province =
{ id       = 1597
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ƒuƒŠƒƒƒ“ƒXƒN
province =
{ id       = 2641
  ic       = 17
  air_base = { size = 6 current_size = 6 }
}            # ƒKƒŠƒi
province = { id = 2642 ic = 16 } # ƒ~ƒ“ƒg
province = { id = 2646 ic = 18 landfort = 8 } # ƒoƒnƒ`
province = { id = 2648 ic = 12 landfort = 8 } # ƒAƒiƒhƒDƒCƒŠ

#####################
# Country main data #
#####################

country =
{ tag                 = SOV
  manpower            = 1000
  energy              = 58000
  metal               = 38000
  rare_materials      = 48000
  oil                 = 5900
  supplies            = 8000
  money               = 580
  capital             = 908
  transports          = 250
  escorts             = 150
  regular_id          = U06
  policy              = { democratic = 2 political_left = 9 freedom = 2 free_market = 2 professional_army = 9 defense_lobby = 10 interventionism = 9 }
  ownedprovinces      = { 1149 1150 1151 1152 1153 1154 1155 1167 1170 1171 1172 1175 123  133  134  135  1366 1367 1368 1369 1370 1371 1372 1383 1384
                          1410 1411 1412 1413 1414 1415 1416 1417 1418 1422 1423 1424 1425 1426 1427 1428 1429 143  145  146  1485 1488 1489 1490 1491
                          150  151  152  1520 1521 1522 1523 1524 1526 1527 1528 1529 153  1533 1534 1536 1535 1538 1539 154  1540 1541 1542 1543 1544
                          1545 1546 1547 1548 1549 155  1550 1552 1555 1556 1558 1559 156  1561 1562 1564 1565 1566 1567 1569 157  1570 1571 1572 1573
                          1574 1575 1576 1577 1578 1579 158  1580 1581 1582 1583 1584 1585 1586 1587 1588 159  1593 1594 1596 1597 1598 160  161  162 
                          163  164  165  166  167  168  169  170  171  172  173  174  175  176  177  1771 1772 1773 1774 1775 1776 1777 1778 178  1780
                          1781 1782 1783 179  180  181  182  1827 1828 1829 183  1830 1831 1832 1833 1834 1836 1837 1838 1839 184  1840 1841 1842
                          1843 1844 1845 1846 1847 1848 1849 185  1850 1856 1857 1858 186  187  1874 188  189  190  1907 191  192  200  201  215  216 
                          217  218  219  220  221  223  2240 225  226  227  228  231  232  233  234  235  236  237  238  239  240  241  242  243  244 
                          245  246  247  2470 248  2488 249  250  251  252  253  254  255  256  257  258  259  260  261  262  263  264  265  266  267 
                          268  269  270  271  272  273  274  275  276  277  278  279  280  281  282  283  284  285  286  287  288  289  510  550  94  
                          908  2641 2642 1399 2646 2647 2648 2649 2650 2652 2653 2654 2655 2656 2657 2658 2659 2651 2660 1525 1560
                        }
  controlledprovinces = { 2648 1170 2646 1171 1172 1523 1399 2641 2642 550  908 1525  1526 1410 1411 1167 2650 2647 2649 2653 2651 2652 2654 2655 2656 2657 2658 1521 1524 1522 1383 2659 
                          1560 1417 1418 1535 1538 1547 1561 1562 1384 1412 1413 1414 1415 1416 1520 2660 
                          1366 1367 1368 1369 1370 1371 1372 1527 1528 1175 1529}
  techapps            = { 10050 10060 10070 10080 10090 1010  10150 10160 10190 1020  10200 10210 10220 1030  1040  10440 10490 1050  1110  1120 
                          1130  1140  1150  1210  1220  1230  1240  1250  1470  1490  1510  1530  1550  1560  1570  1580  1590  1650  1660  1670 
                          1680  1690  1750  1760  1770  1780  1790  1850  1860  1870  1950  1960  1970  1980  2010  2020  20210 20220 2030  20310
                          20320 2040  20410 2050  20510 2060  2070  2080  2310  2320  2330  2610  2620  2630  2640  2650  2660  2910  2920  2930 
                          2940  2950  2960  3010  3020  3030  3040  30410 30420 30430 3050  30510 30520 30530 3110  3120  3130  3140  3210  3220 
                          3230  3240  3310  3320  3330  3340  3350  3410  3460  3470  3480  3490  3500  3610  3620  3630  3710  3720  3810  3820 
                          3830  3910  3920  3930  3940  3950  3960  40100 40110 40120 40130 40200 4390  4400  4410  4420  4430  4480  4490  4500 
                          4510  4560  4570  50020 50030 50040 50050 50070 50080 50090 5010  50100 50110 50120 5020  5030  5040  5090  5100  5110 
                          5120  5170  5180  5190  5200  5250  5260  5270  5280  5330  5340  5350  5360  5410  5420  5430  5460  5490  5500  5600 
                          5610  5620  5630  5680  5690  5760  5770  5780  5790  5800  5810  5820  5830  5860  5910  5920  5930  5940 
                          5950  7010  7500  7510  7520  7530  7540  7550  7560  7570  7670  7680  7690  80080
                          80090 8010  80160 8020  8030  8040  8050  8060  8070  8080  8090  8100  8110  90040 90090 9010  9020  90240 9030  9040 
                          9050  9060  9070  9080  9190  9200  9210  9220  9230  9340  9350  9360  9370  9380  9390  9400  9410  9520  9530  9670 
                          9680  9690  9700  9710  9720  9730  9840  9850  9860  9870  9880  2340  2360  2670  2970
                          10390 4010  4020  4030  4040  4050  4110  4120  4130  4140  4150  4210  4220  4230  4240  4250  4640
                          4650  4660  4670  4680  4820  4830  4840  4850  4860  40000 40010 40020 40030 40040
                          50290 50300 50310 50320 5520  5530  5540  5550  7150  7160  7170  7180
                          6000  6010  6020  6030  6040  6160  6170  6370  6380  6390  6700  6710  6720
                        }
  nationalprovinces   = { 1149 1150 1151 1152 1153 1154 1155 1156 1167 1170 1171 1172 1175 123  133  134  135  1366 1367 1368 1369 1370 1371 1372 1383
                          1384 1410 1411 1412 1413 1414 1415 1416 1417 1418 1422 1423 1424 1425 1426 1427 1428 1429 143  145  146  1485 1488 1489 1490
                          1491 150  151  152  1520 1521 1522 1523 1524 1525 1526 1527 1528 1529 153  1533 1534 1536 1535 1538 1539 154  1540 1541 1542
                          1543 1544 1545 1546 1547 1548 1549 155  1550 1551 1552 1555 1556 1557 1558 1559 156  1560 1561 1562 1564 1565 1566 1567 1568
                          1569 157  1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 158  1580 1581 1582 1583 1584 1585 1586 1587 1588 159  1593 1594
                          1596 1597 1598 160  161  162  163  164  165  166  167  168  169  170  171  172  173  174  175  176  177  1771 1772 1773 1774
                          1775 1776 1777 1778 178  1780 1781 1782 1783 179  180  181  182  1827 1828 1829 183  1830 1831 1832 1833 1834 1836 1837
                          1838 1839 184  1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 185  1850 1856 1857 1858 186  187  1874 188  189  190  1907
                          191  192  200  201  212  215  216  217  218  219  220  221  223  2240 225  226  227  228  231  232  233  234  235  236  237 
                          238  239  240  241  242  243  244  245  246  247  2470 248  2488 249  250  251  252  253  254  255  256  257  258  259  260 
                          261  262  263  264  265  266  267  268  269  270  271  272  273  274  275  276  277  278  279  280  281  282  283  284  285 
                          286  287  288  289  510  550  94   1176 908  2641 2642 1399 2646 2647 2648 2649 2650 2651 2652 2653 2654 2655 2656 2657 2658
                          2659 2660
                        }
free                = { energy = 300 manpower = 0.4 metal = 100 rare_materials = 200 oil = 50 }
inventions             = { 8006 8011 8004 }
  landunit =
  { id       = { type = 19501 id = 3090 }
    name     = "‘æˆê•û–ÊŒRi—ß•”"
    location = 908
    home     = 908
    #mission  = { type = none target = 908 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3092 }
      name          = "‘æ1ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3093 }
    name     = "‘æ20ŒR’c"
    location = 908
    home     = 908
    #mission  = { type = none target = 908 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3095 }
      name          = "‘æ1‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3096 }
      name          = "‘æ2‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3097 }
      name          = "‘æ3‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3098 }
    name     = "‘æ21ŒR’c"
    location = 1535
    home     = 1535
    #mission  = { type = none target = 1336 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3100 }
      name          = "‘æ4‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3101 }
      name          = "‘æ5‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3102 }
    name     = "‘æŒÜ•û–ÊŒRi—ß•”"
    location = 2651
    home     = 2651
    #mission  = { type = none target = 2651 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3104 }
      name          = "‘æ2ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3105 }
    name     = "‘æ22ŒR’c"
    location = 2651
    home     = 2651
    #mission  = { type = none target = 2651 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3107 }
      name          = "‘æ6‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3108 }
      name          = "‘æ7‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3109 }
    name     = "‘æ23ŒR’c"
    location = 2660
    home     = 2660
    #mission  = { type = none target = 2660 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3111 }
      name          = "‘æ8‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3112 }
      name          = "‘æ9‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3113 }
    name     = "‘æ“ñ•û–ÊŒRi—ß•”"
    location = 1412
    home     = 1412
    #mission  = { type = none target = 1412 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3115 }
      name          = "‘æ3ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3116 }
    name     = "‘æ24ŒR’c"
    location = 1561
    home     = 1561
    #mission  = { type = none target = 1561 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3118 }
      name          = "‘æ15íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3119 }
      name          = "‘æ16íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3120 }
      name          = "‘æ5‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3121 }
    name     = "‘æ25ŒR’c"
    location = 1418
    home     = 1418
    #mission  = { type = none target = 1418 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3123 }
      name          = "‘æ17íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3124 }
      name          = "‘æ18íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3125 }
      name          = "‘æ6‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3126 }
    name     = "‘æO•û–ÊŒRi—ß•”"
    location = 2660
    home     = 2660
    #mission  = { type = none target = 2660 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3128 }
      name          = "‘æ4ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3129 }
    name     = "‘æ26ŒR’c"
    location = 1560
    home     = 1560
    #mission  = { type = none target = 1560 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3131 }
      name          = "‘æ19íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3132 }
      name          = "‘æ20íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3133 }
      name          = "‘æ7‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3134 }
    name     = "‘æ27ŒR’c"
    location = 1417
    home     = 1417
    #mission  = { type = none target = 1417 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3136 }
      name          = "‘æ21íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3137 }
      name          = "‘æ22íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3138 }
      name          = "‘æ8‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3139 }
    name     = "‘æl•û–ÊŒRi—ß•”"
    location = 2659
    home     = 2659
    #mission  = { type = none target = 2659 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3141 }
      name          = "‘æ5ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3142 }
    name     = "‘æ28ŒR’c"
    location = 1416
    home     = 1416
    #mission  = { type = none target = 1416 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3144 }
      name          = "‘æ23íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3145 }
      name          = "‘æ24íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3146 }
      name          = "‘æ9‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3147 }
    name     = "‘æ29ŒR’c"
    location = 1547
    home     = 1547
    #mission  = { type = none target = 1522 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3149 }
      name          = "‘æ25íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3150 }
      name          = "‘æ26íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3151 }
      name          = "‘æ10‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3152 }
    name     = "‘æ30ŒR’c"
    location = 1562
    home     = 1562
    #mission  = { type = none target = 1383 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3154 }
      name          = "‘æ27íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3155 }
      name          = "‘æ28íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3156 }
      name          = "‘æ11‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3157 }
    name     = "‘æ31ŒR’c"
    location = 1562
    home     = 1562
    #mission  = { type = none target = 1383 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3159 }
      name          = "‘æ10‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3160 }
      name          = "‘æ11‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3161 }
      name          = "‘æ12‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3162 }
    name     = "‘æ32ŒR’c"
    location = 1560
    home     = 1560
    #mission  = { type = none target = 1560 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3164 }
      name          = "‘æ12‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3165 }
      name          = "‘æ13‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3166 }
      name          = "‘æ14‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3167 }
    name     = "‘æ33ŒR’c"
    location = 1417
    home     = 1417
    #mission  = { type = none target = 1417 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3169 }
      name          = "‘æ15‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3170 }
      name          = "‘æ16‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3171 }
      name          = "‘æ17‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3172 }
    name     = "‘æ34ŒR’c"
    location = 1547
    home     = 1547
    #mission  = { type = none target = 1522 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3174 }
      name          = "‘æ18‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3175 }
      name          = "‘æ19‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3176 }
      name          = "‘æ20‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3177 }
    name     = "‘æ35ŒR’c"
    location = 1562
    home     = 1562
    #mission  = { type = none target = 1383 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3179 }
      name          = "‘æ21‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3180 }
      name          = "‘æ22‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3181 }
      name          = "‘æ23‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3182 }
    name     = "‘æ36ŒR’c"
    location = 1561
    home     = 1561
    #mission  = { type = none target = 1561 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3184 }
      name          = "‘æ1‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3185 }
      name          = "‘æ2‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3186 }
      name          = "‘æ3‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3187 }
    name     = "‘æ37ŒR’c"
    location = 1418
    home     = 1418
    #mission  = { type = none target = 1418 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3189 }
      name          = "‘æ4‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3190 }
      name          = "‘æ5‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3191 }
      name          = "‘æ6‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3192 }
    name     = "‘æ38ŒR’c"
    location = 1416
    home     = 1416
    #mission  = { type = none target = 1416 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3194 }
      name          = "‘æ7‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3195 }
      name          = "‘æ8‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3196 }
      name          = "‘æ9‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3197 }
    name     = "‘æ39ŒR’c"
    location = 1547
    home     = 1547
    #mission  = { type = none target = 1522 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3199 }
      name          = "‘æ10‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3200 }
      name          = "‘æ11‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3201 }
      name          = "‘æ12‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3202 }
    name     = "‘æ40ŒR’c"
    location = 1416
    home     = 1416
    #mission  = { type = none target = 1416 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3204 }
      name          = "‘æ101íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3205 }
      name          = "‘æ102íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3206 }
      name          = "‘æ103íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3207 }
    name     = "‘æ41ŒR’c"
    location = 1547
    home     = 1547
    #mission  = { type = none target = 1522 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3209 }
      name          = "‘æ104íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3210 }
      name          = "‘æ105íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3211 }
      name          = "‘æ106íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3212 }
    name     = "‘æ42ŒR’c"
    location = 1561
    home     = 1561
    #mission  = { type = none target = 1561 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3214 }
      name          = "‘æ13‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3215 }
      name          = "‘æ14‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3216 }
      name          = "‘æ15‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3217 }
    name     = "‘æ43ŒR’c"
    location = 1417
    home     = 1417
    #mission  = { type = none target = 1417 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3219 }
      name          = "‘æ16‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3220 }
      name          = "‘æ17‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3221 }
      name          = "‘æ18‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3222 }
    name     = "‘æ44ŒR’c"
    location = 1562
    home     = 1562
    #mission  = { type = none target = 1383 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3224 }
      name          = "‘æ19‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3225 }
      name          = "‘æ20‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3226 }
      name          = "‘æ21‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3227 }
    name     = "‘æ45ŒR’c"
    location = 1416
    home     = 1416
    #mission  = { type = none target = 1416 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3229 }
      name          = "‘æ22‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3230 }
      name          = "‘æ23‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3231 }
      name          = "‘æ24‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3232 }
    name     = "‘æ46ŒR’c"
    location = 1418
    home     = 1418
    #mission  = { type = none target = 1418 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3234 }
      name          = "‘æ29íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3235 }
      name          = "‘æ30íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3236 }
      name          = "‘æ24‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3237 }
    name     = "‘æ47ŒR’c"
    location = 1560
    home     = 1560
    #mission  = { type = none target = 1560 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3239 }
      name          = "‘æ31íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3240 }
      name          = "‘æ32íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3241 }
      name          = "‘æ25‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3242 }
    name     = "‘æ48ŒR’c"
    location = 1420
    home     = 1420
    #mission  = { type = none target = 1420 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3244 }
      name          = "‘æ33íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3245 }
      name          = "‘æ34íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3246 }
      name          = "‘æ26‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3247 }
    name     = "‘æ49ŒR’c"
    location = 1434
    home     = 1434
    #mission  = { type = none target = 1434 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3249 }
      name          = "‘æ35íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3250 }
      name          = "‘æ36íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3251 }
      name          = "‘æ27‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3252 }
    name     = "‘æ50ŒR’c"
    location = 1417
    home     = 1417
    #mission  = { type = none target = 1417 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3254 }
      name          = "‘æ107íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3255 }
      name          = "‘æ108íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3256 }
      name          = "‘æ109íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3257 }
    name     = "‘æ51ŒR’c"
    location = 1560
    home     = 1560
    #mission  = { type = none target = 1560 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3259 }
      name          = "‘æ37íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3260 }
      name          = "‘æ38íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3261 }
      name          = "‘æ28‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3262 }
    name     = "‘æ52ŒR’c"
    location = 1561
    home     = 1561
    #mission  = { type = none target = 1561 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3264 }
      name          = "‘æ29‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3265 }
      name          = "‘æ30‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3266 }
      name          = "‘æ31‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 19501 id = 3267 }
    name     = "‘æ53ŒR’c"
    location = 1418
    home     = 1418
    #mission  = { type = none target = 1418 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 19501 id = 3269 }
      name          = "‘æ39íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3270 }
      name          = "‘æ40íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 19501 id = 3271 }
      name          = "‘æ32‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  navalunit =
  { id       = { type = 19502 id = 3272 }
    name     = "‘æˆêŠÍ‘à"
    location = 1372
    home     = 1372
    base     = 1372
    division =
    { id       = { type = 19502 id = 3274 }
      name     = "Sovyetskiy Soyuz"
      model    = 4
      type     = battleship
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3275 }
      name     = "Sovyetskaya Ukraina"
      model    = 4
      type     = battleship
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3276 }
      name     = "Sovyetskaya Byelorussiya"
      model    = 4
      type     = battleship
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3277 }
      name     = "Sovyetskaya Rossiya"
      model    = 4
      type     = battleship
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3278 }
      name     = "Kirov"
      model    = 4
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3279 }
      name     = "Voroshilov"
      model    = 4
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3280 }
      name     = "Maxim Gor'kiy"
      model    = 4
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3281 }
      name     = "Molotov"
      model    = 4
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3282 }
      name     = "Chapayev"
      model    = 4
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3283 }
      name     = "Zheleznyakov"
      model    = 4
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3284 }
      name     = "Sverdlov"
      model    = 4
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3285 }
      name     = "Deiatelnyi"
      model    = 4
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3286 }
      name     = "Moskva"
      model    = 4
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3287 }
      name     = "Leningrad"
      model    = 4
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3288 }
      name     = "Kiyev"
      model    = 4
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3289 }
      name     = "Minsk"
      model    = 4
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3290 }
      name     = "Novorossiysk"
      model    = 4
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3291 }
      name     = "Baku"
      model    = 4
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3292 }
      name     = "Tbilisi"
      model    = 4
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3293 }
      name     = "Varyag"
      model    = 4
      type     = destroyer
      strength            = 100
    }
  }
  navalunit =
  { id       = { type = 19502 id = 3294 }
    name     = "‘æ“ñŠÍ‘à"
    location = 1372
    home     = 1372
    base     = 1372
    division =
    { id       = { type = 19502 id = 3296 }
      name     = "Kronshtadt"
      model    = 3
      type     = battleship
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3297 }
      name     = "Sevastopol"
      model    = 3
      type     = battleship
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3298 }
      name     = "Frunze"
      model    = 3
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3299 }
      name     = "Kuybyshev"
      model    = 3
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3300 }
      name     = "Chkalov"
      model    = 3
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3301 }
      name     = "Ordzhonikidze"
      model    = 3
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3302 }
      name     = "Derskyi"
      model    = 4
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3303 }
      name     = "Doblestni"
      model    = 4
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3304 }
      name     = "Zharki"
      model    = 4
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3305 }
      name     = "Zhguchi"
      model    = 4
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3306 }
      name     = "Ulyanovsk"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3307 }
      name     = "Stalingrad"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3308 }
      name     = "Smolensk"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3309 }
      name     = "Kazan"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3310 }
      name     = "Saratov"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3311 }
      name     = "Irkutsk"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3312 }
      name     = "Tashkent"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3313 }
      name     = "Kharkov"
      model    = 3
      type     = destroyer
      strength            = 100
    }
  }
  navalunit =
  { id       = { type = 19502 id = 3314 }
    name     = "‘æˆê—A‘—ŠÍ‘à"
    location = 1372
    home     = 1372
    base     = 1372
    division =
    { id       = { type = 19502 id = 3316 }
      name     = "Bditelnyi"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3317 }
      name     = "Ella"
      model    = 3
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3318 }
      name     = "Vironia"
      model    = 3
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3319 }
      name     = "Kazakhstan"
      model    = 3
      type     = transport
      strength            = 100
    }
  }
  navalunit =
  { id       = { type = 19502 id = 3320 }
    name     = "‘æ“ñ—A‘—ŠÍ‘à"
    location = 1372
    home     = 1372
    base     = 1372
    division =
    { id       = { type = 19502 id = 3322 }
      name     = "Besposhchadnyi"
      model    = 2
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3323 }
      name     = "Naissaar"
      model    = 3
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3324 }
      name     = "Ergonautis"
      model    = 3
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3325 }
      name     = "Balkhash"
      model    = 3
      type     = transport
      strength            = 100
    }
  }
  navalunit =
  { id       = { type = 19502 id = 3326 }
    name     = "‘æˆêö…ŠÍ‘à"
    location = 1372
    home     = 1372
    base     = 1372
    division =
    { id       = { type = 19502 id = 3328 }
      name     = "ShCh220"
      model    = 4
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3329 }
      name     = "ShCh221"
      model    = 4
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3330 }
      name     = "ShCh222"
      model    = 4
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3331 }
      name     = "ShCh223"
      model    = 4
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3332 }
      name     = "ShCh224"
      model    = 4
      type     = submarine
      strength            = 100
    }
  }
  navalunit =
  { id       = { type = 19502 id = 3333 }
    name     = "‘æ“ñö…ŠÍ‘à"
    location = 1372
    home     = 1372
    base     = 1372
    division =
    { id       = { type = 19502 id = 3335 }
      name     = "ShCh225"
      model    = 3
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3336 }
      name     = "ShCh226"
      model    = 3
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3337 }
      name     = "ShCh227"
      model    = 3
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3338 }
      name     = "ShCh228"
      model    = 3
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3339 }
      name     = "ShCh229"
      model    = 3
      type     = submarine
      strength            = 100
    }
  }
  navalunit =
  { id       = { type = 19502 id = 3340 }
    name     = "‘æOö…ŠÍ‘à"
    location = 1372
    home     = 1372
    base     = 1372
    division =
    { id       = { type = 19502 id = 3342 }
      name     = "ShCh230"
      model    = 3
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3343 }
      name     = "ShCh231"
      model    = 3
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3344 }
      name     = "ShCh232"
      model    = 3
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3345 }
      name     = "ShCh233"
      model    = 3
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3346 }
      name     = "ShCh234"
      model    = 3
      type     = submarine
      strength            = 100
    }
  }
  navalunit =
  { id       = { type = 19502 id = 3347 }
    name     = "‘ælö…ŠÍ‘à"
    location = 1372
    home     = 1372
    base     = 1372
    division =
    { id       = { type = 19502 id = 3349 }
      name     = "ShCh235"
      model    = 2
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3350 }
      name     = "ShCh236"
      model    = 2
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3351 }
      name     = "ShCh237"
      model    = 2
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3352 }
      name     = "ShCh238"
      model    = 2
      type     = submarine
      strength            = 100
    }
    division =
    { id       = { type = 19502 id = 3353 }
      name     = "ShCh239"
      model    = 2
      type     = submarine
      strength            = 100
    }
  }
  ####################ŠCŒR®”õŒv‰æŠÖ˜A##############################
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5819 }
    name    = "ƒLƒGƒt"
    type    = carrier
    model   = 2
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5820 }
    name    = "ƒ~ƒ“ƒXƒN"
    type    = carrier
    model   = 2
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5821 }
    name    = "ƒmƒ”ƒHƒVƒ[ƒtƒXƒN"
    type    = carrier
    model   = 2
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5822 }
    name    = "ƒoƒN["
    type    = carrier
    model   = 2
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5823 }
    name    = "ƒAƒhƒ~ƒ‰ƒ‹¥ƒNƒYƒlƒcƒHƒt"
    type    = carrier
    model   = 4
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 19511 id = 5824 }
    name    = "ƒ”ƒ@ƒŠƒƒ[ƒO"
    type    = carrier
    model   = 4
    extra1  = cag
    brigade_model1 = 4
  }
}
