
##############################
# Country definition for U18 #
##############################

province = { id = 1557 air_base = 10 radar_station = 10  rocket_test = 10 infra = 2.0  anti_air = 10 } # ÉXÉãÉOÉg

#####################
# Country main data #
#####################

country =
{ tag                 = U18
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 1557
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 1557 }
  ownedprovinces      = { 1557 }
  controlledprovinces = { 1557 1548 1549 1552 1558 1567 1570 1572 1573 1574 1575 1577 1593 1594 1772 1773 1539 1541 1545 1540 1542 1543 1544 1546 1559 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 15301 id = 4075 }
    name     = "ëÊ2åRíc"
    location = 1539
    division =
    { id            = { type = 15301 id = 4077 }
      name          = "ëÊ2éióﬂåQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15301 id = 4078 }
    name     = "ëÊ3åRíc"
    location = 1542
    division =
    { id            = { type = 15301 id = 4080 }
      name          = "ëÊ3éióﬂåQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15301 id = 4097 }
    name     = "ëÊ5åRíc"
    location = 1578
    division =
    { id            = { type = 15301 id = 4099 }
      name          = "ëÊ12BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4102 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4105 }
      name          = "ëÊ15BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4106 }
      name          = "ëÊ16BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4107 }
      name          = "ëÊ17BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15301 id = 4129 }
    name     = "ëÊ7åRíc"
    location = 1545
    division =
    { id            = { type = 15301 id = 4131 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4134 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4137 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4138 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4139 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15301 id = 4145 }
    name     = "ëÊ8åRíc"
    location = 369
    division =
    { id            = { type = 15301 id = 4147 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4150 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4153 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4154 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4155 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15301 id = 4161 }
    name     = "ëÊ9åRíc"
    location = 423
    division =
    { id            = { type = 15301 id = 4163 }
      name          = "ëÊ56BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4166 }
      name          = "ëÊ16BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4169 }
      name          = "ëÊ59BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4170 }
      name          = "ëÊ60BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15301 id = 4171 }
      name          = "ëÊ61BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15301 id = 1 }
    name     = "ÉXÉãÉOÅ[ÉgÉnÉCÉî"
    location = 1557
    division =
    { type   = garrison
      model  = 13
      id     = { type = 15304 id = 1 }
      name   = "ÉXÉãÉOÅ[ÉgÉnÉCÉî"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 15304 id = 2 }
      name   = "ñÂãâ"
      locked = yes
    }
  }
}
