
##############################
# Country definition for U24 #
##############################

province = { id = 722 air_base = 10 radar_station = 10  rocket_test = 10 infra = 2.0  anti_air = 10 } # É{Å[ÉpÅ[Éã

#####################
# Country main data #
#####################

country =
{ tag                 = U24
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 722
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 722 }
  ownedprovinces      = { 722 }
  controlledprovinces = { 722 1421 1432 1433 1435 1445 1446 1447 1448 1450 1451 1452 1728 1731 1430 1474 736 1705 593 1465 1466 1479 1721 
                          1478 1468 1592 685 687 1476 1477 1469 1470 2092 1472 1473 2199 1455 2043 1456 1464 631 611 1467 1460 714 599 2133 1471 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 15551 id = 4072 }
    name     = "ëÊ1åRíc"
    location = 1721
    division =
    { id            = { type = 15551 id = 4074 }
      name          = "ëÊ1éióﬂåQ"
      model         = 33
      type          = hq
      strength      = 100
      brigade_model = 0
      extra         = light_armor_brigade
    }
  }
  landunit =
  { id       = { type = 15551 id = 4075 }
    name     = "ëÊ2åRíc"
    location = 599
    division =
    { id            = { type = 15551 id = 4077 }
      name          = "ëÊ2éióﬂåQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 4078 }
    name     = "ëÊ3åRíc"
    location = 2043
    division =
    { id            = { type = 15551 id = 4080 }
      name          = "ëÊ3éióﬂåQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 4081 }
    name     = "ëÊ4åRíc"
    location = 1464
    division =
    { id            = { type = 15551 id = 4083 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4086 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4089 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4090 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4091 }
      name          = "ëÊ6BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 4097 }
    name     = "ëÊ5åRíc"
    location = 631
    division =
    { id            = { type = 15551 id = 4099 }
      name          = "ëÊ12BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4102 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4105 }
      name          = "ëÊ15BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4106 }
      name          = "ëÊ16BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4107 }
      name          = "ëÊ17BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 4113 }
    name     = "ëÊ6åRíc"
    location = 714
    division =
    { id            = { type = 15551 id = 4115 }
      name          = "ëÊ23BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4118 }
      name          = "ëÊ7BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4121 }
      name          = "ëÊ26BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4122 }
      name          = "ëÊ27BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4123 }
      name          = "ëÊ28BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 4129 }
    name     = "ëÊ7åRíc"
    location = 1460
    division =
    { id            = { type = 15551 id = 4131 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4134 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4137 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4138 }
      name          = "ëÊ38BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4139 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 4145 }
    name     = "ëÊ8åRíc"
    location = 2133
    division =
    { id            = { type = 15551 id = 4147 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4150 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4153 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4154 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4155 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 4161 }
    name     = "ëÊ9åRíc"
    location = 1472
    division =
    { id            = { type = 15551 id = 4163 }
      name          = "ëÊ56BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4166 }
      name          = "ëÊ16BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4169 }
      name          = "ëÊ59BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4170 }
      name          = "ëÊ60BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4171 }
      name          = "ëÊ61BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 4177 }
    name     = "ëÊ10åRíc"
    location = 1456
    division =
    { id            = { type = 15551 id = 4179 }
      name          = "ëÊ67BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4182 }
      name          = "ëÊ19BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4185 }
      name          = "ëÊ70BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4186 }
      name          = "ëÊ71BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 4187 }
      name          = "ëÊ72BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5476 }
    name     = "ëÊ42åRíc"
    location = 1464
    division =
    { id            = { type = 15551 id = 5478 }
      name          = "ëÊ43BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5479 }
      name          = "ëÊ43BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5480 }
      name          = "ëÊ119BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5481 }
      name          = "ëÊ120BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5482 }
      name          = "ëÊ121BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5483 }
    name     = "ëÊ43åRíc"
    location = 631
    division =
    { id            = { type = 15551 id = 5485 }
      name          = "ëÊ44BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5486 }
      name          = "ëÊ44BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5487 }
      name          = "ëÊ122BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5488 }
      name          = "ëÊ123BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5489 }
      name          = "ëÊ124BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5490 }
    name     = "ëÊ44åRíc"
    location = 714
    division =
    { id            = { type = 15551 id = 5492 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5493 }
      name          = "ëÊ45BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5494 }
      name          = "ëÊ125BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5495 }
      name          = "ëÊ126BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5496 }
      name          = "ëÊ127BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5497 }
    name     = "ëÊ45åRíc"
    location = 1460
    division =
    { id            = { type = 15551 id = 5499 }
      name          = "ëÊ46BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5500 }
      name          = "ëÊ46BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5501 }
      name          = "ëÊ128BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5502 }
      name          = "ëÊ129BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5503 }
      name          = "ëÊ130BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5504 }
    name     = "ëÊ46åRíc"
    location = 2133
    division =
    { id            = { type = 15551 id = 5506 }
      name          = "ëÊ47BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5507 }
      name          = "ëÊ47BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5508 }
      name          = "ëÊ131BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5509 }
      name          = "ëÊ132BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5510 }
      name          = "ëÊ133BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5511 }
    name     = "ëÊ47åRíc"
    location = 1472
    division =
    { id            = { type = 15551 id = 5513 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5514 }
      name          = "ëÊ48BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5515 }
      name          = "ëÊ134BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5516 }
      name          = "ëÊ135BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5517 }
      name          = "ëÊ136BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5518 }
    name     = "ëÊ48åRíc"
    location = 1456
    division =
    { id            = { type = 15551 id = 5520 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5521 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5522 }
      name          = "ëÊ137BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5523 }
      name          = "ëÊ138BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5524 }
      name          = "ëÊ139BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5525 }
    name     = "ëÊ49åRíc"
    location = 1455
    division =
    { id            = { type = 15551 id = 5527 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5528 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5529 }
      name          = "ëÊ140BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5530 }
      name          = "ëÊ141BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15551 id = 5531 }
      name          = "ëÊ142BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5467 }
    name     = "ëÊ39åRíc"
    location = 1721
    division =
    { id            = { type = 15551 id = 5469 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5470 }
    name     = "ëÊ40åRíc"
    location = 599
    division =
    { id            = { type = 15551 id = 5472 }
      name          = "ëÊ14BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = super_heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 5473 }
    name     = "ëÊ41åRíc"
    location = 2043
    division =
    { id            = { type = 15551 id = 5475 }
      name          = "ëÊ15BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15551 id = 1 }
    name     = "É{ÉpÅ[ÉãÉnÉCÉî"
    location = 722
    division =
    { type   = garrison
      model  = 13
      id     = { type = 15554 id = 1 }
      name   = "É{ÉpÅ[ÉãÉnÉCÉî"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 15554 id = 2 }
      name   = "ñÂãâ"
      locked = yes
    }
  }
}
