
##############################
# Country definition for BHU #
##############################
#####################
# Country main data #
#####################

country =
{ tag                 = BHU
  manpower            = 360
  energy              = 8000
  metal               = 3500
  rare_materials      = 5000
  oil                 = 4000
  supplies            = 6000
  money               = 350
  capital             = 1455
  regular_id          = U04
  transports          = 250
  escorts             = 150
  #nationalidentity    = "policy_identity_defensive"
  #socialpolicy        = "policy_social_religious"
  #nationalculture     = "policy_culture_ethnic"
  nationalprovinces   = { 1455 }
  ownedprovinces      = { 1455 }
  controlledprovinces = { 1455 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080
                        }
  policy              = { democratic = 3 political_left = 3 freedom = 2 free_market = 3 professional_army = 9 defense_lobby = 8 interventionism = 9 }
}
