
##############################
# Country definition for U05 #
##############################

province =
{ id       = 559
  ic       = 2
  air_base = { size = 2 current_size = 2 }
}            # Œj—Ñ
province =
{ id         = 696
  ic         = 1
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 100
}              # LB˜p‘dØ’n
province = { id = 746 ic = 2 } # OˆŸ
province =
{ id         = 1202
  ic         = 6
  air_base   = { size = 5 current_size = 5 }
  naval_base = { size = 6 current_size = 6 }
}              # ‘å˜A
province =
{ id         = 1204
  anti_air   = 1
  ic         = 3
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # “V’Ã
province =
{ id       = 1205
  ic       = 20
  air_base = { size = 4 current_size = 4 }
}            # –k‹
province = { id = 1207 ic = 3 } # ŒÄ˜a_“Á
province =
{ id       = 1209
  ic       = 4
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ‘å“¯
province =
{ id       = 1211
  air_base = { size = 2 current_size = 2 }
}            # Î‰Æ¯
province = { id = 1217 ic = 6 } # ˜A‰_`
province = { id = 1219 } # “ì’Ê
province =
{ id       = 1222
  air_base = { size = 2 current_size = 2 }
}            # •Œ—z
province =
{ id       = 1225
  air_base = { size = 2 current_size = 2 }
}            # ‘¾Œ´
province =
{ id       = 1228
  air_base = { size = 2 current_size = 2 }
}            # “AF
province =
{ id       = 1232
  anti_air = 1
  ic       = 3
  air_base = { size = 2 current_size = 2 }
}            # •Š¿
province =
{ id       = 1235
  anti_air = 1
  ic       = 6
  air_base = { size = 4 current_size = 4 }
}            # “ì‹
province =
{ id         = 1237
  anti_air   = 1
  ic         = 3
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # ãŠC
province =
{ id       = 1238
  air_base = { size = 2 current_size = 2 }
}            # YF
province = { id = 1240 ic = 6 } # ‰·F
province =
{ id         = 1244
  anti_air   = 1
  ic         = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 6 current_size = 6 }
}              # •ŸB
province =
{ id       = 1247
  ic       = 3
  air_base = { size = 2 current_size = 2 }
}            # ›ú–å
province = { id = 1248 supplypool = 500 oilpool = 50 } # Ÿˆ“ª
province =
{ id       = 1267
  ic       = 5
  air_base = { size = 2 current_size = 2 }
}            # ¼ˆÀ
province = { id = 1270 ic = 4 landfort = 3 } # ‰„ˆÀ
province = { id = 1271 landfort = 3 } # ¾—Ñ
province = { id = 1275 landfort = 3 } # •½™y
province =
{ id       = 1276
  ic       = 1
  air_base = { size = 2 current_size = 2 }
}            # —–F
province =
{ id       = 1283
  air_base = { size = 5 current_size = 5 }
}            # ¹“s
province =
{ id       = 1307
  ic       = 5
  air_base = { size = 2 current_size = 2 }
}            # ©–¾
province =
{ id         = 1313
  anti_air   = 1
  ic         = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # LB
province = { id = 1314 } # “ŒŠÎ
province =
{ id          = 1315
  anti_air    = 4
  ic          = 5
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 4 current_size = 4 }
  landfort    = 1
  coastalfort = 1
  oilpool     = 200
  supplypool  = 1000
}               # `
province = { id = 1316 ic = 4 } # ƒ}ƒJƒI
province = { id = 1317 } # ]–å
province = { id = 1318 ic = 4 } # —z]
province =
{ id         = 1321
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # ŠCŒû
province = { id = 1322 ic = 6 } # ‘ä“ì
province =
{ id            = 1323
  ic            = 5
  air_base      = { size = 5 current_size = 5 }
}                 # ‘ä–k
province = { id = 1324 ic = 3 } # ‰Ô˜@
province =
{ id       = 1360
  ic       = 2
  air_base = { size = 2 current_size = 2 }
}            # ¬“s
province =
{ id       = 1364
  ic       = 2
  air_base = { size = 2 current_size = 2 }
}            # ‹M—z
province =
{ id       = 1379
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ™û¢•l
province = { id = 1389 ic = 4 } # —ÉŒ¹
province = { id = 1390 ic = 6 } # ‹g—Ñ
province =
{ id         = 1394
  naval_base = { size = 1 current_size = 1 }
}              # ’O“Œ
province =
{ id         = 1396
  naval_base = { size = 1 current_size = 1 }
}              # ‹àŒk
province =
{ id       = 1397
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ³“¿
province =
{ id       = 1433
  air_base = { size = 1 current_size = 1 }
}            # ’¹˜D–Øê
province =
{ id       = 1439
  air_base = { size = 5 current_size = 5 }
}            # ƒoƒ„ƒ“ƒm[ƒ‹
province =
{ id       = 1442
  air_base = { size = 2 current_size = 2 }
}            # Ši¢–Ø
province =
{ id       = 1877
  air_base = { size = 5 current_size = 5 }
}            # ƒ~ƒs
province = { id = 1921 ic = 6 } # ’·¹
province = { id = 1923 ic = 4 } # ‘ä’†
province = { id = 2241 ic = 6 } # V‹
province = { id = 2515 ic = 8 } # ‹–¹
province =
{ id            = 2529
  ic            = 6
  air_base      = { size = 5 current_size = 5 }
  naval_base    = { size = 4 current_size = 4 }
}                 # Â“‡
province = { id = 2533 ic = 6 } # Ï“ì
province = { id = 2569 ic = 5 } # “ì¹
province =
{ id         = 2638
  ic         = 4
  air_base   = { size = 5 current_size = 5 }
  naval_base = { size = 4 current_size = 4 }
}              # ‚—Y
province =
{ id         = 1447
  air_base   = { size = 10 current_size = 10 }
}              # ƒz[ƒ^ƒ“
province =
{ id         = 1448
  air_base   = { size = 10 current_size = 10 }
}              # ˆ¢—¢
province =
{ id         = 1432
  air_base   = { size = 10 current_size = 10 }
}              # Î‰Íq
province = { id = 2639 ic = 1 } # àOŒÎ”“‡

#####################
# Country main data #
#####################

country =
{ tag                 = CHC
  manpower            = 1250
  energy              = 35000
  metal               = 40000
  rare_materials      = 38000
  oil                 = 25000
  supplies            = 8000
  money               = 2200
  capital             = 1205
  regular_id          = U05
  transports          = 1200
  escorts             = 1000
  nationalprovinces   = { 1217 1219 1220 1235 1236 1237 1966 2556 1238 1239 1240 1241 2570 2571 2572 1243 1244 1245 1246 1247 1936 1937 1231 1232 1253
                          1264 1266 1910 1939 1995 1996 1997 2502 1218 1221 1222 1233 1234 1964 1965 2558 2573 2574 1223 1224 1227 1228 1229 1230 2508
                          2513 2515 2516 1209 1225 1226 2517 2518 2520 1203 1204 1205 1206 1210 1211 1212 1397 2318 2523 2525 2526 2527 2576 1213 1214
                          1215 1216 2522 2528 2529 2530 2531 2533 2534 1293 1294 1307 1308 1327 1362 1905 1918 1928 1978 1983 1263 1265 1279 1280 1281
                          1282 1360 1361 1903 2550 2551 2559 2560 2561 746  1321 557  559  674  695  720  1258 1309 1310 1311 1319 1325 568  570  1248
                          1249 1312 1313 1314 1317 1318 1320 1880 1912 1262 1363 1364 1365 1984 1993 2000 2311 1255 1256 1257 1259 1260 1261 1913 1914
                          1921 1922 1242 1250 1251 1252 1254 1938 1941 2567 2568 2569 1442 1443 1444 1275 1276 1277 1440 1441 2503 1267 1268 1269 1270
                          1271 2505 2507 1421 1432 1433 1435 1445 1446 1447 1406 1450 1451 1452 1453 1283 1448 1207 1208 1272 1273 1274 1439 2504 1386
                          1388 1398 2246 2337 1382 1377 1387 1389 1390 2241 2333 2338 2487 2511 1374 1375 1378 1379 1380 1381 1530 2281 2485 2486 1202
                          1394 1395 1396 2317 2340 2341 2344 2345 2346 2347 2348 2349 1322 1323 1324 1923 696  1315 1316 1898 1430 1728 1877 1878 2043
                          2638 2639 1431
                        }
  ownedprovinces      = { 1217 1219 1220 1235 1236 1237 1966 2556 1238 1239 1240 1241 2570 2571 2572 1243 1244 1245 1246 1247 1936 1937 1231 1232 1253
                          1264 1266 1910 1939 1995 1996 1997 2502 1218 1221 1222 1233 1234 1964 1965 2558 2573 2574 1223 1224 1227 1228 1229 1230 2508
                          2513 2515 2516 1209 1225 1226 2517 2518 2520 1203 1204 1205 1206 1210 1211 1212 1397 2318 2523 2525 2526 2527 2576 1213 1214
                          1215 1216 2522 2528 2529 2530 2531 2533 2534 1293 1294 1307 1308 1327 1362 1905 1918 1928 1978 1983 1263 1265 1279 1280 1281
                          1282 1360 1361 1903 2550 2551 2559 2560 2561 746  1321 557  559  674  695  720  1258 1309 1310 1311 1319 1325 568  570  1248
                          1249 1312 1313 1314 1317 1318 1320 1880 1912 1262 1363 1364 1365 1984 1993 2000 2311 1255 1256 1257 1259 1260 1261 1913 1914
                          1921 1922 1242 1250 1251 1252 1254 1938 1941 2567 2568 2569 1442 1443 1444 1275 1276 1277 1440 1441 2503 1267 1268 1269 1270
                          1271 2505 2507 1421 1432 1433 1435 1445 1446 1447 1406 1450 1451 1452 1453 1283 1448 1207 1208 1272 1273 1274 1439 2504 1386
                          1388 1398 2246 2337 1382 1377 1387 1389 1390 2241 2333 2338 2487 2511 1374 1375 1378 1379 1380 1381 1530 2281 2485 2486 1202
                          1394 1395 1396 2317 2340 2341 2344 2345 2346 2347 2348 2349 696  1315 1316 1898 1430 1728 1877 1878 2043
                          2639
                        }
  controlledprovinces = { 1217 1219 1220 1235 1236 1237 1966 2556 1238 1239 1240 1241 2570 2571 2572 1243 1244 1245 1246 1247 1936 1937 1231 1232 1253
                          1264 1266 1910 1939 1995 1996 1997 2502 1218 1221 1222 1233 1234 1964 1965 2558 2573 2574 1223 1224 1227 1228 1229 1230 2508
                          2513 2515 2516 1209 1225 1226 2517 2518 2520 1203 1204 1205 1206 1210 1211 1212 1397 2318 2523 2525 2526 2527 2576 1213 1214
                          1215 1216 2522 2528 2529 2530 2531 2533 2534 1293 1294 1307 1308 1327 1362 1905 1918 1928 1978 1983 1263 1265 1279 1280 1281
                          1282 1360 1361 1903 2550 2551 2559 2560 2561 746  1321 557  559  674  695  720  1258 1309 1310 1311 1319 1325 568  570  1248
                          1249 1312 1313 1314 1317 1318 1320 1880 1912 1262 1363 1364 1365 1984 1993 2000 2311 1255 1256 1257 1259 1260 1261 1913 1914
                          1921 1922 1242 1250 1251 1252 1254 1938 1941 2567 2568 2569 1442 1443 1444 1275 1276 1277 1440 1441 2503 1267 1268 1269 1270
                          1271 2505 2507 1421 1432 1433 1435 1445 1446 1447 1406 1450 1451 1452 1453 1283 1448 1207 1208 1272 1273 1274 1439 2504 1386
                          1388 1398 2246 2337 1382 1377 1387 1389 1390 2241 2333 2338 2487 2511 1374 1375 1378 1379 1380 1381 1530 2281 2485 2486 1202
                          1394 1395 1396 2317 2340 2341 2344 2345 2346 2347 2348 2349 696  1315 1316 1898 1430 1728 1877 1878 2043
                          2639
                        }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010  9020  9030  9040  9050  9060
                          9340  6000  6010  6020  6030  6040  1020  1220  1660  1760  7500  7510  7520  7530  5760  5770  5780  5790
                        }
  inventions          = { 8009 }
  policy              = { democratic = 2 political_left = 1 freedom = 2 free_market = 3 professional_army = 8 defense_lobby = 9 interventionism = 8 }
  landunit = {
	name = "‘æ1íÔt’c"
	id = { type = 19561 id = 1 }
	location = 1728
	division = {
	id = { type = 19561 id = 2 }
	name = "‘æ1íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 3 }
	name = "‘æ2íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 4 }
	name = "‘æ3íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
  }
landunit = {
	name = "‘æ2íÔt’c"
	id = { type = 19561 id = 5 }
	location = 1447
	division = {
	id = { type = 19561 id = 6 }
	name = "‘æ4íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 7 }
	name = "‘æ5íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 8 }
	name = "‘æ6íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
  }
landunit = {
	name = "‘æ3íÔt’c"
	id = { type = 19561 id = 9 }
	location = 1446
	division = {
	id = { type = 19561 id = 10 }
	name = "‘æ7íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 11 }
	name = "‘æ8íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 12 }
	name = "‘æ9íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
  }
landunit = {
	name = "‘æ4íÔt’c"
	id = { type = 19561 id = 13 }
	location = 1205
	division = {
	id = { type = 19561 id = 14 }
	name = "‘æ10íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 15 }
	name = "‘æ11íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 16 }
	name = "‘æ12íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
  }
landunit = {
	name = "‘æ5íÔt’c"
	id = { type = 19561 id = 17 }
	location = 1379
	division = {
	id = { type = 19561 id = 18 }
	name = "‘æ13íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 19 }
	name = "‘æ14íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 20 }
	name = "‘æ15íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
  }
landunit = {
	name = "‘æ6íÔt’c"
	id = { type = 19561 id = 21 }
	location = 1446
	division = {
	id = { type = 19561 id = 22 }
	name = "‘æ16íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 23 }
	name = "‘æ17íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19561 id = 24 }
	name = "‘æ18íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
  }
landunit = {
	name = "‘æ1‹@ŠB‰»•à•ºt’c"
	id = { type = 19561 id = 1000 }
	location = 1205
	division = {
	id = { type = 19561 id = 2000 }
	name = "‘æ1íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 3000 }
	name = "‘æ1‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 4000 }
	name = "‘æ2‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 5000 }
	name = "‘æ3‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 6000 }
	name = "‘æ4‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 7000 }
	name = "‘æ5‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ2‹@ŠB‰»•à•ºt’c"
	id = { type = 19561 id = 8000 }
	location = 1379
	division = {
	id = { type = 19561 id = 9000 }
	name = "‘æ2íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 10000 }
	name = "‘æ6‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 11000 }
	name = "‘æ7‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 12000 }
	name = "‘æ8‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 13000 }
	name = "‘æ9‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 14000 }
	name = "‘æ10‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ3‹@ŠB‰»•à•ºt’c"
	id = { type = 19561 id = 15000 }
	location = 1447
	division = {
	id = { type = 19561 id = 16000 }
	name = "‘æ3íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 17000 }
	name = "‘æ11‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 18000 }
	name = "‘æ12‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 19000 }
	name = "‘æ13‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 20000 }
	name = "‘æ14‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 21000 }
	name = "‘æ15‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ4‹@ŠB‰»•à•ºt’c"
	id = { type = 19561 id = 22000 }
	location = 1447
	division = {
	id = { type = 19561 id = 23000 }
	name = "‘æ4íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 24000 }
	name = "‘æ16‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 25 }
	name = "‘æ17‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 26 }
	name = "‘æ18‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 27 }
	name = "‘æ19‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 28 }
	name = "‘æ20‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ5‹@ŠB‰»•à•ºt’c"
	id = { type = 19561 id = 29 }
	location = 1728
	division = {
	id = { type = 19561 id = 30 }
	name = "‘æ5íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 31 }
	name = "‘æ21‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 32 }
	name = "‘æ22‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 33 }
	name = "‘æ23‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 34 }
	name = "‘æ24‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 35 }
	name = "‘æ25‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ6‹@ŠB‰»•à•ºt’c"
	id = { type = 19561 id = 36 }
	location = 1728
	division = {
	id = { type = 19561 id = 37 }
	name = "‘æ6íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 38 }
	name = "‘æ26‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 39 }
	name = "‘æ27‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 40 }
	name = "‘æ28‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 41 }
	name = "‘æ29‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19561 id = 42 }
	name = "‘æ30‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ1•à•ºt’c"
	id = { type = 19561 id = 43 }
	location = 1530
	division = {
	id = { type = 19561 id = 44 }
	name = "‘æ7íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 45 }
	name = "‘æ1•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 46 }
	name = "‘æ2•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 47 }
	name = "‘æ3•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 48 }
	name = "‘æ4•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 49 }
	name = "‘æ5•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ2•à•ºt’c"
	id = { type = 19561 id = 50 }
	location = 1382
	division = {
	id = { type = 19561 id = 51 }
	name = "‘æ8íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 52 }
	name = "‘æ6•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 53 }
	name = "‘æ7•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 54 }
	name = "‘æ8•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 55 }
	name = "‘æ9•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 56 }
	name = "‘æ10•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ3•à•ºt’c"
	id = { type = 19561 id = 57 }
	location = 1377
	division = {
	id = { type = 19561 id = 58 }
	name = "‘æ9íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 59 }
	name = "‘æ11•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 60 }
	name = "‘æ12•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 61 }
	name = "‘æ13•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 62 }
	name = "‘æ14•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 63 }
	name = "‘æ15•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ4•à•ºt’c"
	id = { type = 19561 id = 64 }
	location = 1421
	division = {
	id = { type = 19561 id = 65 }
	name = "‘æ10íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 66 }
	name = "‘æ16•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 67 }
	name = "‘æ17•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 68 }
	name = "‘æ18•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 69 }
	name = "‘æ19•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 70 }
	name = "‘æ20•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ5•à•ºt’c"
	id = { type = 19561 id = 71 }
	location = 1432
	division = {
	id = { type = 19561 id = 72 }
	name = "‘æ11íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 73 }
	name = "‘æ21•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 74 }
	name = "‘æ22•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 75 }
	name = "‘æ23•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 76 }
	name = "‘æ24•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 77 }
	name = "‘æ25•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ6•à•ºt’c"
	id = { type = 19561 id = 78 }
	location = 1446
	division = {
	id = { type = 19561 id = 79 }
	name = "‘æ12íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 80 }
	name = "‘æ26•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 81 }
	name = "‘æ27•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 82 }
	name = "‘æ28•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 83 }
	name = "‘æ29•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 84 }
	name = "‘æ30•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ7•à•ºt’c"
	id = { type = 19561 id = 85 }
	location = 1446
	division = {
	id = { type = 19561 id = 86 }
	name = "‘æ13íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 87 }
	name = "‘æ31•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 88 }
	name = "‘æ32•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 89 }
	name = "‘æ33•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 90 }
	name = "‘æ34•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 91 }
	name = "‘æ35•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ8•à•ºt’c"
	id = { type = 19561 id = 92 }
	location = 1446
	division = {
	id = { type = 19561 id = 93 }
	name = "‘æ14íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 94 }
	name = "‘æ36•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 95 }
	name = "‘æ37•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 96 }
	name = "‘æ38•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 97 }
	name = "‘æ39•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 98 }
	name = "‘æ40•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ9•à•ºt’c"
	id = { type = 19561 id = 99 }
	location = 1446
	division = {
	id = { type = 19561 id = 100 }
	name = "‘æ15íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 101 }
	name = "‘æ41•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 102 }
	name = "‘æ42•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 103 }
	name = "‘æ43•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 104 }
	name = "‘æ44•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 105 }
	name = "‘æ45•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ10•à•ºt’c"
	id = { type = 19561 id = 106 }
	location = 1446
	division = {
	id = { type = 19561 id = 107 }
	name = "‘æ16íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 108 }
	name = "‘æ46•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 109 }
	name = "‘æ47•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 110 }
	name = "‘æ48•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 111 }
	name = "‘æ49•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 112 }
	name = "‘æ50•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ11•à•ºt’c"
	id = { type = 19561 id = 113 }
	location = 1447
	division = {
	id = { type = 19561 id = 114 }
	name = "‘æ17íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 115 }
	name = "‘æ51•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 116 }
	name = "‘æ52•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 117 }
	name = "‘æ53•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 118 }
	name = "‘æ54•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 119 }
	name = "‘æ55•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ12•à•ºt’c"
	id = { type = 19561 id = 120 }
	location = 1447
	division = {
	id = { type = 19561 id = 121 }
	name = "‘æ18íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 122 }
	name = "‘æ56•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 123 }
	name = "‘æ57•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 124 }
	name = "‘æ58•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 125 }
	name = "‘æ59•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 126 }
	name = "‘æ60•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ13•à•ºt’c"
	id = { type = 19561 id = 127 }
	location = 1447
	division = {
	id = { type = 19561 id = 128 }
	name = "‘æ19íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 129 }
	name = "‘æ61•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 130 }
	name = "‘æ62•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 131 }
	name = "‘æ63•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 132 }
	name = "‘æ64•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 133 }
	name = "‘æ65•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ14•à•ºt’c"
	id = { type = 19561 id = 134 }
	location = 1447
	division = {
	id = { type = 19561 id = 135 }
	name = "‘æ20íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 136 }
	name = "‘æ66•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 137 }
	name = "‘æ67•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 138 }
	name = "‘æ68•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 139 }
	name = "‘æ69•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 140 }
	name = "‘æ70•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ15•à•ºt’c"
	id = { type = 19561 id = 141 }
	location = 1447
	division = {
	id = { type = 19561 id = 142 }
	name = "‘æ21íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 143 }
	name = "‘æ71•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 144 }
	name = "‘æ72•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 145 }
	name = "‘æ73•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 146 }
	name = "‘æ74•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 147 }
	name = "‘æ75•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ16•à•ºt’c"
	id = { type = 19561 id = 148 }
	location = 1728
	division = {
	id = { type = 19561 id = 149 }
	name = "‘æ22íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 150 }
	name = "‘æ76•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 151 }
	name = "‘æ77•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 152 }
	name = "‘æ78•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 153 }
	name = "‘æ79•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 154 }
	name = "‘æ80•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ17•à•ºt’c"
	id = { type = 19561 id = 155 }
	location = 1728
	division = {
	id = { type = 19561 id = 156 }
	name = "‘æ23íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 157 }
	name = "‘æ81•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 158 }
	name = "‘æ82•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 159 }
	name = "‘æ83•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 160 }
	name = "‘æ84•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 161 }
	name = "‘æ85•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ18•à•ºt’c"
	id = { type = 19561 id = 162 }
	location = 1728
	division = {
	id = { type = 19561 id = 163 }
	name = "‘æ24íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 164 }
	name = "‘æ86•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 165 }
	name = "‘æ87•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 166 }
	name = "‘æ88•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 167 }
	name = "‘æ89•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 168 }
	name = "‘æ90•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ19•à•ºt’c"
	id = { type = 19561 id = 169 }
	location = 1728
	division = {
	id = { type = 19561 id = 170 }
	name = "‘æ25íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 171 }
	name = "‘æ91•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 172 }
	name = "‘æ92•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 173 }
	name = "‘æ93•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 174 }
	name = "‘æ94•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 175 }
	name = "‘æ95•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ20•à•ºt’c"
	id = { type = 19561 id = 176 }
	location = 1728
	division = {
	id = { type = 19561 id = 177 }
	name = "‘æ26íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 178 }
	name = "‘æ96•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 179 }
	name = "‘æ97•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 180 }
	name = "‘æ98•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 181 }
	name = "‘æ99•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 182 }
	name = "‘æ100•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ21•à•ºt’c"
	id = { type = 19561 id = 183 }
	location = 1394
	division = {
	id = { type = 19561 id = 184 }
	name = "‘æ27íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 185 }
	name = "‘æ101•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 186 }
	name = "‘æ102•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 187 }
	name = "‘æ103•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 188 }
	name = "‘æ104•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 189 }
	name = "‘æ105•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ22•à•ºt’c"
	id = { type = 19561 id = 190 }
	location = 2345
	division = {
	id = { type = 19561 id = 191 }
	name = "‘æ28íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 192 }
	name = "‘æ106•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 193 }
	name = "‘æ107•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 194 }
	name = "‘æ108•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 195 }
	name = "‘æ109•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 196 }
	name = "‘æ110•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ23•à•ºt’c"
	id = { type = 19561 id = 197 }
	location = 2338
	division = {
	id = { type = 19561 id = 198 }
	name = "‘æ29íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 199 }
	name = "‘æ111•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 200 }
	name = "‘æ112•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 201 }
	name = "‘æ113•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 202 }
	name = "‘æ114•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 203 }
	name = "‘æ115•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ24•à•ºt’c"
	id = { type = 19561 id = 204 }
	location = 2333
	division = {
	id = { type = 19561 id = 205 }
	name = "‘æ30íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 206 }
	name = "‘æ116•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 207 }
	name = "‘æ117•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 208 }
	name = "‘æ118•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 209 }
	name = "‘æ119•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 210 }
	name = "‘æ120•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ25•à•ºt’c"
	id = { type = 19561 id = 211 }
	location = 1377
	division = {
	id = { type = 19561 id = 212 }
	name = "‘æ31íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 213 }
	name = "‘æ121•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 214 }
	name = "‘æ122•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 215 }
	name = "‘æ123•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 216 }
	name = "‘æ124•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 217 }
	name = "‘æ125•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ26•à•ºt’c"
	id = { type = 19561 id = 218 }
	location = 1378
	division = {
	id = { type = 19561 id = 219 }
	name = "‘æ32íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 220 }
	name = "‘æ126•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 221 }
	name = "‘æ127•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 222 }
	name = "‘æ128•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 223 }
	name = "‘æ129•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 224 }
	name = "‘æ130•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ27•à•ºt’c"
	id = { type = 19561 id = 225 }
	location = 1375
	division = {
	id = { type = 19561 id = 226 }
	name = "‘æ33íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 227 }
	name = "‘æ131•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 228 }
	name = "‘æ132•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 229 }
	name = "‘æ133•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 230 }
	name = "‘æ134•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 231 }
	name = "‘æ135•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ28•à•ºt’c"
	id = { type = 19561 id = 232 }
	location = 1374
	division = {
	id = { type = 19561 id = 233 }
	name = "‘æ34íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 234 }
	name = "‘æ136•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 235 }
	name = "‘æ137•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 236 }
	name = "‘æ138•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 237 }
	name = "‘æ139•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 238 }
	name = "‘æ140•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ29•à•ºt’c"
	id = { type = 19561 id = 239 }
	location = 2485
	division = {
	id = { type = 19561 id = 240 }
	name = "‘æ35íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 241 }
	name = "‘æ141•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 242 }
	name = "‘æ142•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 243 }
	name = "‘æ143•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 244 }
	name = "‘æ144•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 245 }
	name = "‘æ145•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ30•à•ºt’c"
	id = { type = 19561 id = 246 }
	location = 2281
	division = {
	id = { type = 19561 id = 247 }
	name = "‘æ36íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 248 }
	name = "‘æ146•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 249 }
	name = "‘æ147•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 250 }
	name = "‘æ148•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 251 }
	name = "‘æ149•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 252 }
	name = "‘æ150•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ31•à•ºt’c"
	id = { type = 19561 id = 253 }
	location = 1530
	division = {
	id = { type = 19561 id = 254 }
	name = "‘æ37íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 255 }
	name = "‘æ151•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 256 }
	name = "‘æ152•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 257 }
	name = "‘æ153•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 258 }
	name = "‘æ154•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 259 }
	name = "‘æ155•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ32•à•ºt’c"
	id = { type = 19561 id = 260 }
	location = 1381
	division = {
	id = { type = 19561 id = 261 }
	name = "‘æ38íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 262 }
	name = "‘æ156•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 263 }
	name = "‘æ157•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 264 }
	name = "‘æ158•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 265 }
	name = "‘æ159•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 266 }
	name = "‘æ160•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ33•à•ºt’c"
	id = { type = 19561 id = 267 }
	location = 1313
	division = {
	id = { type = 19561 id = 268 }
	name = "‘æ39íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 269 }
	name = "‘æ161•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 270 }
	name = "‘æ162•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 271 }
	name = "‘æ163•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 272 }
	name = "‘æ164•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 273 }
	name = "‘æ165•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ34•à•ºt’c"
	id = { type = 19561 id = 274 }
	location = 1928
	division = {
	id = { type = 19561 id = 275 }
	name = "‘æ40íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 276 }
	name = "‘æ166•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 277 }
	name = "‘æ167•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 278 }
	name = "‘æ168•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 279 }
	name = "‘æ169•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 280 }
	name = "‘æ170•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ35•à•ºt’c"
	id = { type = 19561 id = 281 }
	location = 695
	division = {
	id = { type = 19561 id = 282 }
	name = "‘æ41íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 283 }
	name = "‘æ171•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 284 }
	name = "‘æ172•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 285 }
	name = "‘æ173•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 286 }
	name = "‘æ174•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 287 }
	name = "‘æ175•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ36•à•ºt’c"
	id = { type = 19561 id = 288 }
	location = 1325
	division = {
	id = { type = 19561 id = 289 }
	name = "‘æ42íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 290 }
	name = "‘æ176•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 291 }
	name = "‘æ177•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 292 }
	name = "‘æ178•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 293 }
	name = "‘æ179•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 294 }
	name = "‘æ180•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ37•à•ºt’c"
	id = { type = 19561 id = 295 }
	location = 2529
	division = {
	id = { type = 19561 id = 296 }
	name = "‘æ43íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 297 }
	name = "‘æ181•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 298 }
	name = "‘æ182•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 299 }
	name = "‘æ183•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 300 }
	name = "‘æ184•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 301 }
	name = "‘æ185•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ38•à•ºt’c"
	id = { type = 19561 id = 302 }
	location = 1439
	division = {
	id = { type = 19561 id = 303 }
	name = "‘æ44íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 304 }
	name = "‘æ186•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 305 }
	name = "‘æ187•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 306 }
	name = "‘æ188•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 307 }
	name = "‘æ189•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 308 }
	name = "‘æ190•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ39•à•ºt’c"
	id = { type = 19561 id = 309 }
	location = 1433
	division = {
	id = { type = 19561 id = 310 }
	name = "‘æ45íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 311 }
	name = "‘æ191•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 312 }
	name = "‘æ192•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 313 }
	name = "‘æ193•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 314 }
	name = "‘æ194•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 315 }
	name = "‘æ195•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
landunit = {
	name = "‘æ40•à•ºt’c"
	id = { type = 19561 id = 316 }
	location = 1386
	division = {
	id = { type = 19561 id = 317 }
	name = "‘æ46íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19561 id = 318 }
	name = "‘æ196•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 319 }
	name = "‘æ197•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 320 }
	name = "‘æ198•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 321 }
	name = "‘æ199•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
	division = {
	id = { type = 19561 id = 322 }
	name = "‘æ200•à•º‘å‘à"
	type = mechanized
	model = 21
	experience = 0
	}
}
airunit = {
	name = "‘æ1q‹ót’c"
	id = { type = 19563 id = 5 }
	location = 1447
	base = 1447
	division = {
	id = { type = 19563 id = 6 }
	name = "‘æ1q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 7 }
	name = "‘æ2q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 8 }
	name = "‘æ3q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ11q‹ót’c"
	id = { type = 19563 id = 9 }
	location = 1447
	base = 1447
	division = {
	id = { type = 19563 id = 10 }
	name = "‘æ4q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 11 }
	name = "‘æ5q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 12 }
	name = "‘æ6q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ16q‹ót’c"
	id = { type = 19563 id = 13 }
	location = 1447
	base = 1447
	division = {
	id = { type = 19563 id = 14 }
	name = "‘æ7q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 15 }
	name = "‘æ8q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 16 }
	name = "‘æ9q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ21q‹ót’c"
	id = { type = 19563 id = 17 }
	location = 1447
	base = 1447
	division = {
	id = { type = 19563 id = 18 }
	name = "‘æ10q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 19 }
	name = "‘æ11q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 20 }
	name = "‘æ12q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ7q‹ót’c"
	id = { type = 19563 id = 21 }
	location = 1448
	base = 1448
	division = {
	id = { type = 19563 id = 22 }
	name = "‘æ13q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 23 }
	name = "‘æ14q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 24 }
	name = "‘æ15q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ15q‹ót’c"
	id = { type = 19563 id = 25 }
	location = 1448
	base = 1448
	division = {
	id = { type = 19563 id = 26 }
	name = "‘æ16q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 27 }
	name = "‘æ17q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 28 }
	name = "‘æ18q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ24q‹ót’c"
	id = { type = 19563 id = 29 }
	location = 1448
	base = 1448
	division = {
	id = { type = 19563 id = 30 }
	name = "‘æ19q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 31 }
	name = "‘æ20q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 32 }
	name = "‘æ21q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ34q‹ót’c"
	id = { type = 19563 id = 33 }
	location = 1448
	base = 1448
	division = {
	id = { type = 19563 id = 34 }
	name = "‘æ22q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 35 }
	name = "‘æ23q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 36 }
	name = "‘æ24q‹ó˜A‘à"
	type = multi_role
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ5q‹ót’c"
	id = { type = 19563 id = 37 }
	location = 1432
	base = 1432
	division = {
	id = { type = 19563 id = 38 }
	name = "‘æ25q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 39 }
	name = "‘æ26q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 40 }
	name = "‘æ27q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ12q‹ót’c"
	id = { type = 19563 id = 41 }
	location = 1432
	base = 1432
	division = {
	id = { type = 19563 id = 42 }
	name = "‘æ28q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 43 }
	name = "‘æ29q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 44 }
	name = "‘æ30q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ19q‹ót’c"
	id = { type = 19563 id = 45 }
	location = 1432
	base = 1432
	division = {
	id = { type = 19563 id = 46 }
	name = "‘æ31q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 47 }
	name = "‘æ32q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 48 }
	name = "‘æ33q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
}
airunit = {
	name = "‘æ32q‹ót’c"
	id = { type = 19563 id = 49 }
	location = 1432
	base = 1432
	division = {
	id = { type = 19563 id = 50 }
	name = "‘æ34q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 51 }
	name = "‘æ35q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19563 id = 52 }
	name = "‘æ36q‹ó˜A‘à"
	type = tactical_bomber
	model = 1
	experience = 0
	}
}
}
