
##############################
# Country definition for IRQ #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = IRQ
  manpower            = 420
  energy              = 12000
  metal               = 18000
  rare_materials      = 15000
  oil                 = 50000
  supplies            = 80000
  money               = 1800
  capital             = 1865
  regular_id          = U03
  transports          = 400
  escorts             = 300
  nationalprovinces   = { 710 1790 1791 1806 1823 1824 1860 1864 1865 1866 2496 }
  ownedprovinces      = { 710 1790 1791 1806 1823 1824 1860 1864 1865 1866 2496 }
  controlledprovinces = { 710 1790 1791 1806 1823 1824 1860 1864 1865 1866 2496 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080  6090  1020  1220  1660  1760
                        }
  inventions          = { }
  policy              = { democratic = 3 political_left = 2 freedom = 3 free_market = 2 professional_army = 9 defense_lobby = 8 interventionism = 8 }
landunit = {
	name = "‘æ3‹@bt’c"
	id = { type = 24601 id = 1 }
	location = 1824
	division = {
	id = { type = 24601 id = 2 }
	name = "‘æ1íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 3 }
	name = "‘æ2íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 4 }
	name = "‘æ3íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 5 }
	name = "‘æ1‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 6 }
	name = "‘æ2‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24601 id = 7 }
	name = "‘æ3‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ6‹@bt’c"
	id = { type = 24601 id = 8 }
	location = 1860
	division = {
	id = { type = 24601 id = 9 }
	name = "‘æ4íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 10 }
	name = "‘æ5íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 11 }
	name = "‘æ6íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 12 }
	name = "‘æ4‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 13 }
	name = "‘æ5‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24601 id = 14 }
	name = "‘æ6‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ12‹@bt’c"
	id = { type = 24601 id = 15 }
	location = 1823
	division = {
	id = { type = 24601 id = 16 }
	name = "‘æ7íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 17 }
	name = "‘æ8íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 18 }
	name = "‘æ9íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 19 }
	name = "‘æ7‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 20 }
	name = "‘æ8‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24601 id = 21 }
	name = "‘æ9‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ17‹@bt’c"
	id = { type = 24601 id = 22 }
	location = 1864
	division = {
	id = { type = 24601 id = 23 }
	name = "‘æ10íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 24 }
	name = "‘æ11íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 25 }
	name = "‘æ12íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 26 }
	name = "‘æ10‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 27 }
	name = "‘æ11‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24601 id = 28 }
	name = "‘æ12‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ52‹@bt’c"
	id = { type = 24601 id = 29 }
	location = 1791
	division = {
	id = { type = 24601 id = 30 }
	name = "‘æ13íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 31 }
	name = "‘æ14íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 32 }
	name = "‘æ15íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 33 }
	name = "‘æ13‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 34 }
	name = "‘æ14‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24601 id = 35 }
	name = "‘æ15‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ2•à•ºt’c"
	id = { type = 24601 id = 36 }
	location = 1806
	division = {
	id = { type = 24601 id = 37 }
	name = "‘æ16íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 38 }
	name = "‘æ16•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 39 }
	name = "‘æ17•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 40 }
	name = "‘æ18•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 41 }
	name = "‘æ19•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 42 }
	name = "‘æ20‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ7•à•ºt’c"
	id = { type = 24601 id = 43 }
	location = 710
	division = {
	id = { type = 24601 id = 44 }
	name = "‘æ17íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 45 }
	name = "‘æ21•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 46 }
	name = "‘æ22•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 47 }
	name = "‘æ23•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 48 }
	name = "‘æ24•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 49 }
	name = "‘æ25‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ1©“®Ô‰»•à•ºt’c"
	id = { type = 24601 id = 50 }
	location = 1865
	division = {
	id = { type = 24601 id = 51 }
	name = "‘æ18íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 52 }
	name = "‘æ26•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 53 }
	name = "‘æ27•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 54 }
	name = "‘æ28•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 55 }
	name = "‘æ29‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24601 id = 56 }
	name = "‘æ30‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ3©“®Ô‰»•à•ºt’c"
	id = { type = 24601 id = 57 }
	location = 1860
	division = {
	id = { type = 24601 id = 58 }
	name = "‘æ19íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 59 }
	name = "‘æ31•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 60 }
	name = "‘æ32•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 61 }
	name = "‘æ33•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 62 }
	name = "‘æ34‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24601 id = 63 }
	name = "‘æ35‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ4©“®Ô‰»•à•ºt’c"
	id = { type = 24601 id = 64 }
	location = 1824
	division = {
	id = { type = 24601 id = 65 }
	name = "‘æ20íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 66 }
	name = "‘æ36•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 67 }
	name = "‘æ37•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 68 }
	name = "‘æ38•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 69 }
	name = "‘æ39‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24601 id = 70 }
	name = "‘æ40‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ5©“®Ô‰»•à•ºt’c"
	id = { type = 24601 id = 71 }
	location = 2496
	division = {
	id = { type = 24601 id = 72 }
	name = "‘æ21íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 73 }
	name = "‘æ41•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 74 }
	name = "‘æ42•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 75 }
	name = "‘æ43•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 76 }
	name = "‘æ44‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24601 id = 77 }
	name = "‘æ45‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ8©“®Ô‰»•à•ºt’c"
	id = { type = 24601 id = 78 }
	location = 2496
	division = {
	id = { type = 24601 id = 79 }
	name = "‘æ22íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24601 id = 80 }
	name = "‘æ46•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 81 }
	name = "‘æ47•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 82 }
	name = "‘æ48•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24601 id = 83 }
	name = "‘æ49‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24601 id = 84 }
	name = "‘æ50‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
  }
}
