
##############################
# Country definition for NZL #
##############################

province = { id = 1868 ic = 5 } # オークランド
province = { id = 1869 ic = 1 } # ネーピア
province = { id = 1870 ic = 2 } # ニュープリマス
province = { id = 1871 ic = 8 naval_base = 5 air_base = 5 } # ウェリントン
province = { id = 1872 ic = 4 } # クライストチャーチ
province = { id = 1873 ic = 2 } # ダニーデン

#####################
# Country main data #
#####################

country =
{ tag                 = NZL
  energy              = 1000
  metal               = 1500
  rare_materials      = 1000
  oil                 = 500
  supplies            = 1000
  manpower            = 18
  transports          = 48
  escorts             = 16
  capital             = 1871
  money               = 100
  policy              = { democratic = 9 political_left = 2 freedom = 8 free_market = 7 professional_army = 8 defense_lobby = 7 interventionism = 3 }
  ownedprovinces      = { 1868 1869 1870 1871 1872 1873 1768 1767 1753 1754 1751 }
  controlledprovinces = { 1868 1869 1870 1871 1872 1873 1768 1767 1753 1754 1751 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080
                        }
  nationalprovinces   = { 1868 1869 1870 1871 1872 1873 }
}
