
##############################
# Country definition for PAK #
##############################

province =
{ id         = 1285
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
}              # ƒNƒ‹ƒi
province =
{ id         = 1481
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
}              # ƒJƒ‰ƒ`

#####################
# Country main data #
#####################

country =
{ tag                 = PAK
  manpower            = 95
  energy              = 800
  metal               = 800
  rare_materials      = 800
  oil                 = 800
  supplies            = 200
  money               = 100
  capital             = 1285
  regular_id          = U04
  transports          = 55
  escorts             = 12
  policy              = { democratic = 2 political_left = 3 freedom = 3 free_market = 3 professional_army = 7 defense_lobby = 8 interventionism = 6 }
  ownedprovinces      = { 1475 1480 1481 1482 1483 1494 1592 1731 1474 }
  controlledprovinces = { 1475 1480 1481 1482 1483 1494 1592 1731 1474 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080
                        }
  nationalprovinces   = { 1475 1480 1481 1482 1483 1494 1592 1731 1474 }
landunit = {
	name = "‘æ17•à•ºt’c"
	id = { type = 24571 id = 1 }
	location = 1731
	division = {
	id = { type = 24571 id = 2 }
	name = "‘æ1•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 3 }
	name = "‘æ2•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 4 }
	name = "‘æ3•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 5 }
	name = "‘æ4•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 6 }
	name = "‘æ5•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 7 }
	name = "‘æ6•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ37•à•ºt’c"
	id = { type = 24571 id = 8 }
	location = 1731
	division = {
	id = { type = 24571 id = 9 }
	name = "‘æ7•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 10 }
	name = "‘æ8•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 11 }
	name = "‘æ9•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 12 }
	name = "‘æ10•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 13 }
	name = "‘æ11•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 14 }
	name = "‘æ12•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ14•à•ºt’c"
	id = { type = 24571 id = 15 }
	location = 1731
	division = {
	id = { type = 24571 id = 16 }
	name = "‘æ13•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 17 }
	name = "‘æ14•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 18 }
	name = "‘æ15•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 19 }
	name = "‘æ16•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 20 }
	name = "‘æ17•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 21 }
	name = "‘æ18•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ40•à•ºt’c"
	id = { type = 24571 id = 22 }
	location = 1731
	division = {
	id = { type = 24571 id = 23 }
	name = "‘æ19•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 24 }
	name = "‘æ20•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 25 }
	name = "‘æ21•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 26 }
	name = "‘æ22•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 27 }
	name = "‘æ23•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 28 }
	name = "‘æ24•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ10•à•ºt’c"
	id = { type = 24571 id = 29 }
	location = 1480
	division = {
	id = { type = 24571 id = 30 }
	name = "‘æ25•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 31 }
	name = "‘æ26•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 32 }
	name = "‘æ27•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 33 }
	name = "‘æ28•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 34 }
	name = "‘æ29•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 35 }
	name = "‘æ30•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ11•à•ºt’c"
	id = { type = 24571 id = 36 }
	location = 1480
	division = {
	id = { type = 24571 id = 37 }
	name = "‘æ31•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 38 }
	name = "‘æ32•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 39 }
	name = "‘æ33•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 40 }
	name = "‘æ34•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 41 }
	name = "‘æ35•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 42 }
	name = "‘æ36•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ8•à•ºt’c"
	id = { type = 24571 id = 43 }
	location = 1480
	division = {
	id = { type = 24571 id = 44 }
	name = "‘æ37•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 45 }
	name = "‘æ38•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 46 }
	name = "‘æ39•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 47 }
	name = "‘æ40•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 48 }
	name = "‘æ41•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 49 }
	name = "‘æ42•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ15•à•ºt’c"
	id = { type = 24571 id = 50 }
	location = 1592
	division = {
	id = { type = 24571 id = 51 }
	name = "‘æ43•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 52 }
	name = "‘æ44•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 53 }
	name = "‘æ45•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 54 }
	name = "‘æ46•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 55 }
	name = "‘æ47•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 56 }
	name = "‘æ48•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ35•à•ºt’c"
	id = { type = 24571 id = 57 }
	location = 1475
	division = {
	id = { type = 24571 id = 58 }
	name = "‘æ49•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 59 }
	name = "‘æ50•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 60 }
	name = "‘æ51•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 61 }
	name = "‘æ52•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 62 }
	name = "‘æ53•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 63 }
	name = "‘æ54•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ16•à•ºt’c"
	id = { type = 24571 id = 64 }
	location = 1482
	division = {
	id = { type = 24571 id = 65 }
	name = "‘æ55•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 66 }
	name = "‘æ56•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 67 }
	name = "‘æ57•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 68 }
	name = "‘æ58•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 69 }
	name = "‘æ59•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 70 }
	name = "‘æ60•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ18•à•ºt’c"
	id = { type = 24571 id = 71 }
	location = 1474
	division = {
	id = { type = 24571 id = 72 }
	name = "‘æ61•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 73 }
	name = "‘æ62•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 74 }
	name = "‘æ63•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 75 }
	name = "‘æ64•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 76 }
	name = "‘æ65•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 77 }
	name = "‘æ66•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ12•à•ºt’c"
	id = { type = 24571 id = 78 }
	location = 1494
	division = {
	id = { type = 24571 id = 79 }
	name = "‘æ67•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 80 }
	name = "‘æ68•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 81 }
	name = "‘æ69•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 82 }
	name = "‘æ70•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 83 }
	name = "‘æ71•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 84 }
	name = "‘æ72•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ19•à•ºt’c"
	id = { type = 24571 id = 85 }
	location = 1483
	division = {
	id = { type = 24571 id = 86 }
	name = "‘æ73•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 87 }
	name = "‘æ74•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 88 }
	name = "‘æ75•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 89 }
	name = "‘æ76•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 90 }
	name = "‘æ77•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 91 }
	name = "‘æ78•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ23•à•ºt’c"
	id = { type = 24571 id = 92 }
	location = 1592
	division = {
	id = { type = 24571 id = 93 }
	name = "‘æ79•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 94 }
	name = "‘æ80•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 95 }
	name = "‘æ81•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 96 }
	name = "‘æ82•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 97 }
	name = "‘æ83•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 98 }
	name = "‘æ84•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ7•à•ºt’c"
	id = { type = 24571 id = 99 }
	location = 1475
	division = {
	id = { type = 24571 id = 100 }
	name = "‘æ85•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 101 }
	name = "‘æ86•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 102 }
	name = "‘æ87•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 103 }
	name = "‘æ88•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 104 }
	name = "‘æ89•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 105 }
	name = "‘æ90•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ9•à•ºt’c"
	id = { type = 24571 id = 106 }
	location = 1482
	division = {
	id = { type = 24571 id = 107 }
	name = "‘æ91•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 108 }
	name = "‘æ92•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 109 }
	name = "‘æ93•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 110 }
	name = "‘æ94•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 111 }
	name = "‘æ95•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 112 }
	name = "‘æ96•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ33•à•ºt’c"
	id = { type = 24571 id = 113 }
	location = 1474
	division = {
	id = { type = 24571 id = 114 }
	name = "‘æ97•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 115 }
	name = "‘æ98•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 116 }
	name = "‘æ99•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 117 }
	name = "‘æ100•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 118 }
	name = "‘æ101•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 119 }
	name = "‘æ102•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ41•à•ºt’c"
	id = { type = 24571 id = 120 }
	location = 1731
	division = {
	id = { type = 24571 id = 121 }
	name = "‘æ103•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 122 }
	name = "‘æ104•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 123 }
	name = "‘æ105•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 124 }
	name = "‘æ106•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 125 }
	name = "‘æ107•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24571 id = 126 }
	name = "‘æ108•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
  }
landunit = {
	name = "‘æ6‹@bt’c"
	id = { type = 24571 id = 127 }
	location = 1731
	division = {
	id = { type = 24571 id = 128 }
	name = "‘æ1íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 129 }
	name = "‘æ2íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 130 }
	name = "‘æ3íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 131 }
	name = "‘æ1‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 132 }
	name = "‘æ2‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 133 }
	name = "‘æ3‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ1‹@bt’c"
	id = { type = 24571 id = 134 }
	location = 1731
	division = {
	id = { type = 24571 id = 135 }
	name = "‘æ4íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 136 }
	name = "‘æ5íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 137 }
	name = "‘æ6íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 138 }
	name = "‘æ4‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 139 }
	name = "‘æ5‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 140 }
	name = "‘æ6‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
  }
landunit = {
	name = "‘æ26‹@bt’c"
	id = { type = 24571 id = 141 }
	location = 1480
	division = {
	id = { type = 24571 id = 142 }
	name = "‘æ7‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 143 }
	name = "‘æ8‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 144 }
	name = "‘æ9‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 145 }
	name = "‘æ10‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 146 }
	name = "‘æ11‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 147 }
	name = "‘æ12‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ25‹@bt’c"
	id = { type = 24571 id = 148 }
	location = 1731
	division = {
	id = { type = 24571 id = 149 }
	name = "‘æ13‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 150 }
	name = "‘æ14‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 151 }
	name = "‘æ15‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 152 }
	name = "‘æ16‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 153 }
	name = "‘æ17‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24571 id = 154 }
	name = "‘æ18‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
  }
}
