
##############################
# Country definition for PER #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = PER
  manpower            = 420
  energy              = 12000
  metal               = 18000
  rare_materials      = 15000
  oil                 = 50000
  supplies            = 80000
  money               = 1800
  capital             = 1502
  regular_id          = U03
  transports          = 400
  escorts             = 300
  nationalprovinces   = { 1495 1496 1497 1498 1499 1500 1501 1502 1503 1787 1788 1789 1825 1826 1859 }
  ownedprovinces      = { 1495 1496 1497 1498 1499 1500 1501 1502 1503 1787 1788 1789 1825 1826 1859 }
  controlledprovinces = { 1495 1496 1497 1498 1499 1500 1501 1502 1503 1787 1788 1789 1825 1826 1859 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080  6090  1020  1220  1660  1760
                        }
  inventions          = { }
  policy              = { democratic = 3 political_left = 2 freedom = 3 free_market = 2 professional_army = 9 defense_lobby = 8 interventionism = 8 }

landunit = {
	name = "‘æ16‹@bt’c"
	id = { type = 24591 id = 1 }
	location = 1500
	division = {
	id = { type = 24591 id = 2 }
	name = "‘æ1íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 3 }
	name = "‘æ2íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 4 }
	name = "‘æ3íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 5 }
	name = "‘æ1‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 6 }
	name = "‘æ2‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 7 }
	name = "‘æ3‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ81‹@bt’c"
	id = { type = 24591 id = 8 }
	location = 1503
	division = {
	id = { type = 24591 id = 9 }
	name = "‘æ4íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 10 }
	name = "‘æ5íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 11 }
	name = "‘æ6íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 12 }
	name = "‘æ4‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 13 }
	name = "‘æ5‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 14 }
	name = "‘æ6‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ88‹@bt’c"
	id = { type = 24591 id = 15 }
	location = 1859
	division = {
	id = { type = 24591 id = 16 }
	name = "‘æ7íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 17 }
	name = "‘æ8íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 18 }
	name = "‘æ9íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 19 }
	name = "‘æ7‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 20 }
	name = "‘æ8‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 21 }
	name = "‘æ9‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ92‹@bt’c"
	id = { type = 24591 id = 22 }
	location = 1788
	division = {
	id = { type = 24591 id = 23 }
	name = "‘æ10íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 24 }
	name = "‘æ11íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 25 }
	name = "‘æ12íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 26 }
	name = "‘æ10‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 27 }
	name = "‘æ11‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 28 }
	name = "‘æ12‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ28•à•ºt’c"
	id = { type = 24591 id = 29 }
	location = 1498
	division = {
	id = { type = 24591 id = 30 }
	name = "‘æ13íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 31 }
	name = "‘æ1•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 32 }
	name = "‘æ2•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 33 }
	name = "‘æ3•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 34 }
	name = "‘æ13‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 35 }
	name = "‘æ14‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ30•à•ºt’c"
	id = { type = 24591 id = 36 }
	location = 1495
	division = {
	id = { type = 24591 id = 37 }
	name = "‘æ14íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 38 }
	name = "‘æ4•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 39 }
	name = "‘æ5•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 40 }
	name = "‘æ6•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 41 }
	name = "‘æ15‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 42 }
	name = "‘æ16‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ64•à•ºt’c"
	id = { type = 24591 id = 43 }
	location = 1825
	division = {
	id = { type = 24591 id = 44 }
	name = "‘æ15íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 45 }
	name = "‘æ7•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 46 }
	name = "‘æ8•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 47 }
	name = "‘æ9•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 48 }
	name = "‘æ17‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 49 }
	name = "‘æ18‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ77•à•ºt’c"
	id = { type = 24591 id = 50 }
	location = 1789
	division = {
	id = { type = 24591 id = 51 }
	name = "‘æ16íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 52 }
	name = "‘æ10•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 53 }
	name = "‘æ11•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 54 }
	name = "‘æ12•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 55 }
	name = "‘æ19‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 56 }
	name = "‘æ20‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ84•à•ºt’c"
	id = { type = 24591 id = 57 }
	location = 1500
	division = {
	id = { type = 24591 id = 58 }
	name = "‘æ17íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 59 }
	name = "‘æ13•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 60 }
	name = "‘æ14•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 61 }
	name = "‘æ15•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 62 }
	name = "‘æ21‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 63 }
	name = "‘æ22‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ1‹ß‰qt’c"
	id = { type = 24591 id = 64 }
	location = 1502
	division = {
	id = { type = 24591 id = 65 }
	name = "‘æ18íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 66 }
	name = "‘æ16•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 67 }
	name = "‘æ17•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 68 }
	name = "‘æ18•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 69 }
	name = "‘æ23‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 70 }
	name = "‘æ24‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
}
landunit = {
	name = "‘æ2‹ß‰qt’c"
	id = { type = 24591 id = 71 }
	location = 1501
	division = {
	id = { type = 24591 id = 72 }
	name = "‘æ19íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 73 }
	name = "‘æ19•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24591 id = 74 }
	name = "‘æ20•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 75 }
	name = "‘æ21•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24591 id = 76 }
	name = "‘æ25‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
	division = {
	id = { type = 24591 id = 77 }
	name = "‘æ26‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 0
	experience = 0
	}
  }
}
