
##############################
# Country definition for SOV #
##############################

province =
{ id         = 133
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # ƒ€ƒ‹ƒ}ƒ“ƒXƒN
province = { id = 145 landfort = 2 anti_air = 3 } # ƒ”ƒB[ƒvƒŠ
province =
{ id         = 154
  anti_air   = 4
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 10 current_size = 10 }
}              # ƒAƒ‹ƒnƒ“ƒQƒŠƒXƒN
province =
{ id       = 163
  air_base = { size = 4 current_size = 4 }
  landfort = 5
  anti_air = 3
}            # ƒXƒ^[ƒŠƒ“ƒOƒ‰[ƒh
province =
{ id       = 166
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ƒS[ƒŠƒL[
province =
{ id       = 171
  air_base = { size = 2 current_size = 2 }
}            # ƒ”ƒHƒƒOƒ_
province =
{ id       = 175
  air_base = { size = 10 current_size = 10 }
  landfort = 5
  anti_air = 4
}            # ƒ‚ƒXƒNƒ
province =
{ id       = 178
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ƒ”ƒ‰ƒW[ƒ~ƒ‹
province =
{ id              = 187
  anti_air        = 6
  naval_base      = { size = 10 current_size = 10 }
  air_base        = { size = 10 current_size = 10 }
  landfort        = 5
  coastalfort     = 5
}                   # ƒŒƒjƒ“ƒOƒ‰[ƒh
province =
{ id       = 200
  air_base = { size = 4 current_size = 4 }
}            # ƒmƒ”ƒSƒ‹ƒh
province = { id = 216 anti_air = 1 } # ƒhƒm[
province =
{ id       = 217
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # ƒ”ƒBƒeƒuƒXƒN
province =
{ id       = 219
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # ƒXƒ‚ƒŒƒ“ƒXƒN
province =
{ id       = 220
  air_base = { size = 4 current_size = 4 }
}            # ƒ‚ƒMƒŠƒt
province =
{ id       = 223
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒCƒ“ƒXƒeƒ‹ƒuƒ‹ƒN
province =
{ id       = 228
  air_base = { size = 4 current_size = 4 }
}            # ƒ”ƒBƒjƒ“ƒcƒ@
province =
{ id       = 233
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # ƒIƒfƒbƒT
province =
{ id         = 234
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # ƒ€ƒBƒRƒ‰[ƒCƒE
province =
{ id       = 238
  anti_air = 3
  air_base = { size = 8 current_size = 8 }
}            # ƒLƒGƒt
province =
{ id       = 248
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒnƒŠƒRƒt
province =
{ id       = 249
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ƒUƒ|ƒŠ[ƒWƒƒ
province =
{ id          = 253
  anti_air    = 6
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  landfort    = 3
  coastalfort = 5
}               # ƒZƒ”ƒ@ƒXƒgƒ|ƒŠ
province =
{ id       = 256
  air_base = { size = 2 current_size = 2 }
}            # ƒNƒ‰ƒXƒmƒ_[ƒ‹
province =
{ id       = 263
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ƒƒbƒ\
province =
{ id       = 269
  air_base = { size = 4 current_size = 4 }
  anti_air = 2
}            # ƒƒXƒgƒtEƒiEƒhƒk
province =
{ id       = 274
  air_base = { size = 4 current_size = 4 }
}            # ƒzƒƒŠ
province =
{ id       = 276
  air_base = { size = 4 current_size = 4 }
}            # ƒIƒŠƒ‡[ƒ‹
province =
{ id       = 279
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒŠƒƒƒUƒ“
province =
{ id       = 281
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒ”ƒHƒƒlƒW
province =
{ id       = 282
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒNƒ‹ƒXƒN
province =
{ id       = 288
  air_base = { size = 2 current_size = 2 }
}            # ƒ‹ƒWƒFƒt
province =
{ id         = 510
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # ƒP[ƒjƒqƒXƒxƒ‹ƒN
province =
{ id         = 133
  air_base   = { size = 10 current_size = 10 }
  naval_base = { size = 10 current_size = 10 }
}              # ƒ€ƒ‹ƒ}ƒ“ƒXƒN
province =
{ id         = 1167
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 5 current_size = 5 }
}              # ƒ}ƒKƒ_ƒ“
province =
{ id       = 1170
  ic       = 10
  air_base = { size = 8 current_size = 8 }
}            # ƒxƒŠƒSƒ“ƒXƒL[
province = { id = 1171 ic = 8 } # ƒpƒ‰ƒi
province =
{ id       = 1172
  ic       = 12
  air_base = { size = 8 current_size = 8 }
}            # ƒyƒgƒƒpƒ”ƒƒtƒXƒNEƒJƒ€ƒ`ƒƒƒcƒL
province =
{ id            = 1366
  anti_air      = 1
  air_base      = { size = 4 current_size = 4 }
  ic            = 4
}                 # ƒnƒoƒƒtƒXƒN
province = { id = 1367 ic = 3 } # ƒeƒ`ƒ…[ƒw
province = { id = 1368 ic = 4 } # ƒ\ƒ”ƒBƒGƒcƒJƒ„EƒKƒ”ƒ@ƒj
province = { id = 1370 ic = 5 } # ƒZƒ~ƒ‡ƒmƒtƒJ
province = { id = 1371 ic = 6 } # ƒiƒzƒgƒJ
province =
{ id          = 1372
  anti_air    = 5
  naval_base  = { size = 10 current_size = 10 }
  air_base    = { size = 10 current_size = 10 }
  ic          = 14
}               # ƒEƒ‰ƒWƒIƒXƒgƒbƒN
province = { id = 1399 ic = 12 } # ƒzƒ‰ƒCƒgƒ}ƒEƒ“ƒeƒ“
province =
{ id       = 1414
  air_base = { size = 8 current_size = 8 }
}            # ƒCƒ‹ƒN[ƒcƒN
province =
{ id       = 1418
  air_base = { size = 6 current_size = 6 }
}            # ƒLƒWƒ‹
province =
{ id       = 1424
  air_base = { size = 2 current_size = 2 }
}            # ƒAƒ‹ƒ}ƒAƒ^
province =
{ id       = 1427
  air_base = { size = 2 current_size = 2 }
}            # ƒ^ƒVƒ…ƒPƒ“ƒg
province =
{ id       = 1522
  air_base = { size = 8 current_size = 8 }
  ic       = 2
}            # ƒ„ƒN[ƒcƒN
province =
{ id       = 1525
  air_base = { size = 8 current_size = 8 }
}            # ƒuƒ‰ƒSƒ”ƒFƒVƒ`ƒFƒ“ƒXƒN
province =
{ id       = 1527
  air_base = { size = 8 current_size = 8 }
  ic       = 2
}            # ƒRƒ€ƒ\ƒ‚ƒŠƒXƒNEƒiEƒAƒ€[ƒŒ
province =
{ id       = 1539
  air_base = { size = 2 current_size = 2 }
}            # ƒgƒ€ƒXƒN
province =
{ id       = 1543
  air_base = { size = 2 current_size = 2 }
}            # ƒmƒ”ƒHƒVƒrƒ‹ƒXƒN
province = { id = 1544 ic = 2 } # ƒrƒCƒXƒN
province =
{ id       = 1550
  air_base = { size = 2 current_size = 2 }
}            # ƒpƒ”ƒƒ_ƒ‹
province =
{ id       = 1552
  air_base = { size = 2 current_size = 2 }
}            # ƒIƒ€ƒXƒN
province = { id = 1560 ic = 2 } # ƒNƒ‰ƒXƒmƒ„ƒ‹ƒXƒN
province =
{ id       = 1562
  air_base = { size = 2 current_size = 2 }
}            # ƒNƒ‰ƒXƒmƒ„ƒ‹ƒX
province =
{ id       = 1564
  air_base = { size = 4 current_size = 4 }
}            # ƒIƒ|[ƒ`ƒJ
province =
{ id       = 1567
  air_base = { size = 2 current_size = 2 }
}            # ƒ`ƒFƒŠƒƒƒrƒ“ƒXƒN
province =
{ id       = 1575
  air_base = { size = 2 current_size = 2 }
}            # ƒXƒxƒ‹ƒhƒƒtƒXƒN
province =
{ id       = 1597
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ƒuƒŠƒƒƒ“ƒXƒN
province = { id = 2646 ic = 18 } # ƒoƒnƒ`
province = { id = 2651 ic = 1 } # ƒGƒ”ƒFƒ“ƒXƒN
province = { id = 2660 ic = 4 } # ƒIƒŠƒ‡ƒNƒ~ƒ“ƒXƒN

#####################
# Country main data #
#####################

country =
{ tag                 = SOV
  manpower            = 3000
  energy              = 58000
  metal               = 38000
  rare_materials      = 48000
  oil                 = 5900
  supplies            = 8000
  money               = 580
  capital             = 175
  transports          = 250
  escorts             = 150
  regular_id          = U06
  #nationalidentity    = "policy_identity_revolutionary"
  #socialpolicy        = "policy_social_militaristic"
  #nationalculture     = "policy_culture_absolut"
  policy              = { democratic = 2 political_left = 9 freedom = 2 free_market = 2 professional_army = 9 defense_lobby = 10 interventionism = 9 }
  ownedprovinces      = { 1149 1150 1151 1152 1153 1154 1155 1156 1167 1170 1171 1172 1175 123  133  134  135  1366 1367 1368 1369 1370 1371 1372 1383
                          1384 1410 1411 1412 1413 1414 1415 1416 1417 1418 1422 1423 1424 1425 1426 1427 1428 1429 143  145  146  1485 1488 1489 1490
                          1491 150  151  152  1520 1521 1522 1524 1525 1526 1527 1528 1529 153  1533 1534 1536 1535 1538 1539 154  1540 1541 1542
                          1543 1544 1545 1546 1547 1548 1549 155  1550 1551 1552 1555 1556 1557 1558 1559 156  1560 1561 1562 1564 1565 1566 1567 1568
                          1569 157  1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 158  1580 1581 1582 1583 1584 1585 1586 1587 1588 159  1593 1594
                          1596 1597 1598 160  161  162  163  164  165  166  167  168  169  170  171  172  173  174  175  176  177  1771 1772 1773 1774
                          1775 1776 1777 1778 178  1780 1781 1782 1783 179  180  181  182  1827 1828 1829 183  1830 1831 1832 1833 1834 1836 1837
                          1838 1839 184  1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 185  1850 1856 1857 1858 186  187  1874 188  189  190  1907
                          191  192  200  201  212  215  216  217  218  219  220  221  223  2240 225  226  227  228  231  232  233  234  235  236  237 
                          238  239  240  241  242  243  244  245  246  247  2470 248  2488 249  250  251  252  253  254  255  256  257  258  259  260 
                          261  262  263  264  265  266  267  268  269  270  271  272  273  274  275  276  277  278  279  280  281  282  283  284  285 
                          286  287  288  289  510  94   2646 2647 2648 2649 2650 2651 2652 2653 2654 2655 2656 2657 2658
                          2659 2660 503 506 502 229 507 500 501 213 95 209 102 210 562 1885 193 194 195 196 197 198 199 202 203 204 205 206 207 214 509
                          511 577 1886 2606 1173 1401 230 433 434 435 2605 1523
                        }
  controlledprovinces = { 1149 1150 1151 1152 1153 1154 1155 1156 1167 1170 1171 1172 1175 123  133  134  135  1366 1367 1368 1369 1370 1371 1372 1383
                          1384 1410 1411 1412 1413 1414 1415 1416 1417 1418 1422 1423 1424 1425 1426 1427 1428 1429 143  145  146  1485 1488 1489 1490
                          1491 150  151  152  1520 1521 1522 1524 1525 1526 1527 1528 1529 153  1533 1534 1536 1535 1538 1539 154  1540 1541 1542
                          1543 1544 1545 1546 1547 1548 1549 155  1550 1551 1552 1555 1556 1557 1558 1559 156  1560 1561 1562 1564 1565 1566 1567 1568
                          1569 157  1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 158  1580 1581 1582 1583 1584 1585 1586 1587 1588 159  1593 1594
                          1596 1597 1598 160  161  162  163  164  165  166  167  168  169  170  171  172  173  174  175  176  177  1771 1772 1773 1774
                          1775 1776 1777 1778 178  1780 1781 1782 1783 179  180  181  182  1827 1828 1829 183  1830 1831 1832 1833 1834 1836 1837
                          1838 1839 184  1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 185  1850 1856 1857 1858 186  187  1874 188  189  190  1907
                          191  192  200  201  212  215  216  217  218  219  220  221  223  2240 225  226  227  228  231  232  233  234  235  236  237 
                          238  239  240  241  242  243  244  245  246  247  2470 248  2488 249  250  251  252  253  254  255  256  257  258  259  260 
                          261  262  263  264  265  266  267  268  269  270  271  272  273  274  275  276  277  278  279  280  281  282  283  284  285 
                          286  287  288  289  510  94   2646 2647 2648 2649 2650 2651 2652 2653 2654 2655 2656 2657 2658
                          2659 2660 503 506 502 229 507 500 501 213 95 209 102 210 562 1885 193 194 195 196 197 198 199 202 203 204 205 206 207 214 509
                          511 577 1886 2606 1173 1401 230 433 434 435 2605 1523
                        }
  nationalprovinces   = { 1149 1150 1151 1152 1153 1154 1155 1156 1167 1170 1171 1172 1175 123  133  134  135  1366 1367 1368 1369 1370 1371 1372 1383
                          1384 1410 1411 1412 1413 1414 1415 1416 1417 1418 1422 1423 1424 1425 1426 1427 1428 1429 143  145  146  1485 1488 1489 1490
                          1491 150  151  152  1520 1521 1522 1524 1525 1526 1527 1528 1529 153  1533 1534 1536 1535 1538 1539 154  1540 1541 1542
                          1543 1544 1545 1546 1547 1548 1549 155  1550 1551 1552 1555 1556 1557 1558 1559 156  1560 1561 1562 1564 1565 1566 1567 1568
                          1569 157  1570 1571 1572 1573 1574 1575 1576 1577 1578 1579 158  1580 1581 1582 1583 1584 1585 1586 1587 1588 159  1593 1594
                          1596 1597 1598 160  161  162  163  164  165  166  167  168  169  170  171  172  173  174  175  176  177  1771 1772 1773 1774
                          1775 1776 1777 1778 178  1780 1781 1782 1783 179  180  181  182  1827 1828 1829 183  1830 1831 1832 1833 1834 1836 1837
                          1838 1839 184  1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 185  1850 1856 1857 1858 186  187  1874 188  189  190  1907
                          191  192  200  201  212  215  216  217  218  219  220  221  223  2240 225  226  227  228  231  232  233  234  235  236  237 
                          238  239  240  241  242  243  244  245  246  247  2470 248  2488 249  250  251  252  253  254  255  256  257  258  259  260 
                          261  262  263  264  265  266  267  268  269  270  271  272  273  274  275  276  277  278  279  280  281  282  283  284  285 
                          286  287  288  289  510  94   2646 2647 2648 2649 2650 2651 2652 2653 2654 2655 2656 2657 2658
                          2659 2660 503 506 502 229 507 500 501 213 95 209 102 210 562 1885 193 194 195 196 197 198 199 202 203 204 205 206 207 214 509
                          511 577 1886 2606 1173 1401 230 433 434 435 2605 1523
                        }
  techapps            = { 10050 10060 1010  10190 1020  10200 1030  1050  1110  1120 
                          1210  1220  1470  1490  1510  1530  1550  1560  1650  1660
                          1750  1760  1850  1860  1950  1960
                          3010  3020  30410 30420 30510 30520 3110 
                          3120  3210  3220  3460  3470  40200 40210  3310  3320  3610  3620  3710  3720  7500  7510  7520  7530  7540  7670  7680  7690  7700
                          3560  3640  3650  3910  3920
                          3940  40100 40110 4390  4400  4010  4020  4110  4120  4210  4220  4640  4650  4820  4830
                          4560  50020 50030 50040 50050 50070 50080 50090 5010  50100 50110 50120 5020  50290 50300 50310
                          5090  5100  5170  5180  5250  5260  5330  5340  5410  5420
                          5490  5500  5600  5610  5680  5690  5760  5770  5780  5790  5800  5810
                          5910  5920  7010  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990  6000  6010  6020  6030  6040  7030  7040  7050  7060
                        }
  inventions          = { 8000 8009 8011 }
  landunit = {
	name = "‘æ1íÔt’c"
	id = { type = 19501 id = 1 }
	location = 296
	division = {
	id = { type = 19501 id = 2 }
	name = "‘æ1íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 3 }
	name = "‘æ2íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 4 }
	name = "‘æ3íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ2íÔt’c"
	id = { type = 19501 id = 5 }
	location = 297
	division = {
	id = { type = 19501 id = 6 }
	name = "‘æ4íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 7 }
	name = "‘æ5íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 8 }
	name = "‘æ6íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ3íÔt’c"
	id = { type = 19501 id = 9 }
	location = 298
	division = {
	id = { type = 19501 id = 10 }
	name = "‘æ7íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 11 }
	name = "‘æ8íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 12 }
	name = "‘æ9íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ4íÔt’c"
	id = { type = 19501 id = 13 }
	location = 84
	division = {
	id = { type = 19501 id = 14 }
	name = "‘æ10íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 15 }
	name = "‘æ11íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 16 }
	name = "‘æ12íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ5íÔt’c"
	id = { type = 19501 id = 17 }
	location = 311
	division = {
	id = { type = 19501 id = 18 }
	name = "‘æ13íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 19 }
	name = "‘æ14íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 20 }
	name = "‘æ15íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ6íÔt’c"
	id = { type = 19501 id = 21 }
	location = 300
	division = {
	id = { type = 19501 id = 22 }
	name = "‘æ16íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 23 }
	name = "‘æ17íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 24 }
	name = "‘æ18íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ7íÔt’c"
	id = { type = 19501 id = 25 }
	location = 298
	division = {
	id = { type = 19501 id = 26 }
	name = "‘æ19íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 27 }
	name = "‘æ20íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 28 }
	name = "‘æ21íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ8íÔt’c"
	id = { type = 19501 id = 29 }
	location = 296
	division = {
	id = { type = 19501 id = 30 }
	name = "‘æ22íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 31 }
	name = "‘æ23íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 32 }
	name = "‘æ24íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ9íÔt’c"
	id = { type = 19501 id = 33 }
	location = 298
	division = {
	id = { type = 19501 id = 34 }
	name = "‘æ25íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 35 }
	name = "‘æ26íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 36 }
	name = "‘æ27íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ1©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 205 }
	location = 296
	division = {
	id = { type = 19501 id = 206 }
	name = "‘æ1©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 207 }
	name = "‘æ2©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 208 }
	name = "‘æ3©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ2©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 209 }
	location = 296
	division = {
	id = { type = 19501 id = 210 }
	name = "‘æ4©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 211 }
	name = "‘æ5©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 212 }
	name = "‘æ6©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ3©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 213 }
	location = 296
	division = {
	id = { type = 19501 id = 214 }
	name = "‘æ7©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 215 }
	name = "‘æ8©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 216 }
	name = "‘æ9©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ4©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 217 }
	location = 297
	division = {
	id = { type = 19501 id = 218 }
	name = "‘æ10©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 219 }
	name = "‘æ11©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 220 }
	name = "‘æ12©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ5©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 221 }
	location = 298
	division = {
	id = { type = 19501 id = 222 }
	name = "‘æ13©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 223 }
	name = "‘æ14©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 224 }
	name = "‘æ15©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ6©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 225 }
	location = 298
	division = {
	id = { type = 19501 id = 226 }
	name = "‘æ16©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 227 }
	name = "‘æ17©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 228 }
	name = "‘æ18©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ7©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 229 }
	location = 84
	division = {
	id = { type = 19501 id = 230 }
	name = "‘æ19©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 231 }
	name = "‘æ20©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 232 }
	name = "‘æ21©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ8©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 233 }
	location = 84
	division = {
	id = { type = 19501 id = 234 }
	name = "‘æ22©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 235 }
	name = "‘æ23©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 236 }
	name = "‘æ24©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ9©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 237 }
	location = 311
	division = {
	id = { type = 19501 id = 238 }
	name = "‘æ25©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 239 }
	name = "‘æ26©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 240 }
	name = "‘æ27©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ10©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 241 }
	location = 311
	division = {
	id = { type = 19501 id = 242 }
	name = "‘æ28©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 243 }
	name = "‘æ29©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 244 }
	name = "‘æ30©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
#####ª“ŒƒhƒCƒc’“—¯ŒR
landunit = {
	name = "‘æ10íÔt’c"
	id = { type = 19501 id = 37 }
	location = 302
	division = {
	id = { type = 19501 id = 38 }
	name = "‘æ28íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 39 }
	name = "‘æ29íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 40 }
	name = "‘æ30íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ11íÔt’c"
	id = { type = 19501 id = 41 }
	location = 486
	division = {
	id = { type = 19501 id = 42 }
	name = "‘æ31íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 43 }
	name = "‘æ32íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 44 }
	name = "‘æ33íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
###ªƒ|[ƒ‰ƒ“ƒh’“—¯ŒR
landunit = {
	name = "‘æ12íÔt’c"
	id = { type = 19501 id = 45 }
	location = 2447
	division = {
	id = { type = 19501 id = 46 }
	name = "‘æ34íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 47 }
	name = "‘æ35íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 48 }
	name = "‘æ36íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ13íÔt’c"
	id = { type = 19501 id = 49 }
	location = 456
	division = {
	id = { type = 19501 id = 50 }
	name = "‘æ37íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 51 }
	name = "‘æ38íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 52 }
	name = "‘æ39íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ11©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 245 }
	location = 2447
	division = {
	id = { type = 19501 id = 246 }
	name = "‘æ31©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 247 }
	name = "‘æ32©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 248 }
	name = "‘æ33©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ12©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 249 }
	location = 224
	division = {
	id = { type = 19501 id = 250 }
	name = "‘æ34©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 251 }
	name = "‘æ35©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 252 }
	name = "‘æ36©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
###ªƒnƒ“ƒKƒŠ[’“—¯ŒR
landunit = {
	name = "‘æ14íÔt’c"
	id = { type = 19501 id = 53 }
	location = 53
	division = {
	id = { type = 19501 id = 54 }
	name = "‘æ40íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 55 }
	name = "‘æ41íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 56 }
	name = "‘æ42íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ15íÔt’c"
	id = { type = 19501 id = 57 }
	location = 468
	division = {
	id = { type = 19501 id = 58 }
	name = "‘æ43íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 59 }
	name = "‘æ44íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 60 }
	name = "‘æ45íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
  }
landunit = {
	name = "‘æ13©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 253 }
	location = 53
	division = {
	id = { type = 19501 id = 254 }
	name = "‘æ37©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 255 }
	name = "‘æ38©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 256 }
	name = "‘æ39©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ14©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 257 }
	location = 466
	division = {
	id = { type = 19501 id = 258 }
	name = "‘æ40©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 259 }
	name = "‘æ41©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 260 }
	name = "‘æ42©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
landunit = {
	name = "‘æ15©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 261 }
	location = 490
	division = {
	id = { type = 19501 id = 262 }
	name = "‘æ43©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 263 }
	name = "‘æ44©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	locked = yes
	}
	division = {
	id = { type = 19501 id = 264 }
	name = "‘æ45©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	locked = yes
	}
}
###ªƒ`ƒFƒRƒXƒƒ”ƒ@ƒLƒA’“—¯ŒR
landunit = {
	name = "‘æ16íÔt’c"
	id = { type = 19501 id = 61 }
	location = 204
	division = {
	id = { type = 19501 id = 62 }
	name = "‘æ46íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 63 }
	name = "‘æ47íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 64 }
	name = "‘æ48íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ17íÔt’c"
	id = { type = 19501 id = 65 }
	location = 207
	division = {
	id = { type = 19501 id = 66 }
	name = "‘æ49íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 67 }
	name = "‘æ50íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 68 }
	name = "‘æ51íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ18íÔt’c"
	id = { type = 19501 id = 69 }
	location = 510
	division = {
	id = { type = 19501 id = 70 }
	name = "‘æ52íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 71 }
	name = "‘æ53íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 72 }
	name = "‘æ54íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ16©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 265 }
	location = 204
	division = {
	id = { type = 19501 id = 266 }
	name = "‘æ46©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 267 }
	name = "‘æ47©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 268 }
	name = "‘æ48©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 75
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ17©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 269 }
	location = 207
	division = {
	id = { type = 19501 id = 270 }
	name = "‘æ49©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 271 }
	name = "‘æ50©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 272 }
	name = "‘æ51©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 75
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ18©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 273 }
	location = 510
	division = {
	id = { type = 19501 id = 274 }
	name = "‘æ52©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 275 }
	name = "‘æ53©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 276 }
	name = "‘æ54©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 75
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ19©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 277 }
	location = 510
	division = {
	id = { type = 19501 id = 278 }
	name = "‘æ55©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 279 }
	name = "‘æ56©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 280 }
	name = "‘æ57©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ20©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 281 }
	location = 207
	division = {
	id = { type = 19501 id = 282 }
	name = "‘æ58©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 283 }
	name = "‘æ59©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 284 }
	name = "‘æ60©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
###ª‰ˆƒoƒ‹ƒgŒRŠÇ‹æ
landunit = {
	name = "‘æ19íÔt’c"
	id = { type = 19501 id = 73 }
	location = 102
	division = {
	id = { type = 19501 id = 74 }
	name = "‘æ55íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 75 }
	name = "‘æ56íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 76 }
	name = "‘æ57íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ20íÔt’c"
	id = { type = 19501 id = 77 }
	location = 562
	division = {
	id = { type = 19501 id = 78 }
	name = "‘æ58íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 79 }
	name = "‘æ59íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 80 }
	name = "‘æ60íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ21íÔt’c"
	id = { type = 19501 id = 81 }
	location = 1885
	division = {
	id = { type = 19501 id = 82 }
	name = "‘æ61íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 83 }
	name = "‘æ62íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 84 }
	name = "‘æ63íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ22íÔt’c"
	id = { type = 19501 id = 85 }
	location = 272
	division = {
	id = { type = 19501 id = 86 }
	name = "‘æ64íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 87 }
	name = "‘æ65íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 88 }
	name = "‘æ66íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ23íÔt’c"
	id = { type = 19501 id = 89 }
	location = 95
	division = {
	id = { type = 19501 id = 90 }
	name = "‘æ67íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 91 }
	name = "‘æ68íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 92 }
	name = "‘æ69íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ24íÔt’c"
	id = { type = 19501 id = 93 }
	location = 212
	division = {
	id = { type = 19501 id = 94 }
	name = "‘æ70íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 95 }
	name = "‘æ71íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 96 }
	name = "‘æ72íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ25íÔt’c"
	id = { type = 19501 id = 97 }
	location = 210
	division = {
	id = { type = 19501 id = 98 }
	name = "‘æ73íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 99 }
	name = "‘æ74íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 100 }
	name = "‘æ75íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ26íÔt’c"
	id = { type = 19501 id = 105 }
	location = 272
	division = {
	id = { type = 19501 id = 106 }
	name = "‘æ79íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 107 }
	name = "‘æ80íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 108 }
	name = "‘æ81íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ27íÔt’c"
	id = { type = 19501 id = 113 }
	location = 273
	division = {
	id = { type = 19501 id = 114 }
	name = "‘æ85íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 115 }
	name = "‘æ86íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 116 }
	name = "‘æ87íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ21©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 285 }
	location = 272
	division = {
	id = { type = 19501 id = 286 }
	name = "‘æ61©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 287 }
	name = "‘æ62©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 288 }
	name = "‘æ63©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ22©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 289 }
	location = 273
	division = {
	id = { type = 19501 id = 290 }
	name = "‘æ64©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 291 }
	name = "‘æ65©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 292 }
	name = "‘æ66©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
##ª”’ƒƒVƒAŒRŠÇ‹æ
landunit = {
	name = "‘æ28íÔt’c"
	id = { type = 19501 id = 117 }
	location = 501
	division = {
	id = { type = 19501 id = 118 }
	name = "‘æ88íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 119 }
	name = "‘æ89íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 120 }
	name = "‘æ90íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ29íÔt’c"
	id = { type = 19501 id = 121 }
	location = 500
	division = {
	id = { type = 19501 id = 122 }
	name = "‘æ91íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 123 }
	name = "‘æ92íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 124 }
	name = "‘æ93íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ23©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 293 }
	location = 500
	division = {
	id = { type = 19501 id = 294 }
	name = "‘æ67©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 295 }
	name = "‘æ68©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 296 }
	name = "‘æ69©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ24©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 297 }
	location = 501
	division = {
	id = { type = 19501 id = 298 }
	name = "‘æ70©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 299 }
	name = "‘æ71©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 300 }
	name = "‘æ72©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
##ª‰ˆƒJƒ‹ƒpƒgŒRŠÇ‹æ
landunit = {
	name = "‘æ30íÔt’c"
	id = { type = 19501 id = 125 }
	location = 238
	division = {
	id = { type = 19501 id = 126 }
	name = "‘æ94íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 127 }
	name = "‘æ95íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 128 }
	name = "‘æ96íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ31íÔt’c"
	id = { type = 19501 id = 129 }
	location = 227
	division = {
	id = { type = 19501 id = 130 }
	name = "‘æ97íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 131 }
	name = "‘æ98íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 132 }
	name = "‘æ99íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ32íÔt’c"
	id = { type = 19501 id = 133 }
	location = 228
	division = {
	id = { type = 19501 id = 134 }
	name = "‘æ100íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 135 }
	name = "‘æ101íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 136 }
	name = "‘æ102íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ33íÔt’c"
	id = { type = 19501 id = 141 }
	location = 237
	division = {
	id = { type = 19501 id = 142 }
	name = "‘æ106íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 143 }
	name = "‘æ107íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 144 }
	name = "‘æ108íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ34íÔt’c"
	id = { type = 19501 id = 145 }
	location = 238
	division = {
	id = { type = 19501 id = 146 }
	name = "‘æ109íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 147 }
	name = "‘æ110íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 148 }
	name = "‘æ111íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ35íÔt’c"
	id = { type = 19501 id = 149 }
	location = 237
	division = {
	id = { type = 19501 id = 150 }
	name = "‘æ112íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 151 }
	name = "‘æ113íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 152 }
	name = "‘æ114íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ36íÔt’c"
	id = { type = 19501 id = 153 }
	location = 237
	division = {
	id = { type = 19501 id = 154 }
	name = "‘æ115íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 155 }
	name = "‘æ116íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 156 }
	name = "‘æ117íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ25©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 301 }
	location = 237
	division = {
	id = { type = 19501 id = 302 }
	name = "‘æ73©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 303 }
	name = "‘æ74©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 304 }
	name = "‘æ75©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ26©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 305 }
	location = 238
	division = {
	id = { type = 19501 id = 306 }
	name = "‘æ76©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 307 }
	name = "‘æ77©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 308 }
	name = "‘æ78©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ27©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 309 }
	location = 227
	division = {
	id = { type = 19501 id = 310 }
	name = "‘æ79©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 311 }
	name = "‘æ80©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 312 }
	name = "‘æ81©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ28©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 313 }
	location = 228
	division = {
	id = { type = 19501 id = 314 }
	name = "‘æ82©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 315 }
	name = "‘æ83©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 316 }
	name = "‘æ84©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
}
###ªƒLƒGƒtŒRŠÇ‹æ
landunit = {
	name = "‘æ29©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 317 }
	location = 187
	division = {
	id = { type = 19501 id = 318 }
	name = "‘æ85©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 319 }
	name = "‘æ86©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 320 }
	name = "‘æ87©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ30©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 321 }
	location = 151
	division = {
	id = { type = 19501 id = 322 }
	name = "‘æ88©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 323 }
	name = "‘æ89©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 324 }
	name = "‘æ90©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ31©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 325 }
	location = 145
	division = {
	id = { type = 19501 id = 326 }
	name = "‘æ91©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 327 }
	name = "‘æ92©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 328 }
	name = "‘æ93©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ32©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 329 }
	location = 133
	division = {
	id = { type = 19501 id = 330 }
	name = "‘æ94©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 331 }
	name = "‘æ95©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 332 }
	name = "‘æ96©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ33©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 333 }
	location = 154
	division = {
	id = { type = 19501 id = 334 }
	name = "‘æ97©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 335 }
	name = "‘æ98©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 336 }
	name = "‘æ99©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ34©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 337 }
	location = 194
	division = {
	id = { type = 19501 id = 338 }
	name = "‘æ100©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 339 }
	name = "‘æ101©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 340 }
	name = "‘æ102©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ35©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 341 }
	location = 143
	division = {
	id = { type = 19501 id = 342 }
	name = "‘æ103©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 343 }
	name = "‘æ104©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 344 }
	name = "‘æ105©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ36©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 345 }
	location = 200
	division = {
	id = { type = 19501 id = 346 }
	name = "‘æ106©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 347 }
	name = "‘æ107©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 348 }
	name = "‘æ108©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
###ªƒŒƒjƒ“ƒOƒ‰[ƒhŒRŠÇ‹æ
landunit = {
	name = "‘æ37íÔt’c"
	id = { type = 19501 id = 165 }
	location = 175
	division = {
	id = { type = 19501 id = 166 }
	name = "‘æ124íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 167 }
	name = "‘æ125íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 168 }
	name = "‘æ126íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ38íÔt’c"
	id = { type = 19501 id = 169 }
	location = 1155
	division = {
	id = { type = 19501 id = 170 }
	name = "‘æ127íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 171 }
	name = "‘æ128íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 172 }
	name = "‘æ129íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ37©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 349 }
	location = 175
	division = {
	id = { type = 19501 id = 350 }
	name = "‘æ109©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 351 }
	name = "‘æ110©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 352 }
	name = "‘æ111©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ38©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 353 }
	location = 288
	division = {
	id = { type = 19501 id = 354 }
	name = "‘æ112©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 355 }
	name = "‘æ113©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 356 }
	name = "‘æ114©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ39©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 357 }
	location = 94
	division = {
	id = { type = 19501 id = 358 }
	name = "‘æ115©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 359 }
	name = "‘æ116©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 360 }
	name = "‘æ117©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ40©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 361 }
	location = 279
	division = {
	id = { type = 19501 id = 362 }
	name = "‘æ118©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 363 }
	name = "‘æ119©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 364 }
	name = "‘æ120©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
###ªƒ‚ƒXƒNƒŒRŠÇ‹æ
landunit = {
	name = "‘æ41©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 365 }
	location = 233
	division = {
	id = { type = 19501 id = 366 }
	name = "‘æ121©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 367 }
	name = "‘æ122©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 368 }
	name = "‘æ123©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ42©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 369 }
	location = 435
	division = {
	id = { type = 19501 id = 370 }
	name = "‘æ124©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 371 }
	name = "‘æ125©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 372 }
	name = "‘æ126©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ43©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 373 }
	location = 433
	division = {
	id = { type = 19501 id = 374 }
	name = "‘æ127©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 375 }
	name = "‘æ128©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 376 }
	name = "‘æ129©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 50
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ44©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 377 }
	location = 234
	division = {
	id = { type = 19501 id = 378 }
	name = "‘æ130©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 379 }
	name = "‘æ131©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 380 }
	name = "‘æ132©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ45©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 381 }
	location = 234
	division = {
	id = { type = 19501 id = 382 }
	name = "‘æ133©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 383 }
	name = "‘æ134©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 384 }
	name = "‘æ135©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ46©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 385 }
	location = 233
	division = {
	id = { type = 19501 id = 386 }
	name = "‘æ136©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 387 }
	name = "‘æ137©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 388 }
	name = "‘æ138©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	#locked = yes
	}
}
###ªƒIƒfƒbƒTŒRŠÇ‹æ
landunit = {
	name = "‘æ39íÔt’c"
	id = { type = 19501 id = 173 }
	location = 1575
	division = {
	id = { type = 19501 id = 174 }
	name = "‘æ130íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 175 }
	name = "‘æ131íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 176 }
	name = "‘æ132íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ47©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 389 }
	location = 1567
	division = {
	id = { type = 19501 id = 390 }
	name = "‘æ139©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 391 }
	name = "‘æ140©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 392 }
	name = "‘æ141©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ48©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 393 }
	location = 1574
	division = {
	id = { type = 19501 id = 394 }
	name = "‘æ142©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 395 }
	name = "‘æ143©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 396 }
	name = "‘æ144©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 50
	experience = 0
	#locked = yes
	}
}
###ªƒEƒ‰ƒ‹ŒRŠÇ‹æ
landunit = {
	name = "‘æ49©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 397 }
	location = 1832
	division = {
	id = { type = 19501 id = 398 }
	name = "‘æ145©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 399 }
	name = "‘æ146©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 400 }
	name = "‘æ147©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ50©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 401 }
	location = 163
	division = {
	id = { type = 19501 id = 402 }
	name = "‘æ148©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 403 }
	name = "‘æ149©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 404 }
	name = "‘æ150©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ51©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 405 }
	location = 158
	division = {
	id = { type = 19501 id = 406 }
	name = "‘æ151©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 407 }
	name = "‘æ152©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 408 }
	name = "‘æ153©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
###ª‰ˆƒ{ƒ‹ƒKŒRŠÇ‹æ
landunit = {
	name = "‘æ40íÔt’c"
	id = { type = 19501 id = 177 }
	location = 269
	division = {
	id = { type = 19501 id = 178 }
	name = "‘æ133íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 179 }
	name = "‘æ134íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 180 }
	name = "‘æ135íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ52©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 409 }
	location = 269
	division = {
	id = { type = 19501 id = 410 }
	name = "‘æ154©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 411 }
	name = "‘æ155©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 412 }
	name = "‘æ156©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ53©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 413 }
	location = 256
	division = {
	id = { type = 19501 id = 414 }
	name = "‘æ157©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 415 }
	name = "‘æ158©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 416 }
	name = "‘æ159©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ54©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 417 }
	location = 1907
	division = {
	id = { type = 19501 id = 418 }
	name = "‘æ160©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 419 }
	name = "‘æ161©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 420 }
	name = "‘æ162©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ55©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 421 }
	location = 1848
	division = {
	id = { type = 19501 id = 422 }
	name = "‘æ163©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 423 }
	name = "‘æ164©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 424 }
	name = "‘æ165©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ56©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 425 }
	location = 1850
	division = {
	id = { type = 19501 id = 426 }
	name = "‘æ166©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 427 }
	name = "‘æ167©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 428 }
	name = "‘æ168©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ57©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 429 }
	location = 255
	division = {
	id = { type = 19501 id = 430 }
	name = "‘æ169©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 431 }
	name = "‘æ170©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 432 }
	name = "‘æ171©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ58©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 433 }
	location = 269
	division = {
	id = { type = 19501 id = 434 }
	name = "‘æ172©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 435 }
	name = "‘æ173©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 436 }
	name = "‘æ174©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ59©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 437 }
	location = 257
	division = {
	id = { type = 19501 id = 438 }
	name = "‘æ175©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 439 }
	name = "‘æ176©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 440 }
	name = "‘æ177©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ60©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 441 }
	location = 1843
	division = {
	id = { type = 19501 id = 442 }
	name = "‘æ178©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 443 }
	name = "‘æ179©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 444 }
	name = "‘æ180©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ61©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 445 }
	location = 1845
	division = {
	id = { type = 19501 id = 446 }
	name = "‘æ181©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 447 }
	name = "‘æ182©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 448 }
	name = "‘æ183©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ62©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 449 }
	location = 1848
	division = {
	id = { type = 19501 id = 450 }
	name = "‘æ184©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 451 }
	name = "‘æ185©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 452 }
	name = "‘æ186©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ63©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 453 }
	location = 270
	division = {
	id = { type = 19501 id = 454 }
	name = "‘æ187©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 455 }
	name = "‘æ188©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 456 }
	name = "‘æ189©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ64©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 457 }
	location = 1842
	division = {
	id = { type = 19501 id = 458 }
	name = "‘æ190©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 459 }
	name = "‘æ191©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 460 }
	name = "‘æ192©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ65©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 461 }
	location = 1846
	division = {
	id = { type = 19501 id = 462 }
	name = "‘æ193©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 463 }
	name = "‘æ194©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 464 }
	name = "‘æ195©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ66©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 465 }
	location = 256
	division = {
	id = { type = 19501 id = 466 }
	name = "‘æ196©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 467 }
	name = "‘æ197©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 468 }
	name = "‘æ198©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ67©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 469 }
	location = 256
	division = {
	id = { type = 19501 id = 470 }
	name = "‘æ199©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 471 }
	name = "‘æ200©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 472 }
	name = "‘æ201©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ68©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 473 }
	location = 1837
	division = {
	id = { type = 19501 id = 474 }
	name = "‘æ202©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 475 }
	name = "‘æ203©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 476 }
	name = "‘æ204©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ69©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 477 }
	location = 1907
	division = {
	id = { type = 19501 id = 478 }
	name = "‘æ205©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 479 }
	name = "‘æ206©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 480 }
	name = "‘æ207©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ70©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 481 }
	location = 1907
	division = {
	id = { type = 19501 id = 482 }
	name = "‘æ208©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 483 }
	name = "‘æ209©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 484 }
	name = "‘æ210©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ71©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 485 }
	location = 1907
	division = {
	id = { type = 19501 id = 486 }
	name = "‘æ211©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 487 }
	name = "‘æ212©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 488 }
	name = "‘æ213©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ72©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 489 }
	location = 1907
	division = {
	id = { type = 19501 id = 490 }
	name = "‘æ214©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 491 }
	name = "‘æ215©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19501 id = 492 }
	name = "‘æ216©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	#locked = yes
	}
}
###ª–kƒJƒtƒJƒXEƒUƒJƒtƒJƒXEƒgƒ‹ƒPƒXƒ^ƒ“3ŒRŠÇ‹æ
landunit = {
	name = "‘æ41íÔt’c"
	id = { type = 19501 id = 181 }
	location = 1424
	division = {
	id = { type = 19501 id = 182 }
	name = "‘æ136íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 183 }
	name = "‘æ137íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 184 }
	name = "‘æ138íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
  }
landunit = {
	name = "‘æ73©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 493 }
	location = 1424
	division = {
	id = { type = 19501 id = 494 }
	name = "‘æ217©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 495 }
	name = "‘æ218©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 496 }
	name = "‘æ219©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ74©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 497 }
	location = 1427
	division = {
	id = { type = 19501 id = 498 }
	name = "‘æ220©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 499 }
	name = "‘æ221©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 500 }
	name = "‘æ222©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ75©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 501 }
	location = 1429
	division = {
	id = { type = 19501 id = 502 }
	name = "‘æ223©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 503 }
	name = "‘æ224©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 504 }
	name = "‘æ225©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ76©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 505 }
	location = 1488
	division = {
	id = { type = 19501 id = 506 }
	name = "‘æ226©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 507 }
	name = "‘æ227©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 508 }
	name = "‘æ228©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ77©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 509 }
	location = 1428
	division = {
	id = { type = 19501 id = 510 }
	name = "‘æ229©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 511 }
	name = "‘æ230©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 512 }
	name = "‘æ231©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	experience = 0
	##locked = yes
	}
}
###ª’†‰›ƒAƒWƒAŒRŠÇ‹æ
landunit = {
	name = "‘æ78©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 513 }
	location = 1418
	division = {
	id = { type = 19501 id = 514 }
	name = "‘æ232©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 515 }
	name = "‘æ233©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 516 }
	name = "‘æ234©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 50
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ79©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 517 }
	location = 1418
	division = {
	id = { type = 19501 id = 518 }
	name = "‘æ235©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 519 }
	name = "‘æ236©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 520 }
	name = "‘æ237©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 50
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ80©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 521 }
	location = 1562
	division = {
	id = { type = 19501 id = 522 }
	name = "‘æ238©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 523 }
	name = "‘æ239©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 524 }
	name = "‘æ240©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ81©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 525 }
	location = 1562
	division = {
	id = { type = 19501 id = 526 }
	name = "‘æ241©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 527 }
	name = "‘æ242©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 528 }
	name = "‘æ243©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ82©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 529 }
	location = 1562
	division = {
	id = { type = 19501 id = 530 }
	name = "‘æ244©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 531 }
	name = "‘æ245©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 532 }
	name = "‘æ246©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	##locked = yes
	}
}
###ªƒVƒxƒŠƒAŒRŠÇ‹æ
landunit = {
	name = "‘æ42íÔt’c"
	id = { type = 19501 id = 185 }
	location = 1523
	division = {
	id = { type = 19501 id = 186 }
	name = "‘æ139íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 187 }
	name = "‘æ140íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 188 }
	name = "‘æ141íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
  }
landunit = {
	name = "‘æ43íÔt’c"
	id = { type = 19501 id = 189 }
	location = 1384
	division = {
	id = { type = 19501 id = 190 }
	name = "‘æ142íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 191 }
	name = "‘æ143íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 192 }
	name = "‘æ144íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
  }
landunit = {
	name = "‘æ44íÔt’c"
	id = { type = 19501 id = 193 }
	location = 1412
	division = {
	id = { type = 19501 id = 194 }
	name = "‘æ145íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 195 }
	name = "‘æ146íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 196 }
	name = "‘æ147íÔ˜A‘à"
	type = light_armor
	model = 11
	strength = 75
	experience = 0
	##locked = yes
	}
  }
landunit = {
	name = "‘æ83©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 533 }
	location = 1520
	division = {
	id = { type = 19501 id = 534 }
	name = "‘æ247©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 535 }
	name = "‘æ248©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 536 }
	name = "‘æ249©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 50
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ84©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 537 }
	location = 1384
	division = {
	id = { type = 19501 id = 538 }
	name = "‘æ250©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 539 }
	name = "‘æ251©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 50
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 540 }
	name = "‘æ252©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 50
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ85©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 541 }
	location = 1412
	division = {
	id = { type = 19501 id = 542 }
	name = "‘æ253©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 543 }
	name = "‘æ254©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 544 }
	name = "‘æ255©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ86©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 545 }
	location = 1522
	division = {
	id = { type = 19501 id = 546 }
	name = "‘æ256©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 547 }
	name = "‘æ257©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 548 }
	name = "‘æ258©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ87©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 549 }
	location = 1413
	division = {
	id = { type = 19501 id = 550 }
	name = "‘æ259©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 551 }
	name = "‘æ260©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 552 }
	name = "‘æ261©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ88©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 553 }
	location = 1413
	division = {
	id = { type = 19501 id = 554 }
	name = "‘æ262©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 555 }
	name = "‘æ263©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 556 }
	name = "‘æ264©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ89©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 557 }
	location = 1413
	division = {
	id = { type = 19501 id = 558 }
	name = "‘æ265©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 559 }
	name = "‘æ266©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 560 }
	name = "‘æ267©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 23
	strength = 25
	experience = 0
	##locked = yes
	}
}
###ªƒUƒoƒCƒJƒ‹ŒRŠÇ‹æ
landunit = {
	name = "‘æ45íÔt’c"
	id = { type = 19501 id = 197 }
	location = 1366
	division = {
	id = { type = 19501 id = 198 }
	name = "‘æ148íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 199 }
	name = "‘æ149íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 200 }
	name = "‘æ150íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
  }
landunit = {
	name = "‘æ90©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 561 }
	location = 1366
	division = {
	id = { type = 19501 id = 562 }
	name = "‘æ268©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 563 }
	name = "‘æ269©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 564 }
	name = "‘æ270©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ91©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 565 }
	location = 1525
	division = {
	id = { type = 19501 id = 566 }
	name = "‘æ271©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 567 }
	name = "‘æ272©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 568 }
	name = "‘æ273©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ92©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 569 }
	location = 1526
	division = {
	id = { type = 19501 id = 570 }
	name = "‘æ274©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 1
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 571 }
	name = "‘æ275©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 1
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 572 }
	name = "‘æ276©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ93©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 573 }
	location = 1528
	division = {
	id = { type = 19501 id = 574 }
	name = "‘æ280©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 1
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 575 }
	name = "‘æ281©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 1
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 576 }
	name = "‘æ282©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ94©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 577 }
	location = 1175
	division = {
	id = { type = 19501 id = 578 }
	name = "‘æ283©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 579 }
	name = "‘æ284©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 580 }
	name = "‘æ285©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ95©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 581 }
	location = 1370
	division = {
	id = { type = 19501 id = 582 }
	name = "‘æ286©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 583 }
	name = "‘æ287©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 584 }
	name = "‘æ288©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ96©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 585 }
	location = 1369
	division = {
	id = { type = 19501 id = 586 }
	name = "‘æ289©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 587 }
	name = "‘æ290©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 588 }
	name = "‘æ291©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ97©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 589 }
	location = 1372
	division = {
	id = { type = 19501 id = 590 }
	name = "‘æ292©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 591 }
	name = "‘æ293©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 592 }
	name = "‘æ294©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ98©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 593 }
	location = 1172
	division = {
	id = { type = 19501 id = 594 }
	name = "‘æ295©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 595 }
	name = "‘æ296©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 596 }
	name = "‘æ297©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ99©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 597 }
	location = 1522
	division = {
	id = { type = 19501 id = 598 }
	name = "‘æ298©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 599 }
	name = "‘æ299©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 600 }
	name = "‘æ300©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ100©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 601 }
	location = 1529
	division = {
	id = { type = 19501 id = 602 }
	name = "‘æ301©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 603 }
	name = "‘æ302©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 604 }
	name = "‘æ303©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ101©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 605 }
	location = 1529
	division = {
	id = { type = 19501 id = 606 }
	name = "‘æ304©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 607 }
	name = "‘æ305©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 608 }
	name = "‘æ306©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ102©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 609 }
	location = 1529
	division = {
	id = { type = 19501 id = 610 }
	name = "‘æ307©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 611 }
	name = "‘æ308©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 612 }
	name = "‘æ309©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ103©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 613 }
	location = 1167
	division = {
	id = { type = 19501 id = 614 }
	name = "‘æ310©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 615 }
	name = "‘æ311©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 616 }
	name = "‘æ312©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ104©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 617 }
	location = 1520
	division = {
	id = { type = 19501 id = 618 }
	name = "‘æ313©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 619 }
	name = "‘æ314©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 620 }
	name = "‘æ315©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ105©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 621 }
	location = 1170
	division = {
	id = { type = 19501 id = 622 }
	name = "‘æ316©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 623 }
	name = "‘æ317©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 624 }
	name = "‘æ318©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ106©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 625 }
	location = 1522
	division = {
	id = { type = 19501 id = 626 }
	name = "‘æ319©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 627 }
	name = "‘æ320©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 628 }
	name = "‘æ321©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ107©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 629 }
	location = 1526
	division = {
	id = { type = 19501 id = 630 }
	name = "‘æ322©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 631 }
	name = "‘æ323©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 632 }
	name = "‘æ324©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}
landunit = {
	name = "‘æ108©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 633 }
	location = 1368
	division = {
	id = { type = 19501 id = 634 }
	name = "‘æ325©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 635 }
	name = "‘æ326©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 636 }
	name = "‘æ327©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}

landunit = {
	name = "‘æ109©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 637 }
	location = 1368
	division = {
	id = { type = 19501 id = 638 }
	name = "‘æ328©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 639 }
	name = "‘æ329©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 640 }
	name = "‘æ330©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}
###ª‹É“ŒŒRŠÇ‹æ
landunit = {
	name = "‘æ46íÔt’c"
	id = { type = 19501 id = 201 }
	location = 1404
	division = {
	id = { type = 19501 id = 202 }
	name = "‘æ151íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 203 }
	name = "‘æ152íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 204 }
	name = "‘æ153íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	##locked = yes
	}
  }
landunit = {
	name = "‘æ110©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 641 }
	location = 1420
	division = {
	id = { type = 19501 id = 642 }
	name = "‘æ331©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 643 }
	name = "‘æ332©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 644 }
	name = "‘æ333©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}

landunit = {
	name = "‘æ111©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19501 id = 645 }
	location = 1385
	division = {
	id = { type = 19501 id = 646 }
	name = "‘æ334©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 647 }
	name = "‘æ335©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	strength = 25
	experience = 0
	##locked = yes
	}
	division = {
	id = { type = 19501 id = 648 }
	name = "‘æ336©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	strength = 25
	experience = 0
	##locked = yes
	}
}
####ªƒ‚ƒ“ƒSƒ‹’“—¯ŒR
####«ŠCŒR
navalunit = {
	name = "–k•ûŠÍ‘à"
	id = { type = 19502 id = 23227 }
	location = 133
	base = 133
	division = {
	id = { type = 19502 id = 23229 }
	name = "ƒAƒŒƒNƒTƒ“ƒhƒ‹¥ƒlƒtƒXƒL["
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 23230 }
	name = "ƒ€ƒ‹ƒ}ƒ“ƒXƒN"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 23231 }
	name = "ƒ”ƒBƒcƒFƒAƒhƒ~ƒ‰[ƒ‹¥ƒhƒ[ƒXƒg"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 19502 id = 23232 }
	name = "ƒNƒƒ“ƒVƒ…ƒ^ƒbƒg"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 19502 id = 23233 }
	name = "ƒAƒhƒ~ƒ‰ƒ‹¥ƒCƒTƒRƒt"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 19502 id = 23234 }
	name = "ƒAƒhƒ~ƒ‰ƒ‹¥ƒiƒqƒ‚ƒt"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 19502 id = 23235 }
	name = "ƒAƒhƒ~ƒ‰ƒ‹¥ƒ}ƒJƒƒt"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 19502 id = 23236 }
	name = "ƒXƒgƒ[ƒCƒkƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 23237 }
	name = "ƒŒƒV[ƒeƒŠƒkƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 23238 }
	name = "ƒIƒ_ƒŠƒ‡[ƒ“ƒkƒC"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "•ŠCŠÍ‘à"
	id = { type = 19502 id = 33227 }
	location = 253
	base = 253
	division = {
	id = { type = 19502 id = 33229 }
	name = "ƒWƒFƒ‹ƒWƒ“ƒXƒL["
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33230 }
	name = "ƒAƒhƒ~ƒ‰ƒ‹¥ƒEƒVƒƒƒRƒt"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33231 }
	name = "ƒ~ƒnƒCƒ‹¥ƒNƒgƒD[ƒ]ƒt"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33232 }
	name = "ƒAƒhƒ~ƒ‰ƒ‹¥ƒSƒƒtƒR"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33233 }
	name = "ƒRƒ€ƒ\ƒ‚[ƒŒƒcEƒEƒNƒ‰ƒC[ƒkƒB"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33234 }
	name = "ƒ\ƒIƒuƒ‰ƒW[ƒeƒŠƒkƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33235 }
	name = "ƒvƒƒ”ƒH[ƒ‹ƒkƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33236 }
	name = "ƒIƒgƒ”ƒ@[ƒWƒ…ƒkƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33237 }
	name = "ƒNƒ‰[ƒXƒkƒC¥ƒJƒtƒJ[ƒX"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33238 }
	name = "ƒXƒ€ƒBƒVƒ…ƒŠƒ‡[ƒkƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33239 }
	name = "ƒXƒƒgƒŠ[ƒ”ƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33240 }
	name = "ƒNƒ‰[ƒXƒkƒC¥ƒNƒ‹ƒB[ƒ€"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 33241 }
	name = "ƒXƒR[ƒ‹ƒC"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "‘¾•½—mŠÍ‘à"
	id = { type = 19502 id = 43227 }
	location = 1372
	base = 1372
	division = {
	id = { type = 19502 id = 43229 }
	name = "ƒAƒhƒ~ƒ‰ƒ‹¥ƒ‰ƒUƒŒƒt"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 43230 }
	name = "ƒAƒŒƒNƒTƒ“ƒhƒ‹¥ƒXƒ”ƒH[ƒƒt"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 43231 }
	name = "ƒAƒhƒ~ƒ‰ƒ‹¥ƒZƒjƒƒ[ƒ”ƒBƒ“"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 43232 }
	name = "ƒhƒ~ƒgƒŠ[¥ƒ|ƒWƒƒƒ‹ƒXƒL"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 43233 }
	name = "ƒEƒ‰ƒWƒIƒXƒgƒN"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 43234 }
	name = "ƒZƒ”ƒ@ƒXƒgƒ|ƒŠ"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 43235 }
	name = "ƒXƒgƒ[ƒMƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 43236 }
	name = "ƒXƒ|ƒ\[ƒuƒkƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 43237 }
	name = "ƒXƒeƒŒƒO[ƒVƒ`ƒC"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "ƒoƒ‹ƒgŠÍ‘à"
	id = { type = 19502 id = 127 }
	location = 510
	base = 510
	division = {
	id = { type = 19502 id = 129 }
	name = "ƒXƒ”ƒFƒ‹ƒhƒƒt"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 130 }
	name = "ƒIƒ‹ƒWƒ‡ƒjƒL[ƒ["
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 131 }
	name = "ƒWƒ‡ƒ_ƒmƒt"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 132 }
	name = "ƒ‚ƒƒgƒtƒXƒN"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 19502 id = 133 }
	name = "ƒOƒƒYƒkƒC"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 134 }
	name = "ƒAƒhƒ~ƒ‰ƒ‹¥ƒ]ƒY[ƒŠƒƒ"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 19502 id = 135 }
	name = "ƒIƒuƒ‰ƒXƒcƒH[ƒ”ƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 136 }
	name = "ƒXƒ‰[ƒ”ƒkƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 137 }
	name = "ƒXƒ[ƒ‹ƒC"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 19502 id = 138 }
	name = "ƒIƒOƒlƒ”ƒH[ƒC"
	type = destroyer
	model = 1
	experience = 0
	}
  }
}
