
##############################
# Country definition for BRA #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = TEX
  energy              = 5000
  metal               = 5000
  rare_materials      = 5000
  oil                 = 5000
  supplies            = 80000
  manpower            = 156
  transports          = 24
  escorts             = 6
  capital             = 874
  transports          = 50
  escorts             = 20
  money               = 350
  regular_id = U08
  nationalprovinces   = { 874 }
  ownedprovinces      = { 874 }
  controlledprovinces = { 874 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080
                        }
  policy              = { democratic = 3 political_left = 4 freedom = 3 free_market = 7 professional_army = 6 defense_lobby = 7 interventionism = 6 }
}
