
##############################
# Country definition for U02 #
##############################

province =
{ id            = 5
  anti_air      = 4
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 4 current_size = 4 }
}                 # カークウォール
province =
{ id            = 8
  anti_air      = 2
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 8 current_size = 8 }
}                 # グラスゴー
province = { id = 9 } # ダンフリーズ
province = { id = 10 } # サンダーランド
province =
{ id       = 11
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ハル
province =
{ id            = 12
  anti_air      = 4
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 8 current_size = 8 }
}                 # マンチェスター
province = { id = 13 anti_air = 2 } # シェフィールド
province = { id = 14 anti_air = 2 } # バーミンガム
province = { id = 15 ic = 4 } # カーディフ
province =
{ id            = 17
  anti_air      = 4
  ic            = 5
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 2 current_size = 2 }
}                 # ノリッジ
province = { id = 19 anti_air = 3 ic = 7 } # ロンドン
province =
{ id            = 20
  anti_air      = 5
  ic            = 3
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 4 current_size = 4 }
  coastalfort   = 3
}                 # ドーバー
province =
{ id         = 21
  anti_air   = 6
  ic         = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # ポーツマス
province = { id = 22 } # ブリストル
province =
{ id         = 23
  anti_air   = 6
  ic         = 5
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # プリマス
province =
{ id         = 25
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # コーク
province =
{ id         = 28
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
  oilpool    = 1000
  supplypool = 2000
}              # ベルファスト
province =
{ id       = 29
  air_base = { size = 2 current_size = 2 }
}            # ロンドンデリー
province =
{ id         = 30
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
}              # ダブリン
province =
{ id          = 31
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 4 current_size = 4 }
  coastalfort = 1
  oilpool     = 1000
  supplypool  = 1000
}               # マルタ島
province =
{ id         = 32
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # ブレスト
province =
{ id         = 34
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
}              # ロリアン
province =
{ id         = 35
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
}              # ナント
province =
{ id         = 38
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # シェルブール
province = { id = 39 anti_air = 1 } # カーン
province =
{ id       = 44
  air_base = { size = 4 current_size = 4 }
  anti_air = 1
}            # リール
province =
{ id         = 46
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
}              # ロッテルダム
province =
{ id         = 47
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 10 current_size = 10 }
  landfort   = 1
}              # アムステルダム
province =
{ id         = 48
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
}              # ミデルブルフ
province = { id = 49 anti_air = 2 } # アイントホーフェン
province =
{ id       = 56
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}            # パリ
province =
{ id         = 59
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # ボルドー
province =
{ id       = 60
  air_base = { size = 4 current_size = 4 }
}            # ポワチエ
province =
{ id       = 62
  air_base = { size = 4 current_size = 4 }
}            # オルレアン
province =
{ id            = 67
  anti_air      = 3
  air_base      = { size = 2 current_size = 2 }
}                 # エッセン
province =
{ id       = 72
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  landfort = 10
}            # メス
province = { id = 73 anti_air = 2 landfort = 10 } # ストラスブール
province = { id = 76 anti_air = 2 } # デュッセルドルフ
province =
{ id         = 80
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # ヴィルヘルムスハーフェン
province =
{ id       = 81
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ミュンスター
province =
{ id       = 82
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # カッセル
province =
{ id         = 87
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 8 current_size = 8 }
}              # ブレーメン
province =
{ id         = 88
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
}              # ハンブルク
province = { id = 89 anti_air = 1 } # リューベック
province =
{ id         = 90
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # キール
province =
{ id            = 93
  anti_air      = 2
  naval_base    = { size = 6 current_size = 6 }
  air_base      = { size = 2 current_size = 2 }
  coastalfort   = 3
}                 # マルメ
province =
{ id       = 97
  air_base = { size = 2 current_size = 2 }
}            # カルマル
province =
{ id          = 98
  anti_air    = 2
  landfort    = 1
  coastalfort = 3
  naval_base  = { size = 4 current_size = 4 }
  air_base    = { size = 2 current_size = 2 }
}               # イェーテボリ
province = { id = 100 } # リンシェーピング
province =
{ id            = 101
  anti_air      = 2
  naval_base    = { size = 6 current_size = 6 }
  air_base      = { size = 4 current_size = 4 }
  coastalfort   = 3
}                 # ストックホルム
province = { id = 104 } # フレドリクスタ
province =
{ id       = 105
  air_base = { size = 2 current_size = 2 }
}            # オレブロ
province = { id = 106 landfort = 1 } # カールシュタット
province =
{ id          = 107
  anti_air    = 2
  naval_base  = { size = 6 current_size = 6 }
  air_base    = { size = 4 current_size = 4 }
  coastalfort = 3
}               # オスロ
province =
{ id         = 108
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # クリスチャンサン
province =
{ id       = 109
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # スタヴァンゲル
province =
{ id            = 113
  air_base      = { size = 2 current_size = 2 }
}                 # イェヴレ
province =
{ id          = 118
  coastalfort = 2
  anti_air    = 1
  naval_base  = { size = 2 current_size = 2 }
  air_base    = { size = 2 current_size = 2 }
}               # トロンハイム
province =
{ id         = 124
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # ボードー
province =
{ id       = 127
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  landfort = 3
}            # ルーレオ
province =
{ id          = 129
  anti_air    = 2
  naval_base  = { size = 4 current_size = 4 }
  air_base    = { size = 2 current_size = 2 }
  coastalfort = 3
}               # ベルゲン
province =
{ id       = 137
  air_base = { size = 4 current_size = 4 }
}            # オウル
province =
{ id       = 139
  anti_air = 2
  air_base = { size = 8 current_size = 8 }
}            # タンペレ
province =
{ id          = 141
  coastalfort = 1
  anti_air    = 2
  naval_base  = { size = 6 current_size = 6 }
  air_base    = { size = 4 current_size = 4 }
}               # トゥルク
province =
{ id          = 142
  coastalfort = 1
  anti_air    = 3
  naval_base  = { size = 4 current_size = 4 }
  air_base    = { size = 8 current_size = 8 }
}               # ヘルシンキ
province =
{ id       = 195
  air_base = { size = 5 current_size = 5 }
}            # クレサーレ
province =
{ id         = 197
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # リガ
province =
{ id         = 205
  anti_air   = 1
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
}              # リエパーヤ
province =
{ id       = 207
  air_base = { size = 2 current_size = 2 }
}            # カウナス
province = { id = 208 anti_air = 1 } # ブィドゴシュチュ
province =
{ id       = 209
  air_base = { size = 2 current_size = 2 }
  anti_air = 1
}            # グロドゥナ
province = { id = 211 anti_air = 1 } # カリシュ
province =
{ id       = 214
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ビリニュス
province =
{ id       = 294
  air_base = { size = 5 current_size = 5 }
}            # コペンハーゲン
province =
{ id       = 296
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ロストック
province =
{ id       = 298
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # マグデブルク
province =
{ id       = 300
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # ベルリン
province =
{ id            = 302
  anti_air      = 1
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 4 current_size = 4 }
}                 # シュテッティン
province =
{ id         = 303
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
}              # ダンツィヒ
province =
{ id         = 304
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # エルビンク
province = { id = 305 anti_air = 1 } # プウォツク
province =
{ id         = 306
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # グディニャ
province = { id = 307 anti_air = 1 } # トルン
province = { id = 308 anti_air = 2 landfort = 2 } # メーゼリッツ
province =
{ id              = 310
  anti_air        = 1
  air_base        = { size = 4 current_size = 4 }
}                   # ライプツィヒ
province =
{ id       = 312
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ニュルンベルク
province =
{ id       = 313
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # フランクフルト・アム・マイン
province =
{ id       = 314
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # シュッツトガルト
province = { id = 316 anti_air = 2 landfort = 10 } # ミュールーズ
province =
{ id       = 317
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # エピナル
province =
{ id       = 330
  air_base = { size = 2 current_size = 2 }
}            # サラゴサ
province =
{ id         = 331
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 2 current_size = 2 }
}              # ビルバオ
province =
{ id       = 333
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ブルゴス
province =
{ id         = 334
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 2 current_size = 2 }
}              # ラコルニャ
province =
{ id         = 335
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # オポルト
province =
{ id         = 336
  anti_air   = 4
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # リスボン
province =
{ id       = 341
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # マドリッド
province =
{ id       = 342
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # トレド
province =
{ id       = 347
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # セヴィーリャ
province =
{ id         = 348
  anti_air   = 6
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  landfort   = 6
  oilpool    = 1000
  supplypool = 1000
}              # ジブラルタル
province =
{ id          = 352
  anti_air    = 2
  naval_base  = { size = 4 current_size = 4 }
  air_base    = { size = 2 current_size = 2 }
  coastalfort = 3
}               # ムルシア
province =
{ id       = 354
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # バレンシア
province =
{ id         = 357
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # バルセロナ
province =
{ id       = 359
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # トゥールーズ
province =
{ id       = 360
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ヴィシー
province =
{ id         = 364
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # マルセイユ
province =
{ id          = 365
  anti_air    = 5
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 3
  coastalfort = 2
}               # トゥーロン
province = { id = 366 landfort = 3 } # ニース
province =
{ id         = 368
  landfort   = 5
  anti_air   = 3
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 4 current_size = 4 }
}              # ジェノヴァ
province =
{ id       = 370
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # ミラノ
province = { id = 372 landfort = 4 anti_air = 3 } # ルガーノ
province =
{ id       = 376
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ミュンヘン
province =
{ id         = 378
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # ヴェネティア
province =
{ id       = 382
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ザグレブ
province =
{ id         = 384
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # スプリット
province =
{ id       = 385
  anti_air = 1
  air_base = { size = 1 current_size = 1 }
}            # サラエヴォ
province = { id = 388 anti_air = 2 } # ドブロブニク
province =
{ id         = 389
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
}              # ツェティニェ
province =
{ id         = 396
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # イラクリオン
province =
{ id         = 398
  landfort   = 2
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # カリムノス
province =
{ id         = 399
  landfort   = 2
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # ロードス
province =
{ id         = 401
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # アテネ
province = { id = 410 landfort = 5 anti_air = 2 } # コモティニ
province =
{ id         = 411
  landfort   = 5
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # テッサロニキ
province =
{ id       = 424
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ブカレスト
province =
{ id       = 428
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # クルジュナポカ
province =
{ id       = 431
  anti_air = 3
  air_base = { size = 2 current_size = 2 }
}            # プロエスティ
province =
{ id       = 433
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ヤシ
province =
{ id       = 435
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # イスマイル
province =
{ id         = 436
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # コンスタンツァ
province =
{ id       = 444
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ニコシア
province =
{ id       = 453
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # ベオグラード
province =
{ id       = 456
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ペーチ
province =
{ id       = 473
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ブレスラウ
province =
{ id       = 479
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # クラクフ
province = { id = 480 anti_air = 1 } # チェンストホーヴァ
province =
{ id       = 481
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ウッチ
province = { id = 483 anti_air = 2 } # ポズナン
province =
{ id       = 485
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
}            # ワルシャワ
province = { id = 486 anti_air = 2 } # カトヴィツェ
province =
{ id       = 487
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ルブリン
province =
{ id       = 495
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ティムショハラ
province =
{ id       = 497
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # デブレツェン
province =
{ id       = 501
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # リヴォフ
province =
{ id       = 503
  anti_air = 2
  landfort = 1
  air_base = { size = 4 current_size = 4 }
}            # ブレスト・リフトスク
province = { id = 505 anti_air = 1 } # ビェルスク
province =
{ id       = 507
  air_base = { size = 2 current_size = 2 }
}            # スタニスラオ
province = { id = 509 anti_air = 1 } # スヴァウキ
province = { id = 512 anti_air = 1 } # ボローニャ
province = { id = 513 anti_air = 1 } # フィレンツェ
province =
{ id       = 515
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ローマ
province = { id = 519 } # ラティーナ
province =
{ id       = 520
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # フォッジア
province =
{ id            = 521
  anti_air      = 2
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 6 current_size = 6 }
}                 # ナポリ
province =
{ id         = 523
  anti_air   = 1
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 6 current_size = 6 }
}              # ターラント
province =
{ id         = 525
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 10 current_size = 10 }
}              # パレルモ
province = { id = 527 landfort = 3 } # グルノーブル
province =
{ id       = 530
  landfort = 5
  anti_air = 3
  air_base = { size = 2 current_size = 2 }
}            # ジュネーヴ
province = { id = 531 landfort = 5 anti_air = 3 } # トリノ
province =
{ id       = 532
  anti_air = 5
  air_base = { size = 4 current_size = 4 }
  landfort = 5
}            # ベルン
province =
{ id       = 533
  landfort = 5
  anti_air = 3
  air_base = { size = 2 current_size = 2 }
}            # チューリッヒ
province =
{ id         = 534
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
}              # カリャリ
province =
{ id         = 538
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 500
}              # ハミルトン
province =
{ id         = 542
  anti_air   = 1
  naval_base = { size = 6 current_size = 6 }
}              # リヴォルノ
province =
{ id         = 545
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # サッサリ
province =
{ id       = 546
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # フランクフルト・アン・デア・オーダー
province =
{ id       = 652
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ナッソー
province =
{ id         = 666
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
}              # トリエステ
province =
{ id         = 801
  anti_air   = 1
  naval_base = { size = 1 current_size = 1 }
  oilpool    = 100
  supplypool = 500
}              # ウィレムスタッド
province =
{ id         = 866
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 200
}              # スタンレー
province =
{ id       = 873
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ジョージタウン
province = { id = 875 oilpool = 100 supplypool = 100 } # カイエンヌ
province =
{ id         = 899
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  supplypool = 100
  oilpool    = 100
}              # フォール＝ド＝フランス
province =
{ id       = 957
  air_base = { size = 5 current_size = 5 }
}            # セウタ
province =
{ id       = 962
  air_base = { size = 2 current_size = 2 }
}            # サラマンカ
province = { id = 965 } # コヴィリャン
province =
{ id         = 1157
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 2 current_size = 2 }
}              # カディス
province = { id = 1160 } # トゥルーロ
province =
{ id         = 1166
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # エディンバラ
province =
{ id         = 1409
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
}              # スウォンジ
province =
{ id       = 1595
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # グリヴィツェ
province =
{ id         = 1609
  naval_base = { size = 1 current_size = 1 }
}              # スバ
province =
{ id         = 1692
  anti_air   = 2
  naval_base = { size = 1 current_size = 1 }
  oilpool    = 100
  supplypool = 100
}              # ヌメア
province =
{ id       = 1720
  air_base = { size = 5 current_size = 5 }
}            # セント・ヘリア
province = { id = 2245 } # カーライル

#####################
# Country main data #
#####################

country =
{ tag                 = U02
  manpower            = 4250
  energy              = 58000
  metal               = 36000
  rare_materials      = 45000
  oil                 = 12000
  supplies            = 8000
  money               = 3500
  capital             = 28
  transports          = 1800
  escorts             = 1500
  regular_id          = U06
  ##nationalidentity    = "policy_identity_defensive"
  ##socialpolicy        = "policy_social_militaristic"
  #nationalculture     = "policy_culture_libertarian"
  nationalprovinces   = { 45   50   51   52   65   68   69   70   80   81   82   83   85   86   87   88   89   90   312  313  314  315  375  376  374 
                          76   67   75   74   66   547  970  989  1014 1015 1016 1018 1405 56   316  73   72   44   43   18   366  527  367  529  365 
                          364  363  362  358  328  327  326  325  324  359  361  322  323  59   60   61   62   63   318  317  64   54   42   55   41  
                          57   58   32   33   34   35   36   37   38   39   40   320  321  528  319  360  1022 1643 1676 2242 2509 2514 2555 2557 567 
                          581  841  875  898  899  1135 1691 1692 1752 1761 1769 1770 515  525  526  534  544  545  524  523  522  521  520  519  518 
                          517  516  542  543  513  514  512  379  369  368  531  370  371  378  666  668  1408 71   46   47   77   78   79   1019 49  
                          48   1082 801  561  10   11   12   13   14   16   17   19   20   21   22   23   1160 1164 1720 2245 3    5    6    7    8   
                          9    1165 1166 15   1409 28   29   348  538  573  584  587  795  866  896  1147 1148 394  395  401  396  398  399  402  403 
                          393  410  411  412  392  400  405  563  653  2319 2321 335  336  337  344  345  965  1163 1563 1036 1867 332  333  334  338 
                          339  340  341  342  343  346  347  349  350  351  352  353  354  355  356  357  536  537  1726 1161 1531 1714 1734 329  330 
                          331  535  961  962  963  964  1157 1162 1532 1537 2243 2244 954  957  373  377  460  461  462  463  464  465  2327 2328 2329
                          84   298  299  300  301  296  297  310  309  311  546  27   26   25   24   30   93   99   98   97   96   100  101  106  105 
                          119  115  113  121  126  127  2    91   92   120  122  292  293  294  295  800  103  141  142  140  138  139  137  131  130 
                          132  136  148  147  144  149  193  194  195  196  199  1886 203  204  205  197  198  202  206  207  511  577  214  2606 211 
                          222  479  480  481  484  485  486  487  488  489  504  1876 304  308  473  482  1400 1595 1623 1811 208  303 
                          305  306  307  483  505  508  509  1875 1884 31   444  470  469  468  471  472  466  467  474  475  53   1888 476  477  478 
                          490  1887 1889 224  456  457  458  491  492  497  1890 2447 419  420  422  421  417  416  1911 2323 2324 424  425  431  426 
                          432  436  433  2603 2450 2449 2604 1402 423  428  498  1403 1899 427  429  430  495  496  1449 2602 291  380  382  383  384 
                          385  386  387  388  389  413  414  415  451  452  453  454  455  459  493  494  1057 1168 1169 1891 1892 1893 1894 1895
                          1896 1897 381  2325 2326 1    390  391  664  665  530  532  533  372  104  107  108  109  110  111  112  114  116  117  118 
                          124  125  128  129  871  873  874  223  510  95   209  213  435  434  2605 230  1401 1173 507  500  499  501  229  502  506 
                          1885 562  503  102  210  45
                        }
  ownedprovinces      = { }
  controlledprovinces = { }
  techapps            = { 10050 10060 10070 10080 10090 1010  10150 10160 10190 1020  10200 10210 10220 1030  1040  10440 10490 1050  1110  1120 
                          1130  1140  1150  1210  1220  1230  1240  1250  1470  1490  1510  1530  1550  1560  1570  1580  1590  1650  1660  1670 
                          1680  1690  1750  1760  1770  1780  1790  1850  1860  1870  1950  1960  1970  1980  2010  2020  20210 20220 2030  20310
                          20320 2040  20410 2050  20510 20520 2060  2070  2080  2310  2320  2330  2610  2620  2630  2640  2650  2660  2910  2920 
                          2930  2940  2950  2960  3010  3020  3030  3040  30410 30420 30430 30440 30450 3050  30510 30520 30530 30540 30550 3110 
                          3120  3130  3140  3150  3210  3220  3230  3240  3250  3310  3320  3330  3340  3350  3410  3460  3470  3480  3490  3500 
                          3560  3570  3610  3620  3630  3640  3650  3710  3720  3730  3740  3750  3810  3820  3830  3840  3850  3910  3920  3930 
                          3940  3950  3960  40100 40110 40120 40130 40200 40210 40220 40230 4390  4400  4410  4420  4430  4480  4490  4500  4510 
                          4560  4570  4580  50020 50030 50040 50050 50070 50080 50090 5010  50100 50110 50120 5020  50290 5030  50300 50310 5040 
                          5090  5100  5110  5120  5170  5180  5190  5200  5250  5260  5270  5280  5330  5340  5350  5360  5370  5410  5420  5430 
                          5460  5490  5500  5600  5610  5620  5630  5680  5690  5760  5770  5780  5790  5800  5810  5820  5830  5840  5850  5860 
                          5910  5920  5930  5940  5950  6010  6030  6060  6740  6750  6760  6770  6780  6790  7010  7500  7510  7520  7530  7670 
                          7680  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9560  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990 
                        }
  inventions          = { }
  policy =
  { democratic        = 10
    political_left    = 2
    freedom           = 9
    free_market       = 9
    professional_army = 9
    defense_lobby     = 10
    interventionism   = 9
  }
}
