
##############################
# Country definition for U12 #
##############################

province = { id = 1431 air_base = 10 infra = 2.0 } # ö\èY

#####################
# Country main data #
#####################

country =
{ tag                 = U12
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 1431
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 1431 }
  ownedprovinces      = { 1431 }
  controlledprovinces = { 1431 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 500 supplies = 1000 }
  landunit =
  { id       = { type = 15001 id = 5177 }
    name     = "ëÊ1åRíc"
    location = 1431
    division =
    { id            = { type = 15001 id = 5179 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5180 }
    name     = "ëÊ2åRíc"
    location = 1431
    division =
    { id            = { type = 15001 id = 5182 }
      name          = "ëÊ2BETAåQ"
      model         = 33
      type          = hq
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5183 }
    name     = "ëÊ3åRíc"
    location = 1431
    division =
    { id            = { type = 15001 id = 5185 }
      name          = "ëÊ3BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5186 }
    name     = "ëÊ4åRíc"
    location = 1431
    division =
    { id            = { type = 15001 id = 5188 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      type          = marine
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5189 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5190 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      type          = infantry
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5191 }
      name          = "ëÊ2BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5192 }
      name          = "ëÊ3BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5193 }
    name     = "ëÊ5åRíc"
    location = 1431
    division =
    { id            = { type = 15001 id = 5195 }
      name          = "ëÊ2BETAåQ"
      model         = 33
      type          = marine
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5196 }
      name          = "ëÊ2BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5197 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      type          = infantry
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5198 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5199 }
      name          = "ëÊ6BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5200 }
    name     = "ëÊ6åRíc"
    location = 1431
    division =
    { id            = { type = 15001 id = 5202 }
      name          = "ëÊ3BETAåQ"
      model         = 33
      type          = marine
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5203 }
      name          = "ëÊ3BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5204 }
      name          = "ëÊ7BETAåQ"
      model         = 33
      type          = infantry
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5205 }
      name          = "ëÊ8BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5206 }
      name          = "ëÊ9BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5207 }
    name     = "ëÊ7åRíc"
    location = 1431
    division =
    { id            = { type = 15001 id = 5209 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      type          = marine
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5210 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5211 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      type          = infantry
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5212 }
      name          = "ëÊ11BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5213 }
      name          = "ëÊ12BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5214 }
    name     = "ëÊ8åRíc"
    location = 1431
    division =
    { id            = { type = 15001 id = 5216 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      type          = marine
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5217 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5218 }
      name          = "ëÊ13BETAåQ"
      model         = 33
      type          = infantry
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5219 }
      name          = "ëÊ14BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
    }
    division =
    { id            = { type = 15001 id = 5220 }
      name          = "ëÊ15BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5221 }
    name     = "ëÊ9åRíc"
    location = 1431
    division =
    { id            = { type = 15001 id = 5223 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5224 }
    name     = "ëÊ10åRíc"
    location = 1431
    home     = 1431
    division =
    { id            = { type = 15001 id = 5226 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      type          = hq
      strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 15001 id = 5227 }
    name     = "ëÊ11åRíc"
    location = 1431
    home     = 1431
    division =
    { id            = { type = 15001 id = 5229 }
      name          = "ëÊ6BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100.0000
    }
  }
    landunit =
    { id       = { type = 15001 id = 1 }
      name     = "ÉJÉVÉÖÉKÉãÉnÉCÉî"
      location = 1431
      division =
      { type   = garrison
        model  = 11
        id     = { type = 15004 id = 1 }
        name   = "ÉJÉVÉÖÉKÉãÉnÉCÉî"
        locked = yes
      }
      division =
      { type   = garrison
        model  = 33
        id     = { type = 15004 id = 2 }
        name   = "ñÂãâ"
        locked = yes
      }
    }
}
