
##############################
# Country definition for U03 #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = U96
  manpower            = 420
  energy              = 12000
  metal               = 18000
  rare_materials      = 15000
  oil                 = 50000
  supplies            = 80000
  money               = 1800
  capital             = 700
  regular_id          = U03
  transports          = 400
  escorts             = 300
  nationalprovinces   = { 700 }
  ownedprovinces      = { 700 }
  controlledprovinces = { 700 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080
                        }
  inventions          = { }
  policy              = { democratic = 3 political_left = 2 freedom = 3 free_market = 2 professional_army = 9 defense_lobby = 8 interventionism = 8 }
}
