
##############################
# Country definition for ISR #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = ISR
  manpower            = 600
  energy              = 4000
  metal               = 3500
  rare_materials      = 5000
  oil                 = 6000
  supplies            = 3500
  money               = 500
  capital             = 1798
  regular_id          = U06
  transports          = 350
  escorts             = 150
  policy =
  { democratic        = 10
    political_left    = 2
    freedom           = 9
    free_market       = 9
    professional_army = 9
    defense_lobby     = 10
    interventionism   = 9
  }
  ownedprovinces      = { 1795 1800 1801 404 406 1797 1798 1799 1881 }
  controlledprovinces = { 1795 1800 1801 404 406 1797 1798 1799 1881 }
  techapps            = { 10050 10060 10070 10080 10090 1010  10150 10160 10190 1020  10200 10210 10220 1030  1040  10440 10490 1050  1110  1120 
                          1130  1140  1150  1210  1220  1230  1240  1250  1470  1490  1510  1530  1550  1560  1570  1580  1590  1650  1660  1670 
                          1680  1690  1750  1760  1770  1780  1790  1850  1860  1870  1950  1960  1970  1980  2010  2020  20210 20220 2030  20310
                          20320 2040  20410 2050  20510 20520 2060  2070  2080  2310  2320  2330  2360  2370  2610  2620  2630  2640  2650  2660  2910  2920 
                          2930  2940  2950  2960  3010  3020  3030  3040  30410 30420 30430 30440 30450 3050  30510 30520 30530 30540 30550 3110 
                          3120  3130  3140  3150  3210  3220  3230  3240  3250  3310  3320  3330  3340  3350  3410  3460  3470  3480  3490  3500 
                          3560  3570  3610  3620  3630  3640  3650  3710  3720  3730  3740  3750  3810  3820  3830  3840  3850  3910  3920  3930 
                          3940  3950  3960  40100 40110 40120 40130 40200 40210 40220 40230 4390  4400  4410  4420  4430  4480  4490  4500  4510 
                          4560  4570  4580  50020 50030 50040 50050 50070 50080 50090 5010  50100 50110 50120 5020  50290 5030  50300 50310 5040 
                          5090  5100  5110  5120  5170  5180  5190  5200  5250  5260  5270  5280  5330  5340  5350  5360  5370  5410  5420  5430 
                          5460  5490  5500  5600  5610  5620  5630  5680  5690  5760  5770  5780  5790  5800  5810  5820  5830  5860 
                          5910  5920  5930  5940  5950  7010  7500  7510  7520  7530  7670 
                          7680  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9560  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990  10390 4010  4020  4030 
                          4040  4050  4110  4120  4130  4140  4150  4210  4220  4230  4240  4250
                          4640  4650  4660  4670  4680  4820  4830  4840  4850  4860  40000 40010 40020 40030 40040
                          50320 5700  5710  40140 7030  7040  7050
                          6050  6060  6070  6080  6090  6220  6230  6460  6470  6480  6800
                        }
  nationalprovinces   = { 1795 1800 1801 404 406 1797 1798 1799 1881 }
  free                = { energy = 50 manpower = 0.3 metal = 30 oil = 20 }
  inventions          = { 8006 }
  landunit =
  { id       = { type = 11521 id = 1 }
    name     = "ëÊ366ã@çbétíc"
    location = 1795
    home     = 1795
    division =
    { id            = { type = 11521 id = 2 }
      name          = "ëÊ1êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 3 }
      name          = "ëÊ2êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 4 }
      name          = "ëÊ3êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 5 }
      name          = "ëÊ1êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 6 }
      name          = "ëÊ2êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 7 }
      name          = "ëÊ3êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 11521 id = 8 }
    name     = "ëÊ162ã@çbétíc"
    location = 1795
    home     = 1795
    division =
    { id            = { type = 11521 id = 9 }
      name          = "ëÊ4êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 10 }
      name          = "ëÊ5êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 11 }
      name          = "ëÊ6êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 12 }
      name          = "ëÊ4êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 13 }
      name          = "ëÊ5êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 14 }
      name          = "ëÊ6êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 11521 id = 15 }
    name     = "ñkï˚åRícéióﬂïî"
    location = 1795
    home     = 1795
    division =
    { id            = { type = 11521 id = 16 }
      name          = "ñkï˚åRícéióﬂïî"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 11521 id = 17 }
    name     = "íÜâõåRícéióﬂïî"
    location = 1881
    home     = 1881
    division =
    { id            = { type = 11521 id = 18 }
      name          = "íÜâõåRícéióﬂïî"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 11521 id = 19 }
    name     = "ëÊ36ã@çbétíc"
    location = 1881
    home     = 1881
    division =
    { id            = { type = 11521 id = 20 }
      name          = "ëÊ7êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 21 }
      name          = "ëÊ8êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 22 }
      name          = "ëÊ9êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 23 }
      name          = "ëÊ7êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 24 }
      name          = "ëÊ8êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 25 }
      name          = "ëÊ9êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 11521 id = 26 }
    name     = "ëÊ460ã@çbétíc"
    location = 1881
    home     = 1881
    division =
    { id            = { type = 11521 id = 27 }
      name          = "ëÊ10êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 28 }
      name          = "ëÊ11êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 29 }
      name          = "ëÊ12êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 30 }
      name          = "ëÊ10êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 31 }
      name          = "ëÊ11êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 32 }
      name          = "ëÊ12êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 11521 id = 33 }
    name     = "ëÊ401ã@çbétíc"
    location = 1881
    home     = 1881
    division =
    { id            = { type = 11521 id = 34 }
      name          = "ëÊ13êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 35 }
      name          = "ëÊ14êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 36 }
      name          = "ëÊ15êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 37 }
      name          = "ëÊ13êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 38 }
      name          = "ëÊ14êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 39 }
      name          = "ëÊ15êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 11521 id = 40 }
    name     = "ëÊ84ã@çbétíc"
    location = 1798
    home     = 1798
    division =
    { id            = { type = 11521 id = 41 }
      name          = "ëÊ16êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 42 }
      name          = "ëÊ17êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 43 }
      name          = "ëÊ18êÌèpã@çbëÂë‡"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 44 }
      name          = "ëÊ16êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 45 }
      name          = "ëÊ17êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 11521 id = 46 }
      name          = "ëÊ18êÌé‘ëÂë‡"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
}
