
##############################
# Country definition for JAP #
##############################

province = { id = 1174 air_base = 5 ic = 3 } # ÂXŒ§
province = { id = 1176 ic = 3 naval_base = 5 air_base = 5 } # “ìŠ’‘¾
province = { id = 1177 naval_base = 5 air_base = 3 } # –kç“‡
province = { id = 1179 naval_base = 10 air_base = 10 ic = 2 } # –kŠC“¹
province = { id = 1180 air_base = 5 ic = 3 } # H“cŒ§
province = { id = 1181 ic = 2 } # ŠâèŒ§
province = { id = 1182 ic = 1 } # RŒ`Œ§
province = { id = 1183 ic = 2 air_base = 5 } # ‹{éŒ§
province = { id = 1184 ic = 2 naval_base = 5 air_base = 5 } # VŠƒŒ§
province = { id = 1185 naval_base = 10 air_base = 5 } # ²“n“‡
province = { id = 1186 ic = 1 } # •Ÿ“‡Œ§
province = { id = 1187 ic = 3 } # ˆïéŒ§
province = { id = 1189 ic = 2 } # ŒQ”nŒ§
province = { id = 1190 air_base = 10 } # ç—tŒ§
province = { id = 1191 ic = 15 } # é‹ÊŒ§
province = { id = 1192 ic = 17 naval_base = 10 air_base = 10 radar_station = 10 infra = 0.2 } # “Œ‹“s
province = { id = 1193 ic = 10 air_base = 10 radar_station = 10 naval_base = 10 } # _“ŞìŒ§
province = { id = 1599 naval_base = 10 air_base = 10 } # Œ³R(—°‰©“‡)
province = { id = 2607 ic = 1 } # Ã‰ªŒ§
province = { id = 2609 ic = 1 air_base = 5 } # Šò•ŒŒ§
province = { id = 2611 } # ÎìŒ§
province = { id = 2612 air_base = 5 naval_base = 10 } # •ŸˆäŒ§
province = { id = 2615 ic = 19 air_base = 10 radar_station = 10 naval_base = 10 landfort = 1 } # ‹“s•{
province = { id = 2618 naval_base = 10 air_base = 10 ic = 7 } # ‘åã•{
province = { id = 2620 air_base = 5 naval_base = 10 } # ’¹æŒ§
province = { id = 2622 } # “‡ªŒ§
province = { id = 2623 ic = 5 air_base = 10 naval_base = 10 } # L“‡Œ§
province = { id = 2626 ic = 6 } # “¿“‡Œ§
province = { id = 2627 ic = 5 } # ˆ¤•QŒ§
province = { id = 2628 air_base = 3 naval_base = 5 } # ‚’mŒ§
province = { id = 2630 air_base = 3 } # ‘å•ªŒ§
province = { id = 2632 air_base = 10 naval_base = 10 ic = 2 } # ’·èŒ§
province = { id = 2633 ic = 1 } # ‹{èŒ§
province = { id = 2635 air_base = 10 naval_base = 10 ic = 4 } # ­™“‡Œ§

#####################
# Country main data #
#####################

country =
{ tag                 = JAP
  manpower            = 780
  energy              = 35000
  metal               = 48000
  rare_materials      = 24000
  oil                 = 30000
  supplies            = 8000
  money               = 1200
  capital             = 2615
  transports          = 1000
  escorts             = 800
  regular_id          = U06
  policy              = { democratic = 3 political_left = 3 freedom = 8 free_market = 2 professional_army = 9 defense_lobby = 8 interventionism = 9 }
  headofstate            = { type = 9 id = 5000 }
  headofgovernment       = { type = 9 id = 5029 }
  foreignminister        = { type = 9 id = 5065 }
  armamentminister       = { type = 9 id = 5103 }
  ministerofsecurity     = { type = 9 id = 5160 }
  #ministerofintelligence = { type = 9 id = 32006 } ##‚±‚±‚©‚ç‚Ü‚¾Št—»»ì“r’†
  #chiefofstaff           = { type = 9 id = 32007 }
  #chiefofarmy            = { type = 9 id = 32008 }
  #chiefofnavy            = { type = 9 id = 32009 }
  #chiefofair             = { type = 9 id = 32010 }
  ownedprovinces      = { 1174 1176 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1436 1437 1599 1784 1785 2607
                          2608 2609 2610 2611 2612 2613 2614 2615 2616 2617 2618 2619 2620 2621 2622 2623 2624 2625 2626 2627 2628 2629 2630 2631 2632
                          2633 2634 2635 2636 2637 2640
                        }
  controlledprovinces = { 1174 1176 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1436 1437 1599 1784 1785 2607
                          2608 2609 2610 2611 2612 2613 2614 2615 2616 2617 2618 2619 2620 2621 2622 2623 2624 2625 2626 2627 2628 2629 2630 2631 2632
                          2633 2634 2635 2636 2637 2640
                        }
  techapps            = { 10050 10060 10070 10080 10090 1010  10150 10160 10190 1020  10200 10210 10220 1030  1040  10440 10490 1050  1110  1120 
                          1130  1140  1150  1210  1220  1230  1240  1250  1470  1490  1510  1530  1550  1560  1570  1580  1590  1650  1660  1670 
                          1680  1690  1750  1760  1770  1780  1790  1850  1860  1870  1950  1960  1970  1980  2010  2020  20210 2030  20310 20320
                          2040  20410 2050  20510 20520 2060  2070  2080  2310  2320  2330  2610  2620  2630  2640  2650  2660  2910  2920  2930 
                          2940  2950  2960  3010  3020  3030  3040  30410 30420 30430 30440 30450 3050  30510 30520 30530 30540 30550 3110  3120 
                          3130  3140  3150  3210  3220  3230  3240  3250  3310  3320  3330  3340  3350  3410  3460  3470  3480  3490  3500  3560 
                          3570  3610  3620  3630  3640  3650  3710  3720  3730  3740  3750  3810  3820  3830  3840  3850  3910  3920  3930  3940 
                          3950  3960  40100 40110 40120 40130 40200 40210 40220 40230 4390  4400  4410  4420  4430  4480  4490  4500  4510  4560 
                          4570  50020 50030 50040 50050 50070 50080 50090 5010  50100 50110 50120 5020  5030  5040  5050  5090  5100  5110  5120 
                          5170  5180  5190  5200  5250  5260  5270  5280  5330  5340  5350  5360  5370  5410  5420  5430  5460  5490  5500  5600 
                          5610  5620  5630  5760  5770  5780  5790  5800  5810  5820  5830  5860  5910  5920  5930  5940  5950  7010  7670  7680  80080 80090 8010  80100 80160 8020  8030 
                          8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140 90190 9020  9030  9040  9050  9060  9070  9080 
                          9190  9200  9210  9220  9230  9340  9350  9360  9370  9380  9390  9400  9410  9520  9530  9540  9550  9560  9670  9680 
                          9690  9700  9710  9720  9730  9840  9850  9860  9870  9880  9990  10390  4010  4020  4030  4040  4050
                          4110  4120  4130  4140  4150  4210  4220  4230  4240  4250  4640  4650  4660  4670  4680  4820  4830  4840  4850  4860
                          40000 40010 40020 40030 40040 2340  2360  2670  2970
                          5520  5530  5540  5550  5560  50290 50300 50310 50320 40140 5680  5690  5700  5710  7750  7150  7160  7170  7180
                          7320  7030  7040  7050
                          2000  2210  3000  4000  5000  6120  6130  6310  6320  6330  6750 
                        }
  nationalprovinces   = { 1174 1176 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1436 1437 1599 1784 1785 2607
                          2608 2609 2610 2611 2612 2613 2614 2615 2616 2617 2618 2619 2620 2621 2622 2623 2624 2625 2626 2627 2628 2629 2630 2631 2632
                          2633 2634 2635 2636 2637 2640
                        }
free                = { energy = 50 metal = 80 rare_materials = 50 oil = 30 }
inventions             = { 8000 8004 8005 8006 8007 8009 8011 8012 8016 }
  landunit =
  { id       = { type = 10001 id = 2774 }
    name     = "¼•”•û–ÊŒRi—ß•”"
    location = 2226
    division =
    { id            = { type = 10001 id = 2776 }
      name          = "‘æ1ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2777 }
    name     = "‘æ1ŒR’c"
    location = 2226
    division =
    { id            = { type = 10001 id = 2779 }
      name          = "‘æ1íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2780 }
      name          = "‘æ2íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2781 }
      name          = "‘æ1íÔ‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2782 }
    name     = "’†•”•û–ÊŒRi—ß•”"
    location = 2615
    home     = 2615
    division =
    { id            = { type = 10001 id = 2784 }
      name          = "‘æ2ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2785 }
    name     = "‘æ2ŒR’c"
    location = 2615
    home     = 2615
    division =
    { id            = { type = 10001 id = 2787 }
      name          = "‘æ3íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2788 }
      name          = "‘æ4íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2789 }
      name          = "‘æ2íÔ‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2790 }
    name     = "‘æ3ŒR’c"
    location = 2607
    home     = 2607
    division =
    { id            = { type = 10001 id = 2792 }
      name          = "‘æ3íÔ‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2793 }
      name          = "‘æ4íÔ‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2794 }
      name          = "‘æ5íÔ‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2795 }
    name     = "“Œ•”•û–ÊŒRi—ß•”"
    location = 1192
    home     = 1192
    division =
    { id            = { type = 10001 id = 2797 }
      name          = "‘æ3ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2798 }
    name     = "‘æ4ŒR’c"
    location = 1198
    division =
    { id            = { type = 10001 id = 2800 }
      name          = "‘æ5íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2801 }
      name          = "‘æ6íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2802 }
      name          = "‘æ6íÔ‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2803 }
    name     = "“Œ–k•û–ÊŒRi—ß•”"
    location = 1183
    home     = 1183
    division =
    { id            = { type = 10001 id = 2805 }
      name          = "‘æ4ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2806 }
    name     = "‘æ5ŒR’c"
    location = 1183
    home     = 1183
    division =
    { id            = { type = 10001 id = 2808 }
      name          = "‘æ7íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2809 }
      name          = "‘æ8íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2810 }
      name          = "‘æ7íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2811 }
    name     = "–k•”•û–ÊŒRi—ß•”"
    location = 1179
    home     = 1179
    division =
    { id            = { type = 10001 id = 2813 }
      name          = "‘æ5ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2814 }
    name     = "‘æ6ŒR’c"
    location = 1179
    home     = 1179
    division =
    { id            = { type = 10001 id = 2816 }
      name          = "‘æ9íp‹@b‘å‘à"
      model         = 10
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2817 }
      name          = "‘æ10íp‹@b‘å‘à"
      model         = 10
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2818 }
      name          = "‘æ8íÔ‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2819 }
    name     = "‘æ7ŒR’c"
    location = 2607
    home     = 2607
    division =
    { id            = { type = 10001 id = 2821 }
      name          = "‘æ9íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2822 }
      name          = "‘æ10íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2823 }
      name          = "‘æ11íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2824 }
    name     = "‘æ8ŒR’c"
    location = 2635
    home     = 2635
    division =
    { id            = { type = 10001 id = 2826 }
      name          = "‘æ11íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2827 }
      name          = "‘æ12íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2828 }
      name          = "‘æ12íÔ‘å‘à"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2829 }
    name     = "‘æ9ŒR’c"
    location = 2623
    home     = 2623
    division =
    { id            = { type = 10001 id = 2831 }
      name          = "‘æ13íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2832 }
      name          = "‘æ14íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2833 }
      name          = "‘æ13íÔ‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2834 }
    name     = "‘æ10ŒR’c"
    location = 2623
    home     = 2623
    division =
    { id            = { type = 10001 id = 2836 }
      name          = "‘æ201íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = marine
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2837 }
      name          = "‘æ202íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = marine
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2838 }
      name          = "‘æ203íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = marine
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2839 }
    name     = "‘æ11ŒR’c"
    location = 2627
    home     = 2627
    division =
    { id            = { type = 10001 id = 2841 }
      name          = "‘æ15íp‹@b‘å‘à"
      model         = 10
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2842 }
      name          = "‘æ16íp‹@b‘å‘à"
      model         = 10
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2843 }
      name          = "‘æ14íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2844 }
    name     = "‘æ12ŒR’c"
    location = 2632
    home     = 2632
    division =
    { id            = { type = 10001 id = 2846 }
      name          = "‘æ204íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = marine
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2847 }
      name          = "‘æ205íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = marine
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2848 }
      name          = "‘æ206íp‹@b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = marine
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2849 }
    name     = "‘æ13ŒR’c"
    location = 2620
    home     = 2620
    division =
    { id            = { type = 10001 id = 2851 }
      name          = "‘æ1‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2852 }
      name          = "‘æ2‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2853 }
      name          = "‘æ3‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2854 }
    name     = "‘æ14ŒR’c"
    location = 2626
    home     = 2626
    division =
    { id            = { type = 10001 id = 2856 }
      name          = "‘æ4‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2857 }
      name          = "‘æ5‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2858 }
      name          = "‘æ6‘•b‘å‘à"
      model         = 3
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2859 }
    name     = "‘æ15ŒR’c"
    location = 1180
    home     = 1180
    division =
    { id            = { type = 10001 id = 2861 }
      name          = "‘æ101íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2862 }
      name          = "‘æ102íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2863 }
      name          = "‘æ103íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2864 }
    name     = "‘æ16ŒR’c"
    location = 2617
    home     = 2617
    division =
    { id            = { type = 10001 id = 2866 }
      name          = "‘æ104íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2867 }
      name          = "‘æ105íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2868 }
      name          = "‘æ106íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2869 }
    name     = "“ìŠ’‘¾ç”õ‘à"
    location = 2629
    home     = 2629
    division =
    { id            = { type = 10001 id = 2871 }
      name          = "‘æ7‘•b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2872 }
      name          = "‘æ8‘•b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2873 }
      name          = "‘æ9‘•b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2874 }
    name     = "‰«“êç”õ‘à"
    location = 2637
    home     = 2637
    division =
    { id            = { type = 10001 id = 2876 }
      name          = "‘æ1‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2877 }
      name          = "‘æ2‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2878 }
      name          = "‘æ3‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2879 }
    name     = "²“n“‡ç”õ‘à"
    location = 1185
    home     = 1185
    division =
    { id                  = { type = 10001 id = 2881 }
      name                = "‘æ4‹@ŠB‰»‘•b•à•º‘å‘à"
      model               = 3
      brigade_model       = 0
      type                = mechanized
      extra               = artillery
      strength            = 100.0000
      organisation        = 40.0000
      morale              = 95.0000
      experience          = 0.0000
      defaultorganisation = 80.0000
      redep_unit_name     = ""
      maxspeed            = 6.0000
      supplyconsumption   = 0.6000
      fuelconsumption     = 0.0000
      defensiveness       = 13.0000
      toughness           = 16.0000
      softness            = 50.0000
      suppression         = 3.0000
      airdefence          = 2.0000
      softattack          = 11.0000
      hardattack          = 11.0000
      transportweight     = 5.0000
      airattack           = 2.0000
    }
    division =
    { id            = { type = 10001 id = 2882 }
      name          = "‘æ5‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2883 }
      name          = "‘æ6‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2884 }
    name     = "z‰qŒR‘æ1˜A‘à"
    location = 2615
    home     = 2615
    division =
    { id                  = { type = 10001 id = 2886 }
      name                = "‘æ16z‰q‘å‘à"
      model               = 0
      brigade_model       = 1
      type                = cavalry
      extra               = rocket_artillery
      strength            = 100.0000
    }
    division =
    { id            = { type = 10001 id = 2887 }
      name          = "‘æ302z‰q‘å‘à"
      model         = 7
      brigade_model = 0
      type          = cavalry
      extra         = rocket_artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2888 }
      name          = "‘æ303z‰q‘å‘à"
      model         = 21
      brigade_model = 0
      type          = cavalry
      extra         = rocket_artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2889 }
      name          = "‘æ304z‰q‘å‘à"
      model         = 21
      brigade_model = 0
      type          = cavalry
      extra         = rocket_artillery
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2890 }
    name     = "z‰qŒR‘æ2˜A‘à"
    location = 2615
    home     = 2615
    division =
    { id            = { type = 10001 id = 2892 }
      name          = "‘æ6ŒRi—ß•”"
      model         = 15
      brigade_model = 0
      type          = hq
      extra         = rocket_artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2893 }
      name          = "‘æ305z‰q‘å‘à"
      model         = 21
      brigade_model = 0
      type          = cavalry
      extra         = rocket_artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2894 }
      name          = "‘æ306z‰q‘å‘à"
      model         = 21
      brigade_model = 0
      type          = cavalry
      extra         = rocket_artillery
      strength      = 100
    }
    division =
    { id            = { type = 10001 id = 2895 }
      name          = "‘æ307z‰q‘å‘à"
      model         = 21
      brigade_model = 0
      type          = cavalry
      extra         = rocket_artillery
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2896 }
    name     = "‘æ19ŒR’c"
    location = 2640
    home     = 2640
    division =
    { id            = { type = 10001 id = 2898 }
      name          = "‘æ1x‰‡‘å‘à"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2899 }
    name     = "‘æ20ŒR’c"
    location = 1190
    home     = 1190
    division =
    { id            = { type = 10001 id = 2901 }
      name          = "‘æ2x‰‡‘å‘à"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2902 }
    name     = "‘æ21ŒR’c"
    location = 1174
    home     = 1174
    division =
    { id            = { type = 10001 id = 2904 }
      name          = "‘æ3x‰‡‘å‘à"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2905 }
    name     = "‘æ22ŒR’c"
    location = 1176
    home     = 1176
    division =
    { id            = { type = 10001 id = 2907 }
      name          = "‘æ4x‰‡‘å‘à"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2908 }
    name     = "‘æ23ŒR’c"
    location = 1177
    home     = 1177
    division =
    { id            = { type = 10001 id = 2910 }
      name          = "‘æ5x‰‡‘å‘à"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2911 }
    name     = "‘æ24ŒR’c"
    location = 1178
    home     = 1178
    division =
    { id            = { type = 10001 id = 2913 }
      name          = "‘æ6x‰‡‘å‘à"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2914 }
    name     = "‘æ25ŒR’c"
    location = 1599
    home     = 1599
    division =
    { id            = { type = 10001 id = 2916 }
      name          = "‘æ7x‰‡‘å‘à"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 10001 id = 2917 }
    name     = "‘æ26ŒR’c"
    location = 2609
    home     = 2609
    division =
    { id            = { type = 10001 id = 2919 }
      name          = "‘æ8x‰‡‘å‘à"
      model         = 3
      brigade_model = 0
      type          = garrison
      strength      = 100
    }
   }
  landunit =
  { id       = { type = 10001 id = 2920 }
    name     = "•xm‹³“±’c"
    location = 2607
    home     = 2607
    division =
    { id            = { type = 10001 id = 2921 }
      name          = "•xm‹³“±‘à"
      model         = 10
      brigade_model = 0
      type          = paratrooper
      strength      = 100
      experience    = 85
    }
  }
  navalunit =
  { id       = { type = 10002 id = 2920 }
    name     = "‘æˆêŠÍ‘à"
    location = 2623
    home     = 2623
    base     = 2623
    division =
    { id       = { type = 10002 id = 2922 }
      name     = "‘å˜a"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2923 }
      name     = "•‘ "
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2924 }
      name     = "M”Z"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2925 }
      name     = "Ré"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2926 }
      name     = "—˜ª"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2927 }
      name     = "’}–€"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2928 }
      name     = "ŒÃ‘é"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2929 }
      name     = "‰ÁŒÃ"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2930 }
      name     = "_•—"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2931 }
      name     = "’©•—"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2932 }
      name     = "t•—"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2933 }
      name     = "¼•—"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2934 }
      name     = "Šø•—"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2935 }
      name     = "’Ç•—"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2936 }
      name     = "¾•—"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2937 }
      name     = "’©“â"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2938 }
      name     = "—[“â"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2939 }
      name     = "–rŒ"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 2940 }
    name     = "‘æ“ñŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 10002 id = 2942 }
      name     = "ˆÉ¨"
      model    = 3
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2943 }
      name     = "‹ß]"
      model    = 3
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2944 }
      name     = "Â—t"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2945 }
      name     = "ˆßŠ}"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2946 }
      name     = "“ß’q"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2947 }
      name     = "‰H•"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2948 }
      name     = "”@Œ"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2949 }
      name     = "–í¶"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2950 }
      name     = "‰KŒ"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2951 }
      name     = "HŒ"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2952 }
      name     = "…–³Œ"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2953 }
      name     = "•¶Œ"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2954 }
      name     = "’·Œ"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2955 }
      name     = "‹eŒ"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 2956 }
    name     = "‘æOŠÍ‘à"
    location = 1192
    home     = 1192
    base     = 1192
    division =
    { id       = { type = 10002 id = 2958 }
      name     = "”d–"
      model    = 3
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2959 }
      name     = "Û’Ã"
      model    = 3
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2960 }
      name     = "–­‚"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2961 }
      name     = "‘«•¿"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2962 }
      name     = "‚—Y"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2963 }
      name     = "ˆ¤“†"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2964 }
      name     = "O“úŒ"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2965 }
      name     = "–]Œ"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2966 }
      name     = "—[Œ"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2967 }
      name     = "á"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2968 }
      name     = "”’á"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2969 }
      name     = "‰á"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2970 }
      name     = "[á"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2971 }
      name     = "‘p‰_"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 2972 }
    name     = "‘æˆê‹­PŠÍ‘à"
    location = 2623
    home     = 2623
    base     = 2623
    division =
    { id       = { type = 10002 id = 2974 }
      name     = "‘å‘é"
      model    = 4
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 10002 id = 2975 }
      name     = "_‘é"
      model    = 4
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 10002 id = 2976 }
      name     = "’}”g"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2977 }
      name     = "‹îŒÜˆä"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2978 }
      name     = "ˆÉ"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2979 }
      name     = "ˆÆ”n"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2980 }
      name     = "‹à„"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2981 }
      name     = "ƒ~ƒTƒCƒ‹’ø1†"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2982 }
      name     = "ƒ~ƒTƒCƒ‹’ø2†"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2983 }
      name     = "ƒ~ƒTƒCƒ‹’ø3†"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2984 }
      name     = "ƒ~ƒTƒCƒ‹’ø4†"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2985 }
      name     = "ƒ~ƒTƒCƒ‹’ø5†"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2986 }
      name     = "‘æ1—A‘—í‘à"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2987 }
      name     = "‘æ2—A‘—í‘à"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2988 }
      name     = "‘æ3—A‘—í‘à"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2989 }
      name     = "‘æ4—A‘—í‘à"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2990 }
      name     = "‘æ5—A‘—í‘à"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2991 }
      name     = "‘æ6—A‘—í‘à"
      model    = 6
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 2992 }
    name     = "‘æ“ñ‹­PŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 10002 id = 2994 }
      name     = "R‘é"
      model    = 3
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 10002 id = 2995 }
      name     = "ŠC‘é"
      model    = 3
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 10002 id = 2996 }
      name     = "”ä‰b"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2997 }
      name     = "Y–¼"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2998 }
      name     = "–¶“‡"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 2999 }
      name     = "“Vé"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3000 }
      name     = "Ôé"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3001 }
      name     = "ƒ~ƒTƒCƒ‹’ø6†"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3002 }
      name     = "ƒ~ƒTƒCƒ‹’ø7†"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3003 }
      name     = "ƒ~ƒTƒCƒ‹’ø8†"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3004 }
      name     = "ƒ~ƒTƒCƒ‹’ø9†"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3005 }
      name     = "ƒ~ƒTƒCƒ‹’ø10†"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3006 }
      name     = "‘æ7—A‘—í‘à"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3007 }
      name     = "‘æ8—A‘—í‘à"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3008 }
      name     = "‘æ9—A‘—í‘à"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3009 }
      name     = "‘æ10—A‘—í‘à"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3010 }
      name     = "‘æ11—A‘—í‘à"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3011 }
      name     = "‘æ12—A‘—í‘à"
      model    = 5
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 3012 }
    name     = "‘æˆê—A‘—ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 10002 id = 3014 }
      name     = "“Œ‰_"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3015 }
      name     = "‘æ13—A‘—í‘à"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3016 }
      name     = "‘æ14—A‘—í‘à"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3017 }
      name     = "‘æ15—A‘—í‘à"
      model    = 3
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 3018 }
    name     = "‘æ“ñ—A‘—ŠÍ‘à"
    location = 1176
    home     = 1176
    base     = 1176
    division =
    { id       = { type = 10002 id = 3020 }
      name     = "”–‰_"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3021 }
      name     = "‘æ16—A‘—í‘à"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3022 }
      name     = "‘æ17—A‘—í‘à"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3023 }
      name     = "‘æ18—A‘—í‘à"
      model    = 3
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 3024 }
    name     = "‘æO—A‘—ŠÍ‘à"
    location = 2615
    home     = 2615
    base     = 2615
    division =
    { id       = { type = 10002 id = 3026 }
      name     = "”’‰_"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3027 }
      name     = "‘æ19—A‘—í‘à"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3028 }
      name     = "‘æ20—A‘—í‘à"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3029 }
      name     = "‘æ21—A‘—í‘à"
      model    = 3
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 3030 }
    name     = "‘æˆêö…ŠÍ‘à"
    location = 1192
    home     = 1192
    base     = 1192
    division =
    { id       = { type = 10002 id = 3032 }
      name     = "’©’ª"
      model    = 4
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3033 }
      name     = "V’ª"
      model    = 4
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3034 }
      name     = "t’ª"
      model    = 4
      type     = submarine
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 3035 }
    name     = "‘æ“ñö…ŠÍ‘à"
    location = 2623
    home     = 2623
    base     = 2623
    division =
    { id       = { type = 10002 id = 3037 }
      name     = "–’ª"
      model    = 3
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3038 }
      name     = "‰Q’ª"
      model    = 3
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3039 }
      name     = "ˆé’ª"
      model    = 3
      type     = submarine
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 3040 }
    name     = "‘æOö…ŠÍ‘à"
    location = 2615
    home     = 2615
    base     = 2615
    division =
    { id       = { type = 10002 id = 3042 }
      name     = "•’ª"
      model    = 3
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3043 }
      name     = "‚’ª"
      model    = 3
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3044 }
      name     = "–Â’ª"
      model    = 3
      type     = submarine
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 3045 }
    name     = "‘ælö…ŠÍ‘à"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 10002 id = 3047 }
      name     = "Šª’ª"
      model    = 2
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3048 }
      name     = "e’ª"
      model    = 2
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3049 }
      name     = "£ŒË’ª"
      model    = 2
      type     = submarine
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 3050 }
    name     = "‘æŒÜö…ŠÍ‘à"
    location = 2635
    home     = 2635
    base     = 2635
    division =
    { id       = { type = 10002 id = 3051 }
      model    = 2
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3052 }
      name     = "–İ’ª"
      model    = 2
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3053 }
      name     = "‰Ä’ª"
      model    = 2
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3054 }
      name     = "“~’ª"
      model    = 2
      type     = submarine
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 3055 }
    name     = "‘æˆêŒ´öŠÍ‘à"
    location = 1179
    home     = 1179
    base     = 1179
    division =
    { id       = { type = 10002 id = 3057 }
      name     = "‘“—´"
      model    = 0
      type     = nuclear_submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3058 }
      name     = "‰_—´"
      model    = 0
      type     = nuclear_submarine
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 10002 id = 3059 }
    name     = "‘æ“ñŒ´öŠÍ‘à"
    location = 2623
    home     = 2623
    base     = 2623
    division =
    { id       = { type = 10002 id = 3061 }
      name     = "Œ«—´"
      model    = 0
      type     = nuclear_submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 10002 id = 3062 }
      name     = "”’—´"
      model    = 0
      type     = nuclear_submarine
      strength = 100.0000
    }
  }
  ## A-01
  landdivision = {
    dormant = yes
    id = { type = 10001 id = 3001 }
    name = "A-04"
    strength = 100
    experience = 100
    type = motorized
    model = 26
  }
  landdivision = {
    dormant = yes
    id = { type = 10001 id = 3002 }
    name = "å ç’ß"
    strength = 100
    experience = 100
    type = cavalry
    model = 9
  }
  landdivision = {
    dormant = yes
    id = { type = 10001 id = 3003 }
    name = "Ê•ô Œd"
    strength = 100
    experience = 100
    type = cavalry
    model = 16
  }
  landdivision = {
    dormant = yes
    id = { type = 10001 id = 3004 }
    name = "ì£ p•P"
    strength = 100
    experience = 100
    type = cavalry
    model = 16
  }
  landdivision = {
    dormant = yes
    id = { type = 10001 id = 3005 }
    name = "ŒäŒ• –»–é"
    strength = 100
    experience = 100
    type = cavalry
    model = 2
  }
  landdivision = {
    dormant = yes
    id = { type = 10001 id = 3006 }
    name = "ŠZˆß ”ü‹Õ"
    strength = 100
    experience = 100
    type = cavalry
    model = 16
  }
  navaldivision = {
    dormant = yes
    id      = { type = 10002 id = 3063 }
    name    = "ˆÉ"
    type    = carrier
    model   = 2
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 10002 id = 3064 }
    name    = "Ôé"
    type    = carrier
    model   = 3
    extra1  = cag
    brigade_model1 = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 10003 id = 1 }
    name = "G’e“‹Ú‘æ1ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket model = 2
  }
  airdivision = {
    dormant = yes
    id = { type = 10003 id = 2 }
    name = "G’e“‹Ú‘æ2ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket model = 2
  }
}
