
##############################
# Country definition for U02 #
##############################

province =
{ id            = 5
  anti_air      = 4
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 4 current_size = 4 }
}                 # カークウォール
province =
{ id            = 8
  anti_air      = 2
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 8 current_size = 8 }
}                 # グラスゴー
province =
{ id       = 11
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ハル
province =
{ id            = 12
  anti_air      = 4
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 8 current_size = 8 }
}                 # マンチェスター
province = { id = 13 anti_air = 2 } # シェフィールド
province = { id = 14 anti_air = 2 } # バーミンガム
province = { id = 15 ic = 4 } # カーディフ
province =
{ id            = 17
  anti_air      = 4
  ic            = 5
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 2 current_size = 2 }
}                 # ノリッジ
province = { id = 19 anti_air = 3 ic = 7 } # ロンドン
province =
{ id            = 20
  anti_air      = 5
  ic            = 3
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 4 current_size = 4 }
  coastalfort   = 3
}                 # ドーバー
province =
{ id         = 21
  anti_air   = 6
  ic         = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # ポーツマス
province =
{ id         = 23
  anti_air   = 6
  ic         = 5
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # プリマス
province =
{ id         = 25
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # コーク
province =
{ id         = 28
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
  oilpool    = 1000
  supplypool = 2000
}              # ベルファスト
province =
{ id       = 29
  air_base = { size = 2 current_size = 2 }
}            # ロンドンデリー
province =
{ id         = 30
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
}              # ダブリン
province =
{ id          = 31
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 4 current_size = 4 }
  coastalfort = 1
  oilpool     = 1000
  supplypool  = 1000
}               # マルタ島
province =
{ id         = 32
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # ブレスト
province =
{ id         = 34
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
}              # ロリアン
province =
{ id         = 35
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
}              # ナント
province =
{ id         = 38
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # シェルブール
province = { id = 39 anti_air = 1 } # カーン
province =
{ id       = 44
  air_base = { size = 4 current_size = 4 }
  anti_air = 1
}            # リール
province =
{ id         = 46
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
}              # ロッテルダム
province =
{ id         = 47
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 10 current_size = 10 }
  landfort   = 1
}              # アムステルダム
province =
{ id         = 48
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
}              # ミデルブルフ
province = { id = 49 anti_air = 2 } # アイントホーフェン
province =
{ id       = 56
  anti_air = 5
  air_base = { size = 10 current_size = 10 }
}            # パリ
province =
{ id         = 59
  anti_air   = 4
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # ボルドー
province =
{ id       = 60
  air_base = { size = 4 current_size = 4 }
}            # ポワチエ
province =
{ id       = 62
  air_base = { size = 4 current_size = 4 }
}            # オルレアン
province =
{ id            = 67
  anti_air      = 3
  air_base      = { size = 2 current_size = 2 }
}                 # エッセン
province =
{ id       = 72
  anti_air = 3
  air_base = { size = 10 current_size = 10 }
  landfort = 10
}            # メス
province = { id = 73 anti_air = 2 landfort = 10 } # ストラスブール
province = { id = 76 anti_air = 2 } # デュッセルドルフ
province =
{ id         = 80
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # ヴィルヘルムスハーフェン
province =
{ id       = 81
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ミュンスター
province =
{ id       = 82
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # カッセル
province =
{ id         = 87
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 8 current_size = 8 }
}              # ブレーメン
province =
{ id         = 88
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
}              # ハンブルク
province = { id = 89 anti_air = 1 } # リューベック
province =
{ id         = 90
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # キール
province =
{ id            = 93
  anti_air      = 2
  naval_base    = { size = 6 current_size = 6 }
  air_base      = { size = 2 current_size = 2 }
  coastalfort   = 3
}                 # マルメ
province =
{ id       = 97
  air_base = { size = 2 current_size = 2 }
}            # カルマル
province =
{ id          = 98
  anti_air    = 2
  landfort    = 1
  coastalfort = 3
  naval_base  = { size = 4 current_size = 4 }
  air_base    = { size = 2 current_size = 2 }
}               # イェーテボリ
province =
{ id            = 101
  anti_air      = 2
  naval_base    = { size = 6 current_size = 6 }
  air_base      = { size = 4 current_size = 4 }
  coastalfort   = 3
}                 # ストックホルム
province =
{ id       = 105
  air_base = { size = 2 current_size = 2 }
}            # オレブロ
province = { id = 106 landfort = 1 } # カールシュタット
province =
{ id          = 107
  anti_air    = 2
  naval_base  = { size = 6 current_size = 6 }
  air_base    = { size = 4 current_size = 4 }
  coastalfort = 3
}               # オスロ
province =
{ id         = 108
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # クリスチャンサン
province =
{ id       = 109
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # スタヴァンゲル
province =
{ id            = 113
  air_base      = { size = 2 current_size = 2 }
}                 # イェヴレ
province =
{ id          = 118
  coastalfort = 2
  anti_air    = 1
  naval_base  = { size = 2 current_size = 2 }
  air_base    = { size = 2 current_size = 2 }
}               # トロンハイム
province =
{ id         = 124
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # ボードー
province =
{ id       = 127
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
  landfort = 3
}            # ルーレオ
province =
{ id          = 129
  anti_air    = 2
  naval_base  = { size = 4 current_size = 4 }
  air_base    = { size = 2 current_size = 2 }
  coastalfort = 3
}               # ベルゲン
province =
{ id       = 137
  air_base = { size = 4 current_size = 4 }
}            # オウル
province =
{ id       = 139
  anti_air = 2
  air_base = { size = 8 current_size = 8 }
}            # タンペレ
province =
{ id          = 141
  coastalfort = 1
  anti_air    = 2
  naval_base  = { size = 6 current_size = 6 }
  air_base    = { size = 4 current_size = 4 }
}               # トゥルク
province =
{ id          = 142
  coastalfort = 1
  anti_air    = 3
  naval_base  = { size = 4 current_size = 4 }
  air_base    = { size = 8 current_size = 8 }
}               # ヘルシンキ
province =
{ id       = 195
  air_base = { size = 5 current_size = 5 }
}            # クレサーレ
province =
{ id         = 197
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # リガ
province =
{ id         = 205
  anti_air   = 1
  air_base   = { size = 1 current_size = 1 }
  naval_base = { size = 2 current_size = 2 }
}              # リエパーヤ
province =
{ id       = 207
  air_base = { size = 2 current_size = 2 }
}            # カウナス
province = { id = 208 anti_air = 1 } # ブィドゴシュチュ
province =
{ id       = 209
  air_base = { size = 2 current_size = 2 }
  anti_air = 1
}            # グロドゥナ
province = { id = 211 anti_air = 1 } # カリシュ
province =
{ id       = 214
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ビリニュス
province =
{ id       = 296
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ロストック
province =
{ id       = 298
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # マグデブルク
province =
{ id       = 300
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # ベルリン
province =
{ id            = 302
  anti_air      = 1
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 4 current_size = 4 }
}                 # シュテッティン
province =
{ id         = 303
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
}              # ダンツィヒ
province =
{ id         = 304
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # エルビンク
province = { id = 305 anti_air = 1 } # プウォツク
province =
{ id         = 306
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # グディニャ
province = { id = 307 anti_air = 1 } # トルン
province = { id = 308 anti_air = 2 landfort = 2 } # メーゼリッツ
province =
{ id              = 310
  anti_air        = 1
  air_base        = { size = 4 current_size = 4 }
}                   # ライプツィヒ
province =
{ id       = 312
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ニュルンベルク
province =
{ id       = 313
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # フランクフルト・アム・マイン
province =
{ id       = 314
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # シュッツトガルト
province = { id = 316 anti_air = 2 landfort = 10 } # ミュールーズ
province =
{ id       = 317
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # エピナル
province =
{ id       = 330
  air_base = { size = 2 current_size = 2 }
}            # サラゴサ
province =
{ id         = 331
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 2 current_size = 2 }
}              # ビルバオ
province =
{ id       = 333
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ブルゴス
province =
{ id         = 334
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
  air_base   = { size = 2 current_size = 2 }
}              # ラコルニャ
province =
{ id         = 335
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # オポルト
province =
{ id         = 336
  anti_air   = 4
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # リスボン
province =
{ id       = 341
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # マドリッド
province =
{ id       = 342
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # トレド
province =
{ id       = 347
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # セヴィーリャ
province =
{ id         = 348
  anti_air   = 6
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  landfort   = 6
  oilpool    = 1000
  supplypool = 1000
}              # ジブラルタル
province =
{ id          = 352
  anti_air    = 2
  naval_base  = { size = 4 current_size = 4 }
  air_base    = { size = 2 current_size = 2 }
  coastalfort = 3
}               # ムルシア
province =
{ id       = 354
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # バレンシア
province =
{ id         = 357
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # バルセロナ
province =
{ id       = 359
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # トゥールーズ
province =
{ id       = 360
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ヴィシー
province =
{ id         = 364
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # マルセイユ
province =
{ id          = 365
  anti_air    = 5
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 10 current_size = 10 }
  landfort    = 3
  coastalfort = 2
}               # トゥーロン
province = { id = 366 landfort = 3 } # ニース
province =
{ id         = 368
  landfort   = 5
  anti_air   = 3
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 4 current_size = 4 }
}              # ジェノヴァ
province =
{ id       = 370
  air_base = { size = 4 current_size = 4 }
  anti_air = 3
}            # ミラノ
province = { id = 372 landfort = 4 anti_air = 3 } # ルガーノ
province =
{ id       = 376
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ミュンヘン
province =
{ id         = 378
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # ヴェネティア
province =
{ id       = 382
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ザグレブ
province =
{ id         = 384
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # スプリット
province =
{ id       = 385
  anti_air = 1
  air_base = { size = 1 current_size = 1 }
}            # サラエヴォ
province = { id = 388 anti_air = 2 } # ドブロブニク
province =
{ id         = 389
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
}              # ツェティニェ
province =
{ id         = 396
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
}              # イラクリオン(クレタ)
province =
{ id         = 398
  landfort   = 2
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # カリムノス(ドデカネス諸島)
province =
{ id         = 399
  landfort   = 2
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # ロードス
province =
{ id         = 401
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 6 current_size = 6 }
}              # アテネ
province = { id = 410 landfort = 5 anti_air = 2 } # コモティニ
province =
{ id         = 411
  landfort   = 5
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 2 current_size = 2 }
}              # テッサロニキ
province =
{ id       = 424
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ブカレスト
province =
{ id       = 428
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # クルジュナポカ
province =
{ id       = 431
  anti_air = 3
  air_base = { size = 2 current_size = 2 }
}            # プロエスティ
province =
{ id       = 433
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ヤシ
province =
{ id       = 435
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # イスマイル
province =
{ id         = 436
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
}              # コンスタンツァ
province =
{ id       = 444
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ニコシア
province =
{ id       = 453
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # ベオグラード
province =
{ id       = 456
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ペーチ
province =
{ id       = 473
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ブレスラウ
province =
{ id       = 479
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # クラクフ
province = { id = 480 anti_air = 1 } # チェンストホーヴァ
province =
{ id       = 481
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ウッチ
province = { id = 483 anti_air = 2 } # ポズナン
province =
{ id       = 485
  anti_air = 2
  air_base = { size = 6 current_size = 6 }
}            # ワルシャワ
province = { id = 486 anti_air = 2 } # カトヴィツェ
province =
{ id       = 487
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # ルブリン
province =
{ id       = 495
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ティムショハラ
province =
{ id       = 497
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # デブレツェン
province =
{ id       = 501
  anti_air = 2
  air_base = { size = 2 current_size = 2 }
}            # リヴォフ
province =
{ id       = 503
  anti_air = 2
  landfort = 1
  air_base = { size = 4 current_size = 4 }
}            # ブレスト・リフトスク
province = { id = 505 anti_air = 1 } # ビェルスク
province =
{ id       = 507
  air_base = { size = 2 current_size = 2 }
}            # スタニスラオ
province = { id = 509 anti_air = 1 } # スヴァウキ
province = { id = 512 anti_air = 1 } # ボローニャ
province = { id = 513 anti_air = 1 } # フィレンツェ
province =
{ id       = 515
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ローマ
province =
{ id       = 520
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # フォッジア
province =
{ id            = 521
  anti_air      = 2
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 6 current_size = 6 }
}                 # ナポリ
province =
{ id         = 523
  anti_air   = 1
  naval_base = { size = 10 current_size = 10 }
  air_base   = { size = 6 current_size = 6 }
}              # ターラント
province =
{ id         = 525
  anti_air   = 2
  supplypool = 500
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 10 current_size = 10 }
  landfort   = { size = 10 current_size = 10 }
}              # パレルモ
province =
{ id         = 526
  #landfort   = { size = 10 current_size = 10 }
}              # メッシーナ
province = { id = 527 landfort = 3 } # グルノーブル
province =
{ id       = 530
  landfort = 5
  anti_air = 3
  air_base = { size = 2 current_size = 2 }
}            # ジュネーヴ
province = { id = 531 landfort = 5 anti_air = 3 } # トリノ
province =
{ id       = 532
  anti_air = 5
  air_base = { size = 4 current_size = 4 }
  landfort = 5
}            # ベルン
province =
{ id       = 533
  landfort = 5
  anti_air = 3
  air_base = { size = 2 current_size = 2 }
}            # チューリッヒ
province =
{ id         = 534
  anti_air   = 1
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
}              # カリャリ(サルディーニャ)
province =
{ id         = 538
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 500
}              # ハミルトン(バミューダ)
province =
{ id         = 542
  anti_air   = 1
  naval_base = { size = 6 current_size = 6 }
}              # リヴォルノ
province =
{ id         = 544
  landfort   = { size = 10 current_size = 10 }
}              # カターニア
province =
{ id         = 545
  anti_air   = 1
  naval_base = { size = 4 current_size = 4 }
  oilpool    = 100
  supplypool = 500
}              # サッサリ(サルディーニャ)
province =
{ id       = 546
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # フランクフルト・アン・デア・オーダー
province =
{ id       = 652
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ナッソー(バハマ)
province =
{ id         = 666
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
}              # トリエステ
province =
{ id         = 801
  anti_air   = 1
  naval_base = { size = 1 current_size = 1 }
  oilpool    = 100
  supplypool = 500
}              # ウィレムスタッド(カリブ)
province =
{ id         = 866
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 200
}              # スタンレー(フォークランド諸島)
province =
{ id       = 873
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ジョージタウン(ガイアナ)
province = { id = 875 oilpool = 100 supplypool = 100 } # カイエンヌ
province =
{ id         = 899
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  supplypool = 100
  oilpool    = 100
}              # フォール＝ド＝フランス(アンティル諸島)
province =
{ id       = 957
  air_base = { size = 5 current_size = 5 }
}            # セウタ
province =
{ id       = 962
  air_base = { size = 2 current_size = 2 }
}            # サラマンカ
province =
{ id         = 1157
  anti_air   = 2
  naval_base = { size = 6 current_size = 6 }
  air_base   = { size = 2 current_size = 2 }
}              # カディス
province =
{ id         = 1166
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 8 current_size = 8 }
}              # エディンバラ
province =
{ id         = 1409
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
}              # スウォンジ
province =
{ id       = 1595
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # グリヴィツェ
province =
{ id         = 1609
  naval_base = { size = 1 current_size = 1 }
}              # スバ(フィジー諸島)
province =
{ id         = 1692
  anti_air   = 2
  naval_base = { size = 1 current_size = 1 }
  oilpool    = 100
  supplypool = 100
}              # ヌメア
province =
{ id       = 1720
  air_base = { size = 5 current_size = 5 }
}            # セント・ヘリア(チャンネル諸島)

#####################
# Country main data #
#####################

country =
{ tag                 = U02
  manpower            = 1000
  energy              = 58000
  metal               = 36000
  rare_materials      = 45000
  oil                 = 12000
  supplies            = 8000
  money               = 3500
  capital             = 19
  transports          = 1800
  escorts             = 1500
  regular_id          = U92
  policy =
  { democratic        = 10
    political_left    = 2
    freedom           = 9
    free_market       = 9
    professional_army = 9
    defense_lobby     = 10
    interventionism   = 9
  }
  ownedprovinces      = { 1    10   100  101  1014 1015 1016 1018 1019 102  1022 103  1036 104  105  1057 106  107  108  1082 109  11   110  111  112 
                          113  1135 1136 114  1147 1148 115  1157 116  1160 1161 1162 1163 1164 1165 1166 1168 1169 117  1173 118  119  12   120  121 
                          122  124  125  126  127  128  129  13  131  132  136  137  138  139  14   140  1400 1401 1402 1403 1405 1408 1409 141  142 
                          144  1449 147  148  149  15   1531 1532 1537 1563 1595 16   1606 1607 1609 1610 1611 1614 1622 1623 1643 1676 1683 1684
                          1686 1687 1688 1689 1690 1691 1692 17   1714 1720 1726 1734 1752 1756 1759 1761 1764 1769 1770 1779 18   1810 1811 1867 1875
                          1876 1884 1885 1886 1887 1888 1889 1890 1891 1892 1893 1894 1895 1896 1897 1899 19   1911 193  194  195  196  197  198  199 
                          2    20   202  203  204  205  206  207  208  209  21   210  211  213  214  22   222  224  2242 2243 2244 2245 229  23   230 
                          2319 2321 2323 2324 2325 2326 2327 2328 2329 24   2447 2449 2450 25   2509 2514 2555 2557 26   2602 2603 2604 2605 2606 27  
                          28   29   291  292  293  294  295  296  297  298  299  3    30   300  301  302  303  304  305  306  307  308  309  31   310 
                          311  312  313  314  315  316  317  318  319  32   320  321  322  323  324  325  326  327  328  329  33   330  331  332  333 
                          334  335  336  337  338  339  34   340  341  342  343  344  345  346  347  348  349  35   350  351  352  353  354  355  356 
                          357  358  359  36   360  361  362  363  364  365  366  367  368  369  37   370  371  372  373  374  375  376  377  378  379 
                          38   380  381  382  383  384  385  386  387  388  389  39   390  391  392  393  394  395  396  398  399  40   400  401  402 
                          403  405  41   410  411  412  413  414  415  416  417  419  42   420  421  422  423  424  425  426  427  428  429  43  
                          430  431  432  433  434  435  436  44   444  45   451  452  453  454  455  456  458  459  46   460  461  462  463  464  465 
                          466  467  468  469  47   470  471  472  473  474  475  476  477  478  479  48   480  481  482  483  484  485  486  487  488 
                          489  49   490  491  492  493  494  495  496  497  498  499  5    50   500  501  502  503  504  505  506  507  508  509  51  
                          511  512  513  514  515  516  517  518  519  52   520  521  522  523  524  525  526  527  528  53   530  531  532  533  534 
                          535  536  537  538  54   542  543  544  545  546  547  55   56   561  562  563  567  57   572  573  577  58   581  584  586 
                          587  59   591  6    60   61   62   63   64   65   652  653  66   664  665  666  668  67   68   69   7    70   71   72   73  
                          74   75   76   77   78   79   795  8    80   800  801  805  806  807  808  809  81   82   83   84   841  85   86   866 
                          87   88   89   891  896  897  898  899  9    90   91   92   93   95   954  957  96   961  962  963  964
                          965  97   970  98   989  99
                        }
  controlledprovinces = { 1    10   100  101  103  1036 104  105  106  107  108  109  11   110  111  112  113  1135 1136 114  1147 1148 115  116  1160
                          1163 1164 1165 1166 117  118  119  12   121  124  125  126  127  128  129  13   131  132  14   1409 15   1563 16  
                          1606 1607 1609 1610 1611 1614 1622 1683 1684 1686 1687 1688 1689 1690 1691 1692 17   1720 1752 1756 1759 1761 1764 1769 1770
                          1867 19   2    20   21   22   2245 23   24   25   26   27   28   29   294  295  3    30   31   335  336  337  342  343 
                          344  345  346  367  396  399  405  444  5    512  513  514  515  516  517  518  519  520  521  522  523  524  525  526  534 
                          535  538  542  543  544  545  561  563  567  572  573  581  584  586  587  591  6    652  653  7    795  8    800  801 
                          805  806  807  808  809  866  891  896  897  898  899  9    93   954  957  96   962  963  964  965  97  
                          98   99
                        }
  techapps            = { 10050 10060 10070 10080 10090 1010  10150 10160 10190 1020  10200 10210 10220 1030  1040  10440 10490 1050  1110  1120 
                          1130  1140  1150  1210  1220  1230  1240  1250  1470  1490  1510  1530  1550  1560  1570  1580  1590  1650  1660  1670 
                          1680  1690  1750  1760  1770  1780  1790  1850  1860  1870  1950  1960  1970  1980  2010  2020  20210 20220 2030  20310
                          20320 2040  20410 2050  20510 20520 2060  2070  2080  2310  2320  2330  2360  2370  2610  2620  2630  2640  2650  2660  2910  2920 
                          2930  2940  2950  2960  3010  3020  3030  3040  30410 30420 30430 30440 30450 3050  30510 30520 30530 30540 30550 3110 
                          3120  3130  3140  3150  3210  3220  3230  3240  3250  3310  3320  3330  3340  3350  3410  3460  3470  3480  3490  3500 
                          3560  3570  3610  3620  3630  3640  3650  3710  3720  3730  3740  3750  3810  3820  3830  3840  3850  3910  3920  3930 
                          3940  3950  3960  40100 40110 40120 40130 40200 40210 40220 40230 4390  4400  4410  4420  4430  4480  4490  4500  4510 
                          4560  4570  4580  50020 50030 50040 50050 50070 50080 50090 5010  50100 50110 50120 5020  50290 5030  50300 50310 5040 
                          5090  5100  5110  5120  5170  5180  5190  5200  5250  5260  5270  5280  5330  5340  5350  5360  5370  5410  5420  5430 
                          5460  5490  5500  5600  5610  5620  5630  5680  5690  5760  5770  5780  5790  5800  5810  5820  5830  5860 
                          5910  5920  5930  5940  5950  7010  7500  7510  7520  7530  7670 
                          7680  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9560  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990  10390 4010  4020  4030 
                          4040  4050  4110  4120  4130  4140  4150  4210  4220  4230  4240  4250
                          4640  4650  4660  4670  4680  4820  4830  4840  4850  4860  40000 40010 40020 40030 40040
                          50320 5700  5710  40140 7030  7040  7050
                          2000  2210  3000  4000  5000  6120  6130  6310  6320  6330  6650  6660  
                        }
  nationalprovinces   = { 45   50   51   52   65   68   69   70   80   81   82   83   85   86   87   88   89   90   312  313  314  315  375  376  374 
                          76   67   75   74   66   547  970  989  1014 1015 1016 1018 1405 56   316  73   72   44   43   18   366  527  367  529  365 
                          364  363  362  358  328  327  326  325  324  359  361  322  323  59   60   61   62   63   318  317  64   54   42   55   41  
                          57   58   32   33   34   35   36   37   38   39   40   320  321  528  319  360  1022 1643 1676 2242 2509 2514 2555 2557 567 
                          581  841  875  898  899  1135 1691 1692 1752 1761 1769 1770 515  525  526  534  544  545  524  523  522  521  520  519  518 
                          517  516  542  543  513  514  512  379  369  368  531  370  371  378  666  668  1408 71   46   47   77   78   79   1019 49  
                          48   1082 801  561  10   11   12   13   14   16   17   19   20   21   22   23   1160 1164 1720 2245 3    5    6    7    8   
                          9    1165 1166 15   1409 28   29   348  538  573  584  587  795  866  896  1147 1148 394  395  401  396  398  399  402  403 
                          393  410  411  412  392  400  405  563  653  2319 2321 335  336  337  344  345  965  1163 1563 1036 1867 332  333  334  338 
                          339  340  341  342  343  346  347  349  350  351  352  353  354  355  356  357  536  537  1726 1161 1531 1714 1734 329  330 
                          331  535  961  962  963  964  1157 1162 1532 1537 2243 2244 954  957  373  377  460  461  462  463  464  465  2327 2328 2329
                          84   298  299  300  301  296  297  310  309  311  546  27   26   25   24   30   93   99   98   97   96   100  101  106  105 
                          119  115  113  121  126  127  2    91   92   120  122  292  293  294  295  800  103  141  142  140  138  139  137  131  
                          132  136  148  147  144  149  193  194  195  196  199  1886 203  204  205  197  198  202  206  207  511  577  214  2606 211 
                          222  479  480  481  484  485  486  487  488  489  504  1876 302  304  308  473  482  1400 1595 1623 1779 1810 1811 208  303 
                          305  306  307  483  505  508  509  1875 1884 31   444  470  469  468  471  472  466  467  474  475  53   1888 476  477  478 
                          490  1887 1889 224  456  457  458  491  492  497  1890 2447 419  420  422  421  417  416  1911 2323 2324 424  425  431  426 
                          432  436  433  2603 2450 2449 2604 1402 423  428  498  1403 1899 427  429  430  495  496  1449 2602 291  380  382  383  384 
                          385  386  387  388  389  413  414  415  418  451  452  453  454  455  459  493  494  1057 1168 1169 1891 1892 1893 1894 1895
                          1896 1897 381  2325 2326 1    390  391  664  665  530  532  533  372  104  107  108  109  110  111  112  114  116  117  118 
                          124  125  128  129  871  873  874  223  510  95   209  213  435  434  2605 230  1401 1173 507  500  499  501  229  502  506 
                          1885 562  503  102  210 
                        }
#free                = { metal = 10 rare_materials = 25 oil = 10 }
inventions             = { 8006 8011 8001 8000 8012 8009 }
  landunit =
  { id       = { type = 25001 id = 4678 }
    name     = "アイルランド方面軍司令部"
    location = 30
    home     = 30
    division =
    { id            = { type = 25001 id = 4680 }
      name          = "第1軍司令部"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4681 }
    name     = "第22軍団"
    location = 24
    home     = 24
    division =
    { id            = { type = 25001 id = 4683 }
      name          = "第1機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4684 }
    name     = "第23軍団"
    location = 28
    home     = 28
    division =
    { id            = { type = 25001 id = 4686 }
      name          = "第1装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4690 }
    name     = "第24軍団"
    location = 108
    home     = 108
    division =
    { id            = { type = 25001 id = 4692 }
      name          = "第1戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4693 }
      name          = "第2機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4694 }
    name     = "第25軍団"
    location = 98
    home     = 98
    division =
    { id            = { type = 25001 id = 4696 }
      name          = "第2戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4697 }
      name          = "第3機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4698 }
    name     = "第26軍団"
    location = 93
    home     = 93
    division =
    { id            = { type = 25001 id = 4700 }
      name          = "第3戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4701 }
      name          = "第4機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4702 }
    name     = "第27軍団"
    location = 112
    home     = 112
    division =
    { id            = { type = 25001 id = 4704 }
      name          = "第4戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4705 }
      name          = "第2装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4706 }
      name          = "第3装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4707 }
    name     = "スカンジナヴィア方面北部軍司令部"
    location = 127
    home     = 127
    division =
    { id            = { type = 25001 id = 4709 }
      name          = "第3軍司令部"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4710 }
    name     = "第28軍団"
    location = 132
    home     = 132
    division =
    { id            = { type = 25001 id = 4712 }
      name          = "第5戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4713 }
      name          = "第6戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4714 }
      name          = "第1機甲大隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4715 }
    name     = "第29軍団"
    location = 132
    home     = 132
    division =
    { id            = { type = 25001 id = 4717 }
      name          = "第2機甲大隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4718 }
      name          = "第4装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4719 }
      name          = "第5装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4720 }
    name     = "第30軍団"
    location = 132
    home     = 132
    division =
    { id            = { type = 25001 id = 4722 }
      name          = "第3機甲大隊"
      model         = 5
      brigade_model = 0
      type          = armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4723 }
      name          = "第4機甲大隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4724 }
      name          = "第5機甲大隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4725 }
    name     = "第31軍団"
    location = 127
    home     = 127
    division =
    { id            = { type = 25001 id = 4727 }
      name          = "第7戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4728 }
      name          = "第8戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4729 }
      name          = "第6機甲大隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4730 }
    name     = "第32軍団"
    location = 127
    home     = 127
    division =
    { id            = { type = 25001 id = 4732 }
      name          = "第7機甲大隊"
      model         = 5
      brigade_model = 0
      type          = armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4733 }
      name          = "第8機甲大隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4734 }
      name          = "第9機甲大隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4735 }
    name     = "第33軍団"
    location = 127
    home     = 127
    division =
    { id            = { type = 25001 id = 4737 }
      name          = "第5機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4738 }
      name          = "第6機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4739 }
      name          = "第7機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4740 }
      name          = "第8機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4741 }
    name     = "第34軍団"
    location = 127
    home     = 127
    division =
    { id            = { type = 25001 id = 4743 }
      name          = "第101戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = bergsjaeger
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4744 }
      name          = "第102戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4745 }
      name          = "第103戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = bergsjaeger
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4746 }
    name     = "第35軍団"
    location = 131
    home     = 131
    division =
    { id            = { type = 25001 id = 4748 }
      name          = "第9戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4749 }
      name          = "第10戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4750 }
      name          = "第10機甲大隊"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4751 }
    name     = "第36軍団"
    location = 131
    home     = 131
    division =
    { id            = { type = 25001 id = 4753 }
      name          = "第11戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4754 }
      name          = "第6装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4755 }
      name          = "第7装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4756 }
    name     = "第37軍団"
    location = 131
    home     = 131
    division =
    { id            = { type = 25001 id = 4758 }
      name          = "第11機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4759 }
      name          = "第12機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4760 }
      name          = "第13機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4766 }
    name     = "イギリス方面軍司令部"
    location = 19
    home     = 19
    division =
    { id            = { type = 25001 id = 4768 }
      name          = "第4軍司令部"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4769 }
    name     = "第39軍団"
    location = 19
    home     = 19
    division =
    { id            = { type = 25001 id = 4771 }
      name          = "第9機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4772 }
      name          = "第10機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4773 }
      name          = "第11機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4774 }
      name          = "第12機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4780 }
    name     = "第41軍団"
    location = 1160
    home     = 1160
    division =
    { id            = { type = 25001 id = 4782 }
      name          = "第13機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4783 }
      name          = "第8装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4784 }
      name          = "第9装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4785 }
    name     = "第42軍団"
    location = 23
    home     = 23
    division =
    { id            = { type = 25001 id = 4787 }
      name          = "第14戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4788 }
      name          = "第15戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4789 }
      name          = "第15機甲大隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4790 }
    name     = "第43軍団"
    location = 23
    home     = 23
    division =
    { id            = { type = 25001 id = 4792 }
      name          = "第10装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4793 }
      name          = "第11装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4794 }
      name          = "第12装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4795 }
    name     = "第44軍団"
    location = 21
    home     = 21
    division =
    { id            = { type = 25001 id = 4797 }
      name          = "第16戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4798 }
      name          = "第17戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4799 }
      name          = "第16機甲大隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4800 }
    name     = "第45軍団"
    location = 21
    home     = 21
    division =
    { id            = { type = 25001 id = 4802 }
      name          = "第17機甲大隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4803 }
      name          = "第13装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4804 }
      name          = "第14装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4805 }
    name     = "第46軍団"
    location = 20
    home     = 20
    division =
    { id            = { type = 25001 id = 4807 }
      name          = "第18戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4808 }
      name          = "第19戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4809 }
      name          = "第18機甲大隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4810 }
    name     = "第47軍団"
    location = 20
    home     = 20
    division =
    { id            = { type = 25001 id = 4812 }
      name          = "第19機甲大隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4813 }
      name          = "第15装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4814 }
      name          = "第16装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4815 }
    name     = "第48軍団"
    location = 17
    home     = 17
    division =
    { id            = { type = 25001 id = 4817 }
      name          = "第20機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4818 }
      name          = "第21機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4819 }
      name          = "第22機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4825 }
    name     = "第50軍団"
    location = 1720
    home     = 1720
    division =
    { id            = { type = 25001 id = 4827 }
      name          = "第20戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4828 }
      name          = "第14機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4829 }
      name          = "第15機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4830 }
      name          = "第19装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4831 }
      name          = "第20装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4832 }
    name     = "イタリア半島方面軍司令部"
    location = 516
    home     = 516
    division =
    { id            = { type = 25001 id = 4834 }
      name          = "第5軍司令部"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4835 }
    name     = "第51軍団"
    location = 513
    home     = 513
    division =
    { id            = { type = 25001 id = 4837 }
      name          = "第21戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4838 }
      name          = "第22戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 4839 }
      name          = "第24機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4840 }
    name     = "第52軍団"
    location = 367
    home     = 367
    division =
    { id            = { type = 25001 id = 4842 }
      name          = "第23戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4843 }
    name     = "第53軍団"
    location = 545
    home     = 545
    division =
    { id            = { type = 25001 id = 4845 }
      name          = "第24戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4846 }
    name     = "第54軍団"
    location = 396
    home     = 396
    division =
    { id            = { type = 25001 id = 4848 }
      name          = "第25戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 4849 }
    name     = "第55軍団"
    location = 444
    home     = 444
    division =
    { id            = { type = 25001 id = 4851 }
      name          = "第26戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
  }
  # #
  landunit =
  { id       = { type = 25001 id = 5009 }
    name     = "イべリア半島方面軍司令部"
    location = 336
    home     = 336
    division =
    { id            = { type = 25001 id = 5010 }
      name          = "第8軍司令部"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 5011 }
    name     = "第54軍団"
    location = 342
    home     = 342
    division =
    { id            = { type = 25001 id = 5012 }
      name          = "第20戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5013 }
      name          = "第14機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5014 }
      name          = "第15機械化装甲歩兵大隊"
      model         = 3
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5015 }
      name          = "第19装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5016 }
      name          = "第20装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 5017 }
    name     = "第51軍団"
    location = 512
    home     = 512
    division =
    { id            = { type = 25001 id = 5018 }
      name          = "第21戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5019 }
      name          = "第22戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5020 }
      name          = "第24機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 5021 }
    name     = "第58軍団"
    location = 512
    home     = 512
    division =
    { id            = { type = 25001 id = 5022 }
      name          = "第19装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5023 }
      name          = "第20装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5024 }
      name          = "第20装甲大隊"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 5025 }
    name     = "第62軍団"
    location = 513
    home     = 513
    division =
    { id            = { type = 25001 id = 5026 }
      name          = "第52機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5027 }
      name          = "第115機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5028 }
      name          = "第241機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 5029 }
    name     = "第62軍団"
    location = 962
    home     = 962
    division =
    { id            = { type = 25001 id = 5030 }
      name          = "第110機甲大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 5031 }
    name     = "第68軍団"
    location = 346
    home     = 346
    division =
    { id            = { type = 25001 id = 5032 }
      name          = "第158機甲大隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 5033 }
    name     = "第78軍団"
    location = 343
    home     = 343
    division =
    { id            = { type = 25001 id = 5034 }
      name          = "第89戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5035 }
      name          = "第331戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 5036 }
    name     = "第78軍団"
    location = 965
    home     = 965
    division =
    { id            = { type = 25001 id = 5037 }
      name          = "第118戦術機甲大隊"
      model         = 3
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 5038 }
      name          = "第263戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4852 }
    name     = "バルト海艦隊"
    location = 12
    home     = 12
    base     = 12
    division =
    { id       = { type = 25002 id = 4853 }
      name     = "King George V"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4855 }
      name     = "HMS Prince of Wales"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 48550 }
      name     = "HMS Anson"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 48551 }
      name     = "HMS Vanguard"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4856 }
      name     = "HMS Duke of York"
      model    = 3
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4857 }
      name     = "Gascogne"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4854 }
      name     = "Richelieu"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4858 }
      name     = "Duquesne"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4859 }
      name     = "Tourville"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4860 }
      name     = "Suffren"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4861 }
      name     = "Colbert"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4862 }
      name     = "Le Hardi"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4863 }
      name     = "Foudroyant"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4864 }
      name     = "L'Adroit"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4865 }
      name     = "Casque"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4866 }
      name     = "Lansquenet"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4867 }
      name     = "Mameluck"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4868 }
    name     = "第一強襲艦隊"
    location = 12
    home     = 12
    base     = 12
    division =
    { id       = { type = 25002 id = 4870 }
      name     = "Oswald Boelcke"
      model    = 4
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 25002 id = 4871 }
      name     = "Josef Jacobs"
      model    = 4
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 25002 id = 4872 }
      name     = "von der Tann"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4873 }
      name     = "Moltke"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4874 }
      name     = "Goeben"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4875 }
      name     = "Seydlitz"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4876 }
      name     = "Stuttgart"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4877 }
      name     = "Stettin"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4878 }
      name     = "Dresden"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4879 }
      name     = "Nautilus"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4880 }
      name     = "Albatross"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4881 }
      name     = "Datura"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4882 }
      name     = "Francoa"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4883 }
      name     = "Fresia"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4884 }
      name     = "Godetia"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4885 }
      name     = "Djemnah"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4886 }
      name     = "Frondeur"
      model    = 6
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4887 }
    name     = "第一輸送艦隊"
    location = 12
    home     = 12
    base     = 12
    division =
    { id       = { type = 25002 id = 4889 }
      name     = "Sirocco"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4890 }
      name     = "Flandre"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4891 }
      name     = "Gallia"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4892 }
      name     = "Gange"
      model    = 3
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4893 }
    name     = "第一潜水艦隊"
    location = 12
    home     = 12
    base     = 12
    division =
    { id       = { type = 25002 id = 4895 }
      name     = "HMS Oberon"
      model    = 4
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4896 }
      name     = "HMS Otway"
      model    = 4
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4897 }
      name     = "HMS Oxley"
      model    = 4
      type     = submarine
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4902 }
    name     = "北海艦隊"
    location = 21
    home     = 21
    base     = 21
    division =
    { id       = { type = 25002 id = 4904 }
      name     = "Charles de Gaulle"
      model    = 4
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 25002 id = 4905 }
      name     = "HMS Lion"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4906 }
      name     = "HMS Thunderer"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4907 }
      name     = "Foch"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4908 }
      name     = "Dupleix"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4909 }
      name     = "Algerie"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4910 }
      name     = "Belliquese"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4911 }
      name     = "Bison"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4912 }
      name     = "L'Intrepide"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4913 }
      name     = "Le Temeraire"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4914 }
      name     = "L'Aventurier"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4915 }
      name     = "L'Opiniatre"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4916 }
      name     = "L'Iphigenie"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4917 }
      name     = "La Bayonnaise"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4918 }
      name     = "La Bombarde"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4919 }
      name     = "L'Incomprise"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4920 }
      name     = "La Poursuivante"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4921 }
    name     = "第二強襲艦隊"
    location = 21
    home     = 21
    base     = 21
    division =
    { id       = { type = 25002 id = 4923 }
      name     = "Wilhelm Frankl"
      model    = 3
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 25002 id = 4924 }
      name     = "Franz Buchner"
      model    = 3
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 25002 id = 4925 }
      name     = "Derflinger"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4926 }
      name     = "Lutzow"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4927 }
      name     = "Hindenburg"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4928 }
      name     = "Mackensen"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4929 }
      name     = "Kolberg"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4930 }
      name     = "Mainz"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4931 }
      name     = "Koln"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4932 }
      name     = "Augsburg"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4933 }
      name     = "Magdeburg"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4934 }
      name     = "Golo"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4935 }
      name     = "Ipeca"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4936 }
      name     = "Lutetia"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4937 }
      name     = "Niagara"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4938 }
      name     = "Polynesian"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4939 }
      name     = "Paulowina"
      model    = 5
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4940 }
    name     = "第三輸送艦隊"
    location = 21
    home     = 21
    base     = 21
    division =
    { id       = { type = 25002 id = 4942 }
      name     = "La Cordeliere"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4943 }
      name     = "Reseda"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4944 }
      name     = "Farouche"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4945 }
      name     = "Favori"
      model    = 3
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4946 }
    name     = "第六潜水艦隊"
    location = 21
    home     = 21
    base     = 21
    division =
    { id       = { type = 25002 id = 4948 }
      name     = "HMS Odin"
      model    = 3
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4949 }
      name     = "HMS Olympus"
      model    = 3
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4950 }
      name     = "HMS Orpheus"
      model    = 3
      type     = submarine
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4955 }
    name     = "地中海艦隊"
    location = 525
    home     = 525
    base     = 525
    division =
    { id       = { type = 25002 id = 4957 }
      name     = "Joffre"
      model    = 4
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 25002 id = 4958 }
      name     = "HMS Temeraire"
      model    = 3
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4959 }
      name     = "HMS Conqueror"
      model    = 3
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4960 }
      name     = "Alma"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4961 }
      name     = "Armide"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4962 }
      name     = "Atalante"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4963 }
      name     = "Triomphante"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4964 }
      name     = "Baliste"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4965 }
      name     = "Branlebas"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4966 }
      name     = "Bouclier"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4967 }
      name     = "Le Fier"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4968 }
      name     = "L'Agile"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4969 }
      name     = "L'Entreprenant"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4970 }
      name     = "Le Farouche"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4971 }
      name     = "L'Alsacien"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4972 }
      name     = "Le Corse"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4973 }
      name     = "Le Breton"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4974 }
    name     = "第三強襲艦隊"
    location = 525
    home     = 525
    base     = 525
    division =
    { id       = { type = 25002 id = 4975 }
      name     = "Karl Marx"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4976 }
      name     = "Peenemunde"
      model    = 3
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 25002 id = 4977 }
      name     = "Oskar Freiherr von Boenigk"
      model    = 3
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 25002 id = 4978 }
      name     = "Yorck"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4979 }
      name     = "Roon"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4980 }
      name     = "Friedrich Carl"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4981 }
      name     = "PreuBen"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4982 }
      name     = "Sachsen"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4983 }
      name     = "Breslau"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4984 }
      name     = "StraBburg"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4985 }
      name     = "Stralsund"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4986 }
      name     = "Rostock"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4987 }
      name     = "Graudenz"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4988 }
      name     = "Grognard"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4989 }
      name     = "Damier"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4990 }
      name     = "Ivoise"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4991 }
      name     = "Troupier"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4992 }
      name     = "Veteran"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4993 }
      name     = "Furieux"
      model    = 5
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 4994 }
    name     = "第五輸送艦隊"
    location = 525
    home     = 525
    base     = 525
    division =
    { id       = { type = 25002 id = 4996 }
      name     = "Jaguar"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4997 }
      name     = "Franc-Tireur"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4998 }
      name     = "Fusiler"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 4999 }
      name     = "Sauge"
      model    = 3
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 5000 }
    name     = "第五潜水艦隊"
    location = 525
    home     = 525
    base     = 525
    division =
    { id       = { type = 25002 id = 5002 }
      name     = "HMS Osiris"
      model    = 2
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5003 }
      name     = "HMS Oswald"
      model    = 2
      type     = submarine
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5004 }
      name     = "HMS Otus"
      model    = 2
      type     = submarine
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 5009 }
    name     = "西ドイツ海軍第一艦隊"
    location = 20
    home     = 20
    base     = 20
    division =
    { id       = { type = 25002 id = 5010 }
      name     = "Freidrich der Grosse"
      model    = 3
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5011 }
      name     = "Scharnhorst"
      model    = 2
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5012 }
      name     = "Gneisenau"
      model    = 2
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5013 }
      name     = "Admiral Graf Spee"
      model    = 2
      type     = Heavy_Cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5014 }
      name     = "Prinz Eugen"
      model    = 2
      type     = Heavy_Cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5015 }
      name     = "Brandenburg"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5016 }
      name     = "Bremen"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5017 }
      name     = "Niedersachsen"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5018 }
      name     = "Rheinland-Pfalz"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 5019 }
    name     = "西ドイツ海軍第2艦隊"
    location = 20
    home     = 20
    base     = 20
#    division =
#    { id       = { type = 25002 id = 5020 }
#      name     = "Lili Marleen"
#      model    = 2
#      type     = escort_carrier
#      strength = 100.0000
#      extra1        = cavalry_brigade
#      brigade_model1= 4
#    }
    division =
    { id       = { type = 25002 id = 5021 }
      name     = "Graf Zeppelin"
      model    = 2
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 25002 id = 5022 }
      name     = "Peter Strasser"
      model    = 2
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 25002 id = 5023 }
      name     = "Krefeld"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5024 }
      name     = "Essen"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5025 }
      name     = "Regensburg"
      model    = 2
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5026 }
      name     = "Sachsen"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5027 }
      name     = "Emden"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5028 }
      name     = "Cologne"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5029 }
      name     = "Karlsruhe"
      model    = 2
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 25002 id = 5030 }
    name     = "西ドイツ海軍第3艦隊"
    location = 20
    home     = 20
    base     = 20
    division =
    { id       = { type = 25002 id = 5031 }
      name     = "Berlin"
      model    = 1
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5032 }
      name     = "Frankfurt am Main"
      model    = 1
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 25002 id = 5033 }
      name     = "Walchensee"
      model    = 1
      type     = transport
      strength = 100.0000
    }
  }
  navaldivision = {
    dormant = yes
    id = { type = 25002 id = 5034 }
    name = "Lili Marleen"
    strength = 100
    experience = 50
    type = escort_carrier
    model = 3
    extra1        = cavalry_brigade
    brigade_model1= 4
  }
  landdivision = {
    dormant = yes
    id = { type = 25001 id = 14 }
    name = "ルドルフ帝冠戦術機甲大隊"
    strength = 100
    experience = 85
    type = paratrooper
    model = 9
  }
  landdivision = {
    dormant = yes
    id = { type = 25001 id = 15 }
    name = "聖イシュトヴァーン王冠戦術機甲大隊"
    strength = 100
    experience = 85
    type = paratrooper
    model = 9
  }
}