
##############################
# Country definition for U04 #
##############################

province =
{ id       = 631
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # インドール
province = { id = 635 ic = 2 } # ラーイガル
province = { id = 669 ic = 3 } # ブルハーンプル
province =
{ id       = 702
  air_base = { size = 2 current_size = 2 }
}            # ラーヤチュール
province =
{ id       = 773
  air_base = { size = 2 current_size = 2 }
}            # コインバトール
province =
{ id       = 781
  air_base = { size = 2 current_size = 2 }
}            # アディラーバード
province =
{ id       = 791
  air_base = { size = 2 current_size = 2 }
}            # バランギル
province = { id = 1195 ic = 3 air_base = 5 } # 光洲(コワンチュ)
province = { id = 1196 ic = 2 } # 大邱(テグ)
province = { id = 1197 ic = 3 air_base = 5 } # 釜山(プサン)
province = { id = 1201 ic = 4 } # 平壌(ピョンヤン)
province =
{ id         = 1285
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
}              # クルナ
province =
{ id         = 1289
  anti_air   = 1
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 1 current_size = 1 }
}              # ソンクラー
province = { id = 1297 ic = 2 } # シットウェ(ビルマ)
province = { id = 1298 ic = 2 } # パテイン(ビルマ)
province =
{ id         = 1299
  anti_air   = 3
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  ic         = 9
}              # ラングーン(ビルマ)
province = { id = 1301 ic = 1 } # バゴー(ビルマ)
province = { id = 1302 ic = 1 } # モーラミャイン(ビルマ)
province = { id = 1306 ic = 1 } # ムアンサイ
province =
{ id         = 1326
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
}              # ハイフォン
province = { id = 1329 ic = 3 } # ヴィエンチャン
province = { id = 1331 ic = 1 } # コンケーン
province = { id = 1332 ic = 1 } # パクセ
province =
{ id       = 1333
  anti_air = 4
  air_base = { size = 2 current_size = 2 }
}            # ハノイ
province =
{ id         = 1337
  anti_air   = 3
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  supplypool = 1000
  oilpool    = 500
}              # サイゴン
province =
{ id         = 1339
  ic         = 3
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # プノンペン
province = { id = 1340 ic = 2 } # シェムリアップ
province = { id = 1342 ic = 3 } # チョンブリ
province = { id = 1343 ic = 9 } # バンコク
province =
{ id         = 1345
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 4 current_size = 4 }
}              # ナコーンサワン
province = { id = 1348
             ic = 3 
             landfort = 10} # ナコンシータマラート
province = { id = 1351 ic = 1 } # ジョホールバール
province =
{ id         = 1352
  ic         = 6
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
}              # クアラルンプール
province =
{ id          = 1353
  anti_air    = 6
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 8 current_size = 8 }
  landfort    = 5
  coastalfort = 5
  ic          = 10
}               # シンガポール
province = { id = 1354 ic = 1 } # パンカルピナン(バンカ島)
province = { id = 1355 ic = 2 } # クタラジャ
province = { id = 1358 ic = 4 } # パレンバン
province = { id = 1376 ic = 2 } # 清津(チョンジン)
province = { id = 1393 ic = 2 } # 新義州(シンウィジュ)
province =
{ id         = 1457
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
  ic         = 2
}              # カルカッタ
province = { id = 1458 ic = 3 } # ブヴァネーシュヴァル
province = { id = 1459 ic = 2 } # ランチ
province =
{ id       = 1462
  air_base = { size = 5 current_size = 5 }
}            # アマラヴァティー
province =
{ id       = 1469
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # デリー
province =
{ id         = 1481
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 1 current_size = 1 }
}              # カラチ(パキスタン)
province =
{ id         = 1505
  anti_air   = 3
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  oilpool    = 1000
  supplypool = 2000
  ic         = 4
}              # ボンベイ
province = { id = 1507 ic = 3 } # ハイデラバード(インド)
province = { id = 1508 ic = 2 } # ヴィシャーカパトナム
province = { id = 1509 ic = 3 } # ネッロール
province = { id = 1512 ic = 3 } # パナジ
province =
{ id         = 1513
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # マンガロール
province = { id = 1515 ic = 2 } # マドゥライ
province = { id = 1516 ic = 1 } # キャンディ(マハ・ヌヴァラ)
province =
{ id         = 1517
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  ic         = 2
}              # コロンボ
province =
{ id         = 1518
  air_base   = { size = 8 current_size = 8 }
  naval_base = { size = 10 current_size = 10 }
}
province = { id = 1519 ic = 1 } # カラグプル
province = { id = 1553 ic = 1 } # コタバル
province =
{ id          = 1591
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 4 current_size = 4 }
  coastalfort = 3
  oilpool     = 1000
  supplypool  = 2000
  ic          = 3
}               # トリンコマリー
province =
{ id         = 1613
  anti_air   = 2
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 500
}              # バタビア
province = { id = 1629 ic = 3 } # バンドン
province = { id = 1630 ic = 2 } # チレボン
province = { id = 1631 ic = 8 } # ジョグジャカルタ
province =
{ id         = 1632
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # スラバヤ
province = { id = 1640 ic = 1 } # マカッサル
province =
{ id         = 1644
  anti_air   = 1
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 4 current_size = 4 }
  ic         = 2
}              # クチン
province =
{ id         = 1646
  ic         = 6
  naval_base = { size = 7 current_size = 7 }
}              # バンダルスリブガワン(ブルネイ)
province =
{ id         = 1649
  ic         = 1
  anti_air   = 1
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 500
}              # バリクパパン
province = { id = 1650 ic = 3 } # バンジャルマシン
province = { id = 1651 ic = 1 } # パル
province =
{ id         = 1653
  anti_air   = 1
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 500
}              # マナド
province =
{ id         = 1656
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 500
}              # アンボン島
province =
{ id         = 1661
  anti_air   = 1
  naval_base = { size = 1 current_size = 1 }
  air_base   = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 500
}              # バンダールランプン
province = { id = 1665 ic = 2 } # ホランディア
province =
{ id         = 1694
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # マドラス
province = { id = 1735 ic = 1 } # プエルト・プリンセサ(パラワン島)
province =
{ id         = 1737
  anti_air   = 2
  naval_base = { size = 2 current_size = 2 }
  air_base   = { size = 2 current_size = 2 }
  landfort   = 7
  ic         = 5
}              # マニラ
province =
{ id         = 1738
  anti_air   = 2
  #landfort   = 7
  air_base   = { size = 2 current_size = 2 }
  Naval_base = { size = 4 current_size = 4 }
  ic         = 1
}              # オロンガポ
province =
{ id       = 1744
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # カルバヨグ(サマール島)
province = { id = 1745 ic = 1 } # タクロバン(レイテ島)
province =
{ id       = 1750
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
  ic       = 2
}            # ダバオ(ミンダナオ島)
province = { id = 1758 ic = 2 } # コーチ
province = { id = 2219 ic = 3 } # 束草(ソクチョ)
province = { id = 2226 ic = 3 air_base = 5 } # 大田(テジョン)
province =
{ id       = 2592
  air_base = { size = 2 current_size = 2 }
}            # ディブルーガル
province = { id = 1197 supplypool = 2000 } #釜山

#####################
# Country main data #
#####################

country =
{ tag                 = U04
  manpower            = 600
  energy              = 4000
  metal               = 3500
  rare_materials      = 5000
  oil                 = 6000
  supplies            = 3500
  money               = 500
  capital             = 1353
  regular_id          = U06
  transports          = 350
  escorts             = 150
  policy              = { democratic = 3 political_left = 2 freedom = 2 free_market = 10 professional_army = 9 defense_lobby = 8 interventionism = 9 }
  ownedprovinces      = { 1194 1195 1196 1197 1198 1200 1201 1284 1285 1286 1287 1288 1289 1290 1291 1292 1295 1296 1297 1298 1299 1301 1302 1303 1304
                          1305 1306 1326 1328 1329 1330 1331 1332 1333 1334 1335 1336 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347 1348 1349
                          1350 1351 1352 1353 1354 1355 1356 1357 1358 1359 1373 1376 1391 1392 1393 1454 1456 1457 1458 1459 1460 1461 1462 1463 1464
                          1465 1466 1467 1468 1469 1470 1471 1472 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1494 1505 1506 1507 1508 1509 1510
                          1511 1512 1513 1514 1515 1516 1517 1518 1519 1553 1554 1589 1590 1591 1592 1612 1613 1615 1616 1628 1629 1630 1631 1632 1633
                          1634 1635 1636 1637 1638 1639 1640 1641 1642 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654 1655 1656 1657 1658 1659
                          1660 1661 1662 1663 1664 1665 1673 1674 1694 1695 1699 1701 1705 1721 1731 1735 1736 1737 1738 1739 1740 1741 1742 1743 1744
                          1745 1746 1747 1748 1749 1750 1757 1758 1762 1817 2085 2091 2092 2094 2099 2104 2106 2111 2124 2133 2175 2198 2199 2219 2226
                          2231 2236 2592 593  597  599  611  631  635  661  669  685  687  697  702  703  714  726  729  736  769  771  773  774  775 
                          777  781  785  791  1484 1486 1487 1492 1493 1455 1473 1199 1300
                        }
  controlledprovinces = { 661  1373 1612 1613 1628 1629 1630 1631 1632 1633 1634 1615 1641 1642 1645 1648 1649 1650 1762 1354 1355 1356 1357 1358 1359
                          1616 1661 1663 1640 1651 1652 1653 1635 1636 1637 1638 1639 1654 1655 1656 1657 1757 1658 1659 1660 1662 1664 1665 1673 1674
                          2111 1646 1735 1736 1737 1738 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 1554 1289 1349 1553 1350 1352 1351
                          1353 1647 1644 1591 1516 1517 2226 1195 1196 1197 1198 1348 1518 1199 1376 1391 1392 1393 1200 1201 2236 2219 2231 
                          1300 1290 1291 1292 1297 1298 1299 1301 1302 1304 1346 1295 1296 1305 1347 1345 1343 1342 1331 1330 1344 1303
                          1328 1333 1334 1335 1337 1338 1326 1306 1329 1332 1336 1589 1339 1340 1341 1285 1286 1288 1590 1284 1287 1454 1457 1458 1459 
                          1461 1462 1463 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1591
                          1694 1695 1699 1701 1758 1817 2085 2091 2094 2099 2104 2106 2124 2175 2198 2592 597  635  669  697  702  703  726  729  769 
                          771  773  774  775  777  781  785  791  1194
                        }
  techapps            = { 10050 1010  10150 10190 1020  10200 10210 1030  10390 1040  10440 10490 1110  1120  1130  1210  1220  1550  1560  1570 
                          1650  1660  1850  1860  1870  1950  3010  3020  3030  3110  3120  3130  3460  3470  3810  3910  3920  3930  4390  4400 
                          4410  4480  4560  50020 50030 50040 50070 50080 50090 5010  50100 50110 5020  50290 50300 5090  5100  5170  5180  5250 
                          5330  5410  5420  5430  5460  5600  5610  5620  5760  5910  5920  7010  80080
                          80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8880  8890  8900  8910  8920  9010  9020  9030  9040  9050 
                          9190  9200  9340  9350  9360  9370  9380  9520  9530  9670  9680  9690  9700  9840  4010  4020  4030 
                          4040  4050  4110  4120  4130  4140  4150  4210  4220  4230  4240  4250
                          4640  4650  4660  4670  4680  4820  4830  4840  4850  4860  40000 40010 40020 40030 40040 2010  2020  2030  2040  2050
                          2060  2070  2080
                          6050  6060  6070  6080  6090  6260  6270  6520  6530
                        }
  nationalprovinces   = { 1194 1195 1196 1197 1198 1199 1200 1201 1284 1285 1286 1287 1288 1289 1290 1291 1292 1295 1296 1297 1298 1299 1300 1301 1302
                          1303 1304 1305 1306 1326 1328 1329 1330 1331 1332 1333 1334 1335 1336 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347
                          1348 1349 1350 1351 1352 1353 1354 1355 1356 1357 1358 1359 1373 1376 1391 1392 1393 1430 1454 1455 1456 1457 1458 1459 1460
                          1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1494 1505
                          1506 1507 1508 1509 1510 1511 1512 1513 1514 1515 1516 1517 1518 1519 1553 1554 1589 1590 1591 1592 1612 1613 1615 1616 1628
                          1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640 1641 1642 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
                          1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1673 1674 1694 1695 1699 1701 1705 1721 1728 1731 1735 1736 1737 1738
                          1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 1757 1758 1762 1817 1877 1878 2043 2085 2091 2092 2094 2099 2104
                          2106 2111 2124 2133 2175 2198 2199 2219 2226 2231 2236 2592 593  597  599  611  631  635  661  669  685  687  697  702  703 
                          714  722  726  729  736  769  771  773  774  775  777  781  785  791 
                        }
free                = { energy = 50 manpower = 0.3 metal = 30 oil = 20 }
inventions             = { 8006 }
  landunit =
  { id       = { type = 27001 id = 1 }
    name     = "第8師団"
    location = 597 
    division =
    { id            = { type = 27001 id = 2 }
      name          = "第1戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 3 }
      name          = "第1戦車大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4 }
      name          = "第2戦車大隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 5 }
    name     = "第1軍団"
    location = 1699
    division =
    { id            = { type = 27001 id = 6 }
      name          = "第2戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 7 }
      name          = "第3戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 8 }
      name          = "第1機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 9 }
    name     = "第2軍団"
    location = 669
    division =
    { id            = { type = 27001 id = 10 }
      name          = "第4戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 11 }
      name          = "第5戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 12 }
      name          = "第2機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 13 }
    name     = "第3軍団"
    location = 1463
    division =
    { id            = { type = 27001 id = 14 }
      name          = "第6戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 15 }
      name          = "第7戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 16 }
      name          = "第3機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 17 }
    name     = "第4軍団"
    location = 1461
    division =
    { id            = { type = 27001 id = 18 }
      name          = "第8戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 19 }
      name          = "第9戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 20 }
      name          = "第4機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 21 }
    name     = "第5軍団"
    location = 635
    division =
    { id            = { type = 27001 id = 22 }
      name          = "第10戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 23 }
      name          = "第11戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 24 }
      name          = "第5機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 25 }
    name     = "第6軍団"
    location = 1459
    division =
    { id            = { type = 27001 id = 26 }
      name          = "第12戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 27 }
      name          = "第13戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 28 }
      name          = "第6機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 29 }
    name     = "第7軍団"
    location = 2094
    division =
    { id            = { type = 27001 id = 30 }
      name          = "第14戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 31 }
      name          = "第15戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 32 }
      name          = "第7機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 33 }
    name     = "第8軍団"
    location = 1457
    division =
    { id            = { type = 27001 id = 34 }
      name          = "第16戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 35 }
      name          = "第17戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 36 }
      name          = "第8機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 37 }
    name     = "第9軍団"
    location = 1590
    division =
    { id            = { type = 27001 id = 38 }
      name          = "第18戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 39 }
      name          = "第19戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 40 }
      name          = "第9機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 41 }
    name     = "第10軍団"
    location = 1454
    division =
    { id            = { type = 27001 id = 42 }
      name          = "第18戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 43 }
      name          = "第19戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 44 }
      name          = "第9機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 45 }
    name     = "第11軍団"
    location = 1284
    division =
    { id            = { type = 27001 id = 46 }
      name          = "第20戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 47 }
      name          = "第21戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 48 }
      name          = "第10機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 49 }
    name     = "第12軍団"
    location = 1462
    division =
    { id            = { type = 27001 id = 50 }
      name          = "第22戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 51 }
      name          = "第23戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 52 }
      name          = "第11機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 53 }
    name     = "第13軍団"
    location = 1286
    division =
    { id            = { type = 27001 id = 54 }
      name          = "第24戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 55 }
      name          = "第25戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 56 }
      name          = "第12機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 57 }
    name     = "第14軍団"
    location = 597
    division =
    { id            = { type = 27001 id = 58 }
      name          = "第26戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 59 }
      name          = "第27戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 60 }
      name          = "第13機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 90 }
    name     = "第15軍団"
    location = 635
    division =
    { id            = { type = 27001 id = 91 }
      name          = "第26戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 92 }
      name          = "第27戦術機甲大隊"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 93 }
      name          = "第13機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 62 }
    name     = "第22軍団"
    location = 1459
    division =
    { id            = { type = 27001 id = 63 }
      name          = "第28戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 64 }
      name          = "第29戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 65 }
      name          = "第14機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 66 }
    name     = "第23軍団"
    location = 1590
    division =
    { id            = { type = 27001 id = 67 }
      name          = "第30戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 68 }
      name          = "第31戦術機甲大隊"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 69 }
      name          = "第15機甲部隊"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 70 }
    name     = "第16軍団"
    location = 1454
    division =
    { id            = { type = 27001 id = 71 }
      name          = "第32戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 72 }
      name          = "第33戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 73 }
      name          = "第16機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 74 }
    name     = "第17軍団"
    location = 1284
    division =
    { id            = { type = 27001 id = 75 }
      name          = "第34戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 76 }
      name          = "第35戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 77 }
      name          = "第17機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 78 }
    name     = "第18軍団"
    location = 1463
    division =
    { id            = { type = 27001 id = 79 }
      name          = "第36戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 80 }
      name          = "第37戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 81 }
      name          = "第18機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 82 }
    name     = "第19軍団"
    location = 669
    division =
    { id            = { type = 27001 id = 83 }
      name          = "第38戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 84 }
      name          = "第39戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 85 }
      name          = "第19機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 86 }
    name     = "第20軍団"
    location = 2094
    division =
    { id            = { type = 27001 id = 87 }
      name          = "第40戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 88 }
      name          = "第41戦術機甲大隊"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 89 }
      name          = "第20機甲部隊"
      model         = 3
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 97 }
    name     = "第1フィリピン旅団"
    location = 1738
    division =
    { id            = { type = 27001 id = 98 }
      name          = "第1沿岸砲兵大隊"
      model         = 23
      type          = garrison
      strength      = 100
      locked        = yes
    }
    division =
    { id            = { type = 27001 id = 99 }
      name          = "第2沿岸砲兵大隊"
      model         = 23
      type          = garrison
      strength      = 100
      locked        = yes
    }
    division =
    { id            = { type = 27001 id = 100 }
      name          = "第3沿岸砲兵部隊"
      model         = 23
      brigade_model = 0
      type          = garrison
      strength      = 100
      locked        = yes
    }
    division =
    { id            = { type = 27001 id = 94 }
      name          = "第4沿岸砲兵部隊"
      model         = 23
      brigade_model = 0
      type          = garrison
      strength      = 100
      locked        = yes
    }
    division =
    { id            = { type = 27001 id = 95 }
      name          = "第5沿岸砲兵部隊"
      model         = 23
      brigade_model = 0
      type          = garrison
      strength      = 100
      locked        = yes
    }
    division =
    { id            = { type = 27001 id = 96 }
      name          = "第6沿岸砲兵部隊"
      model         = 23
      brigade_model = 0
      type          = garrison
      strength      = 100
      locked        = yes
    }
  }
  navalunit =
  { id       = { type = 27002 id = 2449 }
    name     = "第1戦隊"
    location = 1353
    home     = 1353
    base     = 1353
    division =
    { id       = { type = 27002 id = 4239 }
      name     = "デリー"
      model    = 2
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4240 }
      name     = "マイソール"
      model    = 2
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4241 }
      name     = "ブラマプトラ"
      model    = 3
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4242 }
      name     = "ベトワ"
      model    = 3
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4243 }
      name     = "ベアス"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4244 }
      name     = "タルワー"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4245 }
      name     = "トリシュル"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4246 }
      name     = "タバール"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4247 }
      name     = "コルカタ"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4248 }
      name     = "コチ"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4249 }
      name     = "ラージプート"
      model    = 2
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4250 }
      name     = "ランジート"
      model    = 2
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4251 }
      name     = "ラーナ"
      model    = 2
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4252 }
      name     = "第1輸送艦/揚陸艦師団"
      model    = 4
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4253 }
      name     = "第2輸送艦/揚陸艦師団"
      model    = 4
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 4254 }
      name     = "第3輸送艦/揚陸艦師団"
      model    = 4
      type     = transport
      strength            = 100
    }
  }
  navaldivision = {
    dormant = yes
    id      = { type = 27002 id = 4257 }
    name    = "ヴィクラント"
    type    = carrier
    model   = 1
    extra1  = cag
    brigade_model1 = 4
  }
  navaldivision = {
    dormant = yes
    id      = { type = 27002 id = 4258 }
    name    = "ヴィクラマーディティヤ"
    type    = carrier
    model   = 4
    extra1  = cag
    brigade_model1 = 4
  }  
  landunit =
  { id       = { type = 27001 id = 4146 }
    name     = "第一方面軍"
    location = 1463
    home     = 1463
    #mission  = { type = none target = 1463 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4148 }
      name          = "第一方面軍司令部"
      model         = 2
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4149 }
    name     = "第二方面軍"
    location = 1454
    home     = 1454
    #mission  = { type = none target = 1454 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4151 }
      name          = "第二方面軍司令部"
      model         = 2
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4152 }
    name     = "第1軍団"
    location = 1516
    home     = 1516
    #mission  = { type = none target = 1516 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4154 }
      name          = "第1機械化歩兵大隊"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4155 }
    name     = "第2軍団"
    location = 1505
    home     = 1505
    #mission  = { type = none target = 1505 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4157 }
      name          = "第2機械化歩兵大隊"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4158 }
      name          = "第3機械化歩兵大隊"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4159 }
      name          = "第4機械化歩兵大隊"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4160 }
    name     = "第3軍団"
    location = 2094
    home     = 2094
    #mission  = { type = none target = 2094 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4162 }
      name          = "第1主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4163 }
      name          = "第2主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4164 }
      name          = "第3主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4165 }
    name     = "第4軍団"
    location = 669
    home     = 669
    #mission  = { type = none target = 669 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4167 }
      name          = "第1戦術歩行戦闘機大隊"
      model         = 2
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4168 }
      name          = "第2戦術歩行戦闘機大隊"
      model         = 2
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4169 }
      name          = "第1歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4170 }
    name     = "第5軍団"
    location = 669
    home     = 669
    #mission  = { type = none target = 669 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4172 }
      name          = "第4主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4173 }
      name          = "第5主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4174 }
      name          = "第2歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4175 }
    name     = "第6軍団"
    location = 1463
    home     = 1463
    #mission  = { type = none target = 1463 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4177 }
      name          = "第3戦術歩行戦闘機大隊"
      model         = 2
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4178 }
      name          = "第4戦術歩行戦闘機大隊"
      model         = 2
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4179 }
      name          = "第3歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4180 }
    name     = "第7軍団"
    location = 1463
    home     = 1463
    #mission  = { type = none target = 1463 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4182 }
      name          = "第6主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4183 }
      name          = "第7主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4184 }
      name          = "第4歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4185 }
    name     = "第8軍団"
    location = 1699
    home     = 1699
    #mission  = { type = none target = 1699 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4187 }
      name          = "第5戦術歩行戦闘機大隊"
      model         = 2
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4188 }
      name          = "第6戦術歩行戦闘機大隊"
      model         = 2
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4189 }
      name          = "第8主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4190 }
    name     = "第9軍団"
    location = 1461
    home     = 1461
    #mission  = { type = none target = 1461 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4192 }
      name          = "第5機械化歩兵大隊"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4193 }
      name          = "第6機械化歩兵大隊"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4194 }
      name          = "第5歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4195 }
    name     = "第10軍団"
    location = 1459
    home     = 1459
    #mission  = { type = none target = 1459 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4197 }
      name          = "第6歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4198 }
      name          = "第7歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4199 }
      name          = "第9主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4200 }
    name     = "第11軍団"
    location = 1454
    home     = 1454
    #mission  = { type = none target = 1454 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4202 }
      name          = "第8歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4203 }
      name          = "第9歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4204 }
      name          = "第10主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4205 }
    name     = "第12軍団"
    location = 597
    home     = 597
    #mission  = { type = none target = 597 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4207 }
      name          = "第10歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4208 }
      name          = "第11歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4209 }
      name          = "第11主力戦車大隊"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 27001 id = 4210 }
    name     = "第13軍団"
    location = 635
    home     = 635
    #mission  = { type = none target = 635 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 27001 id = 4212 }
      name          = "第7戦術歩行戦闘機大隊"
      model         = 2
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4213 }
      name          = "第8戦術歩行戦闘機大隊"
      model         = 2
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 27001 id = 4214 }
      name          = "第12歩兵戦車大隊"
      model         = 2
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  navalunit =
  { id       = { type = 27002 id = 5000 }
    name     = "第2戦隊"
    location = 1457
    home     = 1457
    base     = 1457
    division =
    { id       = { type = 27002 id = 5001 }
      name     = "ファタヒラー"
      model    = 2
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5002 }
      name     = "マラハヤティ"
      model    = 2
      type     = heavy_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5003 }
      name     = "ナラ"
      model    = 3
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5004 }
      name     = "ディポネゴロ"
      model    = 3
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5005 }
      name     = "ハサヌデデイン"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5006 }
      name     = "スルタン・イスカンダル・ムダ"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5007 }
      name     = "モンギシディ"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5008 }
      name     = "サマディクン"
      model    = 2
      type     = light_cruiser
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5009 }
      name     = "マルティダナタ"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5010 }
      name     = "ングラ・ライ"
      model    = 3
      type     = destroyer
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5011 }
      name     = "第4輸送艦/揚陸艦大隊"
      model    = 4
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5012 }
      name     = "第5輸送艦/揚陸艦大隊"
      model    = 4
      type     = transport
      strength            = 100
    }
    division =
    { id       = { type = 27002 id = 5013 }
      name     = "第6輸送艦/揚陸艦大隊"
      model    = 4
      type     = transport
      strength            = 100
    }
  }
}
