
##############################
# Country definition for U12 #
##############################

province = { id = 1431 air_base = 10 radar_station = 10  rocket_test = 10 infra = 2.0  anti_air = 10 } # ö\èY

#####################
# Country main data #
#####################

country =
{ tag                 = U12
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 1431
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 1431 }
  ownedprovinces      = { 1431 }
  controlledprovinces = { 1431 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 500 supplies = 1000 }
  landunit =
  { id       = { type = 15001 id = 5177 }
    name     = "ëÊ1åRíc"
    location = 183
    division =
    { id            = { type = 15001 id = 5179 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5180 }
    name     = "ëÊ2åRíc"
    location = 139
    division =
    { id            = { type = 15001 id = 5182 }
      name          = "ëÊ2BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = super_heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5183 }
    name     = "ëÊ3åRíc"
    location = 149
    division =
    { id            = { type = 15001 id = 5185 }
      name          = "ëÊ3BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5221 }
    name     = "ëÊ9åRíc"
    location = 1792
    division =
    { id            = { type = 15001 id = 5223 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5224 }
    name     = "ëÊ10åRíc"
    location = 1806
    division =
    { id            = { type = 15001 id = 5226 }
      name          = "ëÊ5BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = super_heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5282 }
    name     = "ëÊ20åRíc"
    location = 1543
    division =
    { id            = { type = 15001 id = 5284 }
      name          = "ëÊ8BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = super_heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5285 }
    name     = "ëÊ21åRíc"
    location = 1539
    division =
    { id            = { type = 15001 id = 5287 }
      name          = "ëÊ9BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5316 }
    name     = "ëÊ26åRíc"
    location = 1546
    division =
    { id            = { type = 15001 id = 5318 }
      name          = "ëÊ17BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5319 }
      name          = "ëÊ17BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5320 }
      name          = "ëÊ49BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5321 }
      name          = "ëÊ50BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5322 }
      name          = "ëÊ51BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5323 }
    name     = "ëÊ27åRíc"
    location = 1559
    division =
    { id            = { type = 15001 id = 5325 }
      name          = "ëÊ18BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5326 }
      name          = "ëÊ18BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5327 }
      name          = "ëÊ52BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5328 }
      name          = "ëÊ53BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5329 }
      name          = "ëÊ54BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5330 }
    name     = "ëÊ28åRíc"
    location = 1448
    division =
    { id            = { type = 15001 id = 5332 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5333 }
    name     = "ëÊ29åRíc"
    location = 1446
    division =
    { id            = { type = 15001 id = 5335 }
      name          = "ëÊ11BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = super_heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5336 }
    name     = "ëÊ30åRíc"
    location = 1556
    division =
    { id            = { type = 15001 id = 5338 }
      name          = "ëÊ12BETAåQ"
      model         = 33
      brigade_model = 0
      type          = hq
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5339 }
    name     = "ëÊ31åRíc"
    location = 1455
    division =
    { id            = { type = 15001 id = 5341 }
      name          = "ëÊ19BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5342 }
      name          = "ëÊ20BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5343 }
      name          = "ëÊ21BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5344 }
      name          = "ëÊ19BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5345 }
      name          = "ëÊ20BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5346 }
      name          = "ëÊ21BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5347 }
      name          = "ëÊ55BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5348 }
      name          = "ëÊ56BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5349 }
      name          = "ëÊ57BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5350 }
      name          = "ëÊ58BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5351 }
      name          = "ëÊ59BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5352 }
      name          = "ëÊ60BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5353 }
      name          = "ëÊ61BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5354 }
      name          = "ëÊ62BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5355 }
    name     = "ëÊ32åRíc"
    location = 1451
    division =
    { id            = { type = 15001 id = 5357 }
      name          = "ëÊ22BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5358 }
      name          = "ëÊ23BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5359 }
      name          = "ëÊ24BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5360 }
      name          = "ëÊ22BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5361 }
      name          = "ëÊ23BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5362 }
      name          = "ëÊ24BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5363 }
      name          = "ëÊ63BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5364 }
      name          = "ëÊ64BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5365 }
      name          = "ëÊ65BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5366 }
      name          = "ëÊ66BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5367 }
      name          = "ëÊ67BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5368 }
      name          = "ëÊ68BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5369 }
      name          = "ëÊ69BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5370 }
      name          = "ëÊ70BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5371 }
    name     = "ëÊ33åRíc"
    location = 1452
    division =
    { id            = { type = 15001 id = 5373 }
      name          = "ëÊ25BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5374 }
      name          = "ëÊ26BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5375 }
      name          = "ëÊ27BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5376 }
      name          = "ëÊ25BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5377 }
      name          = "ëÊ26BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5378 }
      name          = "ëÊ27BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5379 }
      name          = "ëÊ71BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5380 }
      name          = "ëÊ72BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5381 }
      name          = "ëÊ73BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5382 }
      name          = "ëÊ74BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5383 }
      name          = "ëÊ75BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5384 }
      name          = "ëÊ76BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5385 }
      name          = "ëÊ77BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5386 }
      name          = "ëÊ78BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5387 }
    name     = "ëÊ34åRíc"
    location = 1450
    division =
    { id            = { type = 15001 id = 5389 }
      name          = "ëÊ28BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5390 }
      name          = "ëÊ29BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5391 }
      name          = "ëÊ30BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5392 }
      name          = "ëÊ28BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5393 }
      name          = "ëÊ29BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5394 }
      name          = "ëÊ30BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5395 }
      name          = "ëÊ79BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5396 }
      name          = "ëÊ80BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5397 }
      name          = "ëÊ81BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5403 }
    name     = "ëÊ35åRíc"
    location = 1445
    division =
    { id            = { type = 15001 id = 5405 }
      name          = "ëÊ31BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5406 }
      name          = "ëÊ32BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5407 }
      name          = "ëÊ33BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5408 }
      name          = "ëÊ31BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5409 }
      name          = "ëÊ32BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5410 }
      name          = "ëÊ33BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5411 }
      name          = "ëÊ87BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5412 }
      name          = "ëÊ88BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5413 }
      name          = "ëÊ89BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5419 }
    name     = "ëÊ36åRíc"
    location = 1435
    division =
    { id            = { type = 15001 id = 5421 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5422 }
      name          = "ëÊ35BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5423 }
      name          = "ëÊ36BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5424 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5430 }
      name          = "ëÊ98BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5431 }
      name          = "ëÊ99BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5432 }
      name          = "ëÊ100BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5433 }
      name          = "ëÊ101BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5434 }
      name          = "ëÊ102BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5435 }
    name     = "ëÊ37åRíc"
    location = 1433
    division =
    { id            = { type = 15001 id = 5442 }
      name          = "ëÊ39BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5443 }
      name          = "ëÊ103BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5444 }
      name          = "ëÊ104BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5445 }
      name          = "ëÊ105BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5446 }
      name          = "ëÊ106BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5447 }
      name          = "ëÊ107BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5448 }
      name          = "ëÊ108BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5449 }
      name          = "ëÊ109BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5450 }
      name          = "ëÊ110BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 5451 }
    name     = "ëÊ38åRíc"
    location = 1421
    division =
    { id            = { type = 15001 id = 5453 }
      name          = "ëÊ40BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5454 }
      name          = "ëÊ41BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5455 }
      name          = "ëÊ42BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5456 }
      name          = "ëÊ40BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5457 }
      name          = "ëÊ41BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5458 }
      name          = "ëÊ42BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5459 }
      name          = "ëÊ111BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5460 }
      name          = "ëÊ112BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15001 id = 5461 }
      name          = "ëÊ113BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15001 id = 1 }
    name     = "ÉJÉVÉÖÉKÉãÉnÉCÉî"
    location = 1431
    division =
    { type   = garrison
      model  = 14
      id     = { type = 15004 id = 1 }
      name   = "ÉJÉVÉÖÉKÉãÉnÉCÉî"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 15004 id = 2 }
      name   = "ñÂãâ"
      locked = yes
    }
  }
}
