
##############################
# Country definition for U16 #
##############################

province = { id = 212 air_base = 10 radar_station = 10  rocket_test = 10 infra = 2.0  anti_air = 10 } # ƒ~ƒ“ƒXƒN

#####################
# Country main data #
#####################

country =
{ tag                 = U16
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 212
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 212 }
  ownedprovinces      = { 212 }
  controlledprovinces = { 212 208 211 222 229 305 306 479 480 481 483 484 485 486 487 488 489 500 501 502 503 504 505 506 507 508 
                          1875 1876 1884 303 304 307 1811 223 510 95 102 209 210 213 217 218 220 221 225 272 273 274 562 1153 1566 1874 1885 
                          193 194 195 196 197 198 199 202 203 204 205 206 207 214 509 511 577 1886 2606 155 161 226 227 228 231 232 233 234 
                          235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 258
                          259 260 261 262 263 265 266 267 268 282 1152 1154 1565 1571 1827 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 15201 id = 4072 }
    name     = "‘æ1ŒR’c"
    location = 199
    division =
    { id            = { type = 15201 id = 4074 }
      name          = "‘æ1Ži—ßŒQ"
      model         = 33
      type          = hq
      strength      = 100.0000
      brigade_model = 0
      extra         = light_armor_brigade
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15201 id = 4075 }
    name     = "‘æ2ŒR’c"
    location = 509
    division =
    { id            = { type = 15201 id = 4077 }
      name          = "‘æ2Ži—ßŒQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15201 id = 4078 }
    name     = "‘æ3ŒR’c"
    location = 307
    division =
    { id            = { type = 15201 id = 4080 }
      name          = "‘æ3Ži—ßŒQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15201 id = 4081 }
    name     = "‘æ4ŒR’c"
    location = 303
    division =
    { id            = { type = 15201 id = 4083 }
      name          = "‘æ1BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4086 }
      name          = "‘æ1BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4089 }
      name          = "‘æ4BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4090 }
      name          = "‘æ5BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4091 }
      name          = "‘æ6BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15201 id = 4097 }
    name     = "‘æ5ŒR’c"
    location = 205
    division =
    { id            = { type = 15201 id = 4099 }
      name          = "‘æ12BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4102 }
      name          = "‘æ4BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4105 }
      name          = "‘æ15BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4106 }
      name          = "‘æ16BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4107 }
      name          = "‘æ17BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15201 id = 4113 }
    name     = "‘æ6ŒR’c"
    location = 194
    division =
    { id            = { type = 15201 id = 4115 }
      name          = "‘æ23BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4118 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4121 }
      name          = "‘æ26BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4122 }
      name          = "‘æ27BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4123 }
      name          = "‘æ28BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15201 id = 4129 }
    name     = "‘æ7ŒR’c"
    location = 306
    division =
    { id            = { type = 15201 id = 4131 }
      name          = "‘æ34BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4134 }
      name          = "‘æ10BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4137 }
      name          = "‘æ37BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4138 }
      name          = "‘æ38BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4139 }
      name          = "‘æ39BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15201 id = 4145 }
    name     = "‘æ8ŒR’c"
    location = 223
    division =
    { id            = { type = 15201 id = 4147 }
      name          = "‘æ45BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4150 }
      name          = "‘æ13BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4153 }
      name          = "‘æ48BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4154 }
      name          = "‘æ49BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4155 }
      name          = "‘æ50BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15201 id = 4161 }
    name     = "‘æ9ŒR’c"
    location = 198
    division =
    { id            = { type = 15201 id = 4163 }
      name          = "‘æ56BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4166 }
      name          = "‘æ16BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4169 }
      name          = "‘æ59BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4170 }
      name          = "‘æ60BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 15201 id = 4171 }
      name          = "‘æ61BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 15201 id = 1 }
    name     = "ƒ~ƒ“ƒXƒNƒnƒCƒ”"
    location = 212
    division =
    { type   = garrison
      model  = 15
      id     = { type = 15204 id = 1 }
      name   = "ƒ~ƒ“ƒXƒNƒnƒCƒ”"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 15204 id = 2 }
      name   = "–å‹‰"
      locked = yes
    }
  }
}
