
##############################
# Country definition for U22 #
##############################

province = { id = 457 air_base = 10 radar_station = 10  rocket_test = 10  anti_air = 10 infra = 2.0 } # ƒuƒ_ƒyƒXƒg

#####################
# Country main data #
#####################

country =
{ tag                 = U22
  manpower            = 99999
  energy              = 900000
  metal               = 900000
  rare_materials      = 900000
  oil                 = 900000
  supplies            = 900000
  money               = 900000
  capital             = 457
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 2
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 457 }
  ownedprovinces      = { 457 }
  controlledprovinces = { 457 369 368 370 379 531 378 668 666 2325 2326 
                          371 1408 373 377 460 461 462 2327 2328 2329 463 464 465 2447 224 456 458 491 492 497 1890 459 455 380 382 383 291 384 1893 
                          1891 1892 385 386 387 454 493 494 1895 1897 452 453 1057 389 1894 1896 451 415 1168 1169 413 414 665 390 391 664 
                          392 2319 410 411 412 2321 402 403 401 400 395 394  416 417 419 420 421 422 2323 2324 1911  495 2602 2603 426 424 425 423 2450
                          431 432 436 1402 429 2604 2449  496 427 428 498 1449 1403 1899 430 1173 1401 230 433 434 2605 435 476 478 477 1889 1887 490 499
                          466 470 53 1888 469 471 468 475 467 472 474 388 381  393  398 }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 15451 id = 4072 }
    name     = "‘æ1ŒR’c"
    location = 2319
    division =
    { id            = { type = 15451 id = 4074 }
      name          = "‘æ1Ži—ßŒQ"
      model         = 33
      type          = hq
      strength      = 100
      brigade_model = 0
      extra         = light_armor_brigade
    }
  }
  landunit =
  { id       = { type = 15451 id = 4075 }
    name     = "‘æ2ŒR’c"
    location = 2322
    division =
    { id            = { type = 15451 id = 4077 }
      name          = "‘æ2Ži—ßŒQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 4078 }
    name     = "‘æ3ŒR’c"
    location = 1891
    division =
    { id            = { type = 15451 id = 4080 }
      name          = "‘æ3Ži—ßŒQ"
      model         = 33
      brigade_model = 0
      extra         = light_armor_brigade
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 4081 }
    name     = "‘æ4ŒR’c"
    location = 1893
    division =
    { id            = { type = 15451 id = 4083 }
      name          = "‘æ1BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4086 }
      name          = "‘æ1BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4089 }
      name          = "‘æ4BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4090 }
      name          = "‘æ5BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4091 }
      name          = "‘æ6BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 4097 }
    name     = "‘æ5ŒR’c"
    location = 668
    division =
    { id            = { type = 15451 id = 4099 }
      name          = "‘æ12BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4102 }
      name          = "‘æ4BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4105 }
      name          = "‘æ15BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4106 }
      name          = "‘æ16BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4107 }
      name          = "‘æ17BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 4113 }
    name     = "‘æ6ŒR’c"
    location = 403
    division =
    { id            = { type = 15451 id = 4115 }
      name          = "‘æ23BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4118 }
      name          = "‘æ7BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4121 }
      name          = "‘æ26BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4122 }
      name          = "‘æ27BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4123 }
      name          = "‘æ28BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 4129 }
    name     = "‘æ7ŒR’c"
    location = 390
    division =
    { id            = { type = 15451 id = 4131 }
      name          = "‘æ34BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4134 }
      name          = "‘æ10BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4137 }
      name          = "‘æ37BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4138 }
      name          = "‘æ38BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4139 }
      name          = "‘æ39BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 4145 }
    name     = "‘æ8ŒR’c"
    location = 409
    division =
    { id            = { type = 15451 id = 4147 }
      name          = "‘æ45BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4150 }
      name          = "‘æ13BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4153 }
      name          = "‘æ48BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4154 }
      name          = "‘æ49BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4155 }
      name          = "‘æ50BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 4161 }
    name     = "‘æ9ŒR’c"
    location = 296
    division =
    { id            = { type = 15451 id = 4163 }
      name          = "‘æ56BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4166 }
      name          = "‘æ16BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4169 }
      name          = "‘æ59BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4170 }
      name          = "‘æ60BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4171 }
      name          = "‘æ61BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 4177 }
    name     = "‘æ10ŒR’c"
    location = 80
    division =
    { id            = { type = 15451 id = 4179 }
      name          = "‘æ67BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4182 }
      name          = "‘æ19BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4185 }
      name          = "‘æ70BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4186 }
      name          = "‘æ71BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 4187 }
      name          = "‘æ72BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 5826 }
    name     = "‘æ7ŒR’c"
    location = 368
    division =
    { id            = { type = 15451 id = 5827 }
      name          = "‘æ34BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5828 }
      name          = "‘æ10BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5829 }
      name          = "‘æ37BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5830 }
      name          = "‘æ38BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5831 }
      name          = "‘æ39BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 5832 }
    name     = "‘æ7ŒR’c"
    location = 369
    division =
    { id            = { type = 15451 id = 5833 }
      name          = "‘æ34BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5834 }
      name          = "‘æ10BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5835 }
      name          = "‘æ37BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5836 }
      name          = "‘æ38BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5837 }
      name          = "‘æ39BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 5838 }
    name     = "‘æ7ŒR’c"
    location = 378
    division =
    { id            = { type = 15451 id = 5839 }
      name          = "‘æ34BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5840 }
      name          = "‘æ10BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5841 }
      name          = "‘æ37BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5842 }
      name          = "‘æ38BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5843 }
      name          = "‘æ39BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 9 }
    name     = "‘æ9ŒR’c"
    location = 369
    division =
    { id            = { type = 15451 id = 10 }
      name          = "‘æ56BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 11 }
      name          = "‘æ16BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 12 }
      name          = "‘æ59BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 13 }
      name          = "‘æ60BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 14 }
      name          = "‘æ61BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 3 }
    name     = "‘æ10ŒR’c"
    location = 368
    division =
    { id            = { type = 15451 id = 4 }
      name          = "‘æ67BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5 }
      name          = "‘æ19BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 6 }
      name          = "‘æ70BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 7 }
      name          = "‘æ71BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 8 }
      name          = "‘æ72BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 5844 }
    name     = "‘æ7ŒR’c"
    location = 379
    division =
    { id            = { type = 15451 id = 5845 }
      name          = "‘æ34BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5846 }
      name          = "‘æ10BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5847 }
      name          = "‘æ37BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5848 }
      name          = "‘æ38BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100
    }
    division =
    { id            = { type = 15451 id = 5849 }
      name          = "‘æ39BETAŒQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 15451 id = 1 }
    name     = "ƒuƒ^ƒyƒXƒgƒnƒCƒ”"
    location = 457
    division =
    { type   = garrison
      model  = 13
      id     = { type = 15454 id = 1 }
      name   = "ƒuƒ^ƒyƒXƒgƒnƒCƒ”"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 15454 id = 2 }
      name   = "–å‹‰"
      locked = yes
    }
  }
}
