
##############################
# Country definition for U28 #
##############################

province =
{ id              = 1300
  air_base        = 10
  radar_station   = 10
  
  rocket_test     = 10
  infra           = 2.0
  anti_air        = 10
}                   # É}ÉìÉ_ÉåÅ[(ÉrÉãÉ})

#####################
# Country main data #
#####################

country =
{ tag                 = U28
  manpower            = 50
  energy              = 100
  metal               = 50
  rare_materials      = 25
  oil                 = 50
  supplies            = 200
  money               = 100
  capital             = 1300
  transports          = 9999
  escorts             = 9999
  extra_tc            = 9999
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  nationalprovinces   = { 1300 }
  ownedprovinces      = { 1300 }
  controlledprovinces = { 1300 1290 1291 1292 1297 1298 1299 1301 1302 1304 1346 1295 1296 1305 1347 1345 1343 1342 1331 1330 1344 1303
                          1328 1333 1334 1335 1337 1338 1326 1306 1329 1332 1336 1589 1339 1340 1341 
                               }
  techapps            = { 7020 }
  free                = { energy = 1000 manpower = 9 metal = 1000 rare_materials = 1000 oil = 1000 money = 1000 ic = 300 supplies = 1000 }
  landunit =
  { id       = { type = 17051 id = 4 }
    name     = "ëÊ4åRíc"
    location = 1298
    division =
    { id            = { type = 17051 id = 5 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 6 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 7 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 8 }
    name     = "ëÊ4åRíc"
    location = 1302
    division =
    { id            = { type = 17051 id = 9 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 10 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 11 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 12 }
    name     = "ëÊ4åRíc"
    location = 1347
    division =
    { id            = { type = 17051 id = 13 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 14 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 15 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 16 }
    name     = "ëÊ4åRíc"
    location = 1343
    division =
    { id            = { type = 17051 id = 17 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 18 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 19 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 20 }
    name     = "ëÊ4åRíc"
    location = 1339
    division =
    { id            = { type = 17051 id = 21 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 22 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 23 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 24 }
    name     = "ëÊ4åRíc"
    location = 1338
    division =
    { id            = { type = 17051 id = 25 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 26 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 27 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 28 }
    name     = "ëÊ4åRíc"
    location = 1335
    division =
    { id            = { type = 17051 id = 29 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 30 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 31 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 32 }
    name     = "ëÊ4åRíc"
    location = 1334
    division =
    { id            = { type = 17051 id = 33 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 34 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 35 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 36 }
    name     = "ëÊ4åRíc"
    location = 1333
    division =
    { id            = { type = 17051 id = 37 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 38 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 39 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 40 }
    name     = "ëÊ4åRíc"
    location = 1326
    division =
    { id            = { type = 17051 id = 41 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 42 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 43 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 44 }
    name     = "ëÊ4åRíc"
    location = 1288
    division =
    { id            = { type = 17051 id = 45 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 46 }
      name          = "ëÊ1BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 17051 id = 47 }
      name          = "ëÊ4BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 17051 id = 1 }
    name     = "É}ÉìÉ_ÉåÅ[ÉnÉCÉî"
    location = 1300
    division =
    { type   = garrison
      model  = 14
      id     = { type = 17054 id = 2 }
      name   = "É}ÉìÉ_ÉåÅ[ÉnÉCÉî"
      locked = yes
    }
    division =
    { type   = garrison
      model  = 33
      id     = { type = 17054 id = 3 }
      name   = "ñÂãâ"
      locked = yes
    }
  }
}
