
##############################
# Country definition for USA #
##############################

province = { id = 548 ic = 8 } # ƒfƒBƒoƒŠƒ“ƒOƒnƒ€
province =
{ id         = 549
  anti_air   = 1
  ic         = 5
  air_base   = { size = 2 current_size = 2 }
  Naval_base = { size = 2 current_size = 2 }
}              # ƒAƒ“ƒJƒŒƒbƒW
province = { id = 553 supplypool = 1000 ic = 3 } # ƒWƒ…ƒm[
province = { id = 582 ic = 4 } # ƒoƒ“ƒS[
Province =
{ id       = 592
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒVƒ‰ƒLƒ…[ƒX
province =
{ id       = 595
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒRƒ“ƒR[ƒh
province =
{ id            = 600
  anti_air      = 3
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 8 current_size = 8 }
}                 # ƒ{ƒXƒgƒ“
province = { id = 604 ic = 5 } # ƒnƒŠƒXƒo[ƒO
province =
{ id       = 606
  anti_air = 4
  ic       = 9
  air_base = { size = 10 current_size = 10 }
}            # ƒƒVƒ“ƒgƒ“D.C.
province = { id = 607 ic = 4 } # ƒ{ƒ‹ƒeƒBƒ‚ƒA
province =
{ id            = 608
  anti_air      = 2
  ic            = 3
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 8 current_size = 8 }
}                 # ƒtƒBƒ‰ƒfƒ‹ƒtƒBƒA
province = { id = 609 ic = 5 } # ƒZƒ“ƒgƒƒAƒŠ[
province = { id = 613 ic = 5 } # ƒtƒH[ƒgEƒEƒFƒCƒ“
province =
{ id       = 614
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic       = 10
}            # ƒsƒbƒcƒo[ƒO
province = { id = 615 ic = 3 } # ƒNƒŠ[ƒ”ƒ‰ƒ“ƒh
province =
{ id       = 616
  anti_air = 1
  ic       = 4
  air_base = { size = 4 current_size = 4 }
}            # ƒfƒgƒƒCƒg
province = { id = 619 ic = 3 } # ƒRƒƒ“ƒrƒA
province =
{ id            = 620
  anti_air      = 3
  ic            = 7
  air_base      = { size = 10 current_size = 10 }
}                 # ƒVƒJƒS
province =
{ id            = 621
  anti_air      = 1
  ic            = 8
  air_base      = { size = 4 current_size = 4 }
}                 # ƒ~ƒ‹ƒEƒH[ƒL[
province = { id = 622 ic = 6 } # ƒ}ƒ‹ƒPƒbƒg
province = { id = 623 ic = 5 } # ƒOƒŠ[ƒ“ƒxƒC
province =
{ id       = 624
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒfƒ‚ƒCƒ“
province = { id = 629 ic = 5 } # ƒNƒ‰[ƒNƒXƒo[ƒO
province =
{ id         = 632
  anti_air   = 4
  ic         = 1
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 8 current_size = 8 }
}              # ƒm[ƒtƒH[ƒN
province =
{ id            = 633
  anti_air      = 4
  ic            = 3
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 8 current_size = 8 }
}                 # ƒŠƒbƒ`ƒ‚ƒ“ƒh
Province =
{ id       = 637
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒVƒƒ[ƒƒbƒg
province = { id = 640 ic = 4 } # ƒŒƒLƒVƒ“ƒgƒ“
province =
{ id       = 641
  anti_air = 1
  ic       = 2
  air_base = { size = 4 current_size = 4 }
}            # ƒ‹ƒCƒXƒ”ƒBƒ‹
province =
{ id            = 644
  anti_air      = 1
  ic            = 2
  air_base      = { size = 4 current_size = 4 }
}                 # ƒ`ƒƒ[ƒ‹ƒXƒgƒ“
province = { id = 645 ic = 4 } # ƒOƒŠ[ƒ“ƒrƒ‹
Province =
{ id       = 648
  anti_air = 1
  ic       = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒWƒƒƒNƒ\ƒ“ƒ”ƒBƒ‹
province =
{ id            = 651
  anti_air      = 1
  ic            = 2
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 4 current_size = 4 }
}                 # ƒ}ƒCƒAƒ~
province =
{ id         = 662
  air_base   = { size = 2 current_size = 2 }
  supplypool = 100
}              # ƒ~ƒbƒhƒEƒF[
province =
{ id         = 663
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  oilpool    = 1000
  supplypool = 1000
}              # ƒzƒmƒ‹ƒ‹
province =
{ id            = 670
  anti_air      = 1
  ic            = 5
  air_base      = { size = 4 current_size = 4 }
}                 # ƒAƒgƒ‰ƒ“ƒ^
Province =
{ id       = 673
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒƒ“ƒtƒBƒX
province = { id = 676 ic = 2 } # ƒyƒ“ƒTƒR[ƒ‰
Province =
{ id       = 678
  anti_air = 1
  ic       = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒ‚[ƒrƒ‹
province = { id = 680 ic = 1 } # ƒ‰ƒtƒ@ƒCƒGƒbƒg(ƒ‹ƒCƒWƒAƒi)
province =
{ id            = 683
  anti_air      = 1
  air_base      = { size = 4 current_size = 4 }
}                 # ƒŠƒgƒ‹ƒƒbƒN
province =
{ id       = 689
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒZƒ“ƒgƒ‹ƒCƒX
province = { id = 694 ic = 4 } # ƒZƒ“ƒgƒ|[ƒ‹(ƒ~ƒlƒ\ƒ^)
province =
{ id       = 699
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒrƒXƒ}ƒ‹ƒN
province =
{ id            = 707
  anti_air      = 1
  air_base      = { size = 4 current_size = 4 }
}                 # ƒfƒ“ƒ”ƒ@[
province = { id = 711 ic = 2 } # ƒ^ƒCƒ‰[(ƒeƒLƒTƒX)
province =
{ id            = 716
  anti_air      = 2
  ic            = 2
  air_base      = { size = 4 current_size = 4 }
  nuclear_reactor      = { size = 6 current_size = 6 }
}                 # ƒqƒ…[ƒXƒgƒ“
Province =
{ id       = 725
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒTƒ“ƒ^ƒtƒF
province =
{ id       = 728
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒtƒFƒjƒbƒNƒX
province =
{ id       = 733
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # ƒ\ƒ‹ƒgƒŒƒCƒNƒVƒeƒB
province = { id = 734 ic = 6 } # ƒ‰ƒXƒ”ƒFƒKƒX
Province =
{ id         = 748
  anti_air   = 1
  ic         = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 8 current_size = 8 }
}              # ƒR[ƒpƒXƒNƒŠƒXƒeƒB(ƒeƒLƒTƒX)
province =
{ id            = 761
  anti_air      = 1
  ic            = 5
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 8 current_size = 8 }
}                 # ƒTƒ“ƒfƒBƒGƒS
province =
{ id       = 762
  anti_air = 3
  ic       = 2
  air_base = { size = 4 current_size = 4 }
}            # ƒƒXƒAƒ“ƒWƒFƒ‹ƒX
province = { id = 763 ic = 4 } # ƒtƒŒƒYƒm
province =
{ id            = 764
  anti_air      = 2
  air_base      = { size = 4 current_size = 4 }
}                 # ƒTƒNƒ‰ƒƒ“ƒg
province =
{ id            = 765
  anti_air      = 3
  ic            = 8
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 8 current_size = 8 }
}                 # ƒTƒ“ƒtƒ‰ƒ“ƒVƒXƒR
province =
{ id       = 780
  anti_air = 1
  ic       = 10
  air_base = { size = 4 current_size = 4 }
}            # ƒVƒAƒgƒ‹
province =
{ id         = 782
  anti_air   = 1
  ic         = 9
  Naval_base = { size = 4 current_size = 4 }
}              # ƒ^ƒRƒ}
province =
{ id       = 783
  anti_air = 1
  ic       = 10
  air_base = { size = 4 current_size = 4 }
}            # ƒ|[ƒgƒ‰ƒ“ƒh
province =
{ id       = 790
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒIƒ}ƒn
province =
{ id       = 793
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒIƒNƒ‰ƒzƒ}ƒVƒeƒB
province =
{ id         = 889
  anti_air   = 3
  air_base   = { size = 2 current_size = 2 }
  Naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 100
}              # ƒoƒ‹ƒ{ƒA(ƒpƒiƒ}‰^‰Í)
province =
{ id         = 894
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  Naval_base = { size = 2 current_size = 2 }
}              # ƒOƒ@ƒ“ƒ^ƒiƒ‚ŠCŒRŠî’n
province = { id = 895 supplypool = 50 } # ƒTƒ“ƒtƒAƒ“(ƒvƒGƒ‹ƒgƒŠƒR)
province =
{ id         = 1624
  anti_air   = 3
  air_base   = { size = 2 current_size = 2 }
  Naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 100
}              # ƒAƒKƒi(ƒOƒAƒ€“‡)
province = { id = 2643 ic = 2 } # ƒAƒjƒ}ƒbƒN
province = { id = 2644 ic = 4 } # ƒ‰ƒPEƒNƒ‰[ƒN
province = { id = 2645 ic = 2 } # ƒtƒFƒAƒoƒ“ƒNƒX

#####################
# Country main data #
#####################

country =
{ tag                 = USA
  manpower            = 1250
  energy              = 80000
  metal               = 80000
  rare_materials      = 60000
  oil                 = 60000
  supplies            = 6000
  money               = 3500
  capital             = 606
  regular_id          = U92
  transports          = 2500
  escorts             = 2200
  policy =
  { democratic        = 10
    political_left    = 4
    freedom           = 10
    free_market       = 10
    professional_army = 9
    defense_lobby     = 8
    interventionism   = 10
  }
  headofstate            = { type = 9 id = 6019 }
  headofgovernment       = { type = 9 id = 6037 }
  foreignminister        = { type = 9 id = 6061 }
  armamentminister       = { type = 9 id = 6078 }
  ministerofsecurity     = { type = 9 id = 6102 }
  ministerofintelligence = { type = 9 id = 6119 }
  chiefofstaff           = { type = 9 id = 6134 }
  chiefofarmy            = { type = 9 id = 6145 }
  chiefofnavy            = { type = 9 id = 6157 }
  chiefofair             = { type = 9 id = 6171 }
  ownedprovinces      = { 1278 1600 1601 1602 1603 1604 1605 1608 1618 1619 1620 1621 1624 1755 1760 1763 1765 1766 1786 2255 2259 2261 2365 2367 2377
                          582  583  592  594  595  596  598  600  601  603  604  605  606  607  608  609  610  612  613  614  615  616  617  618  619 
                          620  621  622  623  624  625  626  627  628  629  630  632  633  634  636  637  638  639  640  641  642  643  644  645  646 
                          647  648  649  650  651  658  659  660  662  663  670  671  672  673  675  676  677  678  679  680  681  682  683  684  686 
                          688  689  690  691  693  694  698  699  701  704  705  706  707  708  709  711  712  713  715  716  717  718  719  721 
                          724  725  727  728  730  731  732  733  734  735  748  761  762  763  764  765  766  767  768  770  772  776  778  779  780 
                          782  783  784  786  787  788  789  790  792  793  794  889  894  895  1617 1625 1626 1627 548  2643 2644 2645 549  553 
                        }
  controlledprovinces = { 1278 1600 1601 1602 1603 1604 1605 1608 1617 1618 1619 1620 1621 1624 1625 1626 1627 1755 1760 1763 1765 1766 1786 2255 2259
                          2261 2365 2367 2377 582  583  592  594  595  596  598  600  601  603  604  605  606  607  608  609  610  612  613  614  615 
                          616  617  618  619  620  621  622  623  624  625  626  627  628  629  630  632  633  634  636  637  638  639  640  641  642 
                          643  644  645  646  647  648  649  650  651  658  659  660  662  663  670  671  672  673  675  676  677  678  679  680  681 
                          682  683  684  686  688  689  690  691  693  694  698  699  701  704  705  706  707  708  709  711  712  713  715  716 
                          717  718  719  721  724  725  727  728  730  731  732  733  734  735  748  761  762  763  764  765  766  767  768  770  772 
                          776  778  779  780  782  783  784  786  787  788  789  790  792  793  794  889  894  895  548  2643 2644 2645 549  553 
                        }
  techapps            = { 10050 10060 10070 10080 10090 1010  10150 10160 10190 1020  10200 10210 10220 1030  1040  1050  1110  1120  1130  1140 
                          1150  1210  1220  1230  1240  1250  1470  1490  1510  1530  1550  1560  1570  1580  1590  1650  1660  1670  1680  1690 
                          1750  1760  1770  1780  1790  1850  1860  1870  1880  1950  1960  1970  1980  2010  2020  2030  2040  2050  2060  2070 
                          2080  2310  2320  2330  2610  2620  2630  2640  2650  2660  2910  2920  2930  2940  2950  2960  3010  3020  3030  3040 
                          30410 30420 30430 30440 30450 3050  30510 30520 30530 30540 30550 3110  3120  3130  3140  3150  3210  3220  3230  3240 
                          3250  3310  3320  3330  3340  3350  3410  3460  3470  3480  3490  3500  3560  3570  3610  3620  3630  3640  3650  3710 
                          3720  3730  3740  3750  3810  3820  3830  3840  3850  3910  3920  3930  3940  3950  3960  40100 40110 40120 40130 40200
                          40210 40220 40230 40240 40250 4390  4400  4410  4420  4430  4480  4490  4500  4510  4560  4570  50020 50030 50040 50050 50070
                          50080 50090 5010  50100 50110 50120 5020  50290 5030  50300 50310 5040  5050  5090  5100  5110  5120  5170  5180  5190 
                          5200  5250  5260  5270  5280  5330  5340  5350  5360  5370  5410  5420  5430  5460  5490  5500  5520  5530  5540  5550  5600  5610  5620 
                          5630  5680  5690  5700  5760  5770  5780  5790  5800  5810  5820  5830  5910  5920  5930  5940  5950  7010  7500  7510  7520  7530  7670  7680  7690  80080 80090 8010 
                          80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140 90190 9020  9030  9040 
                          9050  9060  9070  9080  9190  9200  9210  9220  9230  9340  9350  9360  9370  9380  9390  9400  9410  9520  9530  9540 
                          9550  9560  9670  9680  9690  9700  9710  9720  9730  9840  9850  9860  9870  9880  9990  10390
                          4010  4020  4030  4040  4050  4110  4120  4130  4140  4150  4210  4220  4230  4240  4250  2340  2360
                          4640  4650  4660  4670  4680  4820  4830  4840  4850  4860  40000 40010 40020 40030 40040
                          7150  7160  7170  7180  7190  7200  7210  7220  7230  20410 20420 20430 20440 7080  7750  7540  7550  7560  7570  7610  7320
                          7030  7040  7050  7060  30170 30230 30320 30380 50320 5710  40140 40150
                          2000  2210  3000  4000  5000  6100  6110  6280  6290  6300  6550
                        }
  nationalprovinces   = { 651  650  649  648  677  676  672  646  647  670  644  645  634  636  637  643  633  632  638  639  606  607  605  604  603 
                          612  602  598  592  608  609  610  594  595  596  582  583  600  601  613  614  629  630  640  641  642  671  673  675  678 
                          679  615  628  617  616  618  619  627  680  681  682  683  684  686  688  689  626  625  620  621  624  623  622  690  691 
                          693  694  698  699  787  788  789  790  792  793  711  712  713  715  716  717  719  721  748  724  725  727  728  730 
                          731  732  733  706  707  708  709  705  704  701  770  772  776  779  780  782  783  784  786  778  768  734  735  767  761 
                          762  763  764  765  766  553  550  549  548  718  895  889  1278 2365 2367 2377 2261 2259 2255 908  2641 2642 1399 2643 2644
                          2645
                        }
 free                = { energy = 300 metal = 200 rare_materials = 500 oil = 50 ic = -200 }
 inventions             = { 8000 8001 8006 8007 8009 8011 8012 8004 8005 }
  landunit =
  { id       = { type = 23001 id = 5448 }
    name     = "‘æ20ŒR’c"
    location = 606
    home     = 606
    #mission  = { type = none target = 606 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5450 }
      name          = "‘æ1‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5451 }
      name          = "‘æ2‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5452 }
      name          = "‘æ3‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5453 }
    name     = "‘æ21ŒR’c"
    location = 786
    home     = 786
    #mission  = { type = none target = 786 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5455 }
      name          = "‘æ4‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5456 }
      name          = "‘æ5‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5457 }
      name          = "‘æ6‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 2
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5458 }
    name     = "‘æ22ŒR’c"
    location = 606
    home     = 606
    #mission  = { type = none target = 606 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5460 }
      name          = "‘æ1íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5461 }
      name          = "‘æ2íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5462 }
      name          = "‘æ1‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5463 }
    name     = "‘æ23ŒR’c"
    location = 786
    home     = 786
    #mission  = { type = none target = 786 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5465 }
      name          = "‘æ3íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5466 }
      name          = "‘æ4íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5467 }
      name          = "‘æ2‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5468 }
    name     = "İ“ú•ÄŒRi—ß•”"
    location = 1193
    home     = 1193
    #mission  = { type = none target = 1193 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5470 }
      name          = "‘æ1ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5471 }
    name     = "‘æ24ŒR’c"
    location = 1193
    home     = 1193
    #mission  = { type = none target = 1193 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5473 }
      name          = "‘æ5íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5474 }
      name          = "‘æ6íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5475 }
      name          = "‘æ3‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5476 }
    name     = "‘æ25ŒR’c"
    location = 2623
    home     = 2623
    #mission  = { type = none target = 2623 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5478 }
      name          = "‘æ7íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5479 }
      name          = "‘æ8íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5480 }
      name          = "‘æ4‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5481 }
    name     = "‰¢B”hŒ­ŒRi—ß•”"
    location = 130
    home     = 130
    #mission  = { type = none target = 130 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5483 }
      name          = "‘æ2ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5484 }
    name     = "‘æ26ŒR’c"
    location = 132
    home     = 132
    #mission  = { type = none target = 133 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5486 }
      name          = "‘æ9íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5487 }
      name          = "‘æ10íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5488 }
      name          = "‘æ5‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5489 }
    name     = "‘æ27ŒR’c"
    location = 132
    home     = 132
    #mission  = { type = none target = 133 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5491 }
      name          = "‘æ6‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5492 }
      name          = "‘æ7‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5493 }
      name          = "‘æ8‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5494 }
    name     = "‘æ28ŒR’c"
    location = 130
    home     = 130
    #mission  = { type = none target = 130 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5496 }
      name          = "‘æ11íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5497 }
      name          = "‘æ12íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5498 }
      name          = "‘æ9‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5499 }
    name     = "‘æ29ŒR’c"
    location = 131
    home     = 131
    #mission  = { type = none target = 131 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5501 }
      name          = "‘æ13íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5502 }
      name          = "‘æ14íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5503 }
      name          = "‘æ10‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5504 }
    name     = "‘æ30ŒR’c"
    location = 131
    home     = 131
    #mission  = { type = none target = 131 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5506 }
      name          = "‘æ11‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5507 }
      name          = "‘æ1‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5508 }
      name          = "‘æ2‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5509 }
    name     = "‰¢B”hŒ­ŒRi—ß•”"
    location = 21
    home     = 21
    #mission  = { type = none target = 21 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5511 }
      name          = "‘æ3ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5512 }
    name     = "‘æ31ŒR’c"
    location = 1160
    home     = 1160
    #mission  = { type = none target = 1160 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5514 }
      name          = "‘æ15íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5515 }
      name          = "‘æ16íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5516 }
      name          = "‘æ12‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5517 }
    name     = "‘æ32ŒR’c"
    location = 23
    home     = 23
    #mission  = { type = none target = 23 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5519 }
      name          = "‘æ13‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5520 }
      name          = "‘æ14‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5521 }
      name          = "‘æ15‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5522 }
    name     = "‘æ33ŒR’c"
    location = 20
    home     = 20
    #mission  = { type = none target = 20 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5524 }
      name          = "‘æ16‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5525 }
      name          = "‘æ3‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5526 }
      name          = "‘æ4‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5527 }
    name     = "‘æ34ŒR’c"
    location = 21
    home     = 21
    #mission  = { type = none target = 21 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5529 }
      name          = "‘æ17íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5530 }
      name          = "‘æ18íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5531 }
      name          = "‘æ17‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5532 }
    name     = "İ’©•ÄŒRi—ß•”"
    location = 1197
    home     = 1197
    #mission  = { type = none target = 1197 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5534 }
      name          = "‘æ4ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5535 }
    name     = "‘æ35ŒR’c"
    location = 1197
    home     = 1197
    #mission  = { type = none target = 1197 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5537 }
      name          = "‘æ18‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5538 }
      name          = "‘æ5‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5539 }
      name          = "‘æ6‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5540 }
    name     = "‘æ36ŒR’c"
    location = 1197
    home     = 1197
    #mission  = { type = none target = 1197 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5542 }
      name          = "‘æ19íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5543 }
      name          = "‘æ20íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5544 }
      name          = "‘æ19‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5545 }
    name     = "ƒCƒ“ƒh”hŒ­ŒRi—ß•”"
    location = 1461
    home     = 1461
    #mission  = { type = none target = 1461 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5547 }
      name          = "‘æ5ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5548 }
    name     = "‘æ37ŒR’c"
    location = 1461
    home     = 1461
    #mission  = { type = none target = 1461 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5550 }
      name          = "‘æ21íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5551 }
      name          = "‘æ22íp‹@b‘å‘à"
      model         = 7
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5552 }
      name          = "‘æ20‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5553 }
    name     = "‘æ38ŒR’c"
    location = 1461
    home     = 1461
    #mission  = { type = none target = 1461 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5555 }
      name          = "‘æ21‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5556 }
      name          = "‘æ22‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5557 }
      name          = "‘æ23‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5558 }
    name     = "‘æ39ŒR’c"
    location = 1461
    home     = 1461
    #mission  = { type = none target = 1461 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5560 }
      name          = "‘æ23íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5561 }
      name          = "‘æ24íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5562 }
      name          = "‘æ24‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5563 }
    name     = "‘æ40ŒR’c"
    location = 635
    home     = 635
    #mission  = { type = none target = 635 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5565 }
      name          = "‘æ25íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5566 }
      name          = "‘æ26íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5567 }
      name          = "‘æ25‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5568 }
    name     = "‘æ41ŒR’c"
    location = 635
    home     = 635
    #mission  = { type = none target = 635 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5570 }
      name          = "‘æ26‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5571 }
      name          = "‘æ7‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5572 }
      name          = "‘æ8‘•b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = light_armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5573 }
    name     = "‘æ42ŒR’c"
    location = 635
    home     = 635
    #mission  = { type = none target = 635 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5575 }
      name          = "‘æ27‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5576 }
      name          = "‘æ28‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5577 }
      name          = "‘æ7‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 4
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5578 }
      name          = "‘æ8‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 4
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5579 }
      name          = "‘æ9‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 4
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5580 }
    name     = "‘æ43ŒR’c"
    location = 1459
    home     = 1459
    #mission  = { type = none target = 1459 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5582 }
      name          = "‘æ27íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5583 }
      name          = "‘æ28íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5584 }
      name          = "‘æ29‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5585 }
    name     = "‘æ44ŒR’c"
    location = 1459
    home     = 1459
    #mission  = { type = none target = 1459 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5587 }
      name          = "‘æ30‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = armor
      extra         = sp_artillery
      strength      = 100
    }
    division =
    { id                  = { type = 23001 id = 5588 }
      name                = "‘æ9‘•b‘å‘à"
      model               = 5
      brigade_model       = 0
      type                = light_armor
      strength            = 100
    }
    division =
    { id                  = { type = 23001 id = 5589 }
      name                = "‘æ10‘•b‘å‘à"
      model               = 5
      brigade_model       = 0
      type                = light_armor
      strength            = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5590 }
    name     = "‘æ45ŒR’c"
    location = 1459
    home     = 1459
    #mission  = { type = none target = 1459 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5592 }
      name          = "‘æ31‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5593 }
      name          = "‘æ32‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5594 }
      name          = "‘æ33‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id                  = { type = 23001 id = 5595 }
      name                = "‘æ11‘•b‘å‘à"
      model               = 5
      brigade_model       = 0
      type                = light_armor
      strength            = 100
    }
    division =
    { id                  = { type = 23001 id = 5596 }
      name                = "‘æ12‘•b‘å‘à"
      model               = 5
      brigade_model       = 0
      type                = light_armor
      strength            = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5597 }
    name     = "‘æ46ŒR’c"
    location = 2094
    home     = 2094
    #mission  = { type = none target = 2094 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id                  = { type = 23001 id = 5599 }
      name                = "‘æ29íp‹@b‘å‘à"
      model               = 4
      brigade_model       = 0
      type                = paratrooper
      extra               = artillery
      strength            = 100
    }
    division =
    { id            = { type = 23001 id = 5600 }
      name          = "‘æ30íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5601 }
      name          = "‘æ34‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5602 }
    name     = "‘æ47ŒR’c"
    location = 2094
    home     = 2094
    #mission  = { type = none target = 2094 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5604 }
      name          = "‘æ35‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5605 }
      name          = "‘æ36‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5606 }
      name          = "‘æ37‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5607 }
    name     = "‘æ48ŒR’c"
    location = 2094
    home     = 2094
    #mission  = { type = none target = 2094 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5609 }
      name          = "‘æ10‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 4
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5610 }
      name          = "‘æ11‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 4
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5611 }
      name          = "‘æ12‹@ŠB‰»‘•b•à•º‘å‘à"
      model         = 4
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5612 }
    name     = "ƒAƒtƒŠƒJ”hŒ­ŒRi—ß•”"
    location = 900
    home     = 900
    #mission  = { type = none target = 900 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5614 }
      name          = "‘æ6ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5615 }
    name     = "‘æ49ŒR’c"
    location = 901
    home     = 901
    #mission  = { type = none target = 901 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5617 }
      name          = "‘æ31íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5618 }
      name          = "‘æ32íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5619 }
      name          = "‘æ38‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5620 }
    name     = "‘æ50ŒR’c"
    location = 901
    home     = 901
    #mission  = { type = none target = 901 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5622 }
      name          = "‘æ39‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5623 }
      name          = "‘æ40‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5624 }
      name          = "‘æ41‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5625 }
    name     = "‘æ51ŒR’c"
    location = 900
    home     = 900
    #mission  = { type = none target = 900 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5627 }
      name          = "‘æ33íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5628 }
      name          = "‘æ34íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5629 }
      name          = "‘æ42‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5630 }
    name     = "’†“Œ”hŒ­ŒRi—ß•”"
    location = 1796
    home     = 1796
    #mission  = { type = none target = 1796 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5632 }
      name          = "‘æ7ŒRi—ß•”"
      model         = 3
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5633 }
    name     = "‘æ52ŒR’c"
    location = 1808
    home     = 1808
    #mission  = { type = none target = 1808 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5635 }
      name          = "‘æ35íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5636 }
      name          = "‘æ36íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5637 }
      name          = "‘æ43‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5638 }
    name     = "‘æ53ŒR’c"
    location = 1796
    home     = 1796
    #mission  = { type = none target = 1796 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5640 }
      name          = "‘æ44‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5641 }
      name          = "‘æ45‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5642 }
      name          = "‘æ46‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5643 }
    name     = "‘æ54ŒR’c"
    location = 1800
    home     = 1800
    #mission  = { type = none target = 1800 missionscope = 0 percentage = 0.0000 night = yes day = yes }
    division =
    { id            = { type = 23001 id = 5645 }
      name          = "‘æ37íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5646 }
      name          = "‘æ38íp‹@b‘å‘à"
      model         = 6
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5647 }
      name          = "‘æ47‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 23001 id = 5672 }
    name     = "‘æ1ŠC•ºíp‹@’c"
    location = 2632
    division =
    { id            = { type = 23001 id = 5673 }
      name          = "‘æ1ŠC•ºíp‹@’ci—ß•”"
      model         = 2
      brigade_model = 0
      type          = hq
    }
    division =
    { id            = { type = 23001 id = 5674 }
      name          = "‘æ316ŠC•ºíp•àsí“¬‹@‘à"
      model         = 15
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5675 }
      name          = "‘æ317ŠC•ºíp•àsí“¬‹@‘à"
      model         = 15
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5676 }
      name          = "‘æ318ŠC•ºíp•àsí“¬‹@‘à"
      model         = 15
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5677 }
      name          = "‘æ12ŠC•ºíp•àsí“¬‹@‘à"
      model         = 12
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5678 }
      name          = "‘æ24ŠC•ºíp•àsí“¬‹@‘à"
      model         = 12
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
    division =
    { id            = { type = 23001 id = 5679 }
      name          = "‘æ36ŠC•ºíp•àsí“¬‹@‘à"
      model         = 12
      brigade_model = 0
      type          = mechanized
      strength      = 100
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5648 }
    name     = "‘æµŠÍ‘à"
    location = 1193
    home     = 1193
    base     = 1193
    division =
    { id       = { type = 23002 id = 5650 }
      name     = "USS Theodore Roosevelt"
      model    = 10
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5651 }
      name     = "USS Iowa"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 56510 }
      name     = "USS New Jersey"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 56511 }
      name     = "USS Missouri"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 56512 }
      name     = "USS Illinois"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 56513 }
      name     = "USS Kentucky"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5652 }
      name     = "USS San Francisco"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5653 }
      name     = "USS Baltimore"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5654 }
      name     = "USS Boston"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5655 }
      name     = "USS McCall"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5656 }
      name     = "USS Maury"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5657 }
      name     = "USS Sampson"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5658 }
      name     = "USS Davis"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5659 }
      name     = "USS Juett"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5660 }
      name     = "USS Benham"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5661 }
      name     = "USS Ellet"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5662 }
      name     = "USS Lang"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5663 }
      name     = "USS Pope"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5664 }
      name     = "USS John D. Ford"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5665 }
    name     = "‘æOŠÍ‘à"
    location = 396
    home     = 396
    base     = 396
    division =
    { id       = { type = 23002 id = 5667 }
      name     = "USS Kitty Hawk"
      model    = 2
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5668 }
      name     = "USS Montana"
      model    = 10
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5669 }
      name     = "USS Canberra"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5670 }
      name     = "USS Quincy"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5671 }
      name     = "USS Pittsburgh"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5672 }
      name     = "USS Peary"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5673 }
      name     = "USS Pillsbury"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5674 }
      name     = "USS Truxtun"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5675 }
      name     = "USS Paul Jones"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5676 }
      name     = "USS Whipple"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5677 }
      name     = "USS Parrott"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5678 }
      name     = "USS Edsall"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5679 }
      name     = "USS Stewart"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5680 }
      name     = "USS Hatfield"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5681 }
      name     = "USS Upshur"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5682 }
    name     = "‘æŒÜ‹­PŠÍ‘à"
    location = 396
    home     = 396
    base     = 396
    division =
    { id       = { type = 23002 id = 5684 }
      name     = "USS Independence"
      model    = 3
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5685 }
      name     = "USS Princeton"
      model    = 3
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5686 }
      name     = "USS Alaska"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5687 }
      name     = "USS Guam"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5688 }
      name     = "USS Hawaii"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5689 }
      name     = "USS Philippines"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5690 }
      name     = "USS Brooklyn"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5691 }
      name     = "USS Philadelphia"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5692 }
      name     = "USS Savannah"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5693 }
      name     = "USS Nashville"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5694 }
      name     = "USS Vincennes"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5695 }
      name     = "Transport Division 1"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5696 }
      name     = "Transport Division 2"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5697 }
      name     = "Transport Division 3"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5698 }
      name     = "Transport Division 4"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5699 }
      name     = "Transport Division 5"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5700 }
      name     = "Transport Division 6"
      model    = 5
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5701 }
    name     = "‘æˆê—A‘—ŠÍ‘à"
    location = 396
    home     = 396
    base     = 396
    division =
    { id       = { type = 23002 id = 5703 }
      name     = "USS Barker"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5704 }
      name     = "Transport Division 7"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5705 }
      name     = "Transport Division 8"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5706 }
      name     = "Transport Division 9"
      model    = 3
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5707 }
    name     = "‘ælŠÍ‘à"
    location = 1517
    home     = 1517
    base     = 1517
    division =
    { id       = { type = 23002 id = 5709 }
      name     = "USS Constellation"
      model    = 2
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5710 }
      name     = "USS Ohio"
      model    = 10
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5711 }
      name     = "USS Saint Paul"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5712 }
      name     = "USS Columbus"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5713 }
      name     = "USS Helena"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5714 }
      name     = "USS John D. Edwards"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5715 }
      name     = "USS Simpson"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5716 }
      name     = "USS Bulmer"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5717 }
      name     = "USS Alden"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5718 }
      name     = "USS Jacob Jones"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5719 }
      name     = "USS Breckinridge"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5720 }
      name     = "USS Ward"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5721 }
      name     = "USS Blakeley"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5722 }
      name     = "USS Biddle"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5723 }
      name     = "USS Barney"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5724 }
    name     = "‘æl‹­PŠÍ‘à"
    location = 1517
    home     = 1517
    base     = 1517
    division =
    { id       = { type = 23002 id = 5726 }
      name     = "USS Belleau Wood"
      model    = 3
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5727 }
      name     = "USS Cowpens"
      model    = 3
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5728 }
      name     = "USS Puerto Rico"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5729 }
      name     = "USS Samoa"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5730 }
      name     = "USS Chancellorsville"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5731 }
      name     = "USS Gettysburg"
      model    = 3
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5732 }
      name     = "USS Wichita"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5733 }
      name     = "USS Phoenix"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5734 }
      name     = "USS Boise"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5735 }
      name     = "USS Honolulu"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5736 }
      name     = "USS Saint Louis"
      model    = 3
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5737 }
      name     = "Transport Division 11"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5738 }
      name     = "Transport Division 12"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5739 }
      name     = "Transport Division 13"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5740 }
      name     = "Transport Division 14"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5741 }
      name     = "Transport Division 15"
      model    = 5
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5742 }
      name     = "Transport Division 16"
      model    = 5
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5743 }
    name     = "‘æ“ñ—A‘—ŠÍ‘à"
    location = 1517
    home     = 1517
    base     = 1517
    division =
    { id       = { type = 23002 id = 5745 }
      name     = "USS Yarnall"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5746 }
      name     = "Transport Division 17"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5747 }
      name     = "Transport Division 18"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5748 }
      name     = "Transport Division 19"
      model    = 3
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5749 }
    name     = "‘æ˜ZŠÍ‘à"
    location = 939
    home     = 939
    base     = 939
    division =
    { id       = { type = 23002 id = 5751 }
      name     = "USS Enterprise"
      model    = 3
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5752 }
      name     = "USS Maine"
      model    = 10
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5753 }
      name     = "USS Oregon City"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5754 }
      name     = "USS Rochester"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5755 }
      name     = "USS Cambridge"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5756 }
      name     = "USS Tarbell"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5757 }
      name     = "USS Greer"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5758 }
      name     = "USS Ellis"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5759 }
      name     = "USS Du Pont"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5760 }
      name     = "USS Cole"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5761 }
      name     = "USS Bernadou"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5762 }
      name     = "USS Taylor"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5763 }
      name     = "USS Manley"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5764 }
      name     = "USS Hamilton"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5765 }
      name     = "USS Fairfax"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5766 }
    name     = "‘æ“ñŠÍ‘à"
    location = 1037
    home     = 1037
    base     = 1037
    division =
    { id       = { type = 23002 id = 5768 }
      name     = "USS America"
      model    = 3
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5769 }
      name     = "USS New Hampshire"
      model    = 10
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5770 }
      name     = "USS Bridgeport"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5771 }
      name     = "USS Kansas City"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5772 }
      name     = "USS Tulsa"
      model    = 3
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5773 }
      name     = "USS Babbitt"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5774 }
      name     = "USS Tillman"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5775 }
      name     = "USS Claxton"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5776 }
      name     = "USS Tattnall"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5777 }
      name     = "USS Reuben James"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5778 }
      name     = "USS J. Fred Talbott"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5779 }
      name     = "USS Nicholson"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5780 }
      name     = "USS Winslow"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5781 }
      name     = "USS Cushing"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5782 }
      name     = "USS Tucker"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5783 }
    name     = "‘æO‹­PŠÍ‘à"
    location = 1037
    home     = 1037
    base     = 1037
    division =
    { id       = { type = 23002 id = 5785 }
      name     = "USS Monterey"
      model    = 4
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5786 }
      name     = "USS Cabot"
      model    = 4
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5787 }
      name     = "USS Mobile Bay"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5788 }
      name     = "USS Shiloh"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5789 }
      name     = "USS Port Royal"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5790 }
      name     = "USS Vella Gulf"
      model    = 4
      type     = battlecruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5791 }
      name     = "USS Atlanta"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5792 }
      name     = "USS Juneau"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5793 }
      name     = "USS San Diego"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5794 }
      name     = "USS San Juan"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5795 }
      name     = "USS Cleveland"
      model    = 4
      type     = light_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5796 }
      name     = "Transport Division 20"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5797 }
      name     = "Transport Division 21"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5798 }
      name     = "Transport Division 22"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5799 }
      name     = "Transport Division 23"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5800 }
      name     = "Transport Division 24"
      model    = 6
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5801 }
      name     = "Transport Division 25"
      model    = 6
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5802 }
    name     = "‘æO—A‘—ŠÍ‘à"
    location = 1037
    home     = 1037
    base     = 1037
    division =
    { id       = { type = 23002 id = 5804 }
      name     = "USS Wadsworth"
      model    = 3
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5805 }
      name     = "Transport Division 26"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5806 }
      name     = "Transport Division 27"
      model    = 3
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5807 }
      name     = "Transport Division 28"
      model    = 3
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5808 }
    name     = "‘æˆêŠÍ‘à"
    location = 632
    home     = 632
    base     = 632
    division =
    { id       = { type = 23002 id = 5810 }
      name     = "USS John F. Kennedy"
      model    = 3
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5811 }
      name     = "USS Louisiana"
      model    = 10
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5812 }
      name     = "USS Bremerton"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5813 }
      name     = "USS Fall River"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5814 }
      name     = "USS Macon"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5815 }
      name     = "USS Rowan"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5816 }
      name     = "USS Allen"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5817 }
      name     = "USS Caldwell"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5818 }
      name     = "USS Craven"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5819 }
      name     = "USS Gwin"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5820 }
      name     = "USS Conner"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5821 }
      name     = "USS Stockton"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5822 }
      name     = "USS Wickes"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5823 }
      name     = "USS Philip"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5824 }
      name     = "USS Evans"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5825 }
    name     = "‘æŒÜŠÍ‘à"
    location = 765
    home     = 765
    base     = 765
    division =
    { id       = { type = 23002 id = 5827 }
      name     = "USS Nimitz"
      model    = 10
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5828 }
      name     = "USS United States"
      model    = 4
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5829 }
      name     = "USS Toledo"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5830 }
      name     = "USS Des Moines"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5831 }
      name     = "USS Los Angeles"
      model    = 4
      type     = heavy_cruiser
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5832 }
      name     = "USS Little"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5833 }
      name     = "USS Kimberly"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5834 }
      name     = "USS Sigourney"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5835 }
      name     = "USS Gregory"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5836 }
      name     = "USS Stringham"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5837 }
      name     = "USS Dyer"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5838 }
      name     = "USS Colhoun"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5839 }
      name     = "USS Stevens"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5840 }
      name     = "USS McKee"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5841 }
      name     = "USS Robinson"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5842 }
    name     = "‘æ8‹ó•ê‘ÅŒ‚ŒQ"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 23002 id = 5843 }
      name     = "USS Dwight D. Eisenhower"
      model    = 10
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5844 }
      name     = "USS Little"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5845 }
      name     = "USS Lewis B. Puller"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5846 }
      name     = "USS Jack Williams"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5847 }
      name     = "USS Copeland"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5848 }
      name     = "USS Gallery"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5849 }
      name     = "USS Mahlon S. Tisdale"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5850 }
      name     = "USS Boone"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5851 }
      name     = "Transport Division 29"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5852 }
      name     = "Transport Division 30"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5853 }
      name     = "Transport Division 31"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5854 }
      name     = "Transport Division 32"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5855 }
      name     = "Transport Division 33"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5856 }
      name     = "Transport Division 34"
      model    = 4
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5857 }
    name     = "‘æ5‹ó•ê‘ÅŒ‚ŒQ"
    location = 2632
    home     = 2632
    base     = 2632
    division =
    { id       = { type = 23002 id = 5858 }
      name     = "USS Carl Vinson"
      model    = 10
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5859 }
      name     = "USS Stephen W. Groves"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5860 }
      name     = "USS Lewis B. Puller"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5861 }
      name     = "USS Reid"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5862 }
      name     = "USS Stark"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5863 }
      name     = "USS John L. Hall"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5864 }
      name     = "USS Jarrett"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5865 }
      name     = "USS Aubrey Fitch"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5866 }
      name     = "Transport Division 35"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5867 }
      name     = "Transport Division 36"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5868 }
      name     = "Transport Division 37"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5869 }
      name     = "Transport Division 38"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5870 }
      name     = "Transport Division 39"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 58700 }
      name     = "Transport Division 40"
      model    = 4
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5871 }
    name     = "‘æ7‹ó•ê‘ÅŒ‚ŒQ"
    location = 21
    home     = 21
    base     = 21
    division =
    { id       = { type = 23002 id = 5872 }
      name     = "USS Abraham Lincoln"
      model    = 10
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5873 }
      name     = "USS Crommelin"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5874 }
      name     = "USS Underwood"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5875 }
      name     = "USS Curts"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5876 }
      name     = "USS Doyle"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5877 }
      name     = "USS Halyburton"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5878 }
      name     = "USS McClusky"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5879 }
      name     = "USS Klakring"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5880 }
      name     = "Transport Division 41"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5881 }
      name     = "Transport Division 42"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5882 }
      name     = "Transport Division 43"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5883 }
      name     = "Transport Division 44"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5884 }
      name     = "Transport Division 45"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5885 }
      name     = "Transport Division 46"
      model    = 4
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5886 }
    name     = "‘æ10‹ó•ê‘ÅŒ‚ŒQ"
    location = 23
    home     = 23
    base     = 23
    division =
    { id       = { type = 23002 id = 5887 }
      name     = "USS George Washington"
      model    = 10
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5888 }
      name     = "USS Thach"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5889 }
      name     = "USS De Wert"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5890 }
      name     = "USS Rentz"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5891 }
      name     = "USS Nicholas"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5892 }
      name     = "USS Vandegrift"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5893 }
      name     = "USS Robert G. Bradley"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5894 }
      name     = "USS Taylor"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5895 }
      name     = "Transport Division 47"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5896 }
      name     = "Transport Division 48"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5897 }
      name     = "Transport Division 49"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5898 }
      name     = "Transport Division 50"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5899 }
      name     = "Transport Division 51"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5900 }
      name     = "Transport Division 52"
      model    = 4
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5901 }
    name     = "‘æ11‹ó•ê‘ÅŒ‚ŒQ"
    location = 525
    home     = 525
    base     = 525
    division =
    { id       = { type = 23002 id = 5902 }
      name     = "USS John C. Stennis"
      model    = 10
      type     = carrier
      strength = 100.0000
      extra1        = cag
      brigade_model1= 4
    }
    division =
    { id       = { type = 23002 id = 5903 }
      name     = "USS Halsey"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5904 }
      name     = "USS Howard"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5905 }
      name     = "USS Preble"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5906 }
      name     = "USS O'Kane"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5907 }
      name     = "USS Gonzalez"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5908 }
      name     = "USS Cole"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5909 }
      name     = "USS The Sullivans"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5910 }
      name     = "Transport Division 53"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5911 }
      name     = "Transport Division 54"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5912 }
      name     = "Transport Division 55"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5913 }
      name     = "Transport Division 56"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5914 }
      name     = "Transport Division 57"
      model    = 4
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5915 }
      name     = "Transport Division 58"
      model    = 4
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 5931 }
    name     = "‘æ5…ãí“¬ŒQ"
    location = 632
    home     = 632
    base     = 632
    division =
    { id       = { type = 23002 id = 5932 }
      name     = "USS Alaska"
      model    = 2
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5933 }
      name     = "USS Guam"
      model    = 2
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5934 }
      name     = "USS Philippines"
      model    = 2
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5935 }
      name     = "USS Hawaii"
      model    = 2
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5936 }
      name     = "USS Puerto Rico"
      model    = 2
      type     = battleship
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5937 }
      name     = "USS Higgins"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5938 }
      name     = "USS O'Kane"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5939 }
      name     = "USS Porter"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5940 }
      name     = "USS Oscar Austin"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5941 }
      name     = "USS Roosevelt"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5942 }
      name     = "USS Winston S. Churchill"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5943 }
      name     = "USS Lassen"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5944 }
      name     = "USS Howard"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 5945 }
      name     = "USS Bulkeley"
      model    = 4
      type     = destroyer
      strength = 100.0000
    }
  }
  ## ƒuƒŒ[ƒgƒuƒŠƒeƒ““‡ü•Ó•º—Í
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5648 }
    name = "‰¢B”hŒ­ŒR‘æ1íp‹@b‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5649 }
    name = "‰¢B”hŒ­ŒR‘æ2íp‹@b‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5650 }
    name = "‰¢B”hŒ­ŒR‘æ3íp‹@b‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5651 }
    name = "‰¢B”hŒ­ŒR‘æ4íp‹@b‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5652 }
    name = "‰¢B”hŒ­ŒR‘æ5íp‹@b‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5653 }
    name = "‰¢B”hŒ­ŒR‘æ6íp‹@b‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5654 }
    name = "‰¢B”hŒ­ŒR‘æ7íp‹@b‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5655 }
    name = "‰¢B”hŒ­ŒR‘æ8íp‹@b‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5656 }
    name = "‰¢B”hŒ­ŒR‘æ9íp‹@b‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  ## ƒ`ƒ…ƒjƒWƒAü•Ó•º—Í
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5657 }
    name = "–kƒAƒtƒŠƒJ”hŒ­ŒR‘æ1íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5658 }
    name = "–kƒAƒtƒŠƒJ”hŒ­ŒR‘æ1íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5659 }
    name = "–kƒAƒtƒŠƒJ”hŒ­ŒR‘æ1íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  ## ƒVƒ“ƒKƒ|[ƒ‹ü•Ó•º—Í
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5660 }
    name = "‘å“ŒˆŸ˜A‡”hŒ­ŒR‘æ1íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5661 }
    name = "‘å“ŒˆŸ˜A‡”hŒ­ŒR‘æ2íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5662 }
    name = "‘å“ŒˆŸ˜A‡”hŒ­ŒR‘æ3íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  ## “ú–{ü•Ó•º—Í
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5663 }
    name = "İ“ú•ÄŒR‘æ1íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5664 }
    name = "İ“ú•ÄŒR‘æ2íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5665 }
    name = "İ“ú•ÄŒR‘æ3íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5666 }
    name = "İ“ú•ÄŒR‘æ4íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5667 }
    name = "İ“ú•ÄŒR‘æ5íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5668 }
    name = "İ“ú•ÄŒR‘æ6íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5669 }
    name = "İ“ú•ÄŒR‘æ7íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5670 }
    name = "İ“ú•ÄŒR‘æ8íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
  landdivision = {
    dormant = yes
    id = { type = 23001 id = 5671 }
    name = "İ“ú•ÄŒR‘æ9íp‹@‘å‘à"
    strength = 100
    type = paratrooper model = 6
  }
#########################################ƒnƒŠ[¥S¥ƒgƒ‹[ƒ}ƒ“
  navaldivision = {
    dormant = yes
    id = { type = 23002 id = 5916 }
    name = "USS Harry S. Truman"
    strength = 100
    type = carrier model = 10
    extra1        = cag
    brigade_model1= 4
  }
#########################################ƒgƒ‰ƒCƒfƒ“ƒgìí
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 1 }
    name = "G’e“‹Ú‘æ1ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 2 }
    name = "G’e“‹Ú‘æ2ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 3 }
    name = "G’e“‹Ú‘æ3ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 4 }
    name = "G’e“‹Ú‘æ4ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 5 }
    name = "G’e“‹Ú‘æ5ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 6 }
    name = "G’e“‹Ú‘æ6ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 7 }
    name = "G’e“‹Ú‘æ7ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 8 }
    name = "G’e“‹Ú‘æ8ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 9 }
    name = "G’e“‹Ú‘æ9ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 10 }
    name = "G’e“‹Ú‘æ10ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 11 }
    name = "G’e“‹Ú‘æ11ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 12 }
    name = "G’e“‹Ú‘æ12ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 13 }
    name = "G’e“‹Ú‘æ13ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 14 }
    name = "G’e“‹Ú‘æ14ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 15 }
    name = "G’e“‹Ú‘æ15ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 16 }
    name = "G’e“‹Ú‘æ16ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 17 }
    name = "G’e“‹Ú‘æ17ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 18 }
    name = "G’e“‹Ú‘æ18ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 19 }
    name = "G’e“‹Ú‘æ19ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 20 }
    name = "G’e“‹Ú‘æ20ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 21 }
    name = "G’e“‹Ú‘æ21ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 22 }
    name = "G’e“‹Ú‘æ22ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 23 }
    name = "G’e“‹Ú‘æ23ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 24 }
    name = "G’e“‹Ú‘æ24ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 25 }
    name = "G’e“‹Ú‘æ25ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 26 }
    name = "G’e“‹Ú‘æ26ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 27 }
    name = "G’e“‹Ú‘æ27ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 28 }
    name = "G’e“‹Ú‘æ28ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 29 }
    name = "G’e“‹Ú‘æ29ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 30 }
    name = "G’e“‹Ú‘æ30ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 31 }
    name = "G’e“‹Ú‘æ31ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 32 }
    name = "G’e“‹Ú‘æ32ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 33 }
    name = "G’e“‹Ú‘æ33ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 34 }
    name = "G’e“‹Ú‘æ34ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 35 }
    name = "G’e“‹Ú‘æ35ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 36 }
    name = "G’e“‹Ú‘æ36ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 37 }
    name = "G’e“‹Ú‘æ37ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 38 }
    name = "G’e“‹Ú‘æ38ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 39 }
    name = "G’e“‹Ú‘æ39ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 40 }
    name = "G’e“‹Ú‘æ40ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 41 }
    name = "G’e“‹Ú‘æ41ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 42 }
    name = "G’e“‹Ú‘æ42ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 43 }
    name = "G’e“‹Ú‘æ43ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 44 }
    name = "G’e“‹Ú‘æ44ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 45 }
    name = "G’e“‹Ú‘æ45ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 46 }
    name = "G’e“‹Ú‘æ46ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 47 }
    name = "G’e“‹Ú‘æ47ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 48 }
    name = "G’e“‹Ú‘æ48ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 49 }
    name = "G’e“‹Ú‘æ49ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 50 }
    name = "G’e“‹Ú‘æ50ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 51 }
    name = "G’e“‹Ú‘æ51ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
  airdivision = {
    dormant = yes
    id = { type = 23003 id = 52 }
    name = "G’e“‹Ú‘æ52ƒƒPƒbƒg•”‘à"
    strength = 100
    nuke = yes
    type = flying_rocket
    model = 4
  }
}
