
##############################
# Country definition for BRU #
##############################

province =
{ id         = 1646
  ic         = 6
  naval_base = { size = 7 current_size = 7 }
}              # バンダルスリブガワン

#####################
# Country main data #
#####################

country =
{ tag                 = BRU
  manpower            = 14
  energy              = 500
  metal               = 500
  rare_materials      = 500
  oil                 = 500
  supplies            = 80000
  money               = 100
  capital             = 1646
  regular_id          = U04
  transports          = 50
  escorts             = 10
  policy              = { democratic = 8 political_left = 7 freedom = 4 free_market = 8 professional_army = 8 defense_lobby = 7 interventionism = 6 }
  ownedprovinces      = { 1646 }
  controlledprovinces = { 1646 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080
                        }
  nationalprovinces   = { 1646 }
}
