
##############################
# Country definition for SAF #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = GUI
  energy              = 5000
  metal               = 5000
  rare_materials      = 5000
  oil                 = 500
  supplies            = 3000
  manpower            = 50
  transports          = 70
  escorts             = 12
  capital             = 987
  regular_id          = U01
  money               = 350
  policy =
  { date              = { year = 0 month = january day = 0 }
    democratic        = 10
    political_left    = 2
    freedom           = 10
    free_market       = 8
    professional_army = 5
    defense_lobby     = 7
    interventionism   = 6
  }
  ownedprovinces      = { 987 990 991 }
  controlledprovinces = { 987 990 991 }
  nationalprovinces   = { 987 990 991 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080
                        }
}
