
##############################
# Country definition for IND #
##############################

province =
{ id       = 631
  anti_air = 1
  air_base = { size = 2 current_size = 2 }
}            # ƒCƒ“ƒh[ƒ‹
province = { id = 635 ic = 2 } # ƒ‰[ƒCƒKƒ‹
province = { id = 669 ic = 3 } # ƒuƒ‹ƒn[ƒ“ƒvƒ‹
province =
{ id       = 702
  air_base = { size = 2 current_size = 2 }
}            # ƒ‰[ƒ„ƒ`ƒ…[ƒ‹
province =
{ id       = 773
  air_base = { size = 2 current_size = 2 }
}            # ƒRƒCƒ“ƒoƒg[ƒ‹
province =
{ id       = 781
  air_base = { size = 2 current_size = 2 }
}            # ƒAƒfƒBƒ‰[ƒo[ƒh
province =
{ id       = 791
  air_base = { size = 2 current_size = 2 }
}            # ƒoƒ‰ƒ“ƒMƒ‹
province =
{ id         = 1457
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
  ic         = 2
}              # ƒJƒ‹ƒJƒbƒ^
province = { id = 1458 ic = 3 } # ƒuƒ”ƒ@ƒl[ƒVƒ…ƒ”ƒ@ƒ‹
province = { id = 1459 ic = 2 } # ƒ‰ƒ“ƒ`
province =
{ id       = 1462
  air_base = { size = 5 current_size = 5 }
}            # ƒAƒ}ƒ‰ƒ”ƒ@ƒeƒB[
province =
{ id       = 1469
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ƒfƒŠ[
province =
{ id            = 1505
  anti_air      = 3
  air_base      = { size = 2 current_size = 2 }
  naval_base    = { size = 2 current_size = 2 }
  ic            = 4
}                 # ƒ{ƒ“ƒxƒC
province = { id = 1507 ic = 3 } # ƒnƒCƒfƒ‰ƒo[ƒh
province = { id = 1508 ic = 2 } # ƒ”ƒBƒVƒƒ[ƒJƒpƒgƒiƒ€
province = { id = 1509 ic = 3 } # ƒlƒbƒ[ƒ‹
province =
{ id         = 1513
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # ƒ}ƒ“ƒKƒ[ƒ‹
province = { id = 1515 ic = 2 } # ƒ}ƒhƒDƒ‰ƒC
province = { id = 1516 ic = 1 } # ƒLƒƒƒ“ƒfƒB
province =
{ id         = 1517
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 2 current_size = 2 }
  ic         = 2
}              # ƒRƒƒ“ƒ{
province = { id = 1519 ic = 1 } # ƒJƒ‰ƒOƒvƒ‹
province =
{ id          = 1591
  anti_air    = 2
  air_base    = { size = 4 current_size = 4 }
  naval_base  = { size = 4 current_size = 4 }
  coastalfort = 3
  oilpool     = 1000
  supplypool  = 2000
  ic          = 3
}               # ƒgƒŠƒ“ƒRƒ}ƒŠ[
province =
{ id            = 1694
  naval_base    = { size = 4 current_size = 4 }
  air_base      = { size = 2 current_size = 2 }
}                 # ƒ}ƒhƒ‰ƒX
province = { id = 1758 ic = 2 } # ƒR[ƒ`
province =
{ id         = 1817
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 2 current_size = 2 }
}              # ƒ}ƒŒ
province =
{ id       = 2592
  air_base = { size = 2 current_size = 2 }
}            # ƒfƒBƒuƒ‹[ƒKƒ‹

#####################
# Country main data #
#####################

country =
{ tag                 = IND
  manpower            = 360
  energy              = 8000
  metal               = 3500
  rare_materials      = 5000
  oil                 = 4000
  supplies            = 6000
  money               = 350
  capital             = 1469
  regular_id          = U04
  transports          = 250
  escorts             = 150
  nationalprovinces   = { 1458 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1478 1479 1505 1506 1507 1508 1509 1510 1511 1513
                          1514 1515 599  685  687  736  1476 1477 1705 2092 2199 593  597  669  697  726  769  785  1699 611  631  635  714  722  1701
                          1721 2091 2094 2133 773  774  775  1694 1758 2106 702  703  771  1695 2099 2175 729  791  2124 2198 781  1284 1287 1454 1456
                          1457 1519 2104 2592 1518 2085 1512 777  1817
                        }
  ownedprovinces      = { 1458 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1478 1479 1505 1506 1507 1508 1509 1510 1511 1513
                          1514 1515 599  685  687  736  1476 1477 1705 2092 2199 593  597  669  697  726  769  785  1699 611  631  635  714  722  1701
                          1721 2091 2094 2133 773  774  775  1694 1758 2106 702  703  771  1695 2099 2175 729  791  2124 2198 781  1284 1287 1454 1456
                          1457 1519 2104 2592 1518 2085 1512 777  1817
                        }
  controlledprovinces = { 1458 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1478 1479 1505 1506 1507 1508 1509 1510 1511 1513
                          1514 1515 599  685  687  736  1476 1477 1705 2092 2199 593  597  669  697  726  769  785  1699 611  631  635  714  722  1701
                          1721 2091 2094 2133 773  774  775  1694 1758 2106 702  703  771  1695 2099 2175 729  791  2124 2198 781  1284 1287 1454 1456
                          1457 1519 2104 2592 1518 2085 1512 777  1817
                        }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010  9020  9030  9040  9050  9060
                          9340  6050  6060  6070  6080  6090  1020  1220  1660  1760
                        }
  policy              = { democratic = 3 political_left = 3 freedom = 2 free_market = 3 professional_army = 9 defense_lobby = 8 interventionism = 9 }
    landunit = {
	name = "‘æ2RŠx•à•ºt’c"
	id = { type = 24581 id = 1 }
	location = 1457
	division = {
	id = { type = 24581 id = 2 }
	name = "‘æ1RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 3 }
	name = "‘æ2RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 4 }
	name = "‘æ3RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 5 }
	name = "‘æ4RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 6 }
	name = "‘æ5RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 7 }
	name = "‘æ6RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
}
landunit = {
	name = "‘æ56RŠx•à•ºt’c"
	id = { type = 24581 id = 8 }
	location = 1456
	division = {
	id = { type = 24581 id = 9 }
	name = "‘æ7RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 10 }
	name = "‘æ8RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 11 }
	name = "‘æ9RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 12 }
	name = "‘æ10RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 13 }
	name = "‘æ11RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 14 }
	name = "‘æ12RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
}
landunit = {
	name = "‘æ57RŠx•à•ºt’c"
	id = { type = 24581 id = 15 }
	location = 1454
	division = {
	id = { type = 24581 id = 16 }
	name = "‘æ13RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 17 }
	name = "‘æ14RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 18 }
	name = "‘æ15RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 19 }
	name = "‘æ16RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 20 }
	name = "‘æ17RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 21 }
	name = "‘æ18RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
}
landunit = {
	name = "‘æ5RŠx•à•ºt’c"
	id = { type = 24581 id = 22 }
	location = 1284
	division = {
	id = { type = 24581 id = 23 }
	name = "‘æ19RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 24 }
	name = "‘æ20RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 25 }
	name = "‘æ21RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 26 }
	name = "‘æ22RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 27 }
	name = "‘æ23RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 28 }
	name = "‘æ24RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
}
landunit = {
	name = "‘æ21RŠx•à•ºt’c"
	id = { type = 24581 id = 29 }
	location = 2592
	division = {
	id = { type = 24581 id = 30 }
	name = "‘æ25RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 31 }
	name = "‘æ26RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 32 }
	name = "‘æ27RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 33 }
	name = "‘æ28RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 34 }
	name = "‘æ29RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 35 }
	name = "‘æ30RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
}
landunit = {
	name = "‘æ71RŠx•à•ºt’c"
	id = { type = 24581 id = 36 }
	location = 2104
	division = {
	id = { type = 24581 id = 37 }
	name = "‘æ31RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 38 }
	name = "‘æ32RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 39 }
	name = "‘æ33RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 40 }
	name = "‘æ34RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 41 }
	name = "‘æ35RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 42 }
	name = "‘æ36RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
}
landunit = {
	name = "‘æ17RŠx•à•ºt’c"
	id = { type = 24581 id = 43 }
	location = 1287
	division = {
	id = { type = 24581 id = 44 }
	name = "‘æ37RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 45 }
	name = "‘æ38RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 46 }
	name = "‘æ39RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 47 }
	name = "‘æ40RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 48 }
	name = "‘æ41RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 49 }
	name = "‘æ42RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
}
landunit = {
	name = "‘æ20RŠx•à•ºt’c"
	id = { type = 24581 id = 50 }
	location = 1472
	division = {
	id = { type = 24581 id = 51 }
	name = "‘æ43RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 52 }
	name = "‘æ44RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 53 }
	name = "‘æ45RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 54 }
	name = "‘æ46RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 55 }
	name = "‘æ47RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 56 }
	name = "‘æ48RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
}
landunit = {
	name = "‘æ27RŠx•à•ºt’c"
	id = { type = 24581 id = 57 }
	location = 2094
	division = {
	id = { type = 24581 id = 58 }
	name = "‘æ49RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 59 }
	name = "‘æ50RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 60 }
	name = "‘æ51RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 61 }
	name = "‘æ52RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 62 }
	name = "‘æ53RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 63 }
	name = "‘æ54RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
  }
landunit = {
	name = "‘æ8RŠx•à•ºt’c"
	id = { type = 24581 id = 64 }
	location = 736
	division = {
	id = { type = 24581 id = 65 }
	name = "‘æ55RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 66 }
	name = "‘æ56RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 67 }
	name = "‘æ57RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 68 }
	name = "‘æ58RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 69 }
	name = "‘æ59RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 70 }
	name = "‘æ60RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
}
landunit = {
	name = "‘æ28RŠx•à•ºt’c"
	id = { type = 24581 id = 71 }
	location = 687
	division = {
	id = { type = 24581 id = 72 }
	name = "‘æ61RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 73 }
	name = "‘æ62RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 74 }
	name = "‘æ63RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 75 }
	name = "‘æ64RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 76 }
	name = "‘æ65RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 77 }
	name = "‘æ66RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
}
landunit = {
	name = "‘æ6RŠx•à•ºt’c"
	id = { type = 24581 id = 78 }
	location = 703
	division = {
	id = { type = 24581 id = 79 }
	name = "‘æ67RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 80 }
	name = "‘æ68RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 81 }
	name = "‘æ69RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 82 }
	name = "‘æ70RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 83 }
	name = "‘æ71RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
	division = {
	id = { type = 24581 id = 84 }
	name = "‘æ72RŠx•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 50
	}
  }
landunit = {
	name = "‘æ23•à•ºt’c"
	id = { type = 24581 id = 85 }
	location = 1457
	division = {
	id = { type = 24581 id = 86 }
	name = "‘æ1•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 87 }
	name = "‘æ2•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 88 }
	name = "‘æ3•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 89 }
	name = "‘æ4•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 90 }
	name = "‘æ5•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 91 }
	name = "‘æ6•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ3•à•ºt’c"
	id = { type = 24581 id = 92 }
	location = 1705
	division = {
	id = { type = 24581 id = 93 }
	name = "‘æ7•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 94 }
	name = "‘æ8•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 95 }
	name = "‘æ9•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 96 }
	name = "‘æ10•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 97 }
	name = "‘æ11•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 98 }
	name = "‘æ12•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ19•à•ºt’c"
	id = { type = 24581 id = 99 }
	location = 1476
	division = {
	id = { type = 24581 id = 100 }
	name = "‘æ13•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 101 }
	name = "‘æ14•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 102 }
	name = "‘æ15•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 103 }
	name = "‘æ16•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 104 }
	name = "‘æ17•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 105 }
	name = "‘æ18•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ10•à•ºt’c"
	id = { type = 24581 id = 106 }
	location = 1477
	division = {
	id = { type = 24581 id = 107 }
	name = "‘æ19•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 108 }
	name = "‘æ20•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 109 }
	name = "‘æ21•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 110 }
	name = "‘æ22•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 111 }
	name = "‘æ23•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 112 }
	name = "‘æ24•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ25•à•ºt’c"
	id = { type = 24581 id = 113 }
	location = 1478
	division = {
	id = { type = 24581 id = 114 }
	name = "‘æ25•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 115 }
	name = "‘æ26•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 116 }
	name = "‘æ27•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 117 }
	name = "‘æ28•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 118 }
	name = "‘æ29•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 119 }
	name = "‘æ30•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ39•à•ºt’c"
	id = { type = 24581 id = 120 }
	location = 1469
	division = {
	id = { type = 24581 id = 121 }
	name = "‘æ31•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 122 }
	name = "‘æ32•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 123 }
	name = "‘æ33•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 124 }
	name = "‘æ34•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 125 }
	name = "‘æ35•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 126 }
	name = "‘æ36•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ11•à•ºt’c"
	id = { type = 24581 id = 127 }
	location = 1694
	division = {
	id = { type = 24581 id = 128 }
	name = "‘æ37•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 129 }
	name = "‘æ38•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 130 }
	name = "‘æ39•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 131 }
	name = "‘æ40•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 132 }
	name = "‘æ41•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 133 }
	name = "‘æ42•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ54•à•ºt’c"
	id = { type = 24581 id = 134 }
	location = 1513
	division = {
	id = { type = 24581 id = 135 }
	name = "‘æ43•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 136 }
	name = "‘æ44•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 137 }
	name = "‘æ45•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 138 }
	name = "‘æ46•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 139 }
	name = "‘æ47•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 140 }
	name = "‘æ48•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ4•à•ºt’c"
	id = { type = 24581 id = 141 }
	location = 1505
	division = {
	id = { type = 24581 id = 142 }
	name = "‘æ49•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 143 }
	name = "‘æ50•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 144 }
	name = "‘æ51•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 145 }
	name = "‘æ52•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 146 }
	name = "‘æ53•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 147 }
	name = "‘æ54•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ16•à•ºt’c"
	id = { type = 24581 id = 148 }
	location = 1512
	division = {
	id = { type = 24581 id = 149 }
	name = "‘æ55•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 150 }
	name = "‘æ56•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 151 }
	name = "‘æ57•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 152 }
	name = "‘æ58•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 153 }
	name = "‘æ59•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 154 }
	name = "‘æ60•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ22•à•ºt’c"
	id = { type = 24581 id = 155 }
	location = 1479
	division = {
	id = { type = 24581 id = 156 }
	name = "‘æ61•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 157 }
	name = "‘æ62•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 158 }
	name = "‘æ63•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 159 }
	name = "‘æ64•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 160 }
	name = "‘æ65•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 161 }
	name = "‘æ66•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ26•à•ºt’c"
	id = { type = 24581 id = 162 }
	location = 593
	division = {
	id = { type = 24581 id = 163 }
	name = "‘æ67•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 164 }
	name = "‘æ68•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 165 }
	name = "‘æ69•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 166 }
	name = "‘æ70•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 167 }
	name = "‘æ71•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 168 }
	name = "‘æ72•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ29•à•ºt’c"
	id = { type = 24581 id = 169 }
	location = 593
	division = {
	id = { type = 24581 id = 170 }
	name = "‘æ73•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 171 }
	name = "‘æ74•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 172 }
	name = "‘æ75•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 173 }
	name = "‘æ76•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 174 }
	name = "‘æ77•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 175 }
	name = "‘æ78•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ7•à•ºt’c"
	id = { type = 24581 id = 176 }
	location = 1479
	division = {
	id = { type = 24581 id = 177 }
	name = "‘æ79•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 178 }
	name = "‘æ80•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 179 }
	name = "‘æ81•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 180 }
	name = "‘æ82•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 181 }
	name = "‘æ83•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 182 }
	name = "‘æ84•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ9•à•ºt’c"
	id = { type = 24581 id = 183 }
	location = 1721
	division = {
	id = { type = 24581 id = 184 }
	name = "‘æ85•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 185 }
	name = "‘æ86•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 186 }
	name = "‘æ87•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 187 }
	name = "‘æ88•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 188 }
	name = "‘æ89•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 189 }
	name = "‘æ90•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
}
landunit = {
	name = "‘æ15•à•ºt’c"
	id = { type = 24581 id = 190 }
	location = 1479
	division = {
	id = { type = 24581 id = 191 }
	name = "‘æ91•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 192 }
	name = "‘æ92•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 193 }
	name = "‘æ93•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 194 }
	name = "‘æ94•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 195 }
	name = "‘æ95•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
	division = {
	id = { type = 24581 id = 196 }
	name = "‘æ96•à•º‘å‘à"
	type = mechanized
	model = 22
	experience = 0
	}
  }
landunit = {
	name = "‘æ12Œy‹@ŠB‰»•à•ºt’c"
	id = { type = 24581 id = 197 }
	location = 702
	division = {
	id = { type = 24581 id = 198 }
	name = "‘æ1Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 199 }
	name = "‘æ2Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 200 }
	name = "‘æ3Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 201 }
	name = "‘æ4Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 202 }
	name = "‘æ5Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 203 }
	name = "‘æ6Œy‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ36Œy‹@ŠB‰»•à•ºt’c"
	id = { type = 24581 id = 204 }
	location = 1515
	division = {
	id = { type = 24581 id = 205 }
	name = "‘æ7Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 206 }
	name = "‘æ8Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 207 }
	name = "‘æ9Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 208 }
	name = "‘æ10Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 209 }
	name = "‘æ11Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 210 }
	name = "‘æ12Œy‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ18Œy‹@ŠB‰»•à•ºt’c"
	id = { type = 24581 id = 211 }
	location = 1464
	division = {
	id = { type = 24581 id = 212 }
	name = "‘æ13Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 213 }
	name = "‘æ14Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 214 }
	name = "‘æ15Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 215 }
	name = "‘æ16Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 216 }
	name = "‘æ17Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 217 }
	name = "‘æ18Œy‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ24Œy‹@ŠB‰»•à•ºt’c"
	id = { type = 24581 id = 218 }
	location = 1464
	division = {
	id = { type = 24581 id = 219 }
	name = "‘æ19Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 220 }
	name = "‘æ20Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 221 }
	name = "‘æ21Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 222 }
	name = "‘æ22Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 223 }
	name = "‘æ23Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 224 }
	name = "‘æ24Œy‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ14Œy‹@ŠB‰»•à•ºt’c"
	id = { type = 24581 id = 225 }
	location = 1479
	division = {
	id = { type = 24581 id = 226 }
	name = "‘æ25Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 227 }
	name = "‘æ26Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 228 }
	name = "‘æ27Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 229 }
	name = "‘æ28Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 230 }
	name = "‘æ29Œy‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 231 }
	name = "‘æ30Œy‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
  }
landunit = {
	name = "‘æ31‹@bt’c"
	id = { type = 24581 id = 232 }
	location = 1510
	division = {
	id = { type = 24581 id = 233 }
	name = "‘æ1íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 234 }
	name = "‘æ2íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 235 }
	name = "‘æ3íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 236 }
	name = "‘æ1‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 237 }
	name = "‘æ2‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 238 }
	name = "‘æ3‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
	}
}
landunit = {
	name = "‘æ1‹@bt’c"
	id = { type = 24581 id = 239 }
	location = 1479
	division = {
	id = { type = 24581 id = 240 }
	name = "‘æ4íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 241 }
	name = "‘æ5íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 242 }
	name = "‘æ6íÔ‘å‘à"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 243 }
	name = "‘æ4‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 244 }
	name = "‘æ5‹@ŠB‰»•à•º‘å‘à"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 24581 id = 245 }
	name = "‘æ6‹@ŠB‰»•à•º‘å‘à"
	type = light_armor
	model = 1
	experience = 0
   }
  }
}
