
##############################
# Country definition for LAO #
##############################

province = { id = 1306 ic = 1 } # ムアンサイ
province = { id = 1329 ic = 3 } # ヴィエンチャン
province = { id = 1332 ic = 1 } # パクセ

#####################
# Country main data #
#####################

country =
{ tag                 = LAO
  manpower            = 24
  energy              = 500
  metal               = 500
  rare_materials      = 500
  oil                 = 500
  supplies            = 200
  money               = 100
  capital             = 1329
  regular_id          = U04
  transports          = 22
  escorts             = 15
  nationalprovinces   = { 1306 1329 1332 1336 1589 }
  ownedprovinces      = { 1306 1329 1332 1336 1589 }
  controlledprovinces = { 1306 1329 1332 1336 1589 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080
                        }
  policy              = { democratic = 2 political_left = 3 freedom = 3 free_market = 4 professional_army = 7 defense_lobby = 8 interventionism = 8 }
}
