
##############################
# Country definition for PAK #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = U95
  manpower            = 95
  energy              = 800
  metal               = 800
  rare_materials      = 800
  oil                 = 800
  supplies            = 200
  money               = 100
  capital             = 1286
  regular_id          = U04
  transports          = 55
  escorts             = 12
  policy              = { democratic = 2 political_left = 3 freedom = 3 free_market = 3 professional_army = 7 defense_lobby = 8 interventionism = 6 }
  ownedprovinces      = { 1285 1286 1288 1590 }
  controlledprovinces = { 1285 1286 1288 1590 }
  techapps            = { 10050 1010  10190 1020  1110  1120  1210  1550  1650  3010  3020  3110  3460  3810  3910  4390  50020 5010  5020  50290
                          50300 5090  5410  5600  7010  80080 8010  8020  8030  8040  8050  8060  8070  8080  9010 
                          9340  6050  6060  6070  6080
                        }
  nationalprovinces   = { 1285 1286 1288 1590 }
}
