
##############################
# Country definition for USA #
##############################

province = { id = 548 ic = 8 } # ディバリングハム
province =
{ id         = 549
  anti_air   = 1
  ic         = 5
  air_base   = { size = 2 current_size = 2 }
  Naval_base = { size = 2 current_size = 2 }
}              # アンカレッジ
province = { id = 553 supplypool = 1000 ic = 3 } # ジュノー
province = { id = 582 ic = 4 } # バンゴー
province = { id = 583 ic = 4 } # ルイストン
Province =
{ id       = 592
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # シラキュース
province =
{ id       = 595
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # コンコード
province =
{ id            = 600
  anti_air      = 3
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 8 current_size = 8 }
}                 # ボストン
province = { id = 601 ic = 5 } # プロビデンス
province = { id = 603 ic = 2 } # ニューアーク
province = { id = 604 ic = 5 } # ハリスバーグ
province = { id = 605 ic = 2 } # ドーバー
province =
{ id       = 606
  anti_air = 4
  ic       = 9
  air_base = { size = 10 current_size = 10 }
}            # ワシントンD.C.
province = { id = 607 ic = 4 } # ボルティモア
province =
{ id            = 608
  anti_air      = 2
  ic            = 3
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 8 current_size = 8 }
}                 # フィラデルフィア
province = { id = 609 ic = 5 } # セントメアリー
province = { id = 612 ic = 10 } # バッファロー
province = { id = 613 ic = 5 } # フォート・ウェイン
province =
{ id       = 614
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
  ic       = 10
}            # ピッツバーグ
province = { id = 615 ic = 3 } # クリーヴランド
province =
{ id       = 616
  anti_air = 1
  ic       = 4
  air_base = { size = 4 current_size = 4 }
}            # デトロイト
province = { id = 619 ic = 3 } # コロンビア
province =
{ id            = 620
  anti_air      = 3
  ic            = 7
  air_base      = { size = 10 current_size = 10 }
}                 # シカゴ
province =
{ id            = 621
  anti_air      = 1
  ic            = 8
  air_base      = { size = 4 current_size = 4 }
}                 # ミルウォーキー
province = { id = 622 ic = 6 } # マルケット
province = { id = 623 ic = 5 } # グリーンベイ
province =
{ id       = 624
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # デモイン
province = { id = 629 ic = 5 } # クラークスバーグ
province =
{ id         = 632
  anti_air   = 4
  ic         = 1
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
}              # ノーフォーク
province =
{ id            = 633
  anti_air      = 4
  ic            = 3
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 8 current_size = 8 }
}                 # リッチモンド
Province =
{ id       = 637
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # シャーロット
province = { id = 640 ic = 4 } # レキシントン
province =
{ id       = 641
  anti_air = 1
  ic       = 2
  air_base = { size = 4 current_size = 4 }
}            # ルイスヴィル
province =
{ id            = 644
  anti_air      = 1
  ic            = 2
  air_base      = { size = 4 current_size = 4 }
}                 # チャールストン
province = { id = 645 ic = 4 } # グリーンビル
Province =
{ id       = 648
  anti_air = 1
  ic       = 1
  air_base = { size = 4 current_size = 4 }
}            # ジャクソンヴィル
province =
{ id            = 651
  anti_air      = 1
  ic            = 2
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 4 current_size = 4 }
}                 # マイアミ
province =
{ id         = 662
  air_base   = { size = 2 current_size = 2 }
  supplypool = 100
}              # ミッドウェー
province =
{ id         = 663
  anti_air   = 3
  air_base   = { size = 10 current_size = 10 }
  Naval_base = { size = 10 current_size = 10 }
  oilpool    = 1000
  supplypool = 1000
}              # ホノルル
province =
{ id            = 670
  anti_air      = 1
  ic            = 5
  air_base      = { size = 4 current_size = 4 }
}                 # アトランタ
Province =
{ id       = 673
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # メンフィス
province = { id = 676 ic = 2 } # ペンサコーラ
Province =
{ id       = 678
  anti_air = 1
  ic       = 1
  air_base = { size = 4 current_size = 4 }
}            # モービル
province = { id = 680 ic = 1 } # ラファイエット
province =
{ id            = 683
  anti_air      = 1
  air_base      = { size = 4 current_size = 4 }
}                 # リトルロック
province =
{ id       = 689
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # セントルイス
province = { id = 694 ic = 4 } # セントポール
province =
{ id       = 699
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ビスマルク
province =
{ id            = 707
  anti_air      = 1
  air_base      = { size = 4 current_size = 4 }
}                 # デンヴァー
province = { id = 711 ic = 2 } # タイラー
province =
{ id            = 716
  anti_air      = 2
  ic            = 2
  air_base      = { size = 4 current_size = 4 }
}                 # ヒューストン
Province =
{ id       = 725
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # サンタフェ
province =
{ id       = 728
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # フェニックス
province =
{ id       = 733
  anti_air = 1
  air_base = { size = 10 current_size = 10 }
}            # ソルトレイクシティ
province = { id = 734 ic = 6 } # ラスヴェガス
Province =
{ id         = 748
  anti_air   = 1
  ic         = 3
  air_base   = { size = 4 current_size = 4 }
  Naval_base = { size = 8 current_size = 8 }
}              # コーパスクリスティ
province =
{ id            = 761
  anti_air      = 1
  ic            = 5
  air_base      = { size = 10 current_size = 10 }
  Naval_base    = { size = 10 current_size = 10 }
}                 # サンディエゴ
province =
{ id       = 762
  anti_air = 3
  ic       = 2
  air_base = { size = 4 current_size = 4 }
}            # ロスアンジェルス
province = { id = 763 ic = 4 } # フレズノ
province =
{ id            = 764
  anti_air      = 2
  air_base      = { size = 4 current_size = 4 }
}                 # サクラメント
province =
{ id            = 765
  anti_air      = 3
  ic            = 8
  air_base      = { size = 4 current_size = 4 }
  Naval_base    = { size = 10 current_size = 10 }
}                 # サンフランシスコ
province = { id = 766 ic = 5 } # レディング
province = { id = 772 ic = 3 } # ミズーラ
province =
{ id       = 780
  anti_air = 1
  ic       = 10
  air_base = { size = 4 current_size = 4 }
}            # シアトル
province =
{ id         = 782
  anti_air   = 1
  ic         = 9
  Naval_base = { size = 4 current_size = 4 }
}              # タコマ
province =
{ id       = 783
  anti_air = 1
  ic       = 10
  air_base = { size = 4 current_size = 4 }
}            # ポートランド
province =
{ id       = 790
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # オマハ
province =
{ id       = 793
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # オクラホマシティ
province =
{ id         = 889
  anti_air   = 3
  air_base   = { size = 2 current_size = 2 }
  Naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 100
}              # バルボア
province =
{ id         = 894
  anti_air   = 1
  air_base   = { size = 2 current_size = 2 }
  Naval_base = { size = 2 current_size = 2 }
}              # グァンタナモ海軍基地
province = { id = 895 supplypool = 50 } # サンフアン
province =
{ id         = 1624
  anti_air   = 3
  air_base   = { size = 2 current_size = 2 }
  Naval_base = { size = 2 current_size = 2 }
  oilpool    = 100
  supplypool = 100
}              # アガナ
province = { id = 2643 ic = 2 } # アニマック
province = { id = 2644 ic = 4 } # ラケ・クラーク
province = { id = 2645 ic = 2 } # フェアバンクス

#####################
# Country main data #
#####################

country =
{ tag                 = USA
  manpower            = 1250
  energy              = 80000
  metal               = 80000
  rare_materials      = 60000
  oil                 = 60000
  supplies            = 6000
  money               = 3500
  capital             = 606
  regular_id          = U06
  transports          = 2500
  escorts             = 2200
  headofstate            = { type = 9 id = 6001 }
  headofgovernment       = { type = 9 id = 6002 }
  foreignminister        = { type = 9 id = 6003 }
  armamentminister       = { type = 9 id = 6004 }
  ministerofsecurity     = { type = 9 id = 6005 }
  ministerofintelligence = { type = 9 id = 6006 }
  chiefofstaff           = { type = 9 id = 6007 }
  chiefofarmy            = { type = 9 id = 6008 }
  chiefofnavy            = { type = 9 id = 6009 }
  chiefofair             = { type = 9 id = 6010 }
  nationalprovinces   = { 651  650  649  648  677  676  672  646  647  670  644  645  634  636  637  643  633  632  638  639  606  607  605  604  603 
                          612  602  598  592  608  609  610  594  595  596  582  583  600  601  613  614  629  630  640  641  642  671  673  675  678 
                          679  615  628  617  616  618  619  627  680  681  682  683  684  686  688  689  626  625  620  621  624  623  622  690  691 
                          693  694  698  699  787  788  789  790  792  793  711  712  713  715  716  717  719  721  748  724  725  727  728  730 
                          731  732  733  706  707  708  709  705  704  701  770  772  776  779  780  782  783  784  786  778  768  734  735  767  761 
                          762  763  764  765  766  553  550  549  548  718  895  889  1278 2365 2367 2377 2261 2259 2255 908  2641 2642 1399 2643 2644
                          2645 2661
                        }
  ownedprovinces      = { 1278 1600 1601 1602 1603 1604 1605 1608 1618 1619 1620 1621 1624 1755 1760 1763 1765 1766 1786 2255 2259 2261 2365 2367 2377
                          582  583  592  594  595  596  598  600  601  603  604  605  606  607  608  609  610  612  613  614  615  616  617  618  619 
                          620  621  622  623  624  625  626  627  628  629  630  632  633  634  636  637  638  639  640  641  642  643  644  645  646 
                          647  648  649  650  651  658  659  660  662  663  670  671  672  673  675  676  677  678  679  680  681  682  683  684  686 
                          688  689  690  691  693  694  698  699  701  704  705  706  707  708  709  711  712  713  715  716  717  718  719  721 
                          724  725  727  728  730  731  732  733  734  735  748  761  762  763  764  765  766  767  768  770  772  776  778  779  780 
                          782  783  784  786  787  788  789  790  792  793  794  889  894  895  1617 1625 1626 1627 548  2643 2644 2645 549  553 
                          550 908 1399 2641 2642 2661
                        }
  controlledprovinces = { 1278 1600 1601 1602 1603 1604 1605 1608 1617 1618 1619 1620 1621 1624 1625 1626 1627 1755 1760 1763 1765 1766 1786 2255 2259
                          2261 2365 2367 2377 582  583  592  594  595  596  598  600  601  603  604  605  606  607  608  609  610  612  613  614  615 
                          616  617  618  619  620  621  622  623  624  625  626  627  628  629  630  632  633  634  636  637  638  639  640  641  642 
                          643  644  645  646  647  648  649  650  651  658  659  660  662  663  670  671  672  673  675  676  677  678  679  680  681 
                          682  683  684  686  688  689  690  691  693  694  698  699  701  704  705  706  707  708  709  711  712  713  715  716 
                          717  718  719  721  724  725  727  728  730  731  732  733  734  735  748  761  762  763  764  765  766  767  768  770  772 
                          776  778  779  780  782  783  784  786  787  788  789  790  792  793  794  889  894  895  548  2643 2644 2645 549  553 
                          550 908 1399 2641 2642 2661
                        }
  techapps            = { 10050 10060 1010  10190 1020  10200 1030  1050  1110  1120 
                          1210  1220  1470  1490  1510  1530  1550  1560  1650  1660
                          1750  1760  1850  1860  1950  1960
                          3010  3020  30410 30420 30510 30520 3110 
                          3120  3210  3220  3460  3470  40200 40210  3310  3320  3610  3620  3710  3720  7500  7510  7520  7530  7540  7670  7680  7690  7700
                          3560  3640  3650  3910  3920
                          3940  40100 40110 4390  4400  4010  4020  4110  4120  4210  4220  4640  4650  4820  4830
                          4560  50020 50030 50040 50050 50070 50080 50090 5010  50100 50110 50120 5020  50290 50300 50310
                          5090  5100  5170  5180  5250  5260  5330  5340  5410  5420
                          5490  5500  5600  5610  5680  5690  5760  5770  5780  5790  5800  5810
                          5910  5920  7010  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990  2000  2210  3000  4000  5000  7030  7040  7050
                        }
  inventions          = { 8000 8009 8011 }
  blueprints             = { 2010 2020 2030 }
  policy =
  { democratic        = 10
    political_left    = 4
    freedom           = 10
    free_market       = 10
    professional_army = 9
    defense_lobby     = 8
    interventionism   = 10
  }
landunit = {
	name = "第1機甲師団"
	id = { type = 23001 id = 1 }
	location = 312
	division = {
	id = { type = 23001 id = 2 }
	name = "第1戦車大隊"
	type = armor
	model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 3 }
	name = "第2戦車大隊"
	type = armor
	model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 4 }
	name = "第3戦車大隊"
	type = armor
	model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 5 }
	name = "第1機械化歩兵大隊"
	type = mechanized
	model = 1
	extra = anti_air
	brigade_model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 6 }
	name = "第2機械化歩兵大隊"
	type = mechanized
	model = 1
	extra = anti_air
	brigade_model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 7 }
	name = "第1装甲大隊"
	type = light_armor
	model = 1
	experience = 0
        #locked = yes
	}
  }
landunit = {
	name = "第2機甲師団"
	id = { type = 23001 id = 8 }
	location = 313
	division = {
	id = { type = 23001 id = 9 }
	name = "第4戦車大隊"
	type = armor
	model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 10 }
	name = "第5戦車大隊"
	type = armor
	model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 11 }
	name = "第6戦車大隊"
	type = armor
	model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 12 }
	name = "第3機械化歩兵大隊"
	type = mechanized
	model = 1
	extra = anti_air
	brigade_model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 13 }
	name = "第4機械化歩兵大隊"
	type = mechanized
	model = 1
	extra = anti_air
	brigade_model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 14 }
	name = "第2装甲大隊"
	type = light_armor
	model = 1
	experience = 0
        #locked = yes
	}
  }
landunit = {
	name = "第3機甲師団"
	id = { type = 23001 id = 15 }
	location = 376
	division = {
	id = { type = 23001 id = 16 }
	name = "第7戦車大隊"
	type = armor
	model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 17 }
	name = "第8戦車大隊"
	type = armor
	model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 18 }
	name = "第9戦車大隊"
	type = armor
	model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 19 }
	name = "第5機械化歩兵大隊"
	type = mechanized
	model = 1
	extra = anti_air
	brigade_model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 20 }
	name = "第6機械化歩兵大隊"
	type = mechanized
	model = 1
	extra = anti_air
	brigade_model = 1
	experience = 0
        #locked = yes
	}
	division = {
	id = { type = 23001 id = 21 }
	name = "第3装甲大隊"
	type = light_armor
	model = 1
	experience = 0
        #locked = yes
	}
  }
landunit = {
	name = "第3歩兵師団"
	id = { type = 23001 id = 22 }
	location = 375
	division = {
	id = { type = 23001 id = 23 }
	name = "第10戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 24 }
	name = "第1自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 25 }
	name = "第2自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 26 }
	name = "第3自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 27 }
	name = "第7機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 28 }
	name = "第8機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "第26歩兵師団"
	id = { type = 23001 id = 29 }
	location = 600
	division = {
	id = { type = 23001 id = 30 }
	name = "第11戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 31 }
	name = "第4自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 32 }
	name = "第5自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 33 }
	name = "第6自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 34 }
	name = "第9機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 35 }
	name = "第10機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "第28歩兵師団"
	id = { type = 23001 id = 36 }
	location = 627
	division = {
	id = { type = 23001 id = 37 }
	name = "第12戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 38 }
	name = "第7自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 39 }
	name = "第8自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 40 }
	name = "第9自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 41 }
	name = "第11機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 42 }
	name = "第12機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "第2歩兵師団"
	id = { type = 23001 id = 43 }
	location = 1199
	division = {
	id = { type = 23001 id = 44 }
	name = "第13戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 45 }
	name = "第10自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 46 }
	name = "第11自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 47 }
	name = "第12自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 48 }
	name = "第13機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 49 }
	name = "第14機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "第47歩兵師団"
	id = { type = 23001 id = 50 }
	location = 699
	division = {
	id = { type = 23001 id = 51 }
	name = "第14戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 52 }
	name = "第13自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 53 }
	name = "第14自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 54 }
	name = "第15自動車化歩兵大隊"
	type = mechanized
	model = 23
	experience = 0
	}
	division = {
	id = { type = 23001 id = 55 }
	name = "第15機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 56 }
	name = "第16機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
 }
landunit = {
	name = "第1歩兵師団"
	id = { type = 23001 id = 57 }
	location = 792
	division = {
	id = { type = 23001 id = 58 }
	name = "第15戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 59 }
	name = "第16機械化歩兵大隊"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 60 }
	name = "第17機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 61 }
	name = "第18機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 62 }
	name = "第19機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 63 }
	name = "第20機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "第49機甲師団"
	id = { type = 23001 id = 64 }
	location = 686
	division = {
	id = { type = 23001 id = 65 }
	name = "第16戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 66 }
	name = "第21機械化歩兵大隊"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 67 }
	name = "第22機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 68 }
	name = "第23機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 69 }
	name = "第24機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 70 }
	name = "第25機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
  }
}
landunit = {
	name = "第50機甲師団"
	id = { type = 23001 id = 71 }
	location = 613
	division = {
	id = { type = 23001 id = 72 }
	name = "第17戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 73 }
	name = "第26機械化歩兵大隊"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 74 }
	name = "第27機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 75 }
	name = "第28機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 76 }
	name = "第29機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 77 }
	name = "第30機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "第5歩兵師団"
	id = { type = 23001 id = 78 }
	location = 680
	division = {
	id = { type = 23001 id = 79 }
	name = "第18戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 80 }
	name = "第31機械化歩兵大隊"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 81 }
	name = "第32機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 82 }
	name = "第33機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 83 }
	name = "第34機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 84 }
	name = "第35機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
}
landunit = {
	name = "第25歩兵師団"
	id = { type = 23001 id = 85 }
	location = 663
	division = {
	id = { type = 23001 id = 86 }
	name = "第19戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 87 }
	name = "第36機械化歩兵大隊"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 88 }
	name = "第37機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 89 }
	name = "第38機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 90 }
	name = "第39機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 91 }
	name = "第40機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
  }
landunit = {
	name = "第1騎兵師団"
	id = { type = 23001 id = 92 }
	location = 715
	division = {
	id = { type = 23001 id = 93 }
	name = "第20戦車大隊"
	type = armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 94 }
	name = "第41機械化歩兵大隊"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 95 }
	name = "第42機械化歩兵大隊"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 96 }
	name = "第43機械化歩兵大隊"
	type = light_armor
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 97 }
	name = "第44機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23001 id = 98 }
	name = "第45機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 0
	}
  }
landunit = {
	name = "第1海兵師団"
	id = { type = 23001 id = 99 }
	location = 627
	division = {
	id = { type = 23001 id = 100 }
	name = "第21戦車大隊"
	type = armor
	model = 1
	experience = 50
	}
	division = {
	id = { type = 23001 id = 101 }
	name = "第1海兵大隊"
	type = mechanized
	model = 23
	experience = 50
	}
	division = {
	id = { type = 23001 id = 102 }
	name = "第2海兵大隊"
	type = mechanized
	model = 23
	experience = 50
	}
	division = {
	id = { type = 23001 id = 103 }
	name = "第3海兵大隊"
	type = mechanized
	model = 23
	experience = 50
	}
	division = {
	id = { type = 23001 id = 104 }
	name = "第46機械化歩兵大隊"
	type = light_armor
	model = 1
	experience = 50
	}
	division = {
	id = { type = 23001 id = 105 }
	name = "第47機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 50
	}
}
landunit = {
	name = "第2海兵師団"
	id = { type = 23001 id = 106 }
	location = 671
	division = {
	id = { type = 23001 id = 107 }
	name = "第22戦車大隊"
	type = armor
	model = 1
	experience = 50
	}
	division = {
	id = { type = 23001 id = 108 }
	name = "第4海兵大隊"
	type = mechanized
	model = 23
	experience = 50
	}
	division = {
	id = { type = 23001 id = 109 }
	name = "第5海兵大隊"
	type = mechanized
	model = 23
	experience = 50
	}
	division = {
	id = { type = 23001 id = 110 }
	name = "第6海兵大隊"
	type = mechanized
	model = 23
	experience = 50
	}
	division = {
	id = { type = 23001 id = 111 }
	name = "第48機械化歩兵大隊"
	type = light_armor
	model = 1
	experience = 50
	}
	division = {
	id = { type = 23001 id = 112 }
	name = "第49機械化歩兵大隊"
	type = mechanized
	model = 1
	experience = 50
	}
}
landunit = {
	name = "第3海兵師団"
	id = { type = 23001 id = 113 }
	location = 2637
	division = {
	id = { type = 23001 id = 114 }
	name = "第23戦車大隊"
	type = mechanized
	model = 23
	experience = 50
	}
	division = {
	id = { type = 23001 id = 115 }
	name = "第7海兵大隊"
	type = mechanized
	model = 23
	experience = 50
	}
	division = {
	id = { type = 23001 id = 116 }
	name = "第8海兵大隊"
	type = mechanized
	model = 23
	experience = 50
	}
	division = {
	id = { type = 23001 id = 117 }
	name = "第9海兵大隊"
	type = mechanized
	model = 1
	experience = 50
	}
  }
navalunit = {
	name = "第1空母戦闘群"
	id = { type = 23002 id = 1 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 2 }
	name = "イントレピッド"
	type = carrier
	model = 0
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 3 }
	name = "ベルナップ"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 4 }
	name = "リーヒ"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 5 }
	name = "チャールズ･F･アダムズ"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 6 }
	name = "ヘンリー･B･ウィルソン"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 7 }
	name = "フォレスト･シャーマン"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 8 }
	name = "ジョン･ポール･ジョーンズ"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 9 }
	name = "バリー"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第2空母戦闘群"
	id = { type = 23002 id = 10 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 11 }
	name = "タイコンデロガ"
	type = carrier
	model = 0
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 12 }
	name = "ジョセファス･ダニエルズ"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 13 }
	name = "ハリー･E･ヤーネル"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 14 }
	name = "ジョン･キング"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 15 }
	name = "リンド･マコーミック"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 16 }
	name = "ディケーター"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 17 }
	name = "デイヴィス"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 18 }
	name = "ジョナス･イングラム"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第3空母戦闘群"
	id = { type = 23002 id = 19 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 20 }
	name = "ハンコック"
	type = carrier
	model = 0
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 21 }
	name = "ウェインライト"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 22 }
	name = "ウォーデン"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 23 }
	name = "タワーズ"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 24 }
	name = "サンプソン"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 25 }
	name = "マンリー"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 26 }
	name = "デュポン"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 27 }
	name = "ビグロー"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第4空母戦闘群"
	id = { type = 23002 id = 28 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 29 }
	name = "オリスカニー"
	type = carrier
	model = 0
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 30 }
	name = "ジョーエット"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 31 }
	name = "デイル"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 32 }
	name = "セラーズ"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 33 }
	name = "ロビソン"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 34 }
	name = "ブランディ"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 35 }
	name = "ムリニクス"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 36 }
	name = "ハル"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第5空母戦闘群"
	id = { type = 23002 id = 37 }
	location = 1193
	base = 1193
	division = {
	id = { type = 23002 id = 38 }
	name = "ミッドウェイ"
	type = carrier
	model = 0
    extra1        = cag
    brigade_model1= 1
	experience = 30
	}
	division = {
	id = { type = 23002 id = 39 }
	name = "ホーン"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 40 }
	name = "リッチモンド･K･ターナー"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 41 }
	name = "ローレンス"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 42 }
	name = "ブキャナン"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 43 }
	name = "エドソン"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 44 }
	name = "ソマーズ"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 45 }
	name = "モートン"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第6空母戦闘群"
	id = { type = 23002 id = 46 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 47 }
	name = "フランクリン･D･ルーズベルト"
	type = carrier
	model = 0
    extra1        = cag
    brigade_model1= 1
	experience = 30
	}
	division = {
	id = { type = 23002 id = 48 }
	name = "スタレット"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 49 }
	name = "グレッドレイ"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 50 }
	name = "クロード･V･リケッツ"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 51 }
	name = "ホーエル"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 52 }
	name = "パーソンズ"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 53 }
	name = "リチャード･S･エドワーズ"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 54 }
	name = "ターナー･ジョイ"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第7空母戦闘群"
	id = { type = 23002 id = 55 }
	location = 521
	base = 521
	division = {
	id = { type = 23002 id = 56 }
	name = "コーラル･シー"
	type = carrier
	model = 0
    extra1        = cag
    brigade_model1= 1
	experience = 30
	}
	division = {
	id = { type = 23002 id = 57 }
	name = "ウィリアム･H･スタンドレイ"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 58 }
	name = "イングランド"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 59 }
	name = "バーニー"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 60 }
	name = "バークレー"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 61 }
	name = "ファラガット"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 62 }
	name = "ルース"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 63 }
	name = "マクドノー"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第8空母戦闘群"
	id = { type = 23002 id = 64 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 65 }
	name = "フォレスタル"
	type = carrier
	model = 1
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 66 }
	name = "フォックス"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 67 }
	name = "ハルゼー"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 68 }
	name = "セムズ"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 69 }
	name = "ジョセフ･シュトラウス"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 70 }
	name = "クーンツ"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 71 }
	name = "キング"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 72 }
	name = "マハン"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第9空母戦闘群"
	id = { type = 23002 id = 73 }
	location = 761
	base = 761
	division = {
	id = { type = 23002 id = 74 }
	name = "サラトガ"
	type = carrier
	model = 1
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 75 }
	name = "ビドル"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 76 }
	name = "リーヴス"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 77 }
	name = "タットノール"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 78 }
	name = "カニンガム"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 79 }
	name = "ダールグレン"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 80 }
	name = "ウィリアム･V･プラット"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 81 }
	name = "デューイ"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第10空母戦闘群"
	id = { type = 23002 id = 82 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 83 }
	name = "レンジャー"
	type = carrier
	model = 1
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 84 }
	name = "オールバニー"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 85 }
	name = "プロビデンス"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 86 }
	name = "ゴールズボロー"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 87 }
	name = "コクレーン"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 88 }
	name = "プレブル"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 89 }
	name = "ミッチャー"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 90 }
	name = "ジョン･S･マケイン"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第11空母戦闘群"
	id = { type = 23002 id = 91 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 92 }
	name = "インディペンデンス"
	type = carrier
	model = 1
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 93 }
	name = "シカゴ"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 94 }
	name = "スプリングフィールド"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 95 }
	name = "リチャード･E･バード"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 96 }
	name = "ワッデル"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 97 }
	name = "ノックス"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 98 }
	name = "ロアーク"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 99 }
	name = "グレイ"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第12空母戦闘群"
	id = { type = 23002 id = 100 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 101 }
	name = "キティホーク"
	type = carrier
	model = 2
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 102 }
	name = "コロンバス"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 103 }
	name = "リトルロック"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 23002 id = 104 }
	name = "ベンジャミン･ストッダート"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 105 }
	name = "ヘプバーン"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 106 }
	name = "コノール"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 107 }
	name = "ラスバーン"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 108 }
	name = "メイヤコード"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第13空母戦闘群"
	id = { type = 23002 id = 109 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 110 }
	name = "コンステレーション"
	type = carrier
	model = 2
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 111 }
	name = "ニューポート･ニューズ"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 112 }
	name = "ガルベストン"
	type = heavy_cruiser
	model = 0
	experience = 0
	}
	division = {
	id = { type = 23002 id = 113 }
	name = "ウイリアム・S・シムズ"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 114 }
	name = "ラング"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 115 }
	name = "パターソン"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 116 }
	name = "ホイップル"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 117 }
	name = "リーズナー"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第14空母戦闘群"
	id = { type = 23002 id = 118 }
	location = 663
	base = 663
	division = {
	id = { type = 23002 id = 119 }
	name = "エンタープライズ"
	type = carrier
	model = 10
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 120 }
	name = "ロングビーチ"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 121 }
	name = "ベインブリッジ"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 122 }
	name = "ロックウッド"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 123 }
	name = "ステイン"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 124 }
	name = "マーヴィン・シールズ"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 125 }
	name = "フランシス・ハモンド"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 126 }
	name = "ヴィリーランド"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第15空母戦闘群"
	id = { type = 23002 id = 127 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 128 }
	name = "アメリカ"
	type = carrier
	model = 10
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 129 }
	name = "トラクスタン"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 130 }
	name = "バージニア"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 131 }
	name = "バッグレイ"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 132 }
	name = "ダウンズ"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 133 }
	name = "バジャー"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 134 }
	name = "ブラークリー"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 135 }
	name = "ロバート・E・ピアリー"
	type = destroyer
	model = 1
	experience = 0
	}
  }
navalunit = {
	name = "第16空母戦闘群"
	id = { type = 23002 id = 136 }
	location = 632
	base = 632
	division = {
	id = { type = 23002 id = 137 }
	name = "ジョン･F･ケネディ"
	type = carrier
	model = 10
    extra1        = cag
    brigade_model1= 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 138 }
	name = "テキサス"
	type = heavy_cruiser
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 139 }
	name = "ミシシッピ"
	type = heavy_cruiser
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 140 }
	name = "ハロルド・E・ホルト"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 141 }
	name = "トリップ"
	type = destroyer
	model = 2
	experience = 0
	}
	division = {
	id = { type = 23002 id = 142 }
	name = "ファニング"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 143 }
	name = "オーレット"
	type = destroyer
	model = 1
	experience = 0
	}
	division = {
	id = { type = 23002 id = 144 }
	name = "ジョセフ・ヒューズ"
	type = destroyer
	model = 1
	experience = 0
	}
  }
  navalunit =
  { id       = { type = 23002 id = 145 }
    name     = "第1両用即応グループ"
    location = 521
    base     = 521
    division =
    { id       = { type = 23002 id = 146 }
      name     = "イオー･ジマ"
      model    = 1
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 1
    }
    division =
    { id       = { type = 23002 id = 147 }
      name     = "第1輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 148 }
      name     = "第2輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 149 }
    name     = "第2両用即応グループ"
    location = 2632
    base     = 2632
    division =
    { id       = { type = 23002 id = 150 }
      name     = "オキナワ"
      model    = 1
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 1
    }
    division =
    { id       = { type = 23002 id = 151 }
      name     = "第3輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 152 }
      name     = "第4輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 153 }
    name     = "第3両用即応グループ"
    location = 632
    base     = 632
    division =
    { id       = { type = 23002 id = 154 }
      name     = "ガダルカナル"
      model    = 1
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 1
    }
    division =
    { id       = { type = 23002 id = 155 }
      name     = "第5輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 156 }
      name     = "第6輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 157 }
    name     = "第4両用即応グループ"
    location = 632
    base     = 632
    division =
    { id       = { type = 23002 id = 158 }
      name     = "グアム"
      model    = 1
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 1
    }
    division =
    { id       = { type = 23002 id = 159 }
      name     = "第7輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 160 }
      name     = "第8輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 161 }
    name     = "第5両用即応グループ"
    location = 761
    base     = 761
    division =
    { id       = { type = 23002 id = 162 }
      name     = "トリポリ"
      model    = 1
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 1
    }
    division =
    { id       = { type = 23002 id = 163 }
      name     = "第9輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 164 }
      name     = "第10輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 165 }
    name     = "第6両用即応グループ"
    location = 761
    base     = 761
    division =
    { id       = { type = 23002 id = 166 }
      name     = "ニューオーリンズ"
      model    = 1
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 1
    }
    division =
    { id       = { type = 23002 id = 167 }
      name     = "第11輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 168 }
      name     = "第12輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
  }
  navalunit =
  { id       = { type = 23002 id = 169 }
    name     = "第7両用即応グループ"
    location = 663
    base     = 663
    division =
    { id       = { type = 23002 id = 170 }
      name     = "インチョン"
      model    = 1
      type     = escort_carrier
      strength = 100.0000
      extra1        = cavalry_brigade
      brigade_model1= 1
    }
    division =
    { id       = { type = 23002 id = 171 }
      name     = "第13輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
    division =
    { id       = { type = 23002 id = 172 }
      name     = "第14輸送揚陸グループ"
      model    = 1
      type     = transport
      strength = 100.0000
    }
  }
}
