##############################
# Country definition for DFR #
##############################
province =
{ id       = 296
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ƒƒXƒgƒbƒN
province =
{ id       = 298
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ƒ}ƒOƒfƒuƒ‹ƒN
province =
{ id       = 300
  anti_air = 2
  air_base = { size = 10 current_size = 10 }
}            # ƒxƒ‹ƒŠƒ“
province =
{ id            = 302
  anti_air      = 1
  air_base      = { size = 4 current_size = 4 }
  naval_base    = { size = 4 current_size = 4 }
}                 # ƒVƒ…ƒeƒbƒeƒBƒ“
province =
{ id         = 303
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
}              # ƒ_ƒ“ƒcƒBƒq
province =
{ id         = 304
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 4 current_size = 4 }
}              # ƒGƒ‹ƒrƒ“ƒN
province = { id = 305 anti_air = 1 } # ƒvƒEƒHƒcƒN
province =
{ id         = 306
  anti_air   = 2
  naval_base = { size = 4 current_size = 4 }
  air_base   = { size = 4 current_size = 4 }
}              # ƒOƒfƒBƒjƒƒ
province = { id = 307 anti_air = 1 } # ƒgƒ‹ƒ“
province = { id = 308 anti_air = 2 landfort = 2 } # ƒ[ƒ[ƒŠƒbƒc
province =
{ id              = 310
  anti_air        = 1
  air_base        = { size = 4 current_size = 4 }
}                   # ƒ‰ƒCƒvƒcƒBƒq
province =
{ id       = 312
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒjƒ…ƒ‹ƒ“ƒxƒ‹ƒN
province =
{ id       = 313
  anti_air = 3
  air_base = { size = 4 current_size = 4 }
}            # ƒtƒ‰ƒ“ƒNƒtƒ‹ƒgEƒAƒ€Eƒ}ƒCƒ“
province =
{ id       = 314
  anti_air = 2
  air_base = { size = 4 current_size = 4 }
}            # ƒVƒ…ƒbƒcƒgƒKƒ‹ƒg
province = { id = 76 anti_air = 2 } # ƒfƒ…ƒbƒZƒ‹ƒhƒ‹ƒt
province =
{ id         = 80
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # ƒ”ƒBƒ‹ƒwƒ‹ƒ€ƒXƒn[ƒtƒFƒ“
province =
{ id       = 81
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒ~ƒ…ƒ“ƒXƒ^[
province =
{ id       = 82
  anti_air = 1
  air_base = { size = 4 current_size = 4 }
}            # ƒJƒbƒZƒ‹
province =
{ id         = 87
  anti_air   = 2
  air_base   = { size = 2 current_size = 2 }
  naval_base = { size = 8 current_size = 8 }
}              # ƒuƒŒ[ƒƒ“
province =
{ id         = 88
  anti_air   = 2
  naval_base = { size = 8 current_size = 8 }
}              # ƒnƒ“ƒuƒ‹ƒN
province = { id = 89 anti_air = 1 } # ƒŠƒ…[ƒxƒbƒN
province =
{ id         = 90
  anti_air   = 2
  air_base   = { size = 4 current_size = 4 }
  naval_base = { size = 10 current_size = 10 }
}              # ƒL[ƒ‹
#####################
# Country main data #
#####################

country =
{ tag                 = DFR
  manpower            = 4250
  energy              = 58000
  metal               = 36000
  rare_materials      = 45000
  oil                 = 12000
  supplies            = 8000
  money               = 3500
  capital             = 75
  transports          = 1800
  escorts             = 1500
  regular_id          = U02
  nationalprovinces   = { 66 67 74 75 76 80 81 82 83 85 86 87 88 89 90 312 313 314 315 374 375 376 547 970 989 1014 1015 1016 1018 1405 }
  ownedprovinces      = { 66 67 74 75 76 80 81 82 83 85 86 87 88 89 90 312 313 314 315 374 375 376 547 970 989 1014 1015 1016 1018 1405 }
  controlledprovinces = { 66 67 74 75 76 80 81 82 83 85 86 87 88 89 90 312 313 314 315 374 375 376 547 970 989 1014 1015 1016 1018 1405 }
  techapps            = { 
                         1130 1230 1570 1670 1770 1870 1970
                         2010 2020 2030 2040 2050 2310 2320 2610 2620 2910 2920 10050 10060 1010  10190 1020  10200 1030    1110  1120 
                          1210  1220  1470  1490  1510  1530  1550  1560  1650  1660
                          1750  1760  1850  1860  1950  1960
                          3010  3020  30410 30420 30510 30520 3110 
                          3120  3210  3220  3460  3470
                          3560      3910  3920
                          3940  40100 40110 4390  4400  4010  4020  4110  4120  4210  4220  4640  4650  4820  4830
                          4560  50020 50030   50070 50080  5010    50090 50100 5020  50290 50300 50310
                          5090  5100  5170  5180  5250  5260  5330  5340  5410  5420
                          5490  5500  5600  5610  5680  5690  5760  5770  5780  5790  5800  5810
                          5910  5920  7010  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990  2000  2210  3000  4000  5000
                          6130  6120  6310
                        }
  inventions          = { }
  policy =
  { democratic        = 10
    political_left    = 2
    freedom           = 9
    free_market       = 9
    professional_army = 9
    defense_lobby     = 10
    interventionism   = 9
  }
  landunit =
  { id       = { type = 25001 id = 11 }
    name     = "‘æ1ŒR’c"
    location = 88
    home     = 88
    division =
    { id            = { type = 25001 id = 12 }
      name          = "‘æ1ŒR’ci—ß•”"
      model         = 2
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 13 }
    name     = "‘æ2ŒR’c"
    location = 86
    home     = 86
    division =
    { id            = { type = 25001 id = 14 }
      name          = "‘æ2ŒR’ci—ß•”"
      model         = 2
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 15 }
    name     = "‘æ3ŒR’c"
    location = 313
    home     = 313
    division =
    { id            = { type = 25001 id = 16 }
      name          = "‘æ3ŒR’ci—ß•”"
      model         = 2
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 17 }
    name     = "‘æ4ŒR’c"
    location = 376
    home     = 376
    division =
    { id            = { type = 25001 id = 18 }
      name          = "‘æ4ŒR’ci—ß•”"
      model         = 2
      brigade_model = 0
      type          = hq
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 19 }
    name     = "‘æ1íp‘•bt’c"
    location = 89
    division =
    { id            = { type = 25001 id = 20 }
      name          = "‘æ1íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 21 }
      name          = "‘æ2íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 22 }
      name          = "‘æ3íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 23 }
      name          = "‘æ4íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 24 }
      name          = "‘æ1íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 25 }
      name          = "‘æ2íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 26 }
    name     = "‘æ7íp‘•bt’c"
    location = 87
    division =
    { id            = { type = 25001 id = 27 }
      name          = "‘æ5íp‹@b‘å‘à"
      model         = 5
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 28 }
      name          = "‘æ6íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 29 }
      name          = "‘æ7íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 30 }
      name          = "‘æ8íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 31 }
      name          = "‘æ3íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 32 }
      name          = "‘æ4íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 33 }
    name     = "‘æ3íp‘•bt’c"
    location = 82
    division =
    { id            = { type = 25001 id = 34 }
      name          = "‘æ9íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 35 }
      name          = "‘æ10íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 36 }
      name          = "‘æ11íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 37 }
      name          = "‘æ12íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 38 }
      name          = "‘æ5íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 39 }
      name          = "‘æ6íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 40 }
    name     = "‘æ5‘•bt’c"
    location = 547
    division =
    { id            = { type = 25001 id = 41 }
      name          = "‘æ13íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 42 }
      name          = "‘æ14íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 43 }
      name          = "‘æ7íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 44 }
      name          = "‘æ8íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 45 }
      name          = "‘æ9íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 46 }
      name          = "‘æ10íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 47 }
    name     = "‘æ13íp‘•bt’c"
    location = 86
    division =
    { id            = { type = 25001 id = 48 }
      name          = "‘æ15íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 49 }
      name          = "‘æ16íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 50 }
      name          = "‘æ17íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 51 }
      name          = "‘æ18íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 52 }
      name          = "‘æ11íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 53 }
      name          = "‘æ12íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 54 }
    name     = "‘æ10‘•bt’c"
    location = 83
    division =
    { id            = { type = 25001 id = 55 }
      name          = "‘æ19íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 56 }
      name          = "‘æ20íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 57 }
      name          = "‘æ13íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 58 }
      name          = "‘æ14íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 59 }
      name          = "‘æ15íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 60 }
      name          = "‘æ16íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 61 }
    name     = "‘æ6‘•b±’e•ºt’c"
    location = 75
    division =
    { id            = { type = 25001 id = 62 }
      name          = "‘æ21íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 63 }
      name          = "‘æ22íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 64 }
      name          = "‘æ1‹@ŠB‰»•à•º‘•b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 65 }
      name          = "‘æ2‹@ŠB‰»•à•º‘•b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 66 }
      name          = "‘æ3‹@ŠB‰»•à•º‘•b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 67 }
      name          = "‘æ4‹@ŠB‰»•à•º‘•b‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  landunit =
  { id       = { type = 25001 id = 68 }
    name     = "‘æ15‘•bt’c"
    location = 314
    division =
    { id            = { type = 25001 id = 69 }
      name          = "‘æ23íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      extra         = artillery
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 70 }
      name          = "‘æ24íp‹@b‘å‘à"
      model         = 4
      brigade_model = 0
      type          = paratrooper
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 71 }
      name          = "‘æ17íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 72 }
      name          = "‘æ18íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 73 }
      name          = "‘æ19íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
    division =
    { id            = { type = 25001 id = 74 }
      name          = "‘æ20íÔ‘å‘à"
      model         = 2
      brigade_model = 0
      type          = armor
      strength      = 100
    }
  }
  ##‘æ51—·’c ƒL[ƒ‹
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5001 }
    name = "‘æ512‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5002 }
    name = "‘æ513íÔ‘å‘à"
    strength = 100
    type = armor
    model = 2
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5003 }
    name = "‘æ514‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5004 }
    name = "‘æ515íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  ##‘æ61—·’c ƒL[ƒ‹
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5005 }
    name = "‘æ613íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5006 }
    name = "‘æ614‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5007 }
    name = "‘æ615‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  ##‘æ52—·’c ƒnƒm[ƒtƒ@[
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5008 }
    name = "‘æ522‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5009 }
    name = "‘æ523íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5010 }
    name = "‘æ524‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5011 }
    name = "‘æ525íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  ##‘æ62—·’c ƒnƒm[ƒtƒ@[
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5012 }
    name = "‘æ623íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5013 }
    name = "‘æ624‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5014 }
    name = "‘æ625‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  ##‘æ53—·’c ƒfƒ…ƒbƒZƒ‹ƒhƒ‹ƒt
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5015 }
    name = "‘æ532‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5016 }
    name = "‘æ533íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5017 }
    name = "‘æ534‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5018 }
    name = "‘æ535íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  ##‘æ63—·’c ƒfƒ…ƒbƒZƒ‹ƒhƒ‹ƒt
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5019 }
    name = "‘æ633íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5020 }
    name = "‘æ634‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5021 }
    name = "‘æ635‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  ##‘æ54—·’c ƒ}ƒCƒ“ƒc
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5022 }
    name = "‘æ542‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5023 }
    name = "‘æ543íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5024 }
    name = "‘æ544‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5025 }
    name = "‘æ545íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  ##‘æ64—·’c ƒ}ƒCƒ“ƒc
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5026 }
    name = "‘æ643íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5027 }
    name = "‘æ644‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5028 }
    name = "‘æ645‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  ##‘æ55—·’c ƒVƒ…ƒgƒDƒbƒgƒKƒ‹ƒg
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5029 }
    name = "‘æ552‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5030 }
    name = "‘æ553íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5031 }
    name = "‘æ554‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5032 }
    name = "‘æ555íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  ##‘æ65—·’c ƒ}ƒCƒ“ƒc
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5033 }
    name = "‘æ652íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5034 }
    name = "‘æ653‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5035 }
    name = "‘æ654‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  ##‘æ56—·’c ƒ~ƒ…ƒ“ƒwƒ“
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5036 }
    name = "‘æ561‹@b±’e•º‘å‘à"
    strength = 100
    type = mechanized
    model = 2
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5037 }
    name = "‘æ562‹@b±’e•º‘å‘à"
    strength = 100
    type = mechanized
    model = 2
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5038 }
    name = "‘æ563íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5039 }
    name = "‘æ564íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  ##‘æ66—·’c ƒ~ƒ…ƒ“ƒwƒ“
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5040 }
    name = "‘æ663íÔ‘å‘à"
    strength = 100
    type = armor
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5041 }
    name = "‘æ664‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
  landdivision = {
    dormant = yes
    id = { type = 10010 id = 5042 }
    name = "‘æ665‹@b—Â•º‘å‘à"
    strength = 100
    type = mechanized
    model = 1
  }
}
