
##############################
# Country definition for ROM #
##############################

#####################
# Country main data #
#####################

country =
{ tag                 = ROM
  manpower            = 4250
  energy              = 58000
  metal               = 36000
  rare_materials      = 45000
  oil                 = 12000
  supplies            = 8000
  money               = 3500
  capital             = 424
  transports          = 1800
  escorts             = 1500
  regular_id          = U02
  nationalprovinces   = { 423 424 425 426 427 428 429 430 431 432 436 495 496 498 1402 1403 1449 1899 2449 2450 2602 2603 2604 }
  ownedprovinces      = { 423 424 425 426 427 428 429 430 431 432 436 495 496 498 1402 1403 1449 1899 2449 2450 2602 2603 2604 }
  controlledprovinces = { 423 424 425 426 427 428 429 430 431 432 436 495 496 498 1402 1403 1449 1899 2449 2450 2602 2603 2604 }
  techapps            = { 
                         1130 1230 1570 1670 1770 1870 1970
                         2010 2020 2030 2040 2050 2310 2320 2610 2620 2910 2920 10050 10060 1010  10190 1020  10200 1030  1050  1110  1120 
                          1210  1220  1470  1490  1510  1530  1550  1560  1650  1660
                          1750  1760  1850  1860  1950  1960
                          3010  3020  30410 30420 30510 30520 3110 
                          3120  3210  3220  3460  3470
                          3560  3640  3650  3910  3920
                          3940  40100 40110 4390  4400  4010  4020  4110  4120  4210  4220  4640  4650  4820  4830
                          4560  50020 50030 50040 50050 50070 50080 50090 5010  50100 50090 50100 50090 50100 5020  50290 50300 50310
                          5090  5100  5170  5180  5250  5260  5330  5340  5410  5420
                          5490  5500  5600  5610  5680  5690  5760  5770  5780  5790  5800  5810
                          5910  5920  7010  80080 80090 8010  80100 80160 8020  8030  8040  8050  8060  8070  8280  8290  8300  8310  8320  8330  9010  90140
                          90190 9020  9030  9040  9050  9060  9070  9190  9200  9210  9340  9350  9360  9370  9380  9390  9400  9520  9530  9540 
                          9550  9670  9680  9690  9700  9710  9720  9840  9850  9860  9990  6000  6010  6020  6030  6040
                          6180  6190  6400  6410
                        }
  inventions          = { }
  policy              = { democratic = 2 political_left = 9 freedom = 2 free_market = 2 professional_army = 9 defense_lobby = 10 interventionism = 9 }
landunit = {
	name = "‘æ1íÔt’c"
	id = { type = 19541 id = 1 }
	location = 1402
	division = {
	id = { type = 19541 id = 2 }
	name = "‘æ1íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19541 id = 3 }
	name = "‘æ2íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19541 id = 4 }
	name = "‘æ3íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
  }
landunit = {
	name = "‘æ2íÔt’c"
	id = { type = 19541 id = 5 }
	location = 1403
	division = {
	id = { type = 19541 id = 6 }
	name = "‘æ4íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19541 id = 7 }
	name = "‘æ5íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
	division = {
	id = { type = 19541 id = 8 }
	name = "‘æ6íÔ˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	}
  }
landunit = {
	name = "‘æ1©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19541 id = 205 }
	location = 429
	division = {
	id = { type = 19541 id = 206 }
	name = "‘æ1©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 207 }
	name = "‘æ2©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 208 }
	name = "‘æ3©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
  }
landunit = {
	name = "‘æ2©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19541 id = 209 }
	location = 2604
	division = {
	id = { type = 19541 id = 210 }
	name = "‘æ4©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 211 }
	name = "‘æ5©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 212 }
	name = "‘æ6©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ3©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19541 id = 213 }
	location = 436
	division = {
	id = { type = 19541 id = 214 }
	name = "‘æ7©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 215 }
	name = "‘æ8©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 216 }
	name = "‘æ9©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ4©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19541 id = 217 }
	location = 2449
	division = {
	id = { type = 19541 id = 218 }
	name = "‘æ10©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 219 }
	name = "‘æ11©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 220 }
	name = "‘æ12©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ5©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19541 id = 221 }
	location = 436
	division = {
	id = { type = 19541 id = 222 }
	name = "‘æ13©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 223 }
	name = "‘æ14©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 224 }
	name = "‘æ15©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ6©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19541 id = 225 }
	location = 2449
	division = {
	id = { type = 19541 id = 226 }
	name = "‘æ16©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 227 }
	name = "‘æ17©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 228 }
	name = "‘æ18©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ7©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19541 id = 229 }
	location = 429
	division = {
	id = { type = 19541 id = 230 }
	name = "‘æ19©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 231 }
	name = "‘æ20©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 232 }
	name = "‘æ21©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ8©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19541 id = 233 }
	location = 1402
	division = {
	id = { type = 19541 id = 234 }
	name = "‘æ22©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 235 }
	name = "‘æ23©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 236 }
	name = "‘æ24©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
}
landunit = {
	name = "‘æ9©“®Ô‰»‘_Œ‚•ºt’c"
	id = { type = 19541 id = 237 }
	location = 1403
	division = {
	id = { type = 19541 id = 238 }
	name = "‘æ25©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 239 }
	name = "‘æ26©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = light_armor
	model = 11
	experience = 0
	#locked = yes
	}
	division = {
	id = { type = 19541 id = 240 }
	name = "‘æ27©“®Ô‰»‘_Œ‚•º˜A‘à"
	type = mechanized
	model = 1
	experience = 0
	#locked = yes
	}
  }
}
