
##############################
# Country definition for U12 #
##############################

province = { id = 193 landfort = 10 ic = 100 energy = 5000 metal = 5000 rare_materials = 5000 oil = 5000 manpower = 9 }

#####################
# Country main data #
#####################

country =
{ tag                 = U12
  manpower            = 999999
  energy              = 999999
  metal               = 999999
  rare_materials      = 999999
  oil                 = 999999
  supplies            = 999999
  money               = 999999
  capital             = 193
  extra_tc            = 9999
  transports          = 9999
  escorts             = 9999
  belligerence        = 99999
  nationalprovinces   = { 193  520 521 522 523 524 516 517 518 519 542 543 515 512 513 514 369 368 370 379 531 378 668 666 2325 2326 
                          371 1408 373 377 460 461 462 2327 2328 2329 463 464 465 2447 224 456 458 491 492 497 1890 459 455 380 382 383 291 384 1893 
                          1891 1892 385 386 387 454 493 494 1895 1897 452 453 1057 389 1894 1896 451 415 1168 1169 413 414 665 390 391 664 
                          392 2319 410 411 412 2321 402 403 401 400 395 394  416 417 419 420 421 422 2323 2324 1911  495 2602 2603 426 424 425 423 2450
                          431 432 436 1402 429 2604 2449  496 427 428 498 1449 1403 1899 430 1173 1401 230 433 434 2605 435 476 478 477 1889 1887 490 499
                          466 470 53 1888 469 471 468 475 467 472 474 388 381  393  398  32 33 34 35 37 38 39 40 41 2555 18 42 43 44 36 57 58 60 61 323 325 326 59 54 56 62 63 319 320 321 322
                          324 360 361 328 358 359 362 363 55 64 317 841 318 2557 2514 1643 1676 364 365 527 528 2509 2242 327 72 73
                          316 1022 366 45 50 51 52 65 68  69 70 71  46  47  49   1019 1082 77   78  79  530 532 533  372  80  81 86
                          87  88   89  90 296 301 82 84 313 547 970 83 85 374 375 376 312 297 298 299 300 546 302 308 1779 1810 309
                          310 311  314 315 1014 989 66 67 74 75 76  1405 1018 1015 1016 48 
                          1563 345 344 1163 336 965 337 335 348 1157 346 347 343 338 350 351 353 1161 340 349 334 1537 1532 339 333 961 962
                          332 1726 331 2244 2243 341 342 1531 1162 1734 330 352 1714 354 355 356 357 536 537 329 1400 1623 473 482 1595 }
  ownedprovinces      = { 193 194 195 196 197 198 199 202 203 204 205 206 207 214 509 511 577 1886 2606 208 211 222 229 305 306 479 
                          480 481 483 484 485 486 487 488 489 500 501 502 503 504 505 506 507 508 1875 1876 1884 303 304 307 1811 510 223 
                          155 161 226 227 228 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 302 308 1779 1810
                          250 251 252 253 254 258 259 260 261 262 263 265 266 267 268 282 1152 1154 1565 1571 1827 95 102 209 210 123 187 188
                          213 217 218 220 221 225 272 273 274 562 1153 1566 1874 1885 103 131 132 130 137 138 139 140 141 142 143 144 145 146 147 148 149
                          1400 1595 473 482 1623 230 433 434 435 1173 1401 2605 }
  controlledprovinces = { 193 194 195 196 197 198 199 202 203 204 205 206 207 214 509 511 577 1886 2606 208 211 222 229 305 306 479 
                          480 481 483 484 485 486 487 488 489 500 501 502 503 504 505 506 507 508 1875 1876 1884 303 304 307 1811 510 223 
                          155 161 226 227 228 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 302 308 1779 1810
                          250 251 252 253 254 258 259 260 261 262 263 265 266 267 268 282 1152 1154 1565 1571 1827 95 102 209 210 123 187 188
                          213 217 218 220 221 225 272 273 274 562 1153 1566 1874 1885 103 131 132 130 137 138 139 140 141 142 143 144 145 146 147 148 149
                          1400 1595 473 482 1623 230 433 434 435 1173 1401 2605 }
  techapps            = { 
                         1130 1230 1570 1670 1770 1870 1970
                         2010 2020 2030 2040 2050 2310 2320 2610 2620 2910 2920 
                         1130 1230 1570 1670 1770 1870 1970
                         2010 2020 2030 2040 2050 2310 2320 2610 2620 2910 2920 50020 50030 50040 50070 50080 50090 50100 50090 50100 50090 50100 5600 5610 5620 7010 7020 7030 7040 7050 7060 }
  free                = { ic = 300 energy = 9000 metal = 9000 rare_materials = 9000 oil = 9000 money = 1000 manpower = 9 }
  policy =
  { democratic        = 1
    political_left    = 1
    freedom           = 1
    free_market       = 1
    professional_army = 1
    defense_lobby     = 10
    interventionism   = 10
  }
  landunit =
  { id       = { type = 21000 id = 1 }
    name     = "Army 1"
    location = 1400
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 1 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 2 }
      name  = "HQ 2"
    }
    division =
    { type          = infantry#óvåÇãâ
      model = 33
      id    = { type = 21004 id = 3 }
      name  = "Airborne 7"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 4 }
      name  = "Airborne 8"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 5 }
      name  = "Airborne 9"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 6 }
      name  = "Airborne 10"
    }
  }
  landunit =
  { id       = { type = 21000 id = 3 }
    name     = "Army 3"
    location = 501
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 25 }
      name  = "Militia 1"
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 32 }
      name  = "Mountain 22"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 33 }
      name  = "Mountain 23"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 34 }
      name  = "Mountain 24"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 35 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 36 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 4 }
    name     = "Army 4"
    location = 302
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 37 }
      name  = "ìÀåÇãâåıê¸ãâ1"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 38 }
      name  = "ìÀåÇãâåıê¸ãâ2"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 39 }
      name  = "ìÀåÇãâåıê¸ãâ3"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 40 }
      name  = "ìÀåÇãâåıê¸ãâ4"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 41 }
      name  = "ìÀåÇãâåıê¸ãâ5"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 42 }
      name  = "ìÀåÇãâåıê¸ãâ6"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 43 }
      name  = "ìÀåÇãâåıê¸ãâ7"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 44 }
      name  = "ìÀåÇãâåıê¸ãâ8"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 45 }
      name  = "ìÀåÇãâåıê¸ãâ9"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 46 }
      name  = "ìÀåÇãâåıê¸ãâ10"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 47 }
      name  = "ìÀåÇãâåıê¸ãâ11"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 48 }
      name  = "ìÀåÇãâåıê¸ãâ12"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 49 }
      name  = "ìÀåÇãâåıê¸ãâ13"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 50 }
      name  = "ìÀåÇãâåıê¸ãâ14"
      extra         = super_heavy_armor
      brigade_model = 0
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 51 }
      name  = "ìÀåÇãâåıê¸ãâ15"
      extra         = super_heavy_armor
      brigade_model = 0
    }
  }
  landunit =
  { id       = { type = 21000 id = 5 }
    name     = "Army 1"
    location = 479
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 67 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 68 }
      name  = "HQ 2"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 77 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 78 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 6 }
    name     = "Army 1"
    location = 1595
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 79 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 80 }
      name  = "HQ 2"
    }
    division =
    { type          = infantry#óvåÇãâ
      model = 33
      id    = { type = 21004 id = 81 }
      name  = "Airborne 7"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 82 }
      name  = "Airborne 8"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 83 }
      name  = "Airborne 9"
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 86 }
      name  = "Mountain 22"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 87 }
      name  = "Mountain 23"
    }
  }
  landunit =
  { id       = { type = 21000 id = 7 }
    name     = "Army 1"
    location = 1623
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 88 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 89 }
      name  = "HQ 2"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 96 }
      name  = "Mountain 23"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 99 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 8 }
    name     = "Army 1"
    location = 489
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 100 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 101 }
      name  = "HQ 2"
    }
    division =
    { type          = infantry#óvåÇãâ
      model = 33
      id    = { type = 21004 id = 102 }
      name  = "Airborne 7"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 103 }
      name  = "Airborne 8"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 110 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 111 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 9 }
    name     = "Army 1"
    location = 488
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 112 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 113 }
      name  = "HQ 2"
    }
    division =
    { type          = infantry#óvåÇãâ
      model = 33
      id    = { type = 21004 id = 114 }
      name  = "Airborne 7"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 115 }
      name  = "Airborne 8"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 121 }
      name  = "Mountain 24"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 122 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 123 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 10 }
    name     = "Army 1"
    location = 500
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 124 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 125 }
      name  = "HQ 2"
    }
    division =
    { type          = infantry#óvåÇãâ
      model = 33
      id    = { type = 21004 id = 126 }
      name  = "Airborne 7"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 127 }
      name  = "Airborne 8"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 128 }
      name  = "Airborne 9"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 134 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 135 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 11 }
    name     = "Army 1"
    location = 308
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 136 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 137 }
      name  = "HQ 2"
    }
    division =
    { type          = infantry#óvåÇãâ
      model = 33
      id    = { type = 21004 id = 138 }
      name  = "Airborne 7"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 139 }
      name  = "Airborne 8"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 146 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 147 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 12 }
    name     = "Army 1"
    location = 486
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 148 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 149 }
      name  = "HQ 2"
    }
    division =
    { type          = infantry#óvåÇãâ
      model = 33
      id    = { type = 21004 id = 150 }
      name  = "Airborne 7"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 151 }
      name  = "Airborne 8"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 156 }
      name  = "Mountain 23"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 157 }
      name  = "Mountain 24"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 158 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 159 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 13 }
    name     = "Army 1"
    location = 1400
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 160 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 161 }
      name  = "HQ 2"
    }
    division =
    { type          = infantry#óvåÇãâ
      model = 33
      id    = { type = 21004 id = 162 }
      name  = "Airborne 7"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 169 }
      name  = "Mountain 24"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 170 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 171 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 14 }
    name     = "Army 1"
    location = 1884
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 172 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 173 }
      name  = "HQ 2"
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 179 }
      name  = "Mountain 22"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 180 }
      name  = "Mountain 23"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 181 }
      name  = "Mountain 24"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 182 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 183 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 15 }
    name     = "Army 1"
    location = 1623
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 184 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 185 }
      name  = "HQ 2"
    }
    division =
    { type  = marine#ìÀåÇãâ
      model = 33
      id    = { type = 21004 id = 191 }
      name  = "Mountain 22"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 194 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 195 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21000 id = 16 }
    name     = "Army 1"
    location = 1595
    division =
    { type  = hq#óvç«ãâ
      model = 33
      id    = { type = 21004 id = 196 }
      name  = "Militia 1"
    }
    division =
    { type  = hq
      model = 33
      id    = { type = 21004 id = 197 }
      name  = "HQ 2"
    }
    division =
    { type          = infantry#óvåÇãâ
      model = 33
      id    = { type = 21004 id = 198 }
      name  = "Airborne 7"
    }
    division =
    { type          = infantry
      model = 33
      id    = { type = 21004 id = 199 }
      name  = "Airborne 8"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 206 }
      name  = "Mountain 25"
    }
    division =
    { type  = marine
      model = 33
      id    = { type = 21004 id = 207 }
      name  = "Mountain 26"
    }
  }
  landunit =
  { id       = { type = 21004 id = 5732 }
    name     = "ëÊ64åRíc"
    location = 507
    division =
    { id            = { type = 21004 id = 5734 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 5742 }
      name          = "ëÊ233BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 5743 }
      name          = "ëÊ234BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 5746 }
      name          = "ëÊ237BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 5747 }
      name          = "ëÊ238BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 21004 id = 223 }
    name     = "ëÊ66åRíc"
    location = 161
    division =
    { id            = { type = 21004 id = 224 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 232 }
      name          = "ëÊ233BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 233 }
      name          = "ëÊ234BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 236 }
      name          = "ëÊ237BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 237 }
      name          = "ëÊ238BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 21004 id = 238 }
    name     = "ëÊ67åRíc"
    location = 231
    division =
    { id            = { type = 21004 id = 239 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 250 }
      name          = "ëÊ236BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 251 }
      name          = "ëÊ237BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 252 }
      name          = "ëÊ238BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 21004 id = 253 }
    name     = "ëÊ68åRíc"
    location = 1571
    division =
    { id            = { type = 21004 id = 255 }
      name          = "ëÊ94BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 264 }
      name          = "ëÊ235BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 265 }
      name          = "ëÊ236BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 267 }
      name          = "ëÊ238BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 21004 id = 268 }
    name     = "ëÊ69åRíc"
    location = 233
    division =
    { id            = { type = 21004 id = 269 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 278 }
      name          = "ëÊ234BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 281 }
      name          = "ëÊ237BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 282 }
      name          = "ëÊ238BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 21004 id = 283 }
    name     = "âàä›BETAåQ"
    location = 1779
    division =
    { id            = { type = 21004 id = 284 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 285 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 286 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 287 }
    name     = "âàä›BETAåQ"
    location = 306
    division =
    { id            = { type = 21004 id = 288 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 289 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 290 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 291 }
    name     = "âàä›BETAåQ"
    location = 303
    division =
    { id            = { type = 21004 id = 292 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 293 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 294 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 295 }
    name     = "âàä›BETAåQ"
    location = 304
    division =
    { id            = { type = 21004 id = 296 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 297 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 298 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 299 }
    name     = "âàä›BETAåQ"
    location = 510
    division =
    { id            = { type = 21004 id = 300 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 301 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 302 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 303 }
    name     = "âàä›BETAåQ"
    location = 223
    division =
    { id            = { type = 21004 id = 304 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 305 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 306 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 307 }
    name     = "âàä›BETAåQ"
    location = 2606
    division =
    { id            = { type = 21004 id = 308 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 309 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 310 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 311 }
    name     = "âàä›BETAåQ"
    location = 206
    division =
    { id            = { type = 21004 id = 312 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 313 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 314 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 315 }
    name     = "âàä›BETAåQ"
    location = 205
    division =
    { id            = { type = 21004 id = 316 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 317 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 318 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 319 }
    name     = "âàä›BETAåQ"
    location = 204
    division =
    { id            = { type = 21004 id = 320 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 321 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 322 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 323 }
    name     = "âàä›BETAåQ"
    location = 197
    division =
    { id            = { type = 21004 id = 324 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 325 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 326 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 327 }
    name     = "âàä›BETAåQ"
    location = 198
    division =
    { id            = { type = 21004 id = 328 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 329 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 330 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 331 }
    name     = "âàä›BETAåQ"
    location = 196
    division =
    { id            = { type = 21004 id = 332 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 333 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 334 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 335 }
    name     = "âàä›BETAåQ"
    location = 194
    division =
    { id            = { type = 21004 id = 336 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 337 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 338 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 339 }
    name     = "âàä›BETAåQ"
    location = 193
    division =
    { id            = { type = 21004 id = 340 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 341 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 342 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 343 }
    name     = "âàä›BETAåQ"
    location = 188
    division =
    { id            = { type = 21004 id = 344 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 345 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 346 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 347 }
    name     = "âàä›BETAåQ"
    location = 187
    division =
    { id            = { type = 21004 id = 348 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 349 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 350 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 351 }
    name     = "âàä›BETAåQ"
    location = 123
    division =
    { id            = { type = 21004 id = 352 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 353 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 354 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 355 }
    name     = "âàä›BETAåQ"
    location = 145
    division =
    { id            = { type = 21004 id = 356 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 357 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 358 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 359 }
    name     = "âàä›BETAåQ"
    location = 144
    division =
    { id            = { type = 21004 id = 360 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 361 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 362 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 363 }
    name     = "âàä›BETAåQ"
    location = 148
    division =
    { id            = { type = 21004 id = 364 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 365 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 366 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 367 }
    name     = "âàä›BETAåQ"
    location = 142
    division =
    { id            = { type = 21004 id = 368 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 369 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 370 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 371 }
    name     = "âàä›BETAåQ"
    location = 141
    division =
    { id            = { type = 21004 id = 372 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 373 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 374 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 375 }
    name     = "âàä›BETAåQ"
    location = 140
    division =
    { id            = { type = 21004 id = 376 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 377 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 378 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 379 }
    name     = "âàä›BETAåQ"
    location = 138
    division =
    { id            = { type = 21004 id = 380 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 381 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 382 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 383 }
    name     = "âàä›BETAåQ"
    location = 137
    division =
    { id            = { type = 21004 id = 384 }
      name          = "ëÊ34BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 385 }
      name          = "ëÊ10BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
    division =
    { id            = { type = 21004 id = 386 }
      name          = "ëÊ37BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
      locked        = yes
    }
  }
  landunit =
  { id       = { type = 21004 id = 387 }
    name     = "ëÊ69åRíc"
    location = 131
    division =
    { id            = { type = 21004 id = 388 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 390 }
      name          = "ëÊ95BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 391 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 392 }
      name          = "ëÊ94BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 395 }
      name          = "ëÊ232BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 396 }
      name          = "ëÊ233BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 397 }
      name          = "ëÊ234BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 400 }
      name          = "ëÊ237BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 401 }
      name          = "ëÊ238BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 21004 id = 402 }
    name     = "ëÊ69åRíc"
    location = 480
    division =
    { id            = { type = 21004 id = 403 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 407 }
      name          = "ëÊ94BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 408 }
      name          = "ëÊ95BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 409 }
      name          = "ëÊ231BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 410 }
      name          = "ëÊ232BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 411 }
      name          = "ëÊ233BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 412 }
      name          = "ëÊ234BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 415 }
      name          = "ëÊ237BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 416 }
      name          = "ëÊ238BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 21004 id = 417 }
    name     = "ëÊ69åRíc"
    location = 130
    division =
    { id            = { type = 21004 id = 418 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 420 }
      name          = "ëÊ95BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 422 }
      name          = "ëÊ94BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 423 }
      name          = "ëÊ95BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 426 }
      name          = "ëÊ233BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 427 }
      name          = "ëÊ234BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 431 }
      name          = "ëÊ238BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
  }
  landunit =
  { id       = { type = 21004 id = 432 }
    name     = "ëÊ69åRíc"
    location = 132
    division =
    { id            = { type = 21004 id = 433 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 435 }
      name          = "ëÊ95BETAåQ"
      model         = 33
      brigade_model = 0
      type          = marine
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 436 }
      name          = "ëÊ93BETAåQ"
      model         = 33
      brigade_model = 0
      type          = bergsjaeger
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 439 }
      name          = "ëÊ231BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 440 }
      name          = "ëÊ232BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = super_heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 441 }
      name          = "ëÊ233BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 442 }
      name          = "ëÊ234BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = heavy_armor
      #strength      = 100.0000
    }
    division =
    { id            = { type = 21004 id = 446 }
      name          = "ëÊ238BETAåQ"
      model         = 33
      brigade_model = 0
      type          = infantry
      extra         = light_armor_brigade
      #strength      = 100.0000
    }
  }
}